import {useEffect,useMemo,useRef,useState,type PointerEvent as ReactPointerEvent} from "react";
import {RotateCcw} from "lucide-react";
import type {BounceConfig,BounceCurve,BouncePoint} from "./sceneModel";
import {sampleSpring} from "./springRuntime";
type Props={config:BounceConfig;duration:number;onChange:(next:BounceConfig)=>void;onClose:()=>void;onGestureStart?:()=>void};
const clamp=(v:number,min:number,max:number)=>Math.min(max,Math.max(min,v)),clone=(p:BounceCurve)=>p.map(v=>({...v}));
const point=(x:number,y:number):BouncePoint=>({x,y,inX:x-.08,inY:y,outX:x+.08,outY:y});
function simplifiedSpring(config:BounceConfig,duration:number):BounceCurve{const samples=sampleSpring(duration,config,120);const extrema=[samples[0]];for(let i=1;i<samples.length-1;i++){const a=samples[i].y-samples[i-1].y,b=samples[i+1].y-samples[i].y;if(a===0||a*b<0)extrema.push(samples[i])}extrema.push(samples[samples.length-1]);const cap=config.preset==="soft"?2:config.preset==="single"||config.preset==="drop"?3:5,chosen=extrema.slice(0,Math.max(2,cap));if(chosen[chosen.length-1].x<.999)chosen.push(samples[samples.length-1]);return chosen.map((p,i,a)=>{const prev=a[Math.max(0,i-1)],next=a[Math.min(a.length-1,i+1)],span=Math.max(.02,next.x-prev.x),slope=(next.y-prev.y)/span,handle=Math.min(.12,span/3);return{x:p.x,y:p.y,inX:i?Math.max(prev.x,p.x-handle):p.x,inY:i?p.y-slope*handle:p.y,outX:i<a.length-1?Math.min(next.x,p.x+handle):p.x,outY:i<a.length-1?p.y+slope*handle:p.y}})}
export default function BounceCurveEditor({config,duration,onChange,onClose,onGestureStart}:Props){
 const root=useRef<HTMLDivElement>(null),[pos,setPos]=useState({x:0,y:0}),[dragPanel,setDragPanel]=useState(false);
 useEffect(()=>{const el=root.current;if(!el)return;const r=el.getBoundingClientRect();setPos({x:Math.max(12,Math.min(innerWidth-r.width-12,r.left)),y:Math.max(12,Math.min(innerHeight-r.height-12,r.top))})},[]);
 const custom=config.preset==="custom",path=useMemo(()=>custom&&config.customCurve?.length?config.customCurve:simplifiedSpring(config,duration),[custom,config.customCurve,config.preset,config.bounce,config.velocity,duration]);
 const all=path.flatMap(p=>[p.y,p.inY,p.outY]),minY=Math.min(0,...all),maxY=Math.max(1,...all),range=Math.max(.2,maxY-minY),viewMin=minY-range*.22,viewMax=maxY+range*.22,W=480,H=280,pad=28;
 const px=(x:number)=>pad+x*(W-pad*2),py=(y:number)=>pad+(viewMax-y)/(viewMax-viewMin)*(H-pad*2);
 const commit=(next:BounceCurve)=>onChange({...config,preset:"custom",customCurve:next});
 const reset=()=>{onGestureStart?.();onChange({...config,preset:"single",bounce:.12,velocity:.55,distance:1,offscreen:false,customCurve:undefined})};
 const panelDown=(e:ReactPointerEvent)=>{if((e.target as HTMLElement).closest("button"))return;const start={clientX:e.clientX,clientY:e.clientY,panelX:pos.x,panelY:pos.y};setDragPanel(true);const move=(ev:PointerEvent)=>setPos({x:clamp(start.panelX+ev.clientX-start.clientX,8,innerWidth-(root.current?.offsetWidth??520)-8),y:clamp(start.panelY+ev.clientY-start.clientY,8,innerHeight-(root.current?.offsetHeight??400)-8)});const up=()=>{setDragPanel(false);removeEventListener("pointermove",move);removeEventListener("pointerup",up)};addEventListener("pointermove",move);addEventListener("pointerup",up)};
 const drag=(i:number,kind:"anchor"|"in"|"out",e:ReactPointerEvent<SVGCircleElement>)=>{e.preventDefault();e.stopPropagation();const svg=e.currentTarget.ownerSVGElement;if(!svg)return;onGestureStart?.();let current=clone(path);if(!custom)commit(current);const move=(ev:PointerEvent)=>{const r=svg.getBoundingClientRect(),x=clamp((ev.clientX-r.left)/r.width,0,1),y=viewMax-(ev.clientY-r.top)/r.height*(viewMax-viewMin),next=clone(current),p=next[i],left=i?next[i-1].x:0,right=i<next.length-1?next[i+1].x:1;if(kind==="anchor"){const nx=i===0?0:i===next.length-1?1:clamp(x,left+.004,right-.004),dx=nx-p.x,dy=y-p.y;p.x=nx;p.y=y;p.inX+=dx;p.inY+=dy;p.outX+=dx;p.outY+=dy}else{const inSide=kind==="in",kx=inSide?"inX":"outX",ky=inSide?"inY":"outY",ox=inSide?"outX":"inX",oy=inSide?"outY":"inY";p[kx]=inSide?clamp(x,left,p.x):clamp(x,p.x,right);p[ky]=y;if(!ev.altKey){const dx=p[kx]-p.x,dy=p[ky]-p.y,len=Math.hypot(dx,dy)||1,other=Math.hypot(p[ox]-p.x,p[oy]-p.y);p[ox]=p.x-dx/len*other;p[oy]=p.y-dy/len*other}}current=next;commit(next)};const up=()=>{removeEventListener("pointermove",move);removeEventListener("pointerup",up)};addEventListener("pointermove",move);addEventListener("pointerup",up)};
 const dbl=(i:number)=>{if(i===0||i===path.length-1)return;onGestureStart?.();const next=clone(path);next.splice(i,1);commit(next)};
 const add=(e:ReactPointerEvent<SVGPathElement>)=>{if(e.detail!==2)return;const svg=e.currentTarget.ownerSVGElement;if(!svg)return;onGestureStart?.();const r=svg.getBoundingClientRect(),x=clamp((e.clientX-r.left)/r.width,.005,.995),y=viewMax-(e.clientY-r.top)/r.height*(viewMax-viewMin),next=clone(path),idx=next.findIndex(p=>p.x>x);next.splice(idx<0?next.length-1:idx,0,point(x,y));commit(next)};
 const curve=path.slice(0,-1).map((p,i)=>`M${px(p.x)} ${py(p.y)} C ${px(p.outX)} ${py(p.outY)},${px(path[i+1].inX)} ${py(path[i+1].inY)},${px(path[i+1].x)} ${py(path[i+1].y)}`).join(" ");
 return <div ref={root} className={"bm-bounce-editor bm-floating-curve"+(dragPanel?" dragging":"")} style={{left:pos.x,top:pos.y}}><div className="bm-bounce-editor-head bm-curve-dragbar" onPointerDown={panelDown}><div><b>Value graph</b><small>{custom?"Custom bounce":config.preset+" spring"} · drag panel</small></div><div className="bm-curve-actions"><button title="Reset curve" onClick={reset}><RotateCcw size={16}/></button><button className="close" title="Close" onClick={onClose}>×</button></div></div>
 <svg viewBox={`0 0 ${W} ${H}`}><path className="grid" d={`M${pad} ${py(0)}H${W-pad} M${pad} ${py(1)}H${W-pad} M${px(.25)} ${pad}V${H-pad} M${px(.5)} ${pad}V${H-pad} M${px(.75)} ${pad}V${H-pad}`}/><path className="curve curve-hit" d={curve} onPointerDown={add}/><path className="curve" d={curve}/>
 {path.map((p,i)=><g key={i}><path className="guide" d={`M${px(p.inX)} ${py(p.inY)}L${px(p.x)} ${py(p.y)}L${px(p.outX)} ${py(p.outY)}`}/>{i>0&&<><circle className="hit" cx={px(p.inX)} cy={py(p.inY)} r="13" onPointerDown={e=>drag(i,"in",e)}/><circle className="handle" cx={px(p.inX)} cy={py(p.inY)} r="5"/></>}<circle className="hit" cx={px(p.x)} cy={py(p.y)} r="15" onDoubleClick={()=>dbl(i)} onPointerDown={e=>drag(i,"anchor",e)}/><circle className="anchor" cx={px(p.x)} cy={py(p.y)} r="6"/>{i<path.length-1&&<><circle className="hit" cx={px(p.outX)} cy={py(p.outY)} r="13" onPointerDown={e=>drag(i,"out",e)}/><circle className="handle" cx={px(p.outX)} cy={py(p.outY)} r="5"/></>}</g>)}</svg>
 <div className="bm-curve-footer"><span>Double-click curve: add · double-click point: delete · Alt/Option: break tangent</span></div></div>
}