import {useMemo,type PointerEvent as ReactPointerEvent} from "react";
import {RotateCcw,ZoomIn,ZoomOut} from "lucide-react";
import type {BounceConfig,BounceCurve} from "./sceneModel";
import {sampleSpring} from "./springRuntime";

type Props={config:BounceConfig;duration:number;onChange:(next:BounceConfig)=>void;onClose:()=>void;onGestureStart?:()=>void};
const clamp=(v:number,min:number,max:number)=>Math.min(max,Math.max(min,v));
const clone=(p:BounceCurve)=>p.map(v=>({...v}));
function sampledCustom(config:BounceConfig,duration:number):BounceCurve{const samples=sampleSpring(duration,config,6);return samples.map((p,i,a)=>{const prev=a[Math.max(0,i-1)],next=a[Math.min(a.length-1,i+1)],dx=(next.x-prev.x)/6,dy=(next.y-prev.y)/6;return{x:p.x,y:p.y,inX:p.x-dx,inY:p.y-dy,outX:p.x+dx,outY:p.y+dy}})}
export default function BounceCurveEditor({config,duration,onChange,onClose,onGestureStart}:Props){
 const custom=config.preset==="custom",path=useMemo(()=>custom&&config.customCurve?.length?config.customCurve:sampledCustom(config,duration),[custom,config.customCurve,config.preset,config.bounce,config.velocity,duration]);
 const all=path.flatMap(p=>[p.y,p.inY,p.outY]),minY=Math.min(0,...all),maxY=Math.max(1,...all),range=Math.max(.2,maxY-minY),viewMin=minY-range*.22,viewMax=maxY+range*.22,W=420,H=250,pad=26;
 const px=(x:number)=>pad+x*(W-pad*2),py=(y:number)=>pad+(viewMax-y)/(viewMax-viewMin)*(H-pad*2),toData=(clientX:number,clientY:number,svg:SVGSVGElement)=>{const r=svg.getBoundingClientRect();return{x:clamp((clientX-r.left-pad/r.width*r.width)/(r.width-pad/r.width*r.width*2),0,1),y:viewMax-(clientY-r.top)/r.height*(viewMax-viewMin)}};
 const reset=()=>{onGestureStart?.();onChange({...config,preset:"single",bounce:.12,velocity:.55,distance:1,offscreen:false,customCurve:undefined})};
 const drag=(i:number,kind:"anchor"|"in"|"out",e:ReactPointerEvent<SVGCircleElement>)=>{e.preventDefault();e.stopPropagation();const svg=e.currentTarget.ownerSVGElement;if(!svg)return;onGestureStart?.();let current=clone(path);if(!custom)onChange({...config,preset:"custom",customCurve:current});const move=(ev:PointerEvent)=>{const r=svg.getBoundingClientRect(),pos={x:clamp((ev.clientX-r.left)/(r.width),0,1),y:viewMax-(ev.clientY-r.top)/r.height*(viewMax-viewMin)},next=clone(current),p=next[i],left=i?next[i-1].x:0,right=i<next.length-1?next[i+1].x:1;if(kind==="anchor"){const nx=i===0?0:i===next.length-1?1:clamp(pos.x,left+.002,right-.002),dx=nx-p.x,dy=pos.y-p.y;p.x=nx;p.y=pos.y;p.inX+=dx;p.inY+=dy;p.outX+=dx;p.outY+=dy}else{const kx=kind==="in"?"inX":"outX",ky=kind==="in"?"inY":"outY",ox=kind==="in"?"outX":"inX",oy=kind==="in"?"outY":"inY";p[kx]=kind==="in"?Math.min(p.x,pos.x):Math.max(p.x,pos.x);p[ky]=pos.y;if(!ev.altKey){const dx=p[kx]-p.x,dy=p[ky]-p.y,len=Math.hypot(dx,dy)||1,other=Math.hypot(p[ox]-p.x,p[oy]-p.y);p[ox]=p.x-dx/len*other;p[oy]=p.y-dy/len*other}}current=next;onChange({...config,preset:"custom",customCurve:next})};const up=()=>{removeEventListener("pointermove",move);removeEventListener("pointerup",up)};addEventListener("pointermove",move);addEventListener("pointerup",up)};
 const curve=path.slice(0,-1).map((p,i)=>`M${px(p.x)} ${py(p.y)} C ${px(p.outX)} ${py(p.outY)},${px(path[i+1].inX)} ${py(path[i+1].inY)},${px(path[i+1].x)} ${py(path[i+1].y)}`).join(" ");
 return <div className="bm-bounce-editor"><div className="bm-bounce-editor-head"><div><b>Value graph</b><small>{custom?"Custom bounce":config.preset+" spring"} · time → / value ↑</small></div><div className="bm-curve-actions"><button title="Reset curve" onClick={reset}><RotateCcw size={13}/></button><button title="Close" onClick={onClose}>×</button></div></div>
  <svg viewBox={`0 0 ${W} ${H}`} preserveAspectRatio="none"><path className="grid" d={`M${pad} ${py(0)}H${W-pad} M${pad} ${py(1)}H${W-pad} M${px(.25)} ${pad}V${H-pad} M${px(.5)} ${pad}V${H-pad} M${px(.75)} ${pad}V${H-pad}`}/><path className="curve" d={curve}/>
  {path.map((p,i)=><g key={i}><path className="guide" d={`M${px(p.inX)} ${py(p.inY)}L${px(p.x)} ${py(p.y)}L${px(p.outX)} ${py(p.outY)}`}/>{i>0&&<><circle className="hit" cx={px(p.inX)} cy={py(p.inY)} r="13" onPointerDown={e=>drag(i,"in",e)}/><circle className="handle" cx={px(p.inX)} cy={py(p.inY)} r="5"/></>}<circle className="hit" cx={px(p.x)} cy={py(p.y)} r="15" onPointerDown={e=>drag(i,"anchor",e)}/><circle className="anchor" cx={px(p.x)} cy={py(p.y)} r="6"/>{i<path.length-1&&<><circle className="hit" cx={px(p.outX)} cy={py(p.outY)} r="13" onPointerDown={e=>drag(i,"out",e)}/><circle className="handle" cx={px(p.outX)} cy={py(p.outY)} r="5"/></>}</g>)}</svg>
  <div className="bm-curve-footer"><span>Drag points · Alt/Option: break tangent</span><button onClick={reset}><RotateCcw size={12}/> Reset</button></div></div>
}