import {useMemo,type PointerEvent as ReactPointerEvent} from "react";
import type {BounceConfig,BounceCurve,BouncePoint} from "./sceneModel";
import {sampleSpring,springConfig} from "./springRuntime";

type Props={config:BounceConfig;duration:number;onChange:(next:BounceConfig)=>void;onClose:()=>void};
const clamp=(v:number,min:number,max:number)=>Math.min(max,Math.max(min,v));
const clone=(p:BounceCurve)=>p.map(v=>({...v}));
function sampledCustom(config:BounceConfig,duration:number):BounceCurve{const samples=sampleSpring(duration,config,6);return samples.map((p,i,a)=>{const prev=a[Math.max(0,i-1)],next=a[Math.min(a.length-1,i+1)],dx=(next.x-prev.x)/6,dy=(next.y-prev.y)/6;return{x:p.x,y:p.y,inX:p.x-dx,inY:p.y-dy,outX:p.x+dx,outY:p.y+dy}})}
export default function BounceCurveEditor({config,duration,onChange,onClose}:Props){
 const custom=config.preset==="custom",path=useMemo(()=>custom&&config.customCurve?.length?config.customCurve:sampledCustom(config,duration),[custom,config.customCurve,config.preset,config.bounce,config.velocity,duration]);
 const all=path.flatMap(p=>[p.y,p.inY,p.outY]),minY=Math.min(0,...all),maxY=Math.max(1,...all),range=Math.max(.2,maxY-minY),viewMin=minY-range*.18,viewMax=maxY+range*.18,W=300,H=180,pad=18;
 const px=(x:number)=>pad+x*(W-pad*2),py=(y:number)=>pad+(viewMax-y)/(viewMax-viewMin)*(H-pad*2),toData=(clientX:number,clientY:number,svg:SVGSVGElement)=>{const r=svg.getBoundingClientRect();return{x:(clientX-r.left)/r.width,y:viewMax-(clientY-r.top)/r.height*(viewMax-viewMin)}};
 const makeCustom=()=>onChange({...config,preset:"custom",customCurve:clone(path)});
 const drag=(i:number,kind:"anchor"|"in"|"out",e:ReactPointerEvent<SVGCircleElement>)=>{e.preventDefault();e.stopPropagation();const svg=e.currentTarget.ownerSVGElement;if(!svg)return;if(!custom){onChange({...config,preset:"custom",customCurve:clone(path)});return}const move=(ev:PointerEvent)=>{const pos=toData(ev.clientX,ev.clientY,svg),next=clone(path),p=next[i],left=i?next[i-1].x:0,right=i<next.length-1?next[i+1].x:1;if(kind==="anchor"){const nx=i===0?0:i===next.length-1?1:clamp(pos.x,left+.002,right-.002),dx=nx-p.x,dy=pos.y-p.y;p.x=nx;p.y=pos.y;p.inX+=dx;p.inY+=dy;p.outX+=dx;p.outY+=dy}else{const kx=kind==="in"?"inX":"outX",ky=kind==="in"?"inY":"outY",ox=kind==="in"?"outX":"inX",oy=kind==="in"?"outY":"inY";p[kx]=kind==="in"?Math.min(p.x,pos.x):Math.max(p.x,pos.x);p[ky]=pos.y;if(!ev.altKey){const dx=p[kx]-p.x,dy=p[ky]-p.y,len=Math.hypot(dx,dy)||1,other=Math.hypot(p[ox]-p.x,p[oy]-p.y);p[ox]=p.x-dx/len*other;p[oy]=p.y-dy/len*other}}onChange({...config,preset:"custom",customCurve:next})};const up=()=>{removeEventListener("pointermove",move);removeEventListener("pointerup",up)};addEventListener("pointermove",move);addEventListener("pointerup",up)};
 const curve=path.slice(0,-1).map((p,i)=>`M${px(p.x)} ${py(p.y)} C ${px(p.outX)} ${py(p.outY)},${px(path[i+1].inX)} ${py(path[i+1].inY)},${px(path[i+1].x)} ${py(path[i+1].y)}`).join(" ");
 return <div className="bm-bounce-editor"><div className="bm-bounce-editor-head"><div><b>Bounce curve</b><small>{custom?"Custom":config.preset}</small></div><button onClick={onClose}>×</button></div>
  <svg viewBox={`0 0 ${W} ${H}`}><path className="grid" d={`M${pad} ${py(0)}H${W-pad} M${pad} ${py(1)}H${W-pad}`}/><path className="curve" d={curve}/>
  {path.map((p,i)=><g key={i}><path className="guide" d={`M${px(p.inX)} ${py(p.inY)}L${px(p.x)} ${py(p.y)}L${px(p.outX)} ${py(p.outY)}`}/>{i>0&&<circle className="handle" cx={px(p.inX)} cy={py(p.inY)} r="4" onPointerDown={e=>drag(i,"in",e)}/>}<circle className="anchor" cx={px(p.x)} cy={py(p.y)} r="5" onPointerDown={e=>drag(i,"anchor",e)}/>{i<path.length-1&&<circle className="handle" cx={px(p.outX)} cy={py(p.outY)} r="4" onPointerDown={e=>drag(i,"out",e)}/>}</g>)}</svg>
  {!custom&&<button className="bm-bounce-edit-custom" onClick={makeCustom}>Edit preset curve</button>}<small>Drag anchors or tangent handles. Alt/Option breaks a tangent. Viewport auto-fits overshoot.</small></div>
}