import {useEffect,useMemo,useRef,useState,type CSSProperties} from "react";
import {api} from "../mvp2/api";import type {Campaign} from "../mvp2/domain";import {ttForFormat,validateScenesForTT} from "./campaignBridge";
import {DEFAULT_SCENES,MASTER_FORMAT,RESPONSIVE_FAMILY_LABELS,formatInheritance,generateScene,normalizeResponsiveState,type GeneratedLayer,type LayoutFamily,type Scene} from "./sceneModel";
import {mergedDisplayFormats} from "./editorControls";import {registerCampaignFonts} from "./campaignFonts";import {layerVisibleAt,motionFrame} from "./motionRuntime";
import {DEFAULT_TRANSITION,matchLayer,sceneTransitionStyle,transitionBoxFor,transitionProgress} from "./transitionRuntime";
import "./sceneEditor.css";import "./editorProductV2.css";import "./responsiveMasters.css";
const FAMILY_ORDER:LayoutFamily[]=["portrait","tall","rectangle","wide","strip","micro-strip"];
const layerNode=(l:GeneratedLayer,localMs:number,extra:CSSProperties={},box=l.box,key=l.id)=><div key={key} className="bm-preview-object" style={{position:"absolute",left:`${box.x}%`,top:`${box.y}%`,width:`${box.w}%`,height:`${box.h}%`,background:l.kind==="shape"?l.color:undefined,color:l.color,fontFamily:l.fontFamily||"Inter",fontWeight:l.fontWeight,fontSize:l.fontSize,overflow:l.kind==="image"?"hidden":undefined,...motionFrame(l,localMs),...extra} as CSSProperties}>{l.kind==="image"&&l.assetUrl?<img src={l.assetUrl} alt="" loading="lazy" decoding="async" style={{width:"100%",height:"100%",objectFit:l.fit||"contain",transformOrigin:"center",transform:`translate(${l.crop?.x||0}%,${l.crop?.y||0}%) scale(${l.crop?.scale||1})`}}/>:l.kind==="text"?<span>{l.text}</span>:null}</div>;
export default function CampaignPreview(){
 const campaignId=new URLSearchParams(location.search).get("campaignId")||"",[campaign,setCampaign]=useState<Campaign|null>(null),[error,setError]=useState(""),[clock,setClock]=useState(0),[paused,setPaused]=useState(false),restartAt=useRef(performance.now()),pausedAt=useRef(0);
 useEffect(()=>{if(!campaignId){setError("Campaign id is missing");return}let alive=true;const timeout=window.setTimeout(()=>alive&&setError("Campaign preview is taking too long to load. Please retry."),15000);void api.campaign(campaignId).then(c=>{if(!alive)return;window.clearTimeout(timeout);setCampaign(c);void registerCampaignFonts(c.creativeDocument?.fonts||[])}).catch(e=>{window.clearTimeout(timeout);if(alive)setError(e instanceof Error?e.message:String(e))});return()=>{alive=false;window.clearTimeout(timeout)}},[campaignId]);
 useEffect(()=>{if(paused)return;let raf=0;const tick=(now:number)=>{setClock(now-restartAt.current);raf=requestAnimationFrame(tick)};raf=requestAnimationFrame(tick);return()=>cancelAnimationFrame(raf)},[paused]);
 const scenes=((campaign?.creativeDocument?.scenes as Scene[]|undefined)?.length?campaign!.creativeDocument!.scenes as Scene[]:DEFAULT_SCENES),responsive=normalizeResponsiveState({responsiveMasters:campaign?.creativeDocument?.responsiveMasters,formatOverrides:campaign?.creativeDocument?.formatOverrides}),formats=useMemo(()=>{const outputs=mergedDisplayFormats(campaign||undefined).filter(f=>f.width!==MASTER_FORMAT.width||f.height!==MASTER_FORMAT.height);return[MASTER_FORMAT,...outputs]},[campaign]),groups=FAMILY_ORDER.map(family=>({family,formats:formats.filter(format=>format.family===family).sort((a,b)=>a.width*a.height-b.width*b.height)})).filter(group=>group.formats.length),total=scenes.reduce((n,s)=>n+s.durationMs,0)||1,loopMs=clock%total;let local=loopMs,activeIndex=0;for(let i=0;i<scenes.length;i++){if(local<scenes[i].durationMs){activeIndex=i;break}local-=scenes[i].durationMs}const active=scenes[activeIndex],next=scenes[(activeIndex+1)%scenes.length],transition=active.transitionToNext??DEFAULT_TRANSITION,p=transitionProgress(local,active.durationMs,transition),transitioning=p>0&&transition.preset!=="none";
 const restart=()=>{restartAt.current=performance.now();pausedAt.current=0;setClock(0);setPaused(false)},togglePause=()=>setPaused(value=>{if(!value){pausedAt.current=clock;return true}restartAt.current=performance.now()-pausedAt.current;return false});
 if(error)return <main className="bm-campaign-wall"><h2>Could not open preview</h2><p>{error}</p><button onClick={()=>location.reload()}>Retry</button> <button onClick={()=>history.back()}>Back</button></main>;if(!campaign)return <main className="bm-campaign-wall">Loading campaign preview…</main>;
 return <main className="bm-campaign-wall"><header><div><b>{campaign.name}</b><div>All Formats Preview · Scene {activeIndex+1}/{scenes.length}{transitioning?` · ${transition.preset} ${transition.durationMs}ms`:""}</div></div><div><button onClick={()=>{location.href=`/?view=scene-editor&campaignId=${encodeURIComponent(campaign.id)}`}}>← Back to editor</button> <button onClick={togglePause}>{paused?"Play":"Pause"}</button> <button onClick={restart}>Restart all</button></div></header>{groups.map(group=><section className="bm-preview-family" key={group.family}><div className="bm-preview-family-head"><h2>{RESPONSIVE_FAMILY_LABELS[group.family]}</h2><span>{group.formats.length} formats</span></div><div className="bm-campaign-wall-grid">{group.formats.map(format=>{const out=generateScene(active,format,responsive),nextOut=generateScene(next,format,responsive),tt=format.id==="master"?undefined:ttForFormat(campaign,format.id),check=validateScenesForTT(scenes,tt),inheritance=formatInheritance(format,responsive);return <article className={`bm-campaign-card inheritance-${inheritance.kind}`} key={`${format.id}-${format.width}x${format.height}`}><div className="bm-preview-card-head"><div><h3>{format.width}×{format.height}</h3><small>{format.id==="master"?"Original Master":format.label} · {format.id==="master"?"design source":`TT ${check.status}`}</small></div></div><div className="bm-campaign-card-stage"><div className="bm-preview-frame" style={{width:`${format.width}px`,height:`${format.height}px`}}><div className="bm-preview-scene" style={{position:"absolute",inset:0}}>{out.layers.filter(l=>l.visible&&layerVisibleAt(l,local)).map(l=>{const match=matchLayer(l,nextOut.layers),shared=!!match&&l.role!=="headline"&&l.role!=="copy"&&l.role!=="background",box=transitioning&&shared?transitionBoxFor(l,nextOut.layers,transition.preset,p):l.box;return layerNode(l,local,transitioning?sceneTransitionStyle(transition.preset,l.role,"out",p,shared):{},box,`out-${l.id}`)})}{transitioning&&nextOut.layers.filter(l=>l.visible).map(l=>{const prior=matchLayer(l,out.layers),shared=!!prior&&l.role!=="headline"&&l.role!=="copy"&&l.role!=="background";if(shared)return null;return layerNode(l,Math.min(transition.durationMs*p,l.endMs),sceneTransitionStyle(transition.preset,l.role,"in",p,false),l.box,`in-${l.id}`)})}</div></div></div></article>})}</div></section>)}</main>
}