import {useEffect,useRef,useState} from "react";
import {api} from "../mvp2/api";
import type {Campaign,CampaignFont} from "../mvp2/domain";

const styleFromName=(name:string)=>{const n=name.toLowerCase();if(/bold|700/.test(n))return {style:"Bold" as const,weight:700};if(/semi.?bold|600/.test(n))return {style:"Semibold" as const,weight:600};if(/medium|500/.test(n))return {style:"Medium" as const,weight:500};return {style:"Regular" as const,weight:400}};
const familyFromName=(name:string)=>name.replace(/\.(woff2?|ttf|otf)$/i,"").replace(/[-_](regular|medium|semi.?bold|bold|400|500|600|700).*$/i,"").replace(/[-_]+/g," ").trim()||"Campaign Font";
const readDataUrl=(file:File)=>new Promise<string>((resolve,reject)=>{const r=new FileReader();r.onload=()=>resolve(String(r.result));r.onerror=()=>reject(r.error);r.readAsDataURL(file)});
async function registerFont(font:CampaignFont){if(typeof FontFace==="undefined")return;const face=new FontFace(font.family,`url(${font.dataUrl})`,{weight:String(font.weight),style:"normal"});await face.load();document.fonts.add(face)}
function syncFontOptions(fonts:CampaignFont[]){const families=[...new Set(fonts.map(f=>f.family))];for(const select of document.querySelectorAll("select")){const label=select.closest("label")?.querySelector("small")?.textContent?.trim();if(label!=="FONT FAMILY")continue;for(const family of families)if(![...select.options].some(o=>o.value===family)){const option=document.createElement("option");option.value=family;option.textContent=`${family} · Campaign`;select.append(option)}}}

export default function CampaignFonts({campaign,onCampaign}:{campaign:Campaign;onCampaign:(campaign:Campaign)=>void}){
 const [fonts,setFonts]=useState<CampaignFont[]>(campaign.creativeDocument?.fonts||[]),[open,setOpen]=useState(false),[busy,setBusy]=useState(false),[error,setError]=useState("");const input=useRef<HTMLInputElement>(null);
 useEffect(()=>{const list=campaign.creativeDocument?.fonts||[];setFonts(list);void Promise.all(list.map(f=>registerFont(f).catch(()=>undefined))).then(()=>syncFontOptions(list))},[campaign.id]);
 useEffect(()=>{syncFontOptions(fonts);const observer=new MutationObserver(()=>syncFontOptions(fonts));observer.observe(document.body,{subtree:true,childList:true});return()=>observer.disconnect()},[fonts]);
 const upload=async(file?:File)=>{if(!file)return;setError("");if(!/\.(woff2?|ttf|otf)$/i.test(file.name)){setError("Use WOFF, WOFF2, TTF or OTF");return}if(file.size>4*1024*1024){setError("Font file must be 4 MB or smaller");return}setBusy(true);try{const dataUrl=await readDataUrl(file),meta=styleFromName(file.name),font:CampaignFont={id:`font-${crypto.randomUUID()}`,family:familyFromName(file.name),style:meta.style,weight:meta.weight,fileName:file.name,dataUrl};await registerFont(font);const fresh=await api.campaign(campaign.id),nextFonts=[...(fresh.creativeDocument?.fonts||[]).filter(f=>!(f.family===font.family&&f.weight===font.weight)),font],creativeDocument={...(fresh.creativeDocument||{version:2,masterFormat:{width:300,height:600},scenes:[]}),version:Math.max(2,fresh.creativeDocument?.version||1),fonts:nextFonts,updatedAt:new Date().toISOString()};const updated=await api.saveSceneDocument(campaign.id,creativeDocument);setFonts(nextFonts);onCampaign(updated);syncFontOptions(nextFonts);setOpen(true)}catch(e){setError(e instanceof Error?e.message:String(e))}finally{setBusy(false);if(input.current)input.current.value=""}};
 const remove=async(id:string)=>{setBusy(true);setError("");try{const fresh=await api.campaign(campaign.id),nextFonts=(fresh.creativeDocument?.fonts||[]).filter(f=>f.id!==id),creativeDocument={...(fresh.creativeDocument||{version:2,masterFormat:{width:300,height:600},scenes:[]}),version:Math.max(2,fresh.creativeDocument?.version||1),fonts:nextFonts,updatedAt:new Date().toISOString()};const updated=await api.saveSceneDocument(campaign.id,creativeDocument);setFonts(nextFonts);onCampaign(updated)}catch(e){setError(e instanceof Error?e.message:String(e))}finally{setBusy(false)}};
 return <div style={{position:"fixed",right:18,top:66,zIndex:80,fontFamily:"Inter,system-ui"}}><input ref={input} hidden type="file" accept=".woff,.woff2,.ttf,.otf,font/woff,font/woff2,font/ttf,font/otf" onChange={e=>void upload(e.target.files?.[0])}/><button onClick={()=>setOpen(v=>!v)} style={{border:"1px solid #303642",background:"#171b22",color:"#eef2f7",borderRadius:8,padding:"8px 11px",fontSize:12,cursor:"pointer"}}>Fonts · {fonts.length}</button>{open&&<div style={{position:"absolute",right:0,top:40,width:300,background:"#11151b",border:"1px solid #303642",borderRadius:10,padding:12,boxShadow:"0 18px 50px #0008",color:"#eef2f7"}}><div style={{display:"flex",justifyContent:"space-between",alignItems:"center",gap:12}}><div><b style={{fontSize:13}}>Campaign Fonts</b><div style={{fontSize:11,color:"#8f98a7",marginTop:3}}>WOFF/WOFF2/TTF/OTF · max 4 MB</div></div><button disabled={busy} onClick={()=>input.current?.click()} style={{border:0,borderRadius:7,padding:"7px 10px",background:"#665cff",color:"white",cursor:"pointer"}}>{busy?"Saving…":"Upload"}</button></div>{error&&<div style={{fontSize:11,color:"#ff7777",marginTop:9}}>{error}</div>}<div style={{display:"grid",gap:6,marginTop:10}}>{fonts.length===0?<div style={{fontSize:11,color:"#8f98a7",padding:"8px 0"}}>No uploaded fonts yet.</div>:fonts.map(font=><div key={font.id} style={{display:"grid",gridTemplateColumns:"1fr auto",gap:8,alignItems:"center",padding:"8px",borderRadius:7,background:"#181d25"}}><div style={{minWidth:0}}><div style={{fontFamily:font.family,fontSize:14,whiteSpace:"nowrap",overflow:"hidden",textOverflow:"ellipsis"}}>{font.family}</div><small style={{color:"#8f98a7"}}>{font.style} · {font.weight}</small></div><button disabled={busy} onClick={()=>void remove(font.id)} style={{border:0,background:"transparent",color:"#8f98a7",cursor:"pointer"}}>×</button></div>)}</div></div>}</div>
}
