import {useEffect,useMemo,useRef,useState,type CSSProperties} from "react";
import {api} from "../mvp2/api";
import type {Campaign} from "../mvp2/domain";
import {ttForFormat,validateScenesForTT} from "./campaignBridge";
import {DEFAULT_SCENES,MASTER_FORMAT,RESPONSIVE_FAMILY_LABELS,formatInheritance,generateScene,normalizeResponsiveState,type LayoutFamily,type Scene} from "./sceneModel";
import {mergedDisplayFormats} from "./editorControls";
import {registerCampaignFonts} from "./campaignFonts";
import {layerVisibleAt,motionFrame} from "./motionRuntime";
import "./sceneEditor.css";
import "./editorProductV2.css";
import "./responsiveMasters.css";
const FAMILY_ORDER:LayoutFamily[]=["portrait","tall","rectangle","wide","strip","micro-strip"];
const PREVIEW_MAX_WIDTH=520,PREVIEW_MAX_HEIGHT=300;
const previewSize=(width:number,height:number)=>{const scale=Math.min(PREVIEW_MAX_WIDTH/width,PREVIEW_MAX_HEIGHT/height,1);return{width:Math.max(1,Math.round(width*scale)),height:Math.max(1,Math.round(height*scale))}};
export default function CampaignPreview(){
 const campaignId=new URLSearchParams(location.search).get("campaignId")||"",[campaign,setCampaign]=useState<Campaign|null>(null),[error,setError]=useState(""),[clock,setClock]=useState(0),[paused,setPaused]=useState(false),restartAt=useRef(performance.now()),pausedAt=useRef(0);
 useEffect(()=>{if(!campaignId){setError("Campaign id is missing");return}let alive=true;const timeout=window.setTimeout(()=>alive&&setError("Campaign preview is taking too long to load. Please retry."),15000);void api.campaign(campaignId).then(c=>{if(!alive)return;window.clearTimeout(timeout);setCampaign(c);void registerCampaignFonts(c.creativeDocument?.fonts||[])}).catch(e=>{window.clearTimeout(timeout);if(alive)setError(e instanceof Error?e.message:String(e))});return()=>{alive=false;window.clearTimeout(timeout)}},[campaignId]);
 useEffect(()=>{if(paused)return;let raf=0;const tick=(now:number)=>{setClock(now-restartAt.current);raf=requestAnimationFrame(tick)};raf=requestAnimationFrame(tick);return()=>cancelAnimationFrame(raf)},[paused]);
 const scenes=((campaign?.creativeDocument?.scenes as Scene[]|undefined)?.length?campaign!.creativeDocument!.scenes as Scene[]:DEFAULT_SCENES),responsive=normalizeResponsiveState({responsiveMasters:campaign?.creativeDocument?.responsiveMasters,formatOverrides:campaign?.creativeDocument?.formatOverrides}),formats=useMemo(()=>{const outputs=mergedDisplayFormats(campaign||undefined).filter(f=>f.width!==MASTER_FORMAT.width||f.height!==MASTER_FORMAT.height);return [MASTER_FORMAT,...outputs]},[campaign]),groups=FAMILY_ORDER.map(family=>({family,formats:formats.filter(format=>format.family===family).sort((a,b)=>{const ma=formatInheritance(a,responsive),mb=formatInheritance(b,responsive);return Number(mb.kind==="responsive-master")-Number(ma.kind==="responsive-master")||Number(mb.kind==="original")-Number(ma.kind==="original")||a.width*a.height-b.width*b.height})})).filter(group=>group.formats.length),total=scenes.reduce((n,s)=>n+s.durationMs,0)||1;let local=clock%total,active=scenes[0];for(const s of scenes){if(local<s.durationMs){active=s;break}local-=s.durationMs}
 const restart=()=>{restartAt.current=performance.now();pausedAt.current=0;setClock(0);setPaused(false)},togglePause=()=>setPaused(value=>{if(!value){pausedAt.current=clock;return true}restartAt.current=performance.now()-pausedAt.current;return false});
 if(error)return <main className="bm-campaign-wall"><h2>Could not open preview</h2><p>{error}</p><button onClick={()=>location.reload()}>Retry</button> <button onClick={()=>history.back()}>Back</button></main>;if(!campaign)return <main className="bm-campaign-wall">Loading campaign preview…</main>;
 return <main className="bm-campaign-wall"><header><div><b>{campaign.name}</b><div>All Formats Preview · media plan formats · Scene {scenes.indexOf(active)+1}/{scenes.length} · {(local/1000).toFixed(2)}s</div></div><div><button onClick={()=>{location.href=`/?view=scene-editor&campaignId=${encodeURIComponent(campaign.id)}`}}>← Back to editor</button> <button onClick={togglePause}>{paused?"Play":"Pause"}</button> <button onClick={restart}>Restart all</button></div></header>{groups.map(group=><section className="bm-preview-family" key={group.family}><div className="bm-preview-family-head"><h2>{RESPONSIVE_FAMILY_LABELS[group.family]}</h2><span>{group.formats.length} formats</span></div><div className="bm-campaign-wall-grid">{group.formats.map(format=>{const out=generateScene(active,format,responsive),tt=format.id==="master"?undefined:ttForFormat(campaign,format.id),check=validateScenesForTT(scenes,tt),inheritance=formatInheritance(format,responsive),preview=previewSize(format.width,format.height);return <article className={`bm-campaign-card inheritance-${inheritance.kind}`} key={`${format.id}-${format.width}x${format.height}`}><div className="bm-preview-card-head"><div><h3>{format.id==="master"?`Original Master · ${format.width}×${format.height}`:format.label}</h3><small>{format.width} × {format.height}{format.id==="master"?" · design source":` · TT ${check.status}`}</small></div><em>{inheritance.kind==="original"?"Original Master":inheritance.kind==="responsive-master"?"Responsive Master":inheritance.kind==="individual"?`${inheritance.overrideCount} overrides`:"Inherited"}</em></div>{inheritance.sourceLabel&&inheritance.sourceFormatId!==format.id&&<p className="bm-based-on">Based on {inheritance.sourceLabel}</p>}<div className="bm-campaign-card-stage"><div style={{width:`min(100%, ${preview.width}px)`,aspectRatio:`${format.width}/${format.height}`}}>{out.layers.filter(l=>l.visible&&layerVisibleAt(l,local)).map(l=><div key={`${active.id}-${l.id}`} className="bm-preview-object" style={{position:"absolute",left:`${l.box.x}%`,top:`${l.box.y}%`,width:`${l.box.w}%`,height:`${l.box.h}%`,background:l.kind==="shape"?l.color:undefined,color:l.color,fontFamily:l.fontFamily||"Inter",fontWeight:l.fontWeight,fontSize:l.fontSize,overflow:l.kind==="image"?"hidden":undefined,...motionFrame(l,local)} as CSSProperties}>{l.kind==="image"&&l.assetUrl?<img src={l.assetUrl} alt="" loading="lazy" decoding="async" style={{width:"100%",height:"100%",objectFit:l.fit||"contain",transformOrigin:"center",transform:`translate(${l.crop?.x||0}%,${l.crop?.y||0}%) scale(${l.crop?.scale||1})`}}/>:l.kind==="text"?<span>{l.text}</span>:null}</div>)}</div></div></article>})}</div></section>)}</main>
}
