import {resolveSceneLayers,type OutputFormat,type ResponsiveState,type Scene} from "./sceneModel";

const html=(value:unknown)=>String(value??"").replace(/[&<>"']/g,char=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[char]!));
const css=(value:unknown)=>String(value??"").replace(/[<>{};]/g,"");
const motionName=(value:string|undefined)=>({"from-left":"bm-left","from-right":"bm-right","from-top":"bm-top","from-bottom":"bm-bottom","scale-in":"bm-scale",fade:"bm-fade",bounce:"bm-bounce"}[value||""]||"bm-fade");

export function renderSceneDocumentHtml(scenes:Scene[],format:OutputFormat,responsive:ResponsiveState){
  const total=Math.max(1,scenes.reduce((sum,scene)=>sum+scene.durationMs,0));
  const sceneMarkup=scenes.map((scene,index)=>{
    const layers=resolveSceneLayers(scene,format,responsive).filter(layer=>layer.visible);
    return `<section class="bm-scene${index===0?" active":""}" data-duration="${Math.max(200,scene.durationMs)}">${layers.map(layer=>{
      const style=`left:${layer.box.x}%;top:${layer.box.y}%;width:${layer.box.w}%;height:${layer.box.h}%;color:${css(layer.color||"#fff")};opacity:${Math.max(0,Math.min(100,layer.opacity??100))/100};font:${Number(layer.fontWeight||400)} ${Number(layer.fontSize||16)}px/${1.15} ${css(layer.fontFamily||"Arial")};animation-name:${motionName(layer.motion)};animation-duration:${Math.max(0,layer.motionDurationMs)}ms;animation-delay:${Math.max(0,layer.startMs)}ms`;
      const body=layer.kind==="image"&&layer.assetUrl?`<img src="${html(layer.assetUrl)}" alt="" style="object-fit:${layer.fit||"contain"};transform:translate(${layer.crop?.x||0}%,${layer.crop?.y||0}%) scale(${layer.crop?.scale||1})">`:layer.kind==="text"?`<span>${html(layer.text||"")}</span>`:"";
      return `<div class="bm-layer bm-${html(layer.kind)}" data-role="${html(layer.role)}" style="${style};${layer.kind==="shape"?`background:${css(layer.color||"transparent")}`:""}">${body}</div>`;
    }).join("")}</section>`;
  }).join("");
  return `<!doctype html><html><head><meta charset="utf-8"><meta name="ad.size" content="width=${format.width},height=${format.height}"><meta name="bm.duration" content="${total}"><style>*{box-sizing:border-box}html,body{margin:0;width:${format.width}px;height:${format.height}px;overflow:hidden;background:#111}.bm-scene{position:absolute;inset:0;display:none;overflow:hidden}.bm-scene.active{display:block}.bm-layer{position:absolute;overflow:hidden;animation-fill-mode:both;animation-timing-function:ease-out}.bm-layer span{display:block;width:100%;height:100%;white-space:pre-wrap;overflow-wrap:anywhere}.bm-layer img{display:block;width:100%;height:100%;transform-origin:center}@keyframes bm-fade{from{opacity:0}to{opacity:1}}@keyframes bm-left{from{opacity:0;transform:translateX(-25%)}to{opacity:1;transform:none}}@keyframes bm-right{from{opacity:0;transform:translateX(25%)}to{opacity:1;transform:none}}@keyframes bm-top{from{opacity:0;transform:translateY(-25%)}to{opacity:1;transform:none}}@keyframes bm-bottom{from{opacity:0;transform:translateY(25%)}to{opacity:1;transform:none}}@keyframes bm-scale{from{opacity:0;transform:scale(.75)}to{opacity:1;transform:none}}@keyframes bm-bounce{0%{opacity:0;transform:translateY(-30%)}70%{opacity:1;transform:translateY(4%)}100%{opacity:1;transform:none}}</style></head><body>${sceneMarkup}<script>(()=>{const scenes=[...document.querySelectorAll('.bm-scene')];let index=0,timer;function show(next){scenes.forEach((scene,i)=>{scene.classList.toggle('active',i===next);if(i===next){scene.querySelectorAll('.bm-layer').forEach(layer=>{layer.getAnimations().forEach(animation=>animation.cancel());void layer.offsetWidth})}});clearTimeout(timer);timer=setTimeout(()=>show((next+1)%scenes.length),Number(scenes[next].dataset.duration)||1000)}if(scenes.length)show(index)})();<\/script></body></html>`;
}
