import {promises as fs} from "node:fs";import path from "node:path";
const scale=f=>Number(f.exportScale)===2?2:1,physical=f=>({width:f.width*scale(f),height:f.height*scale(f)});
const assetId=l=>l.provenance?.assetId||String(l.assetUrl||"").replace(/^asset:\/\//,"");
export function exportDiagnostics(campaign,document){const diagnostics=[];for(const f of campaign.formats||[]){const p=physical(f);for(const scene of document?.scenes||[])for(const l of scene.layers||[]){const id=assetId(l),a=document?.assets?.[id];if(!a)continue;const box=l.masterBox||l.box||{},placed={width:f.width*Number(box.w||0)/100,height:f.height*Number(box.h||0)/100},required={width:Math.ceil(placed.width*scale(f)),height:Math.ceil(placed.height*scale(f))};if(!a.vector&&a.sourceWidth&&a.sourceHeight&&(a.sourceWidth<required.width||a.sourceHeight<required.height))diagnostics.push({severity:"blocking",type:"density",formatId:f.id,layerId:l.id,assetId:id,message:`${l.name||id}: source ${a.sourceWidth}×${a.sourceHeight}, required ≥${required.width}×${required.height} for @${scale(f)}x`})}if(f.maxBytes&&Number(f.maxBytes)<1024)diagnostics.push({severity:"blocking",type:"weight",formatId:f.id,message:`Weight limit ${f.maxBytes} B is not safely achievable`});diagnostics.push({severity:"info",type:"physical-size",formatId:f.id,message:`${p.width}×${p.height} @${scale(f)}x`})}return diagnostics}
export function exportPlan(campaign,document){const diagnostics=exportDiagnostics(campaign,document);return{formats:(campaign.formats||[]).map(f=>{const p=physical(f),layers=(document?.scenes||[]).flatMap(s=>(s.layers||[]).map(l=>{const id=assetId(l),a=document?.assets?.[id],role=l.semanticRole||l.role;return{id:l.id,name:l.name,role,assetId:id||null,vector:Boolean(a?.vector),preserveVector:Boolean(a?.vector||role==="logo"),preserveText:l.kind==="text",compressionPriority:role==="product"||role==="hero"?"high":role==="background"?"aggressive":"normal"}}));return{formatId:f.id,logical:{width:f.width,height:f.height},physical:p,exportScale:scale(f),exportType:f.exportType||"html5",maxBytes:f.maxBytes||null,layers}}),diagnostics,valid:!diagnostics.some(d=>d.severity==="blocking")}}
export function qualityCandidates(type){if(type==="png")return[100];if(type==="jpg"||type==="webp")return[92,86,80,74,68,60,52,44,36,28];return[100]}
export function chooseQuality({type,maxBytes,encode}){let best=null;for(const quality of qualityCandidates(type)){const bytes=encode(quality);if(!maxBytes||bytes<=maxBytes){best={quality,bytes};break}best={quality,bytes}}return{...best,withinLimit:!maxBytes||best.bytes<=maxBytes}}
export async function optimizeRaster({inputPath,outputPath,width,height,type,maxBytes,role="normal",processor}){if(typeof processor!=="function")throw new Error("Raster processor is required");const result=await processor({inputPath,width,height,type,qualities:qualityCandidates(type),maxBytes,compressionPriority:role==="background"?"aggressive":role==="product"||role==="hero"?"high":"normal"});if(!result?.bytes)throw new Error("Raster processor returned no bytes");if(maxBytes&&result.bytes.length>maxBytes)return{ok:false,blocking:true,bytes:result.bytes.length,maxBytes,message:`Cannot meet ${maxBytes} byte limit without unsafe degradation`};await fs.mkdir(path.dirname(outputPath),{recursive:true});await fs.writeFile(outputPath,result.bytes);return{ok:true,bytes:result.bytes.length,quality:result.quality,width,height,type}}
export function preserveRepresentation(layer,asset){if(layer.kind==="text")return{text:true,mode:"dom-or-vector"};if(asset?.vector||layer.semanticRole==="logo")return{vector:true,mode:"svg"};return{vector:false,mode:"raster"}}
