import crypto from "node:crypto";import {promises as fs} from "node:fs";import path from "node:path";import {validateImportedAsset} from "./figmaHardening.mjs";
const hash=value=>crypto.createHash("sha256").update(typeof value==="string"?value:JSON.stringify(value)).digest("hex");
const idFor=(prefix,...parts)=>prefix+"-"+hash(parts.join("|")).slice(0,18),clone=v=>v==null?v:structuredClone(v);
const roleFor=l=>l.semantic?.role==="product"?"hero":l.semantic?.role==="decor"?"graphic":l.semantic?.role==="unknown"?"graphic":l.semantic?.role||"graphic";
const sceneLayer=(l,assetId,frame,scene)=>({id:idFor("figma-layer",frame.frame.id,l.figmaNodeId),name:l.name,kind:l.kind==="text"?"text":l.kind==="shape"?"shape":"image",role:roleFor(l),semanticRole:l.semantic?.role||"unknown",masterBox:clone(l.box),text:l.text,color:l.fill,assetUrl:assetId?"asset://"+assetId:undefined,fit:l.scaleMode==="FIT"?"contain":"cover",fontSize:l.style?.fontSize,fontWeight:l.style?.fontWeight,fontFamily:l.style?.fontFamily,opacity:l.opacity??1,motion:"none",motionDurationMs:400,easing:"ease-out",startMs:0,endMs:scene.durationMs,visible:true,provenance:{origin:"figma",assetId,fileKey:frame.fileKey,nodeId:l.figmaNodeId,nodeName:l.name,frameNodeId:frame.frame.id,fingerprint:hash({name:l.name,kind:l.kind,box:l.box,text:l.text,imageRef:l.imageRef,semantic:l.semantic})}});
async function download(url){const res=await fetch(url,{signal:AbortSignal.timeout(15000)});if(!res.ok)throw Object.assign(new Error("Figma asset download failed: "+res.status),{status:502});return validateImportedAsset({bytes:Buffer.from(await res.arrayBuffer()),mime:res.headers.get("content-type")||"application/octet-stream"})}
export async function materializeFigmaAssets({workspaceId,fileKey,frames,exportNodes,assetRoot}){const nodes=[];for(const f of frames)for(const l of f.layers||[])if(["image","vector","fallback"].includes(l.kind))nodes.push(l.figmaNodeId);const unique=[...new Set(nodes)],exports=unique.length?await exportNodes(workspaceId,fileKey,unique,"png",2):{images:{}};const assets={};await fs.mkdir(assetRoot,{recursive:true});for(const f of frames)for(const l of f.layers||[]){if(!unique.includes(l.figmaNodeId))continue;const url=exports.images?.[l.figmaNodeId];if(!url)throw Object.assign(new Error("Figma did not return export for node "+l.figmaNodeId),{status:502});const got=await download(url),assetId=idFor("asset",fileKey,l.figmaNodeId),name=assetId+".png",target=path.join(assetRoot,name);await fs.writeFile(target,got.bytes,{mode:0o600});assets[assetId]={id:assetId,origin:"figma",sourceWidth:l.asset?.sourceWidth||Math.round(f.frame.width*(l.box?.w||0)/100*2),sourceHeight:l.asset?.sourceHeight||Math.round(f.frame.height*(l.box?.h||0)/100*2),mimeType:got.mime,storageUrl:"/api/assets/"+name,vector:false,figma:{fileKey,nodeId:l.figmaNodeId,nodeName:l.name},fingerprint:hash(got.bytes)}}return assets}
export function applyFigmaImport({document,frames,assets,sceneId="scene-1",fileKey}){const before=clone(document),next=clone(document)||{version:1,masterFormat:{width:300,height:600},scenes:[]};next.assets={...(next.assets||{}),...assets};const scene=next.scenes.find(s=>s.id===sceneId)||next.scenes[0]||{id:sceneId,name:"Scene 01",durationMs:2200,layers:[]};if(!next.scenes.some(s=>s.id===scene.id))next.scenes.push(scene);const importedIds=new Set();next.formatOverrides={...(next.formatOverrides||{})};for(const frame of frames){const formatId=frame.target?.id;if(!formatId)continue;const imported=frame.layers.map(l=>{const assetId=Object.values(assets).find(a=>a.figma?.nodeId===l.figmaNodeId)?.id,layer=sceneLayer(l,assetId,{...frame,fileKey},scene);importedIds.add(layer.id);return layer});next.formatOverrides[formatId]={...(next.formatOverrides[formatId]||{}),figmaImport:{fileKey,frameNodeId:frame.frame.id,fingerprint:hash(frame),layerIds:imported.map(l=>l.id)},scenes:{...(next.formatOverrides[formatId]?.scenes||{}),[scene.id]:{sceneId:scene.id,layers:Object.fromEntries(imported.map(l=>[l.id,{...l,box:l.masterBox}]))}}};}next.updatedAt=new Date().toISOString();next.version=Number(next.version||0)+1;return{before,next,checkpoint:{kind:"figma-import",createdAt:new Date().toISOString(),document:before},importedLayerIds:[...importedIds]}}
export function undoFigmaImport(result){return clone(result?.checkpoint?.document)}
export {hash as figmaFingerprint};

export function geometryFamily(width,height){const ratio=width/height;if(height<=60)return "micro-strip";if(height<=120||ratio>=5)return "strip";if(ratio>=2.3)return "wide";if(height/width>=1.7)return "tall";if(height>width)return "portrait";return "rectangle"}
const cloneLayerState=l=>({...clone(l),box:clone(l.box||l.masterBox),masterBox:undefined});
export function promoteFigmaImportsToFamilyMasters(document,formats,formatIds){const next=clone(document),selected=new Set(formatIds||[]),candidates=[];next.responsiveMasters=Array.isArray(next.responsiveMasters)?next.responsiveMasters:[];for(const format of formats||[]){if(selected.size&&!selected.has(format.id))continue;const imported=next.formatOverrides?.[format.id]?.figmaImport,sceneStates=next.formatOverrides?.[format.id]?.scenes;if(!imported||!sceneStates)continue;const family=geometryFamily(format.width,format.height),scenes={};for(const [sceneId,state] of Object.entries(sceneStates)){scenes[sceneId]={sceneId,layers:Object.fromEntries(Object.entries(state.layers||{}).map(([id,l])=>[id,cloneLayerState(l)]))}}const master={id:"responsive-"+family+"-"+format.id,family,sourceFormatId:format.id,width:format.width,height:format.height,label:format.size||format.label||format.id,scenes,updatedAt:new Date().toISOString(),origin:"figma-import",figmaImport:clone(imported)};next.responsiveMasters=[...next.responsiveMasters.filter(m=>m.family!==family),master];delete next.formatOverrides[format.id];candidates.push({formatId:format.id,size:format.size,family,masterId:master.id})}next.updatedAt=new Date().toISOString();next.version=Number(next.version||0)+1;return{next,candidates}}
export function figmaFamilyMasterCandidates(document,formats){return (formats||[]).filter(f=>document?.formatOverrides?.[f.id]?.figmaImport).map(f=>({formatId:f.id,size:f.size,width:f.width,height:f.height,family:geometryFamily(f.width,f.height),status:"MASTER"}))}
