import crypto from "node:crypto";
const MAX_FILE_BYTES=Math.max(1024,Number(process.env.FIGMA_IMPORT_MAX_BYTES)||12*1024*1024),MAX_NODES=Math.max(1,Number(process.env.FIGMA_IMPORT_MAX_NODES)||160),MAX_CONCURRENT=Math.max(1,Number(process.env.FIGMA_IMPORT_MAX_CONCURRENT)||2),WINDOW_MS=60_000,RATE_MAX=Math.max(1,Number(process.env.FIGMA_IMPORT_RATE_MAX)||30);
const active=new Map(),rates=new Map(),metrics={imports:0,importFailures:0,unknownRoles:0,totalRoles:0,updateConflicts:0,exportFailures:0,oversizeFiles:0,rateLimited:0};
export function sanitizeSvg(input){let s=String(input||"");s=s.replace(/<script[\s\S]*?<\/script\s*>/gi,"").replace(/<foreignObject[\s\S]*?<\/foreignObject\s*>/gi,"").replace(/\son\w+\s*=\s*("[^"]*"|'[^']*'|[^\s>]+)/gi,"").replace(/\s(?:href|xlink:href)\s*=\s*("|')\s*(?:javascript:|data:text\/html)[\s\S]*?\1/gi,"");return s}
export function validateImportedAsset({bytes,mime}){const size=bytes?.length||0,type=String(mime||"").split(";")[0].trim().toLowerCase(),allowed=new Set(["image/png","image/jpeg","image/webp","image/gif","image/svg+xml","application/octet-stream"]);if(!allowed.has(type))throw Object.assign(new Error("Unsupported imported asset MIME type: "+type),{status:415});if(size>MAX_FILE_BYTES){metrics.oversizeFiles++;throw Object.assign(new Error("Imported asset exceeds file-size limit"),{status:413})}let body=Buffer.from(bytes||[]);if(type==="image/svg+xml")body=Buffer.from(sanitizeSvg(body.toString("utf8")));return{bytes:body,mime:type,size:body.length}}
export function validateNodeBatch(nodeIds){const ids=[...new Set((nodeIds||[]).filter(Boolean).map(String))];if(ids.length>MAX_NODES)throw Object.assign(new Error(`Figma node limit exceeded (${ids.length}/${MAX_NODES})`),{status:413});return ids}
export function rateLimit(key){const now=Date.now(),list=(rates.get(key)||[]).filter(t=>now-t<WINDOW_MS);if(list.length>=RATE_MAX){metrics.rateLimited++;throw Object.assign(new Error("Figma bridge rate limit exceeded"),{status:429})}list.push(now);rates.set(key,list)}
export async function withImportLimit(workspaceId,fn){const n=active.get(workspaceId)||0;if(n>=MAX_CONCURRENT)throw Object.assign(new Error("Too many concurrent Figma imports"),{status:429});active.set(workspaceId,n+1);try{return await fn()}finally{const left=(active.get(workspaceId)||1)-1;if(left)active.set(workspaceId,left);else active.delete(workspaceId)}}
export function recordImportPlan(plan){metrics.imports++;for(const item of plan?.items||[]){metrics.unknownRoles+=Number(item.unknownLayers?.length||item.semantic?.unknown||0);metrics.totalRoles+=Number(item.layerCount||0)}}
export function recordImportFailure(){metrics.importFailures++}export function recordUpdateConflicts(n){metrics.updateConflicts+=Number(n||0)}export function recordExportFailure(){metrics.exportFailures++}
export function figmaBridgeMetrics(){return{...metrics,unknownRoleRate:metrics.totalRoles?metrics.unknownRoles/metrics.totalRoles:0,updateConflictRate:metrics.imports?metrics.updateConflicts/metrics.imports:0,limits:{maxFileBytes:MAX_FILE_BYTES,maxNodes:MAX_NODES,maxConcurrent:MAX_CONCURRENT,ratePerMinute:RATE_MAX}}}
export function resetHardeningState(){active.clear();rates.clear();for(const k of Object.keys(metrics))metrics[k]=0}
