import crypto from "node:crypto";import {promises as fs} from "node:fs";import path from "node:path";import {rateLimit,validateNodeBatch} from "./figmaHardening.mjs";

const API="https://api.figma.com/v1";
const timeoutMs=()=>Math.max(1000,Number(process.env.FIGMA_API_TIMEOUT_MS)||12000);
const keyMaterial=()=>process.env.FIGMA_CREDENTIAL_KEY||process.env.BANNERMATIC_SESSION_SECRET||"";
function key(){const material=keyMaterial();if(!material)throw Object.assign(new Error("FIGMA_CREDENTIAL_KEY is not configured"),{status:503});return crypto.createHash("sha256").update(material).digest()}
function seal(value){const iv=crypto.randomBytes(12),cipher=crypto.createCipheriv("aes-256-gcm",key(),iv),body=Buffer.concat([cipher.update(String(value),"utf8"),cipher.final()]);return [iv.toString("base64url"),cipher.getAuthTag().toString("base64url"),body.toString("base64url")].join(".")}
function open(value){const [a,b,c]=String(value||"").split(".");if(!a||!b||!c)throw new Error("Invalid encrypted credential");const decipher=crypto.createDecipheriv("aes-256-gcm",key(),Buffer.from(a,"base64url"));decipher.setAuthTag(Buffer.from(b,"base64url"));return Buffer.concat([decipher.update(Buffer.from(c,"base64url")),decipher.final()]).toString("utf8")}
const credentials=new Map(),credentialPath=()=>process.env.FIGMA_CREDENTIAL_STORE||path.resolve(process.cwd(),"runtime/figma-credentials.json");let loaded=false;async function loadCredentials(){if(loaded)return;loaded=true;try{const raw=JSON.parse(await fs.readFile(credentialPath(),"utf8"));for(const [k,v] of Object.entries(raw||{}))credentials.set(k,v)}catch(e){if(e?.code!=="ENOENT")throw e}}async function saveCredentials(){await fs.mkdir(path.dirname(credentialPath()),{recursive:true});const target=credentialPath(),tmp=target+"."+process.pid+"."+crypto.randomBytes(4).toString("hex")+".tmp";await fs.writeFile(tmp,JSON.stringify(Object.fromEntries(credentials)),{mode:0o600});await fs.rename(tmp,target);await fs.chmod(target,0o600)}
await loadCredentials();
export function figmaCredentialStatus(workspaceId){const item=credentials.get(workspaceId);return{connected:Boolean(item),connectedAt:item?.connectedAt||null,lastValidatedAt:item?.lastValidatedAt||null,state:item?"connected":"not_connected"}}
export async function disconnectFigma(workspaceId){await loadCredentials();credentials.delete(workspaceId);await saveCredentials();return{state:"not_connected",connected:false}}
async function request(token,path,{method="GET",body,retries=2}={}){let last;for(let attempt=0;attempt<=retries;attempt++){const controller=new AbortController(),timer=setTimeout(()=>controller.abort(),timeoutMs());try{const response=await fetch(API+path,{method,headers:{"X-Figma-Token":token,...(body?{"Content-Type":"application/json"}:{})},body:body?JSON.stringify(body):undefined,signal:controller.signal});if(response.status===401||response.status===403)throw Object.assign(new Error("Figma credential is invalid or revoked"),{status:401,revoked:true});if(response.status===429||response.status>=500){const wait=Math.min(1500,250*2**attempt);last=Object.assign(new Error(`Figma API ${response.status}`),{status:response.status});if(attempt<retries){await new Promise(r=>setTimeout(r,wait));continue}}if(!response.ok)throw Object.assign(new Error(`Figma API ${response.status}: ${(await response.text()).slice(0,300)}`),{status:response.status});return await response.json()}catch(e){last=e;if(e?.revoked)throw e;if(attempt>=retries)throw Object.assign(new Error(e?.name==="AbortError"?"Figma API timeout":e?.message||String(e)),{status:e?.name==="AbortError"?504:e?.status||502})}finally{clearTimeout(timer)}}throw last}
function guard(workspaceId){rateLimit(String(workspaceId||"unknown"))}
async function tokenFor(workspaceId){await loadCredentials();const item=credentials.get(workspaceId);if(!item)throw Object.assign(new Error("Figma is not connected"),{status:409});return open(item.secret)}
export async function connectFigma(workspaceId,token){await loadCredentials();if(!token||String(token).length<10)throw Object.assign(new Error("Figma access token is required"),{status:400});const me=await request(String(token),"/me",{retries:0});credentials.set(workspaceId,{secret:seal(token),connectedAt:new Date().toISOString(),lastValidatedAt:new Date().toISOString()});await saveCredentials();return{state:"connected",connected:true,user:{id:me.id,handle:me.handle,email:me.email||null}}}
export async function validateFigma(workspaceId){try{const me=await request(await tokenFor(workspaceId),"/me",{retries:0}),item=credentials.get(workspaceId);if(item){item.lastValidatedAt=new Date().toISOString();await saveCredentials()}return{...figmaCredentialStatus(workspaceId),user:{id:me.id,handle:me.handle,email:me.email||null}}}catch(e){if(e?.revoked){credentials.delete(workspaceId);await saveCredentials()}throw e}}
export async function getFigmaFile(workspaceId,fileKey,depth){guard(workspaceId);const q=depth?`?depth=${encodeURIComponent(depth)}`:"";return request(await tokenFor(workspaceId),`/files/${encodeURIComponent(fileKey)}${q}`)}
export async function getFigmaNodes(workspaceId,fileKey,nodeIds){guard(workspaceId);const ids=validateNodeBatch(Array.isArray(nodeIds)?nodeIds:[nodeIds]).join(",");return request(await tokenFor(workspaceId),`/files/${encodeURIComponent(fileKey)}/nodes?ids=${encodeURIComponent(ids)}`)}
export async function exportFigmaNodes(workspaceId,fileKey,nodeIds,format="png",scale=1){guard(workspaceId);const ids=validateNodeBatch(Array.isArray(nodeIds)?nodeIds:[nodeIds]).join(",");return request(await tokenFor(workspaceId),`/images/${encodeURIComponent(fileKey)}?ids=${encodeURIComponent(ids)}&format=${encodeURIComponent(format)}&scale=${encodeURIComponent(scale)}`)}
export async function getFigmaVersions(workspaceId,fileKey){guard(workspaceId);return request(await tokenFor(workspaceId),`/files/${encodeURIComponent(fileKey)}/versions`)}
export async function listFigmaFiles(workspaceId,{projectId,teamId}={}){guard(workspaceId);if(projectId)return request(await tokenFor(workspaceId),`/projects/${encodeURIComponent(projectId)}/files`);if(teamId){const projects=await request(await tokenFor(workspaceId),`/teams/${encodeURIComponent(teamId)}/projects`);const files=[];for(const project of projects.projects||[]){const result=await request(await tokenFor(workspaceId),`/projects/${encodeURIComponent(project.id)}/files`);files.push(...(result.files||[]).map(file=>({...file,projectId:project.id,projectName:project.name})))}return{files}}throw Object.assign(new Error("projectId or teamId is required"),{status:400})}
export function figmaPages(file){return (file?.document?.children||[]).filter(n=>n.type==="CANVAS").map(n=>({id:n.id,name:n.name,children:n.children||[]}))}
export function figmaFrames(file){return figmaPages(file).flatMap(page=>(page.children||[]).filter(n=>["FRAME","COMPONENT","INSTANCE"].includes(n.type)).map(n=>({id:n.id,name:n.name,type:n.type,pageId:page.id,pageName:page.name,width:n.absoluteBoundingBox?.width||0,height:n.absoluteBoundingBox?.height||0})))}
