import {describe,expect,it} from "vitest";import {normalizeFigmaFrame,normalizeFigmaNodeResponse} from "./figmaLayerNormalizer.mjs";
const frame={id:"f",name:"300x250",type:"FRAME",absoluteBoundingBox:{x:100,y:200,width:300,height:250},children:[
{id:"t",name:"Headline",type:"TEXT",characters:"Hello",opacity:.8,rotation:5,absoluteBoundingBox:{x:130,y:220,width:150,height:40},style:{fontFamily:"Inter",fontSize:24,fontWeight:700},fills:[{type:"SOLID",color:{r:1,g:1,b:1}}]},
{id:"img",name:"Hero",type:"RECTANGLE",absoluteBoundingBox:{x:100,y:260,width:300,height:140},fills:[{type:"IMAGE",imageRef:"abc",scaleMode:"CROP",imageTransform:[[1,0,0],[0,1,0]]}]},
{id:"v",name:"Logo",type:"VECTOR",absoluteBoundingBox:{x:110,y:210,width:60,height:20}},
{id:"r",name:"CTA",type:"RECTANGLE",cornerRadius:8,absoluteBoundingBox:{x:200,y:410,width:100,height:30},fills:[{type:"SOLID",color:{r:1,g:0,b:0},opacity:.5}]},
{id:"e",name:"Dot",type:"ELLIPSE",absoluteBoundingBox:{x:370,y:210,width:20,height:20},fills:[{type:"SOLID",color:{r:0,g:1,b:0}}]},
{id:"g",name:"Group",type:"GROUP",absoluteBoundingBox:{x:120,y:300,width:80,height:80},children:[{id:"gt",name:"Copy",type:"TEXT",characters:"Nested",absoluteBoundingBox:{x:130,y:310,width:60,height:20}}]},
{id:"nested",name:"Nested frame",type:"FRAME",layoutMode:"VERTICAL",absoluteBoundingBox:{x:250,y:300,width:100,height:80},children:[{id:"nt",name:"Nested text",type:"TEXT",characters:"Inside",absoluteBoundingBox:{x:260,y:310,width:60,height:20}}]},
{id:"fx",name:"Blurred",type:"RECTANGLE",absoluteBoundingBox:{x:100,y:200,width:50,height:50},effects:[{type:"DROP_SHADOW",visible:true}]},
{id:"mask",name:"Mask",type:"RECTANGLE",isMask:true,absoluteBoundingBox:{x:100,y:200,width:40,height:40}},
{id:"blend",name:"Blend",type:"RECTANGLE",blendMode:"MULTIPLY",absoluteBoundingBox:{x:100,y:200,width:40,height:40}},
{id:"odd",name:"Plugin-ish unsupported",type:"WIDGET",absoluteBoundingBox:{x:100,y:200,width:40,height:40}}
]};
describe("Figma layer normalization",()=>{it("normalizes supported nodes and frame-relative geometry without runtime Figma layout",()=>{const n=normalizeFigmaFrame(frame);expect(n.frame).toEqual({id:"f",name:"300x250",width:300,height:250});expect(n.layers.find(x=>x.figmaNodeId==="t")).toMatchObject({kind:"text",text:"Hello",editable:true,opacity:.8,rotation:5,box:{x:10,y:8,w:50,h:16}});expect(n.layers.find(x=>x.figmaNodeId==="img")).toMatchObject({kind:"image",imageRef:"abc",scaleMode:"CROP",asset:{origin:"figma",vector:false,sourceWidth:300,sourceHeight:140}});expect(n.layers.find(x=>x.figmaNodeId==="v")).toMatchObject({kind:"vector",asset:{origin:"figma",vector:true,mimeType:"image/svg+xml"}});expect(n.layers.find(x=>x.figmaNodeId==="r")).toMatchObject({kind:"shape",shape:"rectangle",cornerRadius:8});expect(n.layers.find(x=>x.figmaNodeId==="e")).toMatchObject({kind:"shape",shape:"ellipse"});expect(n.groups.map(x=>x.figmaNodeId)).toEqual(["g","nested"]);expect(n.groups.find(x=>x.figmaNodeId==="nested").layoutMode).toBe("VERTICAL");expect(n.layers.find(x=>x.figmaNodeId==="nt").parentId).toBe("nested")});it("preserves unsupported visual structures as explicit export fallbacks",()=>{const n=normalizeFigmaFrame(frame);for(const id of ["fx","mask","blend","odd"])expect(n.layers.find(x=>x.figmaNodeId===id)).toMatchObject({kind:"fallback",preserveVisual:true,exportNodeId:id});expect(n.requiresFallback).toBe(true)});it("keeps source z-order and image crop metadata",()=>{const n=normalizeFigmaFrame(frame);expect(n.layers.map(x=>x.zIndex)).toEqual([...n.layers.map(x=>x.zIndex)].sort((a,b)=>a-b));expect(n.layers.find(x=>x.figmaNodeId==="img").crop.imageTransform).toBeTruthy()});it("normalizes selected node response only",()=>{const out=normalizeFigmaNodeResponse({nodes:{f:{document:frame},other:{document:{...frame,id:"other"}}}},["f"]);expect(out).toHaveLength(1);expect(out[0].frame.id).toBe("f")})});