const ROLES=["background","product","logo","headline","cta","legal","decor","unknown"];
const aliases={background:["background","bg","backdrop","фон"],product:["product","hero","car","packshot","device","subject","продукт"],logo:["logo","brand","mark","логотип"],headline:["headline","title","heading","h1","заголовок"],cta:["cta","button","btn","action","кнопка"],legal:["legal","disclaimer","terms","copyright","18+","age","дисклеймер"],decor:["decor","decoration","accent","shape","ornament","spark","star","декор"]};
export const normalizeSemanticName=value=>String(value||"").toLowerCase().replace(/[_\-.]+/g," ").replace(/\s+/g," ").trim();
const aliasRole=name=>{const n=normalizeSemanticName(name);for(const [role,words] of Object.entries(aliases))if(words.some(w=>n===w||n.startsWith(w+" ")||n.endsWith(" "+w)||n.includes(" "+w+" ")))return role;return null};
const area=l=>Math.max(0,Number(l.box?.w)||0)*Math.max(0,Number(l.box?.h)||0);
function deterministic(layer){const named=aliasRole(layer.name);if(named)return{role:named,confidence:.99,source:"rule",signals:["name"]};const a=area(layer),y=Number(layer.box?.y)||0,w=Number(layer.box?.w)||0,h=Number(layer.box?.h)||0;
 if(layer.kind==="text"){const text=normalizeSemanticName(layer.text);if(/^(buy|shop|learn more|discover|start|go|купить|подробнее|начать)$/.test(text)||a<12&&y>55)return{role:"cta",confidence:.72,source:"rule",signals:["node-type","position","relative-size"]};if(/18\+|terms|conditions|copyright|©|legal|disclaimer/.test(text)||Number(layer.style?.fontSize||99)<=10&&y>70)return{role:"legal",confidence:.82,source:"rule",signals:["node-type","position","relative-size"]};if(y<45&&(Number(layer.style?.fontSize)||0)>=18)return{role:"headline",confidence:.76,source:"rule",signals:["node-type","position","relative-size"]};}
 if((layer.kind==="image"||layer.kind==="fallback")&&a>=55)return{role:"background",confidence:.7,source:"rule",signals:["node-type","relative-size"]};
 if((layer.kind==="image"||layer.kind==="vector")&&a>=12&&a<55)return{role:"product",confidence:.58,source:"rule",signals:["node-type","relative-size"]};
 if((layer.kind==="vector"||layer.kind==="shape")&&w<35&&h<25)return{role:"decor",confidence:.56,source:"rule",signals:["node-type","relative-size"]};
 return{role:"unknown",confidence:0,source:"rule",signals:[]}}
export function mapSemanticLayers(layers,overrides={}){return(layers||[]).map(layer=>{const manual=overrides[layer.figmaNodeId];if(manual&&ROLES.includes(manual))return{...layer,semantic:{role:manual,confidence:1,source:"user",signals:["manual"]}};return{...layer,semantic:deterministic(layer)}})}
export function ambiguousSemanticLayers(mapped,threshold=.75){return(mapped||[]).filter(l=>l.semantic?.role==="unknown"||Number(l.semantic?.confidence||0)<threshold).map(l=>({id:l.figmaNodeId,name:l.name,nodeType:l.nodeType,kind:l.kind,box:l.box,text:l.kind==="text"?String(l.text||"").slice(0,120):undefined,currentRole:l.semantic?.role,confidence:l.semantic?.confidence}))}
export function applyAiSemanticRoles(mapped,answers=[]){const byId=new Map((answers||[]).filter(a=>ROLES.includes(a.role)).map(a=>[String(a.id),a]));return(mapped||[]).map(layer=>{if(layer.semantic?.source==="user"||layer.semantic?.confidence>=.75)return layer;const ai=byId.get(String(layer.figmaNodeId));return ai?{...layer,semantic:{role:ai.role,confidence:Math.max(0,Math.min(1,Number(ai.confidence)||0)),source:"ai",signals:["ambiguous-ai"]}}:layer})}
export function semanticSummary(mapped){const roles=Object.fromEntries(ROLES.map(r=>[r,0]));for(const l of mapped||[])roles[l.semantic?.role||"unknown"]++;return{total:(mapped||[]).length,recognized:(mapped||[]).filter(l=>l.semantic?.role!=="unknown").length,unknown:(mapped||[]).filter(l=>l.semantic?.role==="unknown").length,roles}}
export {ROLES as SEMANTIC_ROLES};
