import {describe,it,expect} from 'vitest';
import {campaignCompliance,placementCompliance} from './mvp2Compliance.mjs';
const placement:any={id:'p1',platform:'Yandex',placement:'ROS',width:300,height:250,requirements:{maxZipKb:150,maxDurationSec:6,clickTag:true,tracking:true,impressionUrl:'https://tracker.test/pixel',sourceLabel:'Client TT'}};
const base:any={id:'c1',creativeVersion:2,mediaPlanVersion:1,ttSnapshotVersion:1,placements:[placement],formats:[{id:'f1',width:300,height:250,placementIds:['p1'],creativeState:'published',estimatedZipKb:120,durationSec:5,clickTagPresent:true}]};
describe('MVP2 compliance',()=>{
 it('marks fully compliant placement ready',()=>{const result=placementCompliance(base,placement);expect(result.status).toBe('ready');expect(result.checks.every((c:any)=>c.status==='ready')).toBe(true)});
 it('blocks oversize or over-duration creative and exposes an explicit Figma fix action',()=>{const c={...base,formats:[{...base.formats[0],estimatedZipKb:180,durationSec:8}]};const result=placementCompliance(c,placement);expect(result.status).toBe('blocked');expect(result.checks.find((c:any)=>c.name==='zip')?.status).toBe('blocked');expect(result.checks.find((c:any)=>c.name==='duration')?.fix?.type).toBe('open-figma')});
 it('preserves unknown instead of inventing unpublished metadata',()=>{const c={...base,formats:[{...base.formats[0],estimatedZipKb:undefined,durationSec:undefined,clickTagPresent:undefined}]};const result=placementCompliance(c,placement);expect(result.status).toBe('warning');expect(result.unknown).toBeGreaterThan(0)});
 it('validates safe zones and required creative elements when TT defines them',()=>{const p={...placement,requirements:{...placement.requirements,safeZone:'20px',requiredElements:['logo','cta']}};const good={...base,placements:[p],formats:[{...base.formats[0],safeZonePassed:true,presentElements:['logo','cta']}]};expect(placementCompliance(good,p).status).toBe('ready');const bad={...good,formats:[{...good.formats[0],safeZonePassed:false,presentElements:['logo']}]};const result=placementCompliance(bad,p);expect(result.status).toBe('blocked');expect(result.checks.find((c:any)=>c.name==='safe-zone')?.fix?.type).toBe('open-figma');expect(result.checks.find((c:any)=>c.name==='required-elements')?.detail).toContain('cta')});
 it('keeps safe-zone and required-element checks unknown when publish has no evidence',()=>{const p={...placement,requirements:{...placement.requirements,safeZone:'20px',requiredElements:['logo']}};const result=placementCompliance({...base,placements:[p]},p);expect(result.status).toBe('warning');expect(result.checks.filter((c:any)=>['safe-zone','required-elements'].includes(c.name)).every((c:any)=>c.status==='unknown')).toBe(true)});
 it('summarizes readiness N/N',()=>{expect(campaignCompliance(base).summary).toEqual({ready:1,warning:0,blocked:0,total:1})});
});
