import {afterEach,describe,expect,it} from "vitest";
import {mkdtemp,rm} from "node:fs/promises";
import os from "node:os";
import path from "node:path";
import {BannermaticStore} from "./mvp2Store.mjs";

const dirs:string[]=[];
async function makeStore(){const dir=await mkdtemp(path.join(os.tmpdir(),"bannermatic-"));dirs.push(dir);return new BannermaticStore(path.join(dir,"db.json"));}
afterEach(async()=>{while(dirs.length)await rm(dirs.pop()!,{recursive:true,force:true})});

describe("BannermaticStore",()=>{
 it("registers, persists and restores authenticated owner sessions",async()=>{const store=await makeStore();const created=await store.register({email:"Owner@Example.com",password:"verystrong",name:"Mike"});expect(created.role).toBe("owner");expect(created.user.email).toBe("owner@example.com");const restored=new BannermaticStore(store.filePath);const auth=await restored.authenticate(created.token);expect(auth?.user.email).toBe("owner@example.com");expect(auth?.workspace.id).toBe(created.workspace.id)});
 it("rejects bad credentials",async()=>{const store=await makeStore();await store.register({email:"a@b.com",password:"12345678",name:"A"});await expect(store.login({email:"a@b.com",password:"wrongpass"})).rejects.toMatchObject({status:401})});
 it("creates workspace campaigns and keeps them scoped to authenticated workspace",async()=>{const store=await makeStore();const created=await store.register({email:"owner@b.com",password:"12345678",name:"Owner"});const auth=await store.authenticate(created.token);const campaign=await store.createCampaign(auth!,{name:"Nike September",locale:"ru"});expect(campaign.name).toBe("Nike September");expect(store.listCampaigns(auth!)).toHaveLength(1);const next=await store.updateCampaign(auth!,campaign.id,{placements:[{id:"p1"}],mediaPlanVersion:2});expect(next.mediaPlanVersion).toBe(2);expect(next.placements).toEqual([{id:"p1"}])});
 it("enforces role permissions",async()=>{const store=await makeStore();const created=await store.register({email:"owner@c.com",password:"12345678",name:"Owner"});const auth=await store.authenticate(created.token);expect(()=>store.requireRole({...auth!,role:"viewer"} as any,["owner","admin"])).toThrow("Forbidden")});
 it("creates one-time Figma pairing codes and scopes plugin session to one campaign",async()=>{const store=await makeStore();const created=await store.register({email:"figma@example.com",password:"12345678",name:"Designer"});const auth=await store.authenticate(created.token);const first=await store.createCampaign(auth!,{name:"Campaign A",locale:"en"}),second=await store.createCampaign(auth!,{name:"Campaign B",locale:"en"});const pair=await store.createFigmaPair(auth!,first.id);expect(pair.code).toMatch(/^\d{6}$/);const claimed=await store.claimFigmaPair(pair.code);expect(claimed.campaignId).toBe(first.id);const plugin=await store.authenticatePlugin(claimed.token);expect(plugin?.campaign.id).toBe(first.id);expect(plugin?.campaign.id).not.toBe(second.id);await expect(store.claimFigmaPair(pair.code)).rejects.toMatchObject({status:404})});
 it("exposes the visible Browser to Figma handoff state for the same campaign",async()=>{const store=await makeStore();const created=await store.register({email:"handoff@example.com",password:"12345678",name:"Designer"});const auth=await store.authenticate(created.token);const campaign=await store.createCampaign(auth!,{name:"Launch",locale:"en"});expect(store.figmaConnectionStatus(auth!,campaign.id).state).toBe("not_connected");const pair=await store.createFigmaPair(auth!,campaign.id);expect(store.figmaConnectionStatus(auth!,campaign.id)).toMatchObject({campaignId:campaign.id,campaignName:"Launch",state:"ready_to_continue"});await store.claimFigmaPair(pair.code);expect(store.figmaConnectionStatus(auth!,campaign.id)).toMatchObject({campaignId:campaign.id,state:"connected"})});
 it("replaces an unused pairing code while preserving an already connected plugin session",async()=>{const store=await makeStore();const created=await store.register({email:"reconnect@example.com",password:"12345678",name:"Designer"});const auth=await store.authenticate(created.token);const campaign=await store.createCampaign(auth!,{name:"Reconnect",locale:"en"});const connectedPair=await store.createFigmaPair(auth!,campaign.id),plugin=await store.claimFigmaPair(connectedPair.code);const first=await store.createFigmaPair(auth!,campaign.id),replacement=await store.createFigmaPair(auth!,campaign.id);expect(replacement.code).not.toBe(first.code);await expect(store.claimFigmaPair(first.code)).rejects.toMatchObject({status:404});expect((await store.authenticatePlugin(plugin.token))?.campaign.id).toBe(campaign.id);expect(store.figmaConnectionStatus(auth!,campaign.id).state).toBe("connected")});
 it("renames and deletes a campaign with its pending and active Figma connections",async()=>{const store=await makeStore();const created=await store.register({email:"lifecycle@example.com",password:"12345678",name:"Owner"});const auth=await store.authenticate(created.token);const campaign=await store.createCampaign(auth!,{name:"Draft name",locale:"en"});const renamed=await store.updateCampaign(auth!,campaign.id,{name:"Launch name"});expect(renamed.name).toBe("Launch name");const activePair=await store.createFigmaPair(auth!,campaign.id),plugin=await store.claimFigmaPair(activePair.code);const pending=await store.createFigmaPair(auth!,campaign.id);expect(await store.deleteCampaign(auth!,campaign.id)).toMatchObject({id:campaign.id,name:"Launch name"});expect(store.listCampaigns(auth!)).toHaveLength(0);expect(await store.authenticatePlugin(plugin.token)).toBeNull();await expect(store.claimFigmaPair(pending.code)).rejects.toMatchObject({status:404});await expect(store.deleteCampaign(auth!,campaign.id)).rejects.toMatchObject({status:404})});
 it("does not allow viewer role to issue a Figma pairing code",async()=>{const store=await makeStore();const created=await store.register({email:"viewer@example.com",password:"12345678",name:"Viewer"});const auth=await store.authenticate(created.token);const campaign=await store.createCampaign(auth!,{name:"Scoped",locale:"en"});await expect(store.createFigmaPair({...auth!,role:"viewer"} as any,campaign.id)).rejects.toMatchObject({status:403})});
 it("invites a new member with a scoped role and accepts the invite into the existing workspace",async()=>{const store=await makeStore();const owner=await store.register({email:"owner@team.com",password:"12345678",name:"Owner"});const auth=await store.authenticate(owner.token);const invite=await store.createInvitation(auth!,{email:"designer@team.com",role:"designer"});expect(invite.role).toBe("designer");expect(store.listInvitations(auth!)).toHaveLength(1);const joined=await store.acceptInvitation({token:invite.token,password:"designer-pass",name:"Designer"});expect(joined.workspace.id).toBe(owner.workspace.id);expect(joined.role).toBe("designer");const joinedAuth=await store.authenticate(joined.token);expect(joinedAuth?.workspace.id).toBe(owner.workspace.id);expect(store.listMembers(auth!).some(m=>m.user?.email==="designer@team.com"&&m.role==="designer")).toBe(true);expect(store.listInvitations(auth!)).toHaveLength(0)});
});
