import {createHash,randomUUID} from 'node:crypto';
import {createPlacementPackage} from './mvp2Packaging.mjs';
import {productionCampaign} from '../src/mvp2/production.mjs';
import {promises as fs} from 'node:fs';
import path from 'node:path';
import {campaignCompliance} from './mvp2Compliance.mjs';

const now=()=>new Date().toISOString();const buildId=()=>`bld_${randomUUID()}`;

export function createCampaignBuildManifest(input,{artifacts={}}={}){const campaign=productionCampaign(input),compliance=campaignCompliance(input);let deliveryBlocked=false;const placements=(campaign.placements||[]).map(p=>{const format=(campaign.formats||[]).find(f=>(f.placementIds||[]).includes(p.id)),pkg=createPlacementPackage(format,p,artifacts),maxBytes=Number(p.requirements?.maxZipKb||0)*1000,issues=[];if(!pkg.files.length)issues.push(`Missing rendered ${pkg.outputType} artifact for ${format?.size||`${p.width}×${p.height}`}`);if(maxBytes&&pkg.packageBytes>maxBytes)issues.push(`Output is ${pkg.packageBytes} B; placement limit is ${maxBytes} B`);if(issues.length)deliveryBlocked=true;const digest=pkg.files.length?createHash('sha256').update(pkg.files.map(file=>String(file.content||'')).join('|')).digest('hex'):'';return{placementId:p.id,packageBytes:pkg.packageBytes,platform:p.platform,placement:p.placement,width:p.width,height:p.height,formatId:format?.id||null,creativeVersion:Number(format?.creativeVersion||0),previewUrl:format?.previewUrl||'',previewHtml:format?.previewHtml||'',previewSvg:format?.previewSvg||'',previewType:format?.previewType||'',durationSec:Number.isFinite(Number(format?.durationSec))?Number(format.durationSec):null,estimatedZipKb:pkg.packageBytes/1000,clickTagPresent:Boolean(p.requirements?.clickUrl)||format?.clickTagPresent===true,impressionUrl:p.requirements?.impressionUrl||'',clickUrl:p.requirements?.clickUrl||'',ttSource:p.requirements?.sourceLabel||p.requirements?.sourceUrl||'',outputType:pkg.outputType,fileName:pkg.fileName,mimeType:pkg.mimeType,sha256:digest,status:issues.length?'blocked':compliance.placements.find(x=>x.placementId===p.sourcePlacementId||x.placementId===p.id)?.status||'blocked',deliveryIssues:issues,files:pkg.files};});const blocked=compliance.summary.blocked>0||compliance.summary.warning>0||!campaign.placements?.length||deliveryBlocked;const exact={ready:placements.filter(p=>p.status==='ready').length,warning:placements.filter(p=>p.status==='warning').length,blocked:placements.filter(p=>p.status==='blocked').length,total:placements.length};return{id:buildId(),campaignId:campaign.id,campaignName:campaign.name,createdAt:now(),state:blocked?'blocked':'ready',pins:{creativeVersion:Number(campaign.creativeVersion||0),mediaPlanVersion:Number(campaign.mediaPlanVersion||0),ttSnapshotVersion:Number(campaign.ttSnapshotVersion||0)},compliance:exact,placements};}
export class BuildStore{constructor(filePath,artifactStore=null){this.filePath=filePath;this.artifactStore=artifactStore;this.items=[];this.loaded=false;this.writeQueue=Promise.resolve();}async load(){if(this.loaded)return this;try{this.items=JSON.parse(await fs.readFile(this.filePath,'utf8'));}catch(error){if(error?.code!=='ENOENT')throw error;await fs.mkdir(path.dirname(this.filePath),{recursive:true});await this.persist();}this.loaded=true;return this;}async persist(){await fs.mkdir(path.dirname(this.filePath),{recursive:true});const payload=JSON.stringify(this.items,null,2),temp=`${this.filePath}.tmp`;this.writeQueue=this.writeQueue.then(async()=>{await fs.writeFile(temp,payload,{mode:0o600});await fs.rename(temp,this.filePath)});return this.writeQueue;}list(campaignId){return this.items.filter(x=>x.campaignId===campaignId).map(x=>structuredClone(x)).sort((a,b)=>String(b.createdAt).localeCompare(String(a.createdAt)));}async create(campaign){await this.load();const artifacts=this.artifactStore?await this.artifactStore.contents(campaign.id):{};const build=createCampaignBuildManifest(campaign,{artifacts});this.items.push(build);await this.persist();return structuredClone(build);}get(campaignId,id){const item=this.items.find(x=>x.campaignId===campaignId&&x.id===id);return item?structuredClone(item):null;}async deleteCampaign(campaignId){await this.load();this.items=this.items.filter(x=>x.campaignId!==campaignId);await this.persist();}}
