import {publishTemplate} from '../src/mvp2/production.mjs';
import {campaignZip} from './mvp2Packaging.mjs';
import path from "node:path";
import {BannermaticStore} from "./mvp2Store.mjs";
import {CreativeDocumentStore} from "./mvp2CreativeDocuments.mjs";
import {applyCreativePublish,figmaSpecFromCampaign} from "./mvp2Contract.mjs";
import {campaignCompliance} from "./mvp2Compliance.mjs";
import {BuildStore} from "./mvp2Builds.mjs";
import {CreativeVersionStore} from "./mvp2CreativeVersions.mjs";
import {matchTT,resolveCampaignTT} from "./mvp2TT.mjs";
import {handleOAuth} from "./oauth.mjs";
const STORE_PATH=process.env.BANNERMATIC_DATA_FILE||path.resolve(process.cwd(),"runtime/bannermatic.json");const BUILD_STORE_PATH=process.env.BANNERMATIC_BUILD_FILE||path.resolve(process.cwd(),"runtime/bannermatic-builds.json");const CREATIVE_STORE_PATH=process.env.BANNERMATIC_CREATIVE_FILE||path.resolve(process.cwd(),"runtime/bannermatic-creative-versions.json");const DOCUMENT_STORE_PATH=process.env.BANNERMATIC_DOCUMENT_FILE||path.resolve(process.cwd(),"runtime/bannermatic-creative-documents.json");
export const bannermaticStore=new BannermaticStore(STORE_PATH);export const bannermaticBuildStore=new BuildStore(BUILD_STORE_PATH);export const bannermaticCreativeStore=new CreativeVersionStore(CREATIVE_STORE_PATH);export const bannermaticDocumentStore=new CreativeDocumentStore(DOCUMENT_STORE_PATH);
function bearer(req){const raw=String(req.headers.authorization||"");return raw.toLowerCase().startsWith("bearer ")?raw.slice(7).trim():""}function matchCampaignPath(url){return String(url||"").match(/^\/api\/campaigns\/([^/?#]+)$/)}function matchCampaignAction(url,action){return String(url||"").match(new RegExp(`^/api/campaigns/([^/?#]+)/${action}$`))}function matchBuildPath(url){return String(url||"").match(/^\/api\/campaigns\/([^/?#]+)\/builds\/([^/?#]+)$/)}function matchCreativeVersionPath(url){return String(url||"").match(/^\/api\/campaigns\/([^/?#]+)\/creative-versions\/([^/?#]+)$/)}function matchMemberPath(url){return String(url||"").match(/^\/api\/workspace\/members\/([^/?#]+)$/)}function light(c){if(!c)return c;const {creativeDocument,...rest}=c;return rest}
async function documentFor(auth,id){const c=bannermaticStore.getCampaign(auth,id),stored=bannermaticDocumentStore.get(id);if(stored)return stored;if(c.creativeDocument){await bannermaticDocumentStore.set(id,c.creativeDocument);await bannermaticStore.updateCampaign({...auth,role:"owner"},id,{creativeDocument:undefined});return c.creativeDocument}return null}
export async function handleMvp2Api(req,res,{json,readBody,layoutReview,aiDirector}){const url=String(req.url||"").split("?")[0];if(!url.startsWith("/api/auth/")&&!url.startsWith("/api/campaigns")&&!url.startsWith("/api/workspace/")&&!url.startsWith("/api/figma/"))return false;await Promise.all([bannermaticStore.load(),bannermaticBuildStore.load(),bannermaticCreativeStore.load(),bannermaticDocumentStore.load()]);try{
 if(await handleOAuth(req,res,{json,store:bannermaticStore}))return true;const requestContext={ip:String(req.headers["x-forwarded-for"]||req.socket?.remoteAddress||"").split(",")[0].trim(),userAgent:req.headers["user-agent"]||""};
 if(req.method==="POST"&&url==="/api/auth/register")return json(req,res,201,await bannermaticStore.register(await readBody(req),requestContext));if(req.method==="POST"&&url==="/api/auth/login")return json(req,res,200,await bannermaticStore.login(await readBody(req)));if(req.method==="POST"&&url==="/api/auth/invitation")return json(req,res,200,await bannermaticStore.acceptInvitation(await readBody(req),requestContext));if(req.method==="POST"&&url==="/api/figma/pair/claim"){const b=await readBody(req);return json(req,res,200,await bannermaticStore.claimFigmaPair(b.code))}
 if(url.startsWith("/api/figma/")){const p=await bannermaticStore.authenticatePlugin(bearer(req));if(!p)return json(req,res,401,{error:"Plugin session is invalid or expired"});if(req.method==="GET"&&url==="/api/figma/campaign")return json(req,res,200,figmaSpecFromCampaign(p.campaign));if(req.method==="POST"&&url==="/api/figma/layout-review"){if(typeof layoutReview!=="function")return json(req,res,503,{error:"AI layout review is not available"});return json(req,res,200,await layoutReview(await readBody(req),{campaignId:p.campaign.id,workspaceId:p.workspaceId}))}if(req.method==="POST"&&url==="/api/figma/creative-publish"){if(!["owner","admin","designer"].includes(p.role))return json(req,res,403,{error:"Creative publish is not allowed for this role"});const body=await readBody(req),publication=applyCreativePublish(p.campaign,body),auth={workspace:{id:p.workspaceId},user:{id:p.userId},role:"owner"},updated=await bannermaticStore.updateCampaign(auth,p.campaign.id,publication.patch),version=await bannermaticCreativeStore.add(updated,{touched:publication.touched});return json(req,res,200,{campaign:updated,touched:publication.touched,version,compliance:campaignCompliance(updated)})}return json(req,res,404,{error:"Figma endpoint not found"})}
 const token=bearer(req),auth=await bannermaticStore.authenticate(token);if(req.method==="POST"&&url==="/api/auth/logout"){if(token)await bannermaticStore.logout(token);return json(req,res,200,{ok:true})}if(req.method==="GET"&&url==="/api/auth/me"){if(!auth)return json(req,res,401,{error:"Unauthorized"});return json(req,res,200,{user:auth.user,workspace:auth.workspace,role:auth.role,expiresAt:auth.session.expiresAt})}if(!auth)return json(req,res,401,{error:"Unauthorized"});
 if(req.method==="GET"&&url==="/api/campaigns")return json(req,res,200,{items:bannermaticStore.listCampaigns(auth)});if(req.method==="POST"&&url==="/api/campaigns"){bannermaticStore.requireRole(auth,["owner","admin","producer"]);return json(req,res,201,await bannermaticStore.createCampaign(auth,await readBody(req)))}
 const directorMatch=matchCampaignAction(url,"ai-director");if(directorMatch&&req.method==="POST"){bannermaticStore.requireRole(auth,["owner","admin","designer"]);if(typeof aiDirector!=="function")return json(req,res,503,{error:"AI Director is not available"});const id=decodeURIComponent(directorMatch[1]);bannermaticStore.getCampaign(auth,id);return json(req,res,200,await aiDirector(await readBody(req),{campaignId:id,workspaceId:auth.workspace.id,userId:auth.user.id}))}\n const sceneDocumentMatch=matchCampaignAction(url,"scene-document");if(sceneDocumentMatch&&req.method==="GET"){const id=decodeURIComponent(sceneDocumentMatch[1]);bannermaticStore.getCampaign(auth,id);return json(req,res,200,{creativeDocument:await documentFor(auth,id)})}if(sceneDocumentMatch&&req.method==="PATCH"){bannermaticStore.requireRole(auth,["owner","admin","designer"]);const id=decodeURIComponent(sceneDocumentMatch[1]),body=await readBody(req),creativeDocument=body?.creativeDocument;if(!creativeDocument||!Array.isArray(creativeDocument.scenes))return json(req,res,400,{error:"Valid creativeDocument.scenes is required"});await bannermaticDocumentStore.set(id,creativeDocument);const current=bannermaticStore.getCampaign(auth,id),updated=await bannermaticStore.updateCampaign({...auth,role:"owner"},id,{creativeDocument:undefined,status:current.status==="delivered"?"delivered":"creative"});return json(req,res,200,{...light(updated),creativeDocument})}
 const templateMatch=matchCampaignAction(url,"template-publish");if(templateMatch&&req.method==="POST"){bannermaticStore.requireRole(auth,["owner","admin","designer"]);const id=decodeURIComponent(templateMatch[1]),campaign=bannermaticStore.getCampaign(auth,id),updated=await bannermaticStore.updateCampaign(auth,id,publishTemplate(campaign));await bannermaticCreativeStore.add(updated,{touched:updated.formats.map(f=>f.id)});return json(req,res,200,light(updated))}
 const download=url.match(/^\/api\/campaigns\/([^/?#]+)\/builds\/([^/?#]+)\/download$/);if(download&&req.method==="GET"){const id=decodeURIComponent(download[1]);bannermaticStore.getCampaign(auth,id);const build=bannermaticBuildStore.get(id,decodeURIComponent(download[2]));if(!build)return json(req,res,404,{error:"Build not found"});const bytes=campaignZip(build);res.writeHead(200,{"Content-Type":"application/zip","Content-Length":bytes.length,"Content-Disposition":"attachment; filename=\"campaign.zip\"","Cache-Control":"private, no-store"});res.end(bytes);return true}
 const pair=matchCampaignAction(url,"figma-pair");if(pair&&req.method==="POST")return json(req,res,201,await bannermaticStore.createFigmaPair(auth,decodeURIComponent(pair[1])));const status=matchCampaignAction(url,"figma-status");if(status&&req.method==="GET")return json(req,res,200,bannermaticStore.figmaConnectionStatus(auth,decodeURIComponent(status[1])));const spec=matchCampaignAction(url,"figma-spec");if(spec&&req.method==="GET")return json(req,res,200,figmaSpecFromCampaign(bannermaticStore.getCampaign(auth,decodeURIComponent(spec[1]))));
 const tt=matchCampaignAction(url,"tt-resolve");if(tt&&req.method==="GET")return json(req,res,200,resolveCampaignTT(bannermaticStore.getCampaign(auth,decodeURIComponent(tt[1]))));if(tt&&req.method==="POST"){const campaign=bannermaticStore.getCampaign(auth,decodeURIComponent(tt[1])),body=await readBody(req);return json(req,res,200,body.placementId?(()=>{const placement=(campaign.placements||[]).find(p=>p.id===body.placementId);if(!placement)throw Object.assign(new Error("Placement not found"),{status:404});return{campaignId:campaign.id,placementId:placement.id,...matchTT({...placement,...body})}})():resolveCampaignTT(campaign))}
 const compliance=matchCampaignAction(url,"compliance");if(compliance&&req.method==="GET")return json(req,res,200,campaignCompliance(bannermaticStore.getCampaign(auth,decodeURIComponent(compliance[1]))));const versions=matchCampaignAction(url,"creative-versions");if(versions&&req.method==="GET"){const id=decodeURIComponent(versions[1]);bannermaticStore.getCampaign(auth,id);return json(req,res,200,{items:bannermaticCreativeStore.list(id)})}const version=matchCreativeVersionPath(url);if(version&&req.method==="GET"){const id=decodeURIComponent(version[1]),item=bannermaticCreativeStore.get(id,Number(decodeURIComponent(version[2])));bannermaticStore.getCampaign(auth,id);return item?json(req,res,200,item):json(req,res,404,{error:"Creative version not found"})}
 const builds=matchCampaignAction(url,"builds");if(builds&&req.method==="GET"){const id=decodeURIComponent(builds[1]);bannermaticStore.getCampaign(auth,id);return json(req,res,200,{items:bannermaticBuildStore.list(id)})}if(builds&&req.method==="POST"){bannermaticStore.requireRole(auth,["owner","admin","producer"]);const id=decodeURIComponent(builds[1]),campaign=bannermaticStore.getCampaign(auth,id),build=await bannermaticBuildStore.create(campaign);return json(req,res,build.state==="ready"?201:409,{build,compliance:campaignCompliance(campaign)})}const build=matchBuildPath(url);if(build&&req.method==="GET"){const id=decodeURIComponent(build[1]);bannermaticStore.getCampaign(auth,id);const item=bannermaticBuildStore.get(id,decodeURIComponent(build[2]));return item?json(req,res,200,item):json(req,res,404,{error:"Build not found"})}
 const publish=matchCampaignAction(url,"creative-publish");if(publish&&req.method==="POST"){bannermaticStore.requireRole(auth,["owner","admin","designer"]);const id=decodeURIComponent(publish[1]),campaign=bannermaticStore.getCampaign(auth,id),publication=applyCreativePublish(campaign,await readBody(req)),updated=await bannermaticStore.updateCampaign({...auth,role:"owner"},id,publication.patch),v=await bannermaticCreativeStore.add(updated,{touched:publication.touched});return json(req,res,200,{campaign:light(updated),touched:publication.touched,version:v,compliance:campaignCompliance(updated)})}
 const cm=matchCampaignPath(url);if(cm&&req.method==="GET")return json(req,res,200,light(bannermaticStore.getCampaign(auth,decodeURIComponent(cm[1]))));if(cm&&(req.method==="PATCH"||req.method==="PUT")){bannermaticStore.requireRole(auth,["owner","admin","producer"]);const body=await readBody(req);delete body.creativeDocument;return json(req,res,200,light(await bannermaticStore.updateCampaign(auth,decodeURIComponent(cm[1]),body)))}if(cm&&req.method==="DELETE"){bannermaticStore.requireRole(auth,["owner","admin","producer"]);const id=decodeURIComponent(cm[1]),deleted=await bannermaticStore.deleteCampaign(auth,id);await Promise.all([bannermaticBuildStore.deleteCampaign(id),bannermaticCreativeStore.deleteCampaign(id),bannermaticDocumentStore.remove(id)]);return json(req,res,200,{ok:true,...deleted})}
 if(req.method==="GET"&&url==="/api/workspace/members")return json(req,res,200,{items:bannermaticStore.listMembers(auth)});if(url==="/api/workspace/invitations"&&req.method==="GET")return json(req,res,200,{items:bannermaticStore.listInvitations(auth)});if(url==="/api/workspace/invitations"&&req.method==="POST")return json(req,res,201,await bannermaticStore.createInvitation(auth,await readBody(req)));const member=matchMemberPath(url);if(member&&req.method==="PATCH"){const body=await readBody(req);return json(req,res,200,await bannermaticStore.updateMemberRole(auth,decodeURIComponent(member[1]),String(body.role||"")))}return json(req,res,404,{error:"Not found"})}catch(error){return json(req,res,Number(error?.status)||500,{error:error instanceof Error?error.message:String(error)})}}
