import {describe,it,expect} from 'vitest';
import {createCampaignBuildManifest} from './mvp2Builds.mjs';
const placement:any={id:'p1',platform:'Yandex',placement:'ROS',width:300,height:250,requirements:{maxZipKb:150,maxDurationSec:6,sourceLabel:'Client TT',impressionUrl:'https://tracker/p',clickUrl:'https://click'}};
const ready:any={id:'c1',name:'Launch',creativeVersion:4,mediaPlanVersion:2,ttSnapshotVersion:3,placements:[placement],formats:[{id:'f1',width:300,height:250,placementIds:['p1'],creativeState:'published',creativeVersion:4,estimatedZipKb:120,durationSec:5,previewHtml:'<!doctype html><html><body>Ad</body></html>',previewType:'html'}]};
describe('MVP2 campaign builds',()=>{
 it('pins all campaign versions and placement-specific creative payload in a reproducible manifest',()=>{const b=createCampaignBuildManifest(ready);expect(b.pins).toEqual({creativeVersion:4,mediaPlanVersion:2,ttSnapshotVersion:3});expect(b.placements[0]).toMatchObject({placementId:'p1',formatId:'f1',creativeVersion:4,previewType:'html',impressionUrl:'https://tracker/p',clickUrl:'https://click'});expect(b.placements[0].previewHtml).toContain('<!doctype html>')});
 it('generates a placement-specific HTML5 file with dimensions, click URL and impression tracking',()=>{const b=createCampaignBuildManifest(ready);const file=b.placements[0].files[0];expect(file.name).toBe('index.html');expect(file.mime).toBe('text/html');expect(file.content).toContain('width=300,height=250');expect(file.content).toContain('https://click');expect(file.content).toContain('https://tracker/p');expect(file.content).toContain('srcdoc=')});
 it('reuses one visual creative while producing different delivery wrappers for placements',()=>{const second={...placement,id:'p2',platform:'Adfox',placement:'Top',requirements:{...placement.requirements,clickUrl:'https://click-2',impressionUrl:'https://tracker/p2'}};const campaign={...ready,placements:[placement,second],formats:[{...ready.formats[0],placementIds:['p1','p2']}]};const b=createCampaignBuildManifest(campaign);expect(b.placements).toHaveLength(2);expect(b.placements[0].formatId).toBe(b.placements[1].formatId);expect(b.placements[0].files[0].content).toContain('https://click');expect(b.placements[1].files[0].content).toContain('https://click-2')});
 it('is ready only when compliance has no warning or block',()=>{expect(createCampaignBuildManifest(ready).state).toBe('ready');const blocked={...ready,formats:[{...ready.formats[0],estimatedZipKb:300}]};expect(createCampaignBuildManifest(blocked).state).toBe('blocked')});
});
