import {deflateRawSync} from 'node:zlib';

const esc=value=>String(value||'').replace(/[&"<>]/g,c=>({'&':'&amp;','"':'&quot;','<':'&lt;','>':'&gt;'}[c]));
const script=value=>JSON.stringify(String(value||'')).replace(/</g,'\\u003c');
const safeName=value=>String(value||'placement').replace(/[^a-z0-9_-]/gi,'-').replace(/-+/g,'-').replace(/^-|-$/g,'')||'placement';
const ARTIFACT_EXT={"image/png":"png","image/jpeg":"jpg","image/gif":"gif","image/webp":"webp","video/mp4":"mp4","video/webm":"webm","video/quicktime":"mov"};

export function normalizeOutputType(value){const raw=String(value||'html5').toLowerCase().replace(/\s+/g,'').replace(/_/g,'-');if(raw.includes('html')&&raw.includes('gif'))return'html5+gif';if(raw.includes('html'))return'html5';if(raw==='jpeg'||raw==='jpg')return'jpg';if(raw==='png')return'png';if(raw==='gif')return'gif';if(raw==='mp4'||raw==='webm'||raw==='mov'||raw.includes('video'))return'video';if(raw==='webp')return'webp';return'html5'}
export function outputTypeForPlacement(placement,format){return normalizeOutputType(placement?.requirements?.exportType||placement?.creativeType||format?.exportType)}

function artifactKey(formatId,kind){return`${formatId}:${kind}`}
export function artifactForOutput(artifacts,format,type){const formatId=String(format?.id||''),baseId=formatId.split('::')[0],get=kind=>artifacts?.[artifactKey(formatId,kind)]||artifacts?.[artifactKey(baseId,kind)]||null;if(type==='jpg')return get('jpg');if(type==='png')return get('png');if(type==='webp')return get('webp');if(type==='gif'||type==='html5+gif')return get('gif');if(type==='video')return get('video');return get('gif')||get('png')||get('jpg')||get('webp')||get('video')}
function artifactBytes(artifact){if(!artifact)return null;if(Buffer.isBuffer(artifact.content))return artifact.content;if(artifact.encoding==='base64')return Buffer.from(String(artifact.content||''),'base64');return Buffer.from(artifact.content||'')}
function storedFile(name,mime,content){const bytes=Buffer.isBuffer(content)?content:Buffer.from(content);return String(mime).startsWith('text/')?{name,mime,content:bytes.toString('utf8'),encoding:'utf8',bytes:bytes.length}:{name,mime,content:bytes.toString('base64'),encoding:'base64',bytes:bytes.length}}
function fileBytes(file){return file?.encoding==='base64'?Buffer.from(String(file.content||''),'base64'):Buffer.from(file?.content||'')}

function creativeBody(format,artifact,assetName){if(artifact){if(String(artifact.mimeType).startsWith('video/'))return`<video id="creative" src="${esc(assetName)}" autoplay muted loop playsinline></video>`;return`<img id="creative" src="${esc(assetName)}" alt="">`}if(format?.previewHtml)return`<iframe id="creative" sandbox="allow-scripts" srcdoc="${esc(format.previewHtml)}"></iframe>`;if(format?.previewSvg)return`<div id="creative">${format.previewSvg}</div>`;return''}

export function placementHtml(format,placement,artifact=null,assetName='creative.png'){const body=creativeBody(format,artifact,assetName);if(!body)return'';const clickVariable=/^[A-Za-z_$][\w$]*$/.test(String(placement.requirements?.clickTagVariable||''))?String(placement.requirements.clickTagVariable):'clickTag';return`<!doctype html><html><head><meta charset="utf-8"><meta name="ad.size" content="width=${placement.width},height=${placement.height}"><style>html,body,#creative{margin:0;width:100%;height:100%;overflow:hidden}iframe,img,video{border:0;display:block;width:100%;height:100%;object-fit:cover}#bm-click{position:fixed;inset:0;z-index:2147483647}</style></head><body>${body}<a id="bm-click" aria-label="Advertisement" target="_blank" rel="noopener"></a><script>window.${clickVariable}=window.${clickVariable}||${script(placement.requirements?.clickUrl)};window.clickTag=window.${clickVariable};const a=document.getElementById('bm-click');a.onclick=function(e){e.preventDefault();if(/^https?:\\/\\//i.test(window.${clickVariable}))window.open(window.${clickVariable},'_blank','noopener')};a.href=window.${clickVariable}||'#';const imp=${script(placement.requirements?.impressionUrl)};if(imp){const i=new Image(1,1);i.src=imp;document.body.appendChild(i)}<\/script></body></html>`}

function crc32(bytes){let n=0xffffffff;for(const b of bytes){n^=b;for(let i=0;i<8;i++)n=(n>>>1)^(n&1?0xedb88320:0)}return(n^0xffffffff)>>>0}
export function zipFiles(files){const local=[],central=[];let offset=0;for(const f of files){if(!f.name||f.name.startsWith('/')||f.name.split('/').some(p=>p==='..'||!p)||f.name.includes('\\'))throw new Error('Unsafe package path');const name=Buffer.from(f.name),raw=Buffer.isBuffer(f.content)?f.content:Buffer.from(f.content),data=deflateRawSync(raw,{level:9}),crc=crc32(raw);const h=Buffer.alloc(30);h.writeUInt32LE(0x04034b50);h.writeUInt16LE(20,4);h.writeUInt16LE(0x800,6);h.writeUInt16LE(8,8);h.writeUInt16LE(33,12);h.writeUInt32LE(crc,14);h.writeUInt32LE(data.length,18);h.writeUInt32LE(raw.length,22);h.writeUInt16LE(name.length,26);local.push(h,name,data);const c=Buffer.alloc(46);c.writeUInt32LE(0x02014b50);c.writeUInt16LE(20,4);h.copy(c,6,4,30);c.writeUInt32LE(offset,42);central.push(c,name);offset+=h.length+name.length+data.length}const directory=Buffer.concat(central),end=Buffer.alloc(22);end.writeUInt32LE(0x06054b50);end.writeUInt16LE(files.length,8);end.writeUInt16LE(files.length,10);end.writeUInt32LE(directory.length,12);end.writeUInt32LE(offset,16);return Buffer.concat([...local,directory,end])}

export function createPlacementPackage(format,placement,artifacts={}){const outputType=outputTypeForPlacement(placement,format),artifact=artifactForOutput(artifacts,format,outputType),base=`${safeName(placement.platform)}-${safeName(placement.placement)}-${placement.width}x${placement.height}`;if(['jpg','png','gif','video','webp'].includes(outputType)){if(!artifact)return{outputType,artifact:null,fileName:'',mimeType:'',files:[],packageBytes:0};const ext=ARTIFACT_EXT[artifact.mimeType]||outputType,bytes=artifactBytes(artifact);return{outputType,artifact,fileName:`${base}.${ext}`,mimeType:artifact.mimeType,files:[storedFile(`${base}.${ext}`,artifact.mimeType,bytes)],packageBytes:bytes.length}}const ext=artifact?ARTIFACT_EXT[artifact.mimeType]:'',assetName=outputType==='html5+gif'?'fallback.gif':artifact?`creative.${ext}`:'',html=placementHtml(format,placement,artifact,assetName);if(!html)return{outputType,artifact:null,fileName:'',mimeType:'',files:[],packageBytes:0};const files=[{name:'index.html',content:html},...(artifact?[{name:assetName,content:artifactBytes(artifact)}]:[])],zip=zipFiles(files);return{outputType,artifact,fileName:`${base}.zip`,mimeType:'application/zip',files:files.map(file=>storedFile(file.name,file.name.endsWith('.html')?'text/html':artifact?.mimeType||'application/octet-stream',file.content)),packageBytes:zip.length}}

export function placementZip(format,placement,artifacts={}){const item=createPlacementPackage(format,placement,artifacts);return item.mimeType==='application/zip'?zipFiles(item.files.map(file=>({name:file.name,content:fileBytes(file)}))):null}

export function campaignZip(build){if(build.state!=='ready'||!build.placements.length)throw Object.assign(new Error('Build is not ready for delivery'),{status:409});const files=build.placements.map(p=>{const content=p.mimeType==='application/zip'?zipFiles(p.files.map(file=>({name:file.name,content:fileBytes(file)}))):fileBytes(p.files[0]);return{name:p.fileName,content}});files.push({name:'manifest.json',content:JSON.stringify({id:build.id,campaignId:build.campaignId,pins:build.pins,placements:build.placements.map(p=>({placementId:p.placementId,formatId:p.formatId,outputType:p.outputType,package:p.fileName,mimeType:p.mimeType,bytes:p.packageBytes,sha256:p.sha256||null,clickUrl:p.clickUrl||'',ttSource:p.ttSource||''}))},null,2)});return zipFiles(files)}
