const nonEmpty=value=>value!==undefined&&value!==null&&String(value).trim()!=='';
const asList=value=>Array.isArray(value)?value.filter(Boolean):nonEmpty(value)?[value]:[];

function check(name,status,actual,expected,detail='',fix=null){return{name,status,actual:actual??null,expected:expected??null,detail,fix};}
function requirementBool(value){return value===true||String(value).toLowerCase()==='true'||String(value).toLowerCase()==='required'}

export function placementCompliance(campaign,placement){
 const format=(campaign.formats||[]).find(f=>(f.placementIds||[]).includes(placement.id));
 const requirements=placement.requirements||{};const checks=[];
 if(!format){checks.push(check('creative','blocked',null,'published creative','No visual format is linked to this placement.'));return summarize(placement,format,checks)}
 checks.push(check('dimensions',Number(format.width)===Number(placement.width)&&Number(format.height)===Number(placement.height)?'ready':'blocked',`${format.width}×${format.height}`,`${placement.width}×${placement.height}`,'',Number(format.width)!==Number(placement.width)||Number(format.height)!==Number(placement.height)?{type:'open-figma',label:'Resize creative to required dimensions'}:null));
 checks.push(check('creative',format.creativeState==='published'?'ready':'blocked',format.creativeState||'missing','published','',format.creativeState!=='published'?{type:'open-figma',label:'Publish creative from Figma'}:null));
 if(nonEmpty(requirements.maxZipKb))checks.push(nonEmpty(format.estimatedZipKb)?check('zip',Number(format.estimatedZipKb)<=Number(requirements.maxZipKb)?'ready':'blocked',Number(format.estimatedZipKb),Number(requirements.maxZipKb),'KB',Number(format.estimatedZipKb)>Number(requirements.maxZipKb)?{type:'open-figma',label:'Optimize creative assets'}:null):check('zip','unknown',null,Number(requirements.maxZipKb),'Published creative has no ZIP estimate yet.'));
 if(nonEmpty(requirements.maxDurationSec))checks.push(nonEmpty(format.durationSec)?check('duration',Number(format.durationSec)<=Number(requirements.maxDurationSec)?'ready':'blocked',Number(format.durationSec),Number(requirements.maxDurationSec),'sec',Number(format.durationSec)>Number(requirements.maxDurationSec)?{type:'open-figma',label:'Shorten animation'}:null):check('duration','unknown',null,Number(requirements.maxDurationSec),'Published creative has no duration metadata yet.'));
 if(requirementBool(requirements.clickTag)){const clickOk=format.clickTagPresent===true||nonEmpty(requirements.clickUrl);checks.push(check('clickTag',clickOk?'ready':format.clickTagPresent===false?'blocked':'unknown',clickOk?'configured':format.clickTagPresent??null,true,clickOk?'':format.clickTagPresent===undefined?'Creative publish did not report clickTag presence and no click URL is configured.':'',!clickOk&&format.clickTagPresent===false?{type:'open-figma',label:'Add clickTag'}:null));}
 if(requirementBool(requirements.tracking)){const configured=nonEmpty(requirements.impressionUrl);checks.push(check('tracking',configured?'ready':'blocked',configured?'configured':'missing','impression URL','',configured?null:{type:'campaign-setting',label:'Add impression URL'}));}
 const safeZone=requirements.safeZone||requirements.safeArea;if(safeZone){const report=format.safeZonePassed;checks.push(check('safe-zone',report===true?'ready':report===false?'blocked':'unknown',report??null,safeZone,report===undefined?'Creative publish has no safe-zone validation result.':'',report===false?{type:'open-figma',label:'Fix safe-zone violation'}:null));}
 const requiredElements=asList(requirements.requiredElements||requirements.requiredElement);if(requiredElements.length){const present=new Set(asList(format.presentElements).map(x=>String(x).toLowerCase()));const missing=requiredElements.filter(x=>!present.has(String(x).toLowerCase()));checks.push(check('required-elements',format.presentElements?missing.length?'blocked':'ready':'unknown',format.presentElements||null,requiredElements,format.presentElements?missing.length?`Missing: ${missing.join(', ')}`:'':'Creative publish has no required-element report.',missing.length?{type:'open-figma',label:'Add required elements'}:null));}
 const sourceKnown=nonEmpty(requirements.sourceUrl)||nonEmpty(requirements.sourceLabel)&&!String(requirements.sourceLabel).toLowerCase().startsWith('unknown');checks.push(check('tt-source',sourceKnown?'ready':'unknown',requirements.sourceLabel||requirements.sourceUrl||null,'verified or client TT source'));
 return summarize(placement,format,checks);
}
function summarize(placement,format,checks){const blocked=checks.filter(c=>c.status==='blocked').length,unknown=checks.filter(c=>c.status==='unknown').length;return{placementId:placement.id,platform:placement.platform,placement:placement.placement,size:`${placement.width}×${placement.height}`,formatId:format?.id||null,status:blocked?'blocked':unknown?'warning':'ready',checks,blocked,unknown};}
export function campaignCompliance(campaign){const placements=(campaign.placements||[]).map(p=>placementCompliance(campaign,p));const summary={ready:placements.filter(p=>p.status==='ready').length,warning:placements.filter(p=>p.status==='warning').length,blocked:placements.filter(p=>p.status==='blocked').length,total:placements.length};return{campaignId:campaign.id,creativeVersion:Number(campaign.creativeVersion||0),mediaPlanVersion:Number(campaign.mediaPlanVersion||0),ttSnapshotVersion:Number(campaign.ttSnapshotVersion||0),summary,placements};}
