import {publishTemplate} from '../src/mvp2/production.mjs';
import {campaignZip} from './mvp2Packaging.mjs';
import path from "node:path";
import {BannermaticStore} from "./mvp2Store.mjs";
import {CreativeDocumentStore} from "./mvp2CreativeDocuments.mjs";
import {applyCreativePublish,figmaSpecFromCampaign} from "./mvp2Contract.mjs";
import {campaignCompliance} from "./mvp2Compliance.mjs";
import {BuildStore} from "./mvp2Builds.mjs";
import {CreativeVersionStore} from "./mvp2CreativeVersions.mjs";
import {matchTT,resolveCampaignTT} from "./mvp2TT.mjs";
const STORE_PATH=process.env.BANNERMATIC_DATA_FILE||path.resolve(process.cwd(),"runtime/bannermatic.json");const BUILD_STORE_PATH=process.env.BANNERMATIC_BUILD_FILE||path.resolve(process.cwd(),"runtime/bannermatic-builds.json");const CREATIVE_STORE_PATH=process.env.BANNERMATIC_CREATIVE_FILE||path.resolve(process.cwd(),"runtime/bannermatic-creative-versions.json");const DOCUMENT_STORE_PATH=process.env.BANNERMATIC_DOCUMENT_FILE||path.resolve(process.cwd(),"runtime/bannermatic-creative-documents.json");
export const bannermaticStore=new BannermaticStore(STORE_PATH);export const bannermaticBuildStore=new BuildStore(BUILD_STORE_PATH);export const bannermaticCreativeStore=new CreativeVersionStore(CREATIVE_STORE_PATH);export const bannermaticDocumentStore=new CreativeDocumentStore(DOCUMENT_STORE_PATH);
const bearer=req=>{const raw=String(req.headers.authorization||"");return raw.toLowerCase().startsWith("bearer ")?raw.slice(7).trim():""};const action=(url,name)=>String(url||"").match(new RegExp(`^/api/campaigns/([^/?#]+)/${name}$`));const campaignPath=url=>String(url||"").match(/^\/api\/campaigns\/([^/?#]+)$/);
function light(c){if(!c)return c;const {creativeDocument,...rest}=c;return rest}
async function documentFor(auth,id){const c=bannermaticStore.getCampaign(auth,id),stored=bannermaticDocumentStore.get(id);if(stored)return stored;if(c.creativeDocument){await bannermaticDocumentStore.set(id,c.creativeDocument);await bannermaticStore.updateCampaign({...auth,role:"owner"},id,{creativeDocument:undefined});return c.creativeDocument}return null}
export async function handleMvp2Api(req,res,{json,readBody,layoutReview}){const url=String(req.url||"").split("?")[0];if(!url.startsWith("/api/auth/")&&!url.startsWith("/api/campaigns")&&!url.startsWith("/api/workspace/")&&!url.startsWith("/api/figma/"))return false;await Promise.all([bannermaticStore.load(),bannermaticBuildStore.load(),bannermaticCreativeStore.load(),bannermaticDocumentStore.load()]);try{
 if(req.method==="POST"&&url==="/api/auth/register")return json(req,res,201,await bannermaticStore.register(await readBody(req)));if(req.method==="POST"&&url==="/api/auth/login")return json(req,res,200,await bannermaticStore.login(await readBody(req)));if(req.method==="POST"&&url==="/api/auth/invitation")return json(req,res,200,await bannermaticStore.acceptInvitation(await readBody(req)));if(req.method==="POST"&&url==="/api/figma/pair/claim"){const b=await readBody(req);return json(req,res,200,await bannermaticStore.claimFigmaPair(b.code))}
 if(url.startsWith("/api/figma/")){const p=await bannermaticStore.authenticatePlugin(bearer(req));if(!p)return json(req,res,401,{error:"Plugin session is invalid or expired"});if(req.method==="GET"&&url==="/api/figma/campaign")return json(req,res,200,figmaSpecFromCampaign(p.campaign));if(req.method==="POST"&&url==="/api/figma/layout-review"){if(typeof layoutReview!=="function")return json(req,res,503,{error:"AI layout review is not available"});return json(req,res,200,await layoutReview(await readBody(req),{campaignId:p.campaign.id,workspaceId:p.workspaceId}))}return json(req,res,404,{error:"Figma endpoint not found"})}
 const token=bearer(req),auth=await bannermaticStore.authenticate(token);if(req.method==="POST"&&url==="/api/auth/logout"){if(token)await bannermaticStore.logout(token);return json(req,res,200,{ok:true})}if(req.method==="GET"&&url==="/api/auth/me"){if(!auth)return json(req,res,401,{error:"Unauthorized"});return json(req,res,200,{user:auth.user,workspace:auth.workspace,role:auth.role,expiresAt:auth.session.expiresAt})}if(!auth)return json(req,res,401,{error:"Unauthorized"});
 if(req.method==="GET"&&url==="/api/campaigns")return json(req,res,200,{items:bannermaticStore.listCampaigns(auth)});if(req.method==="POST"&&url==="/api/campaigns"){bannermaticStore.requireRole(auth,["owner","admin","producer"]);return json(req,res,201,await bannermaticStore.createCampaign(auth,await readBody(req)))}
 const doc=action(url,"scene-document");if(doc&&req.method==="GET"){const id=decodeURIComponent(doc[1]);bannermaticStore.getCampaign(auth,id);return json(req,res,200,{creativeDocument:await documentFor(auth,id)})}if(doc&&req.method==="PATCH"){bannermaticStore.requireRole(auth,["owner","admin","designer"]);const id=decodeURIComponent(doc[1]),body=await readBody(req),creativeDocument=body?.creativeDocument;if(!creativeDocument||!Array.isArray(creativeDocument.scenes))return json(req,res,400,{error:"Valid creativeDocument.scenes is required"});await bannermaticDocumentStore.set(id,creativeDocument);const current=bannermaticStore.getCampaign(auth,id),updated=await bannermaticStore.updateCampaign({...auth,role:"owner"},id,{creativeDocument:undefined,status:current.status==="delivered"?"delivered":"creative"});return json(req,res,200,{...light(updated),creativeDocument})}
 const pair=action(url,"figma-pair");if(pair&&req.method==="POST")return json(req,res,201,await bannermaticStore.createFigmaPair(auth,decodeURIComponent(pair[1])));const status=action(url,"figma-status");if(status&&req.method==="GET")return json(req,res,200,bannermaticStore.figmaConnectionStatus(auth,decodeURIComponent(status[1])));const spec=action(url,"figma-spec");if(spec&&req.method==="GET")return json(req,res,200,figmaSpecFromCampaign(bannermaticStore.getCampaign(auth,decodeURIComponent(spec[1]))));const compliance=action(url,"compliance");if(compliance&&req.method==="GET")return json(req,res,200,campaignCompliance(bannermaticStore.getCampaign(auth,decodeURIComponent(compliance[1]))));
 const cm=campaignPath(url);if(cm&&req.method==="GET")return json(req,res,200,light(bannermaticStore.getCampaign(auth,decodeURIComponent(cm[1]))));if(cm&&(req.method==="PATCH"||req.method==="PUT")){bannermaticStore.requireRole(auth,["owner","admin","producer"]);const body=await readBody(req);delete body.creativeDocument;return json(req,res,200,light(await bannermaticStore.updateCampaign(auth,decodeURIComponent(cm[1]),body)))}if(cm&&req.method==="DELETE"){bannermaticStore.requireRole(auth,["owner","admin","producer"]);const id=decodeURIComponent(cm[1]),deleted=await bannermaticStore.deleteCampaign(auth,id);await Promise.all([bannermaticBuildStore.deleteCampaign(id),bannermaticCreativeStore.deleteCampaign(id),bannermaticDocumentStore.remove(id)]);return json(req,res,200,{ok:true,...deleted})}
 return json(req,res,404,{error:"Not found"})}catch(error){return json(req,res,Number(error?.status)||500,{error:error instanceof Error?error.message:String(error)})}}
