import crypto from "node:crypto";
import geoip from "geoip-lite";
import {LEGAL_VERSION} from "./mvp2Store.mjs";

const states=new Map();
const ORIGIN=String(process.env.BANNERMATIC_PUBLIC_ORIGIN||"https://studio.bannermatic.online").replace(/\/$/,"");
const PROVIDERS={
 google:{clientId:process.env.GOOGLE_OAUTH_CLIENT_ID||"",clientSecret:process.env.GOOGLE_OAUTH_CLIENT_SECRET||""},
 yandex:{clientId:process.env.YANDEX_OAUTH_CLIENT_ID||"",clientSecret:process.env.YANDEX_OAUTH_CLIENT_SECRET||""},
 vk:{clientId:process.env.VK_OAUTH_CLIENT_ID||"",clientSecret:process.env.VK_OAUTH_CLIENT_SECRET||""}
};
const callback=provider=>`${ORIGIN}/api/auth/oauth/${provider}/callback`;
const clientIp=req=>String(req.headers["x-forwarded-for"]||req.socket?.remoteAddress||"").split(",")[0].trim().replace(/^::ffff:/,"");
const isRussian=req=>geoip.lookup(clientIp(req))?.country==="RU"||String(req.headers["accept-language"]||"").toLowerCase().startsWith("ru");
const configured=provider=>Boolean(PROVIDERS[provider]?.clientId&&PROVIDERS[provider]?.clientSecret);
const context=req=>({ip:clientIp(req),userAgent:req.headers["user-agent"]||""});
const redirect=(res,url)=>{res.writeHead(302,{location:url,"cache-control":"no-store"});res.end();return true};
const form=values=>new URLSearchParams(values).toString();
async function requestJson(url,init){const response=await fetch(url,init);const data=await response.json().catch(()=>({}));if(!response.ok||data.error)throw new Error(data.error_description||data.error?.error_msg||data.error||`OAuth request failed: ${response.status}`);return data}

function authorizationUrl(provider,state){const p=PROVIDERS[provider],common={client_id:p.clientId,redirect_uri:callback(provider),response_type:"code",state};if(provider==="google")return `https://accounts.google.com/o/oauth2/v2/auth?${form({...common,scope:"openid email profile",prompt:"select_account"})}`;if(provider==="yandex")return `https://oauth.yandex.ru/authorize?${form({...common,scope:"login:email login:info login:avatar",force_confirm:"yes"})}`;return `https://oauth.vk.com/authorize?${form({...common,scope:"email",display:"page",v:"5.199"})}`}
async function exchange(provider,code){const p=PROVIDERS[provider];if(provider==="google"){const token=await requestJson("https://oauth2.googleapis.com/token",{method:"POST",headers:{"content-type":"application/x-www-form-urlencoded"},body:form({client_id:p.clientId,client_secret:p.clientSecret,code,grant_type:"authorization_code",redirect_uri:callback(provider)})});const me=await requestJson("https://openidconnect.googleapis.com/v1/userinfo",{headers:{authorization:`Bearer ${token.access_token}`}});return{subject:me.sub,email:me.email,name:me.name,avatar:me.picture}}
 if(provider==="yandex"){const token=await requestJson("https://oauth.yandex.ru/token",{method:"POST",headers:{"content-type":"application/x-www-form-urlencoded"},body:form({grant_type:"authorization_code",code,client_id:p.clientId,client_secret:p.clientSecret})});const me=await requestJson("https://login.yandex.ru/info?format=json",{headers:{authorization:`OAuth ${token.access_token}`}});return{subject:String(me.id),email:me.default_email||me.emails?.[0],name:me.real_name||me.display_name||me.login,avatar:me.default_avatar_id?`https://avatars.yandex.net/get-yapic/${me.default_avatar_id}/islands-200`:""}}
 const token=await requestJson(`https://oauth.vk.com/access_token?${form({client_id:p.clientId,client_secret:p.clientSecret,redirect_uri:callback(provider),code})}`);const profile=await requestJson(`https://api.vk.com/method/users.get?${form({access_token:token.access_token,fields:"photo_200",v:"5.199"})}`);const me=profile.response?.[0]||{};return{subject:String(token.user_id),email:token.email,name:[me.first_name,me.last_name].filter(Boolean).join(" "),avatar:me.photo_200}}

export function oauthConfig(req){const order=isRussian(req)?["vk","yandex","google"]:["google","yandex","vk"];return{region:isRussian(req)?"ru":"global",legalVersion:LEGAL_VERSION,providers:order.map(id=>({id,enabled:configured(id)}))}}

export async function handleOAuth(req,res,{json,store}){const requestUrl=new URL(req.url,ORIGIN);if(req.method==="GET"&&requestUrl.pathname==="/api/auth/oauth/config")return json(req,res,200,oauthConfig(req));const start=requestUrl.pathname.match(/^\/api\/auth\/oauth\/(google|yandex|vk)\/start$/);if(req.method==="GET"&&start){const provider=start[1];if(!configured(provider))return json(req,res,503,{error:`${provider} OAuth is not configured`});if(requestUrl.searchParams.get("terms")!=="1"||requestUrl.searchParams.get("privacy")!=="1"||requestUrl.searchParams.get("version")!==LEGAL_VERSION)return json(req,res,400,{error:"Legal consent is required"});const state=crypto.randomBytes(24).toString("base64url");states.set(state,{provider,createdAt:Date.now(),legalVersion:LEGAL_VERSION,termsAccepted:true,privacyAccepted:true,context:context(req)});return redirect(res,authorizationUrl(provider,state))}const done=requestUrl.pathname.match(/^\/api\/auth\/oauth\/(google|yandex|vk)\/callback$/);if(req.method==="GET"&&done){try{const state=requestUrl.searchParams.get("state")||"",pending=states.get(state);states.delete(state);if(!pending||pending.provider!==done[1]||Date.now()-pending.createdAt>10*60*1000)throw new Error("OAuth state is invalid or expired");const profile=await exchange(done[1],requestUrl.searchParams.get("code")||"");const session=await store.oauthLogin({provider:done[1],...profile,legalVersion:pending.legalVersion,termsAccepted:pending.termsAccepted,privacyAccepted:pending.privacyAccepted},pending.context);return redirect(res,`${ORIGIN}/#oauth_token=${encodeURIComponent(session.token)}`)}catch(error){return redirect(res,`${ORIGIN}/?auth=login&oauth_error=${encodeURIComponent(error instanceof Error?error.message:String(error))}`)}}return false}
