export const TT_KB_VERSION="2026-09-04";
export const ttKnowledgeBase=[
  {id:"yandex-direct-html5",platform:"Yandex Direct",publisher:"Yandex",category:"DSP / publisher",status:"verified",sourceType:"official",sourceUrl:"https://yandex.ru/support/direct/ru/products-cpm-campaign/requirements",sourceTitle:"Требования к HTML5-баннерам",lastCheckedAt:"2026-09-04",sourceUpdatedAt:null,formats:["240×400","300×250","300×500","300×600","320×50","320×100","320×480","336×280","480×320","728×90","970×250"],fileTypes:["ZIP","JPG","PNG","GIF"],html5:true,maxZipKb:512,maxIndexKb:150,maxDurationSec:null,maxFiles:20,clickTracking:"Click must open advertised site only after left mouse click",tracking:"Placement-specific",notes:["HTML5 size must match ad slot","Archive links must be relative","No video/audio in HTML5 banner"],refreshMode:"web+ai"},
  {id:"adfox-banner-html5",platform:"Adfox",publisher:"Yandex",category:"Ad server",status:"verified",sourceType:"official",sourceUrl:"https://yandex.ru/support/adfox/ru/banners/specs/",sourceTitle:"Требования к баннерам",lastCheckedAt:"2026-09-04",sourceUpdatedAt:null,formats:[],fileTypes:["HTML5","Image","Video"],html5:true,maxZipKb:null,maxIndexKb:null,maxDurationSec:null,maxFiles:null,clickTracking:"Format-specific; supports transition URL/click handling",tracking:"Format-specific; impression/click tracking supported",notes:["Requirements differ by Adfox banner format","Use exact placement/banner subtype before applying limits"],refreshMode:"web+ai"},
  {id:"adriver",platform:"AdRiver",publisher:"AdRiver",category:"Ad server",status:"verified",sourceType:"official",sourceUrl:"https://www.adriver.ru/doc/agency/interface/main/placement/",sourceTitle:"AdRiver placement documentation",lastCheckedAt:"2026-09-04",sourceUpdatedAt:null,formats:[],fileTypes:["HTML5","Image"],html5:true,maxZipKb:null,maxIndexKb:null,maxDurationSec:null,maxFiles:null,clickTracking:"AdRiver click URL / click tracking integration",tracking:"Impression URL can return 1×1 GIF; placement-specific",notes:["Final TT may be defined by publisher placement","Do not infer size/weight limits without placement source"],refreshMode:"web+ai"},
  {id:"habr",platform:"Habr",publisher:"Habr",category:"Publisher",status:"verified",sourceType:"official",sourceUrl:"https://habr.com/ru/docs/docs/ad_code/",sourceTitle:"Рекламный кодекс Хабра",lastCheckedAt:"2026-09-04",sourceUpdatedAt:null,formats:[],fileTypes:["JPG","PNG"],html5:false,maxZipKb:null,maxIndexKb:null,maxDurationSec:0,maxFiles:null,clickTracking:"Publisher-managed",tracking:"Publisher-managed",notes:["Animation, video and sound are not accepted","Max 200 KiB desktop, 150 KiB mobile","Light background requires 1px #D5DDDF border"],refreshMode:"web+ai"},
  {id:"yandex-services",platform:"Yandex Services",publisher:"Yandex",category:"Publisher",status:"verified",sourceType:"official",sourceUrl:"https://yandex.ru/support/direct/ru/fixed-cpm-campaigns/product-yandex-services/requirements-ya",sourceTitle:"Требования к баннерам на сервисах Яндекса",lastCheckedAt:"2026-09-04",sourceUpdatedAt:null,formats:["300×600","240×400","300×250","300×300"],fileTypes:["HTML5","JPG","PNG","GIF"],html5:true,maxZipKb:512,maxIndexKb:null,maxDurationSec:null,maxFiles:null,clickTracking:"Yandex Direct HTML5 rules",tracking:"Placement-specific",notes:["Different creative sets for desktop/mobile/cross"],refreshMode:"web+ai"},
  {id:"yandex-frontpage",platform:"Yandex Frontpage / ya.ru",publisher:"Yandex",category:"Publisher",status:"verified",sourceType:"official",sourceUrl:"https://www.yandex.ru/support/direct/ru/products-cpm-campaign-frontpage/requirements",sourceTitle:"Требования к баннеру",lastCheckedAt:"2026-09-04",sourceUpdatedAt:null,formats:["1456×180","640×134"],fileTypes:["HTML5","JPG","PNG","GIF"],html5:true,maxZipKb:1024,maxIndexKb:null,maxDurationSec:null,maxFiles:null,clickTracking:"Yandex Direct HTML5 rules",tracking:"Placement-specific",notes:["HTML5 is desktop-only for this product","Mobile ya.ru does not accept HTML5"],refreshMode:"web+ai"},
  {id:"hh",platform:"hh.ru",publisher:"HeadHunter",category:"Publisher",status:"needs-refresh",sourceType:"official",sourceUrl:"https://feedback.hh.ru/knowledge-base/article/00222",sourceTitle:"Технические требования к рекламным материалам",lastCheckedAt:"2026-09-04",sourceUpdatedAt:"2026-07-09",formats:["250×160","320×100"],fileTypes:["Image","HTML5 via Adfox"],html5:true,maxZipKb:null,maxIndexKb:null,maxDurationSec:null,maxFiles:null,clickTracking:"Placement-specific / Adfox for HTML5",tracking:"Placement-specific",notes:["Contains placement-specific safe zones and 2× assets","Refresh before applying to a campaign because rules vary by placement"],refreshMode:"web+ai"}
];
