import {describe,it,expect} from 'vitest';
import {publishTemplate,productionCampaign} from '../src/mvp2/production.mjs';
import {campaignCompliance} from './mvp2Compliance.mjs';
import {createCampaignBuildManifest} from './mvp2Builds.mjs';
import {campaignZip,zipFiles} from './mvp2Packaging.mjs';
const campaign=()=>({id:'c',name:'Campaign',contentVariants:[{id:'en',name:'EN',language:'en',headline:'Summer sale',copy:'Selected items',cta:'Shop now',legal:'18+'},{id:'ru',name:'RU',language:'ru',headline:'Летняя акция',copy:'Выбранные товары',cta:'Подробнее',legal:'18+'}],placements:[{id:'p',platform:'Client',placement:'Top',width:300,height:250,contentVariantIds:['en','ru'],creativeType:'HTML5',requirements:{sourceLabel:'Client brief',maxZipKb:150,maxDurationSec:1,clickTag:true,clickUrl:'https://example.test/shop',legal:'18+'}}],formats:[{id:'f',width:300,height:250,placementIds:['p'],creativeState:'missing',creativeVersion:0}]});
const published=()=>{const c=campaign();return {...c,...publishTemplate(c)}};
describe('campaign production vertical slice',()=>{
 it('expands content assignments without multiplying source frames',()=>{const c=published(),p=productionCampaign(c);expect(c.formats).toHaveLength(1);expect(p.placements).toHaveLength(2);expect(campaignCompliance(c).summary).toEqual({ready:2,total:2,blocked:0,warning:0})});
 it('blocks stale publication and preserves property overrides on republish',()=>{let c=published();c.formats[0].roleOverrides={'headline.primary':{fontSize:20}};expect(campaignCompliance(c).summary.blocked).toBe(2);c={...c,...publishTemplate(c)};c.contentVariants[0].headline='New sale';expect(campaignCompliance(c).summary.blocked).toBe(2);c={...c,...publishTemplate(c)};expect(c.formats[0].variantRenders.en.roles.find((r:any)=>r.id==='headline.primary').fontSize).toBe(20);expect(campaignCompliance(c).summary.ready).toBe(2)});
 it('blocks required legal mismatch, missing assignments, long text and unsupported outputs',()=>{for(const mutate of [(c:any)=>c.contentVariants[0].legal='',(c:any)=>c.placements[0].contentVariantIds=[],(c:any)=>c.contentVariants[0].headline='long '.repeat(200),(c:any)=>c.placements[0].creativeType='MP4']){const c=campaign();mutate(c);const p={...c,...publishTemplate(c)};expect(createCampaignBuildManifest(p).state).toBe('blocked')}});
 it('produces real ZIP bytes with immutable per-variant HTML and pinned versions',()=>{const c=published(),b=createCampaignBuildManifest(c);expect(b.state).toBe('ready');expect(b.placements).toHaveLength(2);expect(b.placements[0].files[0].content).toContain('Summer sale');expect(b.placements[1].files[0].content).toContain('Летняя акция');const bytes=campaignZip(b);expect(bytes.readUInt32LE(0)).toBe(0x04034b50);expect(bytes.equals(campaignZip(b))).toBe(true);c.contentVariants[0].headline='Changed';expect(b.placements[0].files[0].content).toContain('Summer sale')});
 it('refuses replacing a Figma publication with a template',()=>{const c=campaign();c.formats[0].creativeState='published';expect(()=>publishTemplate(c)).toThrow('Figma')});
 it('refuses unsafe package paths and empty builds',()=>{expect(()=>zipFiles([{name:'../x',content:'x'}])).toThrow();expect(createCampaignBuildManifest({id:'empty',placements:[],formats:[]}).state).toBe('blocked')});
});
