import { useMemo, useRef, useState } from "react";
import { AlertTriangle, ArrowRight, Check, ChevronDown, CircleCheck, Clock3, Download, FileSpreadsheet, Image, LayoutGrid, MoreHorizontal, PackageCheck, Plus, Search, Settings2, Upload, Users } from "lucide-react";

type Status="ready"|"review"|"missing";
type Format={id:string;name:string,size:string,family:string,status:Status,note:string,anchor?:boolean};
const seed:Format[]=[
 {id:"f1",name:"Medium rectangle",size:"300 × 250",family:"Rectangles",status:"ready",note:"Google Ads · 128 KB",anchor:true},
 {id:"f2",name:"Large rectangle",size:"336 × 280",family:"Rectangles",status:"ready",note:"Inherited from 300×250"},
 {id:"f3",name:"Square",size:"300 × 300",family:"Rectangles",status:"review",note:"Headline wraps to 3 lines"},
 {id:"f4",name:"Half page",size:"300 × 600",family:"Vertical",status:"ready",note:"Google Ads · 141 KB",anchor:true},
 {id:"f5",name:"Wide skyscraper",size:"160 × 600",family:"Vertical",status:"review",note:"Product crop needs review"},
 {id:"f6",name:"Leaderboard",size:"728 × 90",family:"Wide",status:"ready",note:"Yandex · 96 KB",anchor:true},
 {id:"f7",name:"Super leaderboard",size:"970 × 90",family:"Wide",status:"ready",note:"Inherited from 728×90"},
 {id:"f8",name:"Mobile banner",size:"320 × 50",family:"Mobile strips",status:"missing",note:"Short copy is missing",anchor:true},
];
const families=[{name:"Rectangles",detail:"3 formats · 1 anchor"},{name:"Vertical",detail:"2 formats · 1 anchor"},{name:"Wide",detail:"2 formats · 1 anchor"},{name:"Mobile strips",detail:"1 format · 1 anchor"}];

export default function CampaignHub(){
 const [formats,setFormats]=useState(seed),[family,setFamily]=useState("All formats"),[query,setQuery]=useState(""),[toast,setToast]=useState("");
 const mediaInput=useRef<HTMLInputElement>(null),assetInput=useRef<HTMLInputElement>(null);
 const shown=useMemo(()=>formats.filter(f=>(family==="All formats"||f.family===family)&&`${f.name} ${f.size}`.toLowerCase().includes(query.toLowerCase())),[formats,family,query]);
 const ready=formats.filter(f=>f.status==="ready").length,review=formats.filter(f=>f.status==="review").length,missing=formats.filter(f=>f.status==="missing").length;
 const notify=(message:string)=>{setToast(message);window.setTimeout(()=>setToast(""),2600)};
 const addMedia=(files:FileList|null)=>{if(!files?.length)return;notify(`${files[0].name} imported · requirements matched`)};
 const addAssets=(files:FileList|null)=>{if(!files?.length)return;notify(`${files.length} campaign asset${files.length>1?"s":""} added`)};
 const openEditor=(format:Format)=>{sessionStorage.setItem("campaign:selected-format",format.id);location.href="?view=editor"};
 const approve=(id:string)=>setFormats(current=>current.map(f=>f.id===id?{...f,status:"ready",note:"Approved manually"}:f));
 return <div className="campaign-app">
  <header className="campaign-top"><div className="campaign-brand"><b>B</b><span>Banner Campaigns</span></div><div className="campaign-crumb"><span>Campaigns</span><b>/</b><strong>Summer Product Launch</strong><em>Draft</em></div><div className="campaign-actions"><button><Users size={15}/> Share</button><button><MoreHorizontal size={17}/></button><button className="export" onClick={()=>notify("Export queue prepared for 5 ready formats")}><Download size={15}/> Export ready</button></div></header>
  <div className="campaign-layout">
   <aside className="campaign-nav"><nav><button className="active"><LayoutGrid size={16}/> Overview</button><button><Image size={16}/> Campaign assets <i>12</i></button><button><FileSpreadsheet size={16}/> Media plan</button><button><PackageCheck size={16}/> QA & export <i className="warn">3</i></button></nav><div className="nav-divider"/><small>FORMAT FAMILIES</small><button className={family==="All formats"?"family active":"family"} onClick={()=>setFamily("All formats")}><span><b>All formats</b><em>8 total</em></span></button>{families.map(item=><button key={item.name} className={family===item.name?"family active":"family"} onClick={()=>setFamily(item.name)}><span><b>{item.name}</b><em>{item.detail}</em></span></button>)}<button className="add-family"><Plus size={14}/> Add family</button><div className="nav-bottom"><button><Settings2 size={15}/> Campaign settings</button></div></aside>
   <main className="campaign-main">
    <section className="campaign-heading"><div><span>CAMPAIGN WORKSPACE</span><h1>Summer Product Launch</h1><p>20 planned formats · 4 composition families · Google Ads, Yandex</p></div><button className="media-button" onClick={()=>mediaInput.current?.click()}><Upload size={15}/> Update media plan</button><input ref={mediaInput} hidden type="file" accept=".xlsx,.xls,.csv" onChange={e=>addMedia(e.target.files)}/></section>
    <section className="readiness"><div className="progress-card"><div className="progress-title"><span><b>Campaign readiness</b><small>5 of 8 configured formats can be exported</small></span><strong>{Math.round(ready/formats.length*100)}%</strong></div><div className="progress"><i style={{width:`${ready/formats.length*100}%`}}/></div><div className="status-legend"><span className="ok"><CircleCheck size={14}/><b>{ready} ready</b></span><span className="review"><Clock3 size={14}/><b>{review} review</b></span><span className="missing"><AlertTriangle size={14}/><b>{missing} blocked</b></span></div></div><div className="next-card"><span>NEXT ACTION</span><b>Finish mobile strip</b><p>Add a short headline for 320 × 50. Other assets are linked.</p><button onClick={()=>openEditor(formats[7])}>Open format <ArrowRight size={14}/></button></div></section>
    <section className="asset-strip"><div><span>LINKED CAMPAIGN ASSETS</span><b>Change once, update every format</b></div>{["Background · wide","Background · tall","Brand logo","Product hero","CTA copy"].map((name,index)=><button key={name} className="asset-slot"><i className={`slot-art art-${index}`}/><span><b>{name}</b><small>{index===4?"Shop now":"Linked · 4 families"}</small></span><Check size={13}/></button>)}<button className="asset-upload" onClick={()=>assetInput.current?.click()}><Plus size={15}/><span>Add assets</span></button><input ref={assetInput} hidden multiple type="file" accept="image/*,.svg" onChange={e=>addAssets(e.target.files)}/></section>
    <section className="formats-section"><div className="formats-toolbar"><div><h2>{family}</h2><span>{shown.length} formats</span></div><label><Search size={14}/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search formats"/></label><button><Settings2 size={14}/> Filter</button><button className="add-format"><Plus size={14}/> Add format</button></div><div className="format-table"><div className="format-table-head"><span>FORMAT</span><span>FAMILY / SOURCE</span><span>TECHNICAL STATUS</span><span>READY</span><span/></div>{shown.map(format=><div className="format-row" key={format.id}><button className="format-preview" onClick={()=>openEditor(format)}><i className={`preview-art ${format.family.toLowerCase().replace(" ","-")}`}><small>{format.size.replace(" × ","×")}</small></i><span><b>{format.name}</b><small>{format.size}</small></span></button><div className="source-cell"><b>{format.family}</b><small>{format.anchor?"Anchor composition":"Linked responsive version"}</small>{format.anchor&&<em>ANCHOR</em>}</div><div className={`qa-cell ${format.status}`}><span>{format.status==="ready"?<CircleCheck size={15}/>:format.status==="review"?<Clock3 size={15}/>:<AlertTriangle size={15}/>}<b>{format.status==="ready"?"Passed":format.status==="review"?"Needs review":"Blocked"}</b></span><small>{format.note}</small></div><div className="ready-cell"><i className={format.status}/><span>{format.status==="ready"?"Ready":format.status==="review"?"Review":"Missing"}</span></div><div className="row-actions">{format.status==="review"&&<button title="Approve" onClick={()=>approve(format.id)}><Check size={14}/></button>}<button className="open-editor" onClick={()=>openEditor(format)}>Open editor <ArrowRight size={13}/></button></div></div>)}</div></section>
   </main>
  </div>{toast&&<div className="campaign-toast"><CircleCheck size={16}/>{toast}</div>}
 </div>
}
