import { useEffect, useMemo, useRef, useState } from "react";
import { AlertTriangle, ArrowRight, Check, CircleCheck, Clock3, Download, FileSpreadsheet, FileText, Image, LayoutGrid, Link2, LoaderCircle, MoreHorizontal, PackageCheck, Plus, Search, Settings2, Upload, Users, X } from "lucide-react";
import { matchPlanFormats, processDeliveryInput, type DeliveryPlan } from "./deliveryPlan";

type Status="ready"|"review"|"missing";
type Format={id:string;name:string,size:string,family:string,status:Status,note:string,anchor?:boolean};
const seed:Format[]=[
 {id:"f1",name:"Medium rectangle",size:"300 × 250",family:"Rectangles",status:"ready",note:"Google Ads · 128 KB",anchor:true},
 {id:"f2",name:"Large rectangle",size:"336 × 280",family:"Rectangles",status:"ready",note:"Inherited from 300×250"},
 {id:"f3",name:"Square",size:"300 × 300",family:"Rectangles",status:"review",note:"Headline wraps to 3 lines"},
 {id:"f4",name:"Half page",size:"300 × 600",family:"Vertical",status:"ready",note:"Google Ads · 141 KB",anchor:true},
 {id:"f5",name:"Wide skyscraper",size:"160 × 600",family:"Vertical",status:"review",note:"Product crop needs review"},
 {id:"f6",name:"Leaderboard",size:"728 × 90",family:"Wide",status:"ready",note:"Yandex · 96 KB",anchor:true},
 {id:"f7",name:"Super leaderboard",size:"970 × 90",family:"Wide",status:"ready",note:"Inherited from 728×90"},
 {id:"f8",name:"Mobile banner",size:"320 × 50",family:"Mobile strips",status:"missing",note:"Short copy is missing",anchor:true},
];
const families=[{name:"Rectangles",detail:"3 formats · 1 anchor"},{name:"Vertical",detail:"2 formats · 1 anchor"},{name:"Wide",detail:"2 formats · 1 anchor"},{name:"Mobile strips",detail:"1 format · 1 anchor"}];
const PLAN_KEY="banner-editor:delivery-plan";

export default function CampaignHub(){
 const [formats,setFormats]=useState(seed),[family,setFamily]=useState("All formats"),[query,setQuery]=useState(""),[toast,setToast]=useState("");
 const [plan,setPlan]=useState<DeliveryPlan|null>(()=>{try{return JSON.parse(localStorage.getItem(PLAN_KEY)||"null")}catch{return null}}),[planOpen,setPlanOpen]=useState(false),[planFiles,setPlanFiles]=useState<File[]>([]),[planNotes,setPlanNotes]=useState(""),[processing,setProcessing]=useState(false);
 const mediaInput=useRef<HTMLInputElement>(null),assetInput=useRef<HTMLInputElement>(null);
 const shown=useMemo(()=>formats.filter(f=>(family==="All formats"||f.family===family)&&`${f.name} ${f.size}`.toLowerCase().includes(query.toLowerCase())),[formats,family,query]);
 const ready=formats.filter(f=>f.status==="ready").length,review=formats.filter(f=>f.status==="review").length,missing=formats.filter(f=>f.status==="missing").length;
 const planMatch=useMemo(()=>plan?matchPlanFormats(plan,formats.map(f=>f.size)):null,[plan,formats]);
 const platforms=useMemo(()=>plan?[...new Set(plan.placements.map(p=>p.platform).filter(Boolean))]:[],[plan]);
 useEffect(()=>{if(plan)localStorage.setItem(PLAN_KEY,JSON.stringify(plan));else localStorage.removeItem(PLAN_KEY)},[plan]);
 const notify=(message:string)=>{setToast(message);window.setTimeout(()=>setToast(""),2600)};
 const addAssets=(files:FileList|null)=>{if(!files?.length)return;notify(`${files.length} campaign asset${files.length>1?"s":""} added`)};
 const openEditor=(format:Format)=>{sessionStorage.setItem("campaign:selected-format",format.id);location.href="?view=editor"};
 const approve=(id:string)=>setFormats(current=>current.map(f=>f.id===id?{...f,status:"ready",note:"Approved manually"}:f));
 const choosePlanFiles=(files:FileList|null)=>{if(!files?.length)return;setPlanFiles(current=>[...current,...Array.from(files)]);setPlanOpen(true)};
 const removePlanFile=(index:number)=>setPlanFiles(current=>current.filter((_,i)=>i!==index));
 const processPlan=async()=>{if(!planFiles.length&&!planNotes.trim())return;setProcessing(true);try{const result=await processDeliveryInput(planFiles,planNotes);setPlan(result);notify(`${result.uniqueFormats.length} formats recognized · creative state preserved`)}finally{setProcessing(false)}};
 return <div className="campaign-app">
  <header className="campaign-top"><div className="campaign-brand"><b>B</b><span>Banner Campaigns</span></div><div className="campaign-crumb"><span>Campaigns</span><b>/</b><strong>Summer Product Launch</strong><em>Draft</em></div><div className="campaign-actions"><button><Users size={15}/> Share</button><button><MoreHorizontal size={17}/></button><button className="export" onClick={()=>notify(`Export queue prepared for ${ready} ready formats`)}><Download size={15}/> Export ready</button></div></header>
  <div className="campaign-layout">
   <aside className="campaign-nav"><nav><button className="active"><LayoutGrid size={16}/> Overview</button><button><Image size={16}/> Creative assets <i>12</i></button><button onClick={()=>setPlanOpen(true)} className={plan?"has-plan":""}><FileSpreadsheet size={16}/> Delivery plan {plan&&<i>{plan.uniqueFormats.length}</i>}</button><button><PackageCheck size={16}/> QA & export <i className="warn">3</i></button></nav><div className="nav-divider"/><small>FORMAT FAMILIES</small><button className={family==="All formats"?"family active":"family"} onClick={()=>setFamily("All formats")}><span><b>All formats</b><em>{formats.length} total</em></span></button>{families.map(item=><button key={item.name} className={family===item.name?"family active":"family"} onClick={()=>setFamily(item.name)}><span><b>{item.name}</b><em>{item.detail}</em></span></button>)}<button className="add-family"><Plus size={14}/> Add family</button><div className="nav-bottom"><button><Settings2 size={15}/> Campaign settings</button></div></aside>
   <main className="campaign-main">
    <section className="campaign-heading"><div><span>CAMPAIGN WORKSPACE</span><h1>Summer Product Launch</h1><p>{plan?`${plan.uniqueFormats.length} planned formats · ${platforms.length||1} placement groups · plan connected`:`${formats.length} creative formats · Delivery Plan can be connected at any time`}</p></div></section>

    <section className={`delivery-summary ${plan?"connected":"empty"}`}>
     <div className="delivery-icon"><FileSpreadsheet size={18}/></div>
     <div className="delivery-copy"><span>DELIVERY PLAN / TECHNICAL REQUIREMENTS</span>{plan?<><b>{plan.sources.length} sources connected · {plan.placements.length} placements recognized</b><p>Creative work stays independent. Updating the plan only rematches requirements against the current campaign.</p></>:<><b>Start designing now. Attach the media plan or TT whenever it arrives.</b><p>Excel, CSV, DOCX, PDF, links or pasted notes. Connecting requirements never resets formats, assets or animation.</p></>}</div>
     {plan&&planMatch?<div className="delivery-coverage"><strong>{planMatch.coverage}%</strong><span>{planMatch.matched.length} matched</span><small>{planMatch.missing.length} missing</small></div>:<div className="delivery-state"><span>Optional now</span><small>Always available</small></div>}
     <button className="delivery-action" onClick={()=>setPlanOpen(true)}><Upload size={14}/>{plan?"Review / update":"Attach plan or TT"}</button>
    </section>

    {planOpen&&<section className="plan-workbench">
     <div className="plan-workbench-head"><div><span>DELIVERY INPUT</span><h2>{plan?"Review or update Delivery Plan":"Connect campaign requirements"}</h2><p>Add whatever you actually received. Existing creative state is never replaced by this step.</p></div><button className="plan-close" onClick={()=>setPlanOpen(false)}><X size={16}/></button></div>
     <div className="plan-input-grid">
      <button className="plan-drop" onClick={()=>mediaInput.current?.click()}><Upload size={20}/><b>Add files</b><span>Excel · CSV · DOCX · PDF · TXT</span><small>Multiple sources are supported</small></button>
      <input ref={mediaInput} hidden multiple type="file" accept=".xlsx,.xls,.csv,.tsv,.txt,.docx,.pdf" onChange={e=>choosePlanFiles(e.target.files)}/>
      <label className="plan-notes"><span><Link2 size={13}/> Links, notes or a format list</span><textarea value={planNotes} onChange={e=>setPlanNotes(e.target.value)} placeholder={'RBC | 970×250 | HTML5 | https://…\n300×250, 300×600 — TT in the link above'}/><small>Paste raw client text as-is. The normalizer extracts formats and links first; AI enrichment is the next processing layer.</small></label>
     </div>
     {!!planFiles.length&&<div className="plan-files">{planFiles.map((file,index)=><div key={`${file.name}-${index}`}><span>{file.name.match(/\.xlsx?|\.csv|\.tsv/i)?<FileSpreadsheet size={14}/>:<FileText size={14}/>}<b>{file.name}</b><small>{Math.max(1,Math.round(file.size/1024))} KB</small></span><button onClick={()=>removePlanFile(index)}><X size={13}/></button></div>)}</div>}
     <div className="plan-process-row"><div><b>Processing is non-destructive</b><span>Parse → normalize → match. Unknown documents are marked for OpenRouter extraction instead of being guessed.</span></div><button disabled={processing||(!planFiles.length&&!planNotes.trim())} onClick={processPlan}>{processing?<LoaderCircle className="spin" size={15}/>:<ArrowRight size={15}/>} {processing?"Processing…":"Process sources"}</button></div>

     {plan&&planMatch&&<div className="plan-result">
      <div className="plan-result-title"><div><span>IMPORT RESULT</span><h3>{plan.uniqueFormats.length} required formats found</h3></div><div className="result-metrics"><span><b>{planMatch.matched.length}</b><small>already covered</small></span><span><b>{planMatch.missing.length}</b><small>not in campaign</small></span><span><b>{plan.needsAi}</b><small>need AI extraction</small></span></div></div>
      <div className="source-status-list">{plan.sources.map(source=><div key={source.id} className={source.status}><span>{source.kind==="link"?<Link2 size={14}/>:source.kind==="spreadsheet"?<FileSpreadsheet size={14}/>:<FileText size={14}/>}<b>{source.name}</b></span><small>{source.detail}</small><em>{source.status==="parsed"?"Parsed":source.status==="needs-ai"?"OpenRouter next":"Check source"}</em></div>)}</div>
      <div className="plan-match-grid"><div><span>CURRENT CAMPAIGN</span><b>{planMatch.matched.length} plan formats already exist</b><div className="format-chips">{planMatch.matched.length?planMatch.matched.map(size=><i className="matched" key={size}>{size}</i>):<small>No direct matches yet</small>}</div></div><div><span>NEXT DEVELOPMENT STAGE</span><b>{planMatch.missing.length?`${planMatch.missing.length} formats need matching / creation logic`:"All recognized sizes are covered"}</b><div className="format-chips">{planMatch.missing.length?planMatch.missing.map(size=><i className="missing" key={size}>{size}</i>):<i className="matched">Ready for validation rules</i>}</div></div></div>
      {!!plan.placements.length&&<div className="placement-preview"><div className="placement-head"><span>PLACEMENT</span><span>FORMAT</span><span>TYPE</span><span>TT SOURCE</span></div>{plan.placements.slice(0,8).map(p=><div className="placement-row" key={p.id}><span><b>{p.platform}</b><small>{p.source}{p.row?` · row ${p.row}`:""}</small></span><b>{p.size}</b><span>{p.creativeType}</span><span>{p.ttUrl?<a href={p.ttUrl} target="_blank" rel="noreferrer">Linked TT</a>:Object.keys(p.requirements).length?"Inline rules":"Not resolved"}</span></div>)}</div>}
      <div className="plan-result-foot"><span><Check size={14}/> Campaign formats, assets and Motion were not changed.</span><button onClick={()=>setPlanOpen(false)}>Keep working <ArrowRight size={14}/></button></div>
     </div>}
    </section>}

    <section className="readiness"><div className="progress-card"><div className="progress-title"><span><b>Creative readiness</b><small>{ready} of {formats.length} configured formats can be exported</small></span><strong>{Math.round(ready/formats.length*100)}%</strong></div><div className="progress"><i style={{width:`${ready/formats.length*100}%`}}/></div><div className="status-legend"><span className="ok"><CircleCheck size={14}/><b>{ready} ready</b></span><span className="review"><Clock3 size={14}/><b>{review} review</b></span><span className="missing"><AlertTriangle size={14}/><b>{missing} blocked</b></span></div></div><div className="next-card"><span>NEXT CREATIVE ACTION</span><b>Finish mobile strip</b><p>Delivery requirements are independent from creative progress.</p><button onClick={()=>openEditor(formats[7])}>Open format <ArrowRight size={14}/></button></div></section>
    <section className="asset-strip"><div><span>LINKED CAMPAIGN ASSETS</span><b>Change once, update every format</b></div>{["Background · wide","Background · tall","Brand logo","Product hero","CTA copy"].map((name,index)=><button key={name} className="asset-slot"><i className={`slot-art art-${index}`}/><span><b>{name}</b><small>{index===4?"Shop now":"Linked · 4 families"}</small></span><Check size={13}/></button>)}<button className="asset-upload" onClick={()=>assetInput.current?.click()}><Plus size={15}/><span>Add assets</span></button><input ref={assetInput} hidden multiple type="file" accept="image/*,.svg" onChange={e=>addAssets(e.target.files)}/></section>
    <section className="formats-section"><div className="formats-toolbar"><div><h2>{family}</h2><span>{shown.length} formats</span></div><label><Search size={14}/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search formats"/></label><button><Settings2 size={14}/> Filter</button><button className="add-format"><Plus size={14}/> Add format</button></div><div className="format-table"><div className="format-table-head"><span>FORMAT</span><span>FAMILY / SOURCE</span><span>TECHNICAL STATUS</span><span>READY</span><span/></div>{shown.map(format=><div className="format-row" key={format.id}><button className="format-preview" onClick={()=>openEditor(format)}><i className={`preview-art ${format.family.toLowerCase().replace(" ","-")}`}><small>{format.size.replace(" × ","×")}</small></i><span><b>{format.name}</b><small>{format.size}</small></span></button><div className="source-cell"><b>{format.family}</b><small>{format.anchor?"Anchor composition":"Linked responsive version"}</small>{format.anchor&&<em>ANCHOR</em>}</div><div className={`qa-cell ${format.status}`}><span>{format.status==="ready"?<CircleCheck size={15}/>:format.status==="review"?<Clock3 size={15}/>:<AlertTriangle size={15}/>}<b>{format.status==="ready"?"Passed":format.status==="review"?"Needs review":"Blocked"}</b></span><small>{format.note}</small></div><div className="ready-cell"><i className={format.status}/><span>{format.status==="ready"?"Ready":format.status==="review"?"Review":"Missing"}</span></div><div className="row-actions">{format.status==="review"&&<button title="Approve" onClick={()=>approve(format.id)}><Check size={14}/></button>}<button className="open-editor" onClick={()=>openEditor(format)}>Open editor <ArrowRight size={13}/></button></div></div>)}</div></section>
   </main>
  </div>{toast&&<div className="campaign-toast"><CircleCheck size={16}/>{toast}</div>}
 </div>
}
