export type DeliverySourceKind="spreadsheet"|"document"|"link"|"text";
export type DeliverySourceStatus="parsed"|"needs-ai"|"error";
export type DeliverySource={id:string;name:string;kind:DeliverySourceKind,status:DeliverySourceStatus,detail:string};
export type DeliveryRequirement={maxZipKb?:number,maxDurationSec?:number,clickTag?:boolean,tracking?:boolean};
export type DeliveryPlacement={id:string,platform:string,size:string,width:number,height:number,creativeType:string,ttUrl?:string,requirements:DeliveryRequirement,source:string,row?:number};
export type DeliveryPlan={sources:DeliverySource[],placements:DeliveryPlacement[],uniqueFormats:string[],needsAi:number,createdAt:number};

const SIZE_RE=/(\d{2,4})\s*[x×х]\s*(\d{2,4})/gi;
const URL_RE=/https?:\/\/[^\s,;]+/i;
const textDecoder=new TextDecoder();
const xmlText=(xml:string)=>new DOMParser().parseFromString(xml,"application/xml");
const clean=(value:string)=>value.replace(/\s+/g," ").trim();
const sizeKey=(w:number,h:number)=>`${w}×${h}`;

function detectDelimiter(line:string){const options=[",",";","\t"];return options.sort((a,b)=>line.split(b).length-line.split(a).length)[0]}
export function parseDelimited(text:string){const lines=text.replace(/^\uFEFF/,"").split(/\r?\n/).filter(Boolean);if(!lines.length)return[];const delimiter=detectDelimiter(lines[0]);return lines.map(line=>{const cells:string[]=[];let cell="",quoted=false;for(let i=0;i<line.length;i++){const ch=line[i];if(ch==='"'){if(quoted&&line[i+1]==='"'){cell+='"';i++}else quoted=!quoted}else if(ch===delimiter&&!quoted){cells.push(clean(cell));cell=""}else cell+=ch}cells.push(clean(cell));return cells})}

function inferPlatform(text:string){const lower=text.toLowerCase();const known:[[RegExp,string]]|any=[[/google|gdn/,"Google Ads"],[/яндекс|yandex/,"Yandex"],[/adfox/,"AdFox"],[/vk|вконтакте/,"VK"],[/rbc|рбк/,"RBC"]];for(const [pattern,name] of known)if(pattern.test(lower))return name;const first=clean(text.split(/[|,;\t]/)[0]||"");return first&&first.length<40?first:"Unknown platform"}
function inferRequirements(text:string):DeliveryRequirement{const req:DeliveryRequirement={};const weight=text.match(/(\d+(?:[.,]\d+)?)\s*(kb|кб|mb|мб)/i);if(weight){const n=Number(weight[1].replace(",","."));req.maxZipKb=Math.round(n*(/mb|мб/i.test(weight[2])?1024:1))}const duration=text.match(/(?:duration|длительност\w*)[^\d]{0,12}(\d+(?:[.,]\d+)?)\s*(?:s|sec|сек|с\b)/i);if(duration)req.maxDurationSec=Number(duration[1].replace(",","."));if(/clicktag|click\s*tag/i.test(text))req.clickTag=true;if(/tracking|пиксел|pixel/i.test(text))req.tracking=true;return req}
function placementsFromRows(rows:string[][],source:string){const out:DeliveryPlacement[]=[];rows.forEach((cells,index)=>{const text=clean(cells.join(" | "));const matches=[...text.matchAll(SIZE_RE)];for(const match of matches){const width=Number(match[1]),height=Number(match[2]);const url=text.match(URL_RE)?.[0];out.push({id:`${source}-${index}-${width}x${height}`,platform:inferPlatform(text),size:sizeKey(width,height),width,height,creativeType:/static|jpg|jpeg|png|статик/i.test(text)?"Static":"HTML5",ttUrl:url,requirements:inferRequirements(text),source,row:index+1})}});return out}
function placementsFromText(text:string,source:string){return placementsFromRows(text.split(/\r?\n/).filter(Boolean).map(line=>[line]),source)}

async function inflateRaw(bytes:Uint8Array){const stream=new Blob([bytes]).stream().pipeThrough(new DecompressionStream("deflate-raw" as any));return new Uint8Array(await new Response(stream).arrayBuffer())}
async function unzip(buffer:ArrayBuffer){const data=new Uint8Array(buffer),view=new DataView(buffer);let eocd=-1;for(let i=data.length-22;i>=Math.max(0,data.length-65557);i--){if(view.getUint32(i,true)===0x06054b50){eocd=i;break}}if(eocd<0)throw new Error("ZIP directory not found");const entries=view.getUint16(eocd+10,true),centralOffset=view.getUint32(eocd+16,true);let cursor=centralOffset;const files=new Map<string,Uint8Array>();for(let i=0;i<entries;i++){if(view.getUint32(cursor,true)!==0x02014b50)break;const method=view.getUint16(cursor+10,true),compressed=view.getUint32(cursor+20,true),nameLen=view.getUint16(cursor+28,true),extraLen=view.getUint16(cursor+30,true),commentLen=view.getUint16(cursor+32,true),localOffset=view.getUint32(cursor+42,true),name=textDecoder.decode(data.slice(cursor+46,cursor+46+nameLen));const localNameLen=view.getUint16(localOffset+26,true),localExtraLen=view.getUint16(localOffset+28,true),start=localOffset+30+localNameLen+localExtraLen,chunk=data.slice(start,start+compressed);files.set(name,method===0?chunk:method===8?await inflateRaw(chunk):new Uint8Array());cursor+=46+nameLen+extraLen+commentLen}return files}
function sharedStrings(xml?:Uint8Array){if(!xml)return[];const doc=xmlText(textDecoder.decode(xml));return [...doc.getElementsByTagName("si")].map(si=>[...si.getElementsByTagName("t")].map(t=>t.textContent||"").join(""))}
function sheetRows(xml:Uint8Array,shared:string[]){const doc=xmlText(textDecoder.decode(xml)),rows:string[][]=[];for(const row of [...doc.getElementsByTagName("row")]){const cells:string[]=[];for(const c of [...row.getElementsByTagName("c")]){const ref=c.getAttribute("r")||"A1",letters=ref.match(/[A-Z]+/)?.[0]||"A";let col=0;for(const ch of letters)col=col*26+(ch.charCodeAt(0)-64);const type=c.getAttribute("t"),v=c.getElementsByTagName("v")[0]?.textContent||"";cells[col-1]=type==="s"?shared[Number(v)]||"":type==="inlineStr"?c.getElementsByTagName("t")[0]?.textContent||"":v}rows.push(cells.map(v=>v||""))}return rows}
async function parseXlsx(file:File){const zip=await unzip(await file.arrayBuffer()),shared=sharedStrings(zip.get("xl/sharedStrings.xml"));const sheets=[...zip.entries()].filter(([name])=>/^xl\/worksheets\/sheet\d+\.xml$/.test(name)).sort();const rows:string[][]=[];for(const [,xml] of sheets)rows.push(...sheetRows(xml,shared));return rows}
async function parseDocx(file:File){const zip=await unzip(await file.arrayBuffer()),xml=zip.get("word/document.xml");if(!xml)return"";const doc=xmlText(textDecoder.decode(xml));return [...doc.getElementsByTagName("w:t")].map(n=>n.textContent||"").join("\n")}

export async function processDeliveryInput(files:File[],pastedText=""):Promise<DeliveryPlan>{const sources:DeliverySource[]=[],placements:DeliveryPlacement[]=[];for(const file of files){const ext=file.name.split(".").pop()?.toLowerCase()||"";try{if(["csv","tsv","txt"].includes(ext)){const rows=parseDelimited(await file.text());placements.push(...placementsFromRows(rows,file.name));sources.push({id:crypto.randomUUID(),name:file.name,kind:ext==="txt"?"text":"spreadsheet",status:"parsed",detail:`${rows.length} rows scanned`})}else if(ext==="xlsx"){const rows=await parseXlsx(file);placements.push(...placementsFromRows(rows,file.name));sources.push({id:crypto.randomUUID(),name:file.name,kind:"spreadsheet",status:"parsed",detail:`${rows.length} spreadsheet rows scanned`})}else if(ext==="docx"){const text=await parseDocx(file);placements.push(...placementsFromText(text,file.name));sources.push({id:crypto.randomUUID(),name:file.name,kind:"document",status:"parsed",detail:"Document text extracted locally"})}else{sources.push({id:crypto.randomUUID(),name:file.name,kind:"document",status:"needs-ai",detail:"Queued for OpenRouter extraction in the AI processing stage"})}}catch(error){sources.push({id:crypto.randomUUID(),name:file.name,kind:"document",status:"error",detail:error instanceof Error?error.message:String(error)})}}
 if(clean(pastedText)){placements.push(...placementsFromText(pastedText,"Pasted notes & links"));sources.push({id:crypto.randomUUID(),name:"Pasted notes & links",kind:/https?:\/\//.test(pastedText)?"link":"text",status:"parsed",detail:"Text and links scanned"})}
 const deduped=new Map<string,DeliveryPlacement>();for(const placement of placements){const key=`${placement.platform}|${placement.size}|${placement.ttUrl||""}|${placement.row||""}`;if(!deduped.has(key))deduped.set(key,placement)}const final=[...deduped.values()];return{sources,placements:final,uniqueFormats:[...new Set(final.map(p=>p.size))],needsAi:sources.filter(s=>s.status==="needs-ai").length,createdAt:Date.now()}}

export function matchPlanFormats(plan:DeliveryPlan,creativeSizes:string[]){const creative=new Set(creativeSizes.map(s=>s.replace(/\s/g,"").replace(/[xх]/gi,"×")));const matched=plan.uniqueFormats.filter(size=>creative.has(size)),missing=plan.uniqueFormats.filter(size=>!creative.has(size));return{matched,missing,coverage:plan.uniqueFormats.length?Math.round(matched.length/plan.uniqueFormats.length*100):100}}
