import BezierEditor from "bezier-easing-editor";
import { Download, Eye, EyeOff, Image as ImageIcon, Lock, Plus, RefreshCw, Sparkles, Trash2, Type, Unlock, Upload } from "lucide-react";
import { useRef, useState } from "react";
import { formats } from "../model";
import { EASING_PRESETS, type Bezier, type Easing } from "../timeline";
import { aiAdaptAll, aiAdaptFormat, type AiFormatStatus } from "./aiLayout";
import CanvasV2 from "./CanvasV2";
import TimelineV2, { TransformInspector } from "./TimelineV2";
import { editorActions, useEditorState, type ProjectState } from "./editorStore";
import "./core.css";

const FONTS=["Manrope","Inter","Arial","Helvetica Neue","Roboto","PT Sans","PT Serif","Noto Sans","Georgia","Times New Roman"];
const download=(blob:Blob,name:string)=>{const a=document.createElement("a");a.href=URL.createObjectURL(blob);a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000)};
const pretty=(name:string)=>name.replaceAll("-"," ").replace(/\b\w/g,(m)=>m.toUpperCase());

export default function EditorCoreV2(){
  const state=useEditorState(),imageInput=useRef<HTMLInputElement>(null),projectInput=useRef<HTMLInputElement>(null),aiAbort=useRef<AbortController|null>(null);
  const [aiBusy,setAiBusy]=useState(false),[aiStatus,setAiStatus]=useState(""),[aiProgress,setAiProgress]=useState<Record<string,AiFormatStatus>>({});
  const elements=state.elementsByFormat[state.activeFormat]??[],selected=elements.find((e)=>e.id===state.selectedId)??null;
  const selectedKey=state.selectedId&&state.selectedKeyframeId?(state.keyframesByFormat[state.activeFormat]?.[state.selectedId]??[]).find((f)=>f.id===state.selectedKeyframeId)??null:null;
  const format=formats.find((f)=>f.id===state.activeFormat)!;
  const save=()=>download(new Blob([editorActions.exportProject()],{type:"application/json"}),`${state.title.replace(/[^a-z0-9-_]+/gi,"-").toLowerCase()||"banner-project"}.banner.json`);
  const open=async(file?:File)=>{if(!file)return;try{const parsed=JSON.parse(await file.text()) as ProjectState;if(parsed.version!==2)throw new Error("Unsupported project version");editorActions.importProject(parsed)}catch(error){alert(error instanceof Error?error.message:"Could not open project")}};
  const addFiles=async(files:FileList|null)=>{if(!files)return;for(const file of Array.from(files)){if(!file.type.startsWith("image/"))continue;const url=await new Promise<string>((resolve,reject)=>{const reader=new FileReader();reader.onload=()=>resolve(String(reader.result));reader.onerror=reject;reader.readAsDataURL(file)});editorActions.addImage(file.name,url)}if(imageInput.current)imageInput.current.value=""};
  const setEasing=(easing:Easing,curve?:Bezier)=>{if(!selectedKey)return;editorActions.setSelectedKeyEasing(easing,curve??(selectedKey.bezier??[.42,0,.58,1]) as Bezier)};
  const curve=(selectedKey?.bezier??[.42,0,.58,1]) as Bezier;
  const finishAi=()=>{aiAbort.current=null;setAiBusy(false)};
  const cancelAi=()=>{aiAbort.current?.abort();setAiStatus("Cancelling AI…")};
  const runAiAll=async()=>{const controller=new AbortController();aiAbort.current=controller;setAiBusy(true);setAiProgress({});setAiStatus("Preparing rule-based layouts…");try{const messages=await aiAdaptAll(setAiStatus,(formatId,status)=>setAiProgress((current)=>({...current,[formatId]:status})),controller.signal);setAiStatus(`AI ready · ${messages.length} formats`)}catch(error){setAiStatus(controller.signal.aborted?"AI adaptation cancelled":error instanceof Error?error.message:"AI Layout Director failed")}finally{finishAi()}};
  const runAiCurrent=async()=>{const controller=new AbortController();aiAbort.current=controller;setAiBusy(true);setAiProgress({[state.activeFormat]:"running"});setAiStatus(`AI: ${format.label}…`);try{const rationale=await aiAdaptFormat(state.activeFormat,controller.signal);setAiProgress({[state.activeFormat]:"ready"});setAiStatus(rationale||"AI resize ready")}catch(error){if(!controller.signal.aborted)setAiProgress({[state.activeFormat]:"fallback"});setAiStatus(controller.signal.aborted?"AI adaptation cancelled":error instanceof Error?error.message:"AI Layout Director failed")}finally{finishAi()}};
  return <div className="core-app">
    <header className="core-topbar"><div className="core-brand"><b>B</b><span><strong>{state.title}</strong><small>Editor Core v2 · Konva</small></span></div><nav><button onClick={()=>{if(confirm("Create a new project? Unsaved changes will be cleared."))editorActions.newProject()}}>New</button><button onClick={()=>projectInput.current?.click()}>Open</button><button onClick={save}>Save</button><button className="primary" onClick={save}><Download size={15}/> Save project</button></nav><input ref={projectInput} hidden type="file" accept=".json,.banner.json,application/json" onChange={(e)=>{void open(e.target.files?.[0]);e.currentTarget.value=""}}/></header>
    <main className="core-main"><aside className="core-sidebar"><div className="core-section-head"><span>ASSETS</span><b>Library</b></div><input ref={imageInput} hidden type="file" multiple accept="image/*" onChange={(e)=>void addFiles(e.target.files)}/><button className="core-upload" onClick={()=>imageInput.current?.click()}><Upload size={15}/> Upload images</button><button className="core-upload" onClick={()=>editorActions.addText()}><Type size={15}/> Add text</button><div className="core-section-head formats"><span>CAMPAIGN</span><b>Formats</b></div>{formats.map((f)=><button key={f.id} className={`core-format ${state.activeFormat===f.id?"active":""}`} onClick={()=>editorActions.setFormat(f.id)}><i style={{aspectRatio:`${f.width}/${f.height}`}}/><span><b>{f.label}</b><small>{f.width} × {f.height}{f.id!=="master"?aiProgress[f.id]==="running"?" · AI…":aiProgress[f.id]==="ready"?" · AI ready":aiProgress[f.id]==="fallback"?" · fallback":state.formatOverrides[f.id]?" · manual":" · auto":""}</small></span></button>)}</aside>
      <section className="core-workspace"><div className="core-stagebar"><b>{format.label}</b><span>{format.width} × {format.height}</span><div className="core-ai-status">{aiStatus}</div>{state.activeFormat==="master"?<><button disabled={aiBusy} className="core-ai-button" onClick={()=>void runAiAll()}><Sparkles size={14}/>{aiBusy?"AI adapting…":"AI adapt all"}</button>{aiBusy&&<button className="core-ai-cancel" onClick={cancelAi}>Cancel</button>}<button onClick={()=>editorActions.adaptAll(true)}><RefreshCw size={14}/> Rules only</button></>:<><button disabled={aiBusy} className="core-ai-button" onClick={()=>void runAiCurrent()}><Sparkles size={14}/>{aiBusy?"AI adapting…":"AI improve resize"}</button>{aiBusy&&<button className="core-ai-cancel" onClick={cancelAi}>Cancel</button>}<button onClick={()=>editorActions.resetFormatFromMaster()}><RefreshCw size={14}/> Reset from master</button></>}<button onClick={()=>editorActions.addText()}><Plus size={14}/> Text</button><button onClick={()=>imageInput.current?.click()}><ImageIcon size={14}/> Image</button></div><CanvasV2/></section>
      <aside className="core-right"><div className="core-section-head"><span>LAYERS</span><b>{elements.length} layers</b></div><div className="core-layers">{elements.slice().reverse().map((el)=><div key={el.id} className={`core-layer ${el.id===state.selectedId?"active":""}`}><button onClick={()=>editorActions.updateElement(el.id,{visible:!el.visible},false)}>{el.visible?<Eye size={14}/>:<EyeOff size={14}/>}</button><button className="name" onClick={()=>editorActions.select(el.id)}>{el.kind==="image"?<ImageIcon size={14}/>:<Type size={14}/>}<span>{el.name}</span></button><button onClick={()=>editorActions.updateElement(el.id,{locked:!el.locked},false)}>{el.locked?<Lock size={14}/>:<Unlock size={14}/>}</button></div>)}</div>
        {selected&&<><div className="core-object-actions"><button onClick={()=>editorActions.removeSelected()}><Trash2 size={14}/> Delete layer</button></div>{selected.kind!=="image"&&<section className="core-text-panel"><div className="core-section-head"><span>TEXT</span><b>Typography</b></div><textarea value={selected.text} onChange={(e)=>editorActions.updateElement(selected.id,{text:e.target.value},false)}/><label>Font<select value={selected.fontFamily} onChange={(e)=>editorActions.updateElement(selected.id,{fontFamily:e.target.value},false)}>{FONTS.map((f)=><option key={f}>{f}</option>)}</select></label><div className="core-text-grid"><label>Size<input type="number" min="6" max="300" value={selected.fontSize} onChange={(e)=>editorActions.updateElement(selected.id,{fontSize:Number(e.target.value)},false)}/></label><label>Line<input type="number" min="50" max="300" value={selected.lineHeight} onChange={(e)=>editorActions.updateElement(selected.id,{lineHeight:Number(e.target.value)},false)}/></label><label>Width<input type="number" min="5" max="100" value={selected.width} onChange={(e)=>editorActions.updateElement(selected.id,{width:Number(e.target.value)},false)}/></label><label>Color<input type="color" value={selected.color} onChange={(e)=>editorActions.updateElement(selected.id,{color:e.target.value},false)}/></label></div></section>}
        <TransformInspector element={selected}/>
        {selectedKey&&<section className="core-easing"><div className="core-section-head"><span>KEYFRAME GROUP</span><b>Motion / Easing</b></div><p className="core-motion-help">Preset applies to all animated properties in this keyframe.</p><div className="core-easing-presets">{EASING_PRESETS.filter((p)=>p!=="custom").map((preset)=><button key={preset} className={selectedKey.easing===preset?"active":""} onClick={()=>setEasing(preset)}>{pretty(preset)}</button>)}</div><button className={`core-custom-ease ${selectedKey.easing==="custom"?"active":""}`} onClick={()=>setEasing("custom")}>Custom cubic-bezier</button>{selectedKey.easing==="custom"&&<div className="core-bezier-editor"><BezierEditor value={curve} onChange={(value)=>setEasing("custom",value as Bezier)} width={260} height={170} padding={[14,14,22,22]}/><div className="core-bezier-fields">{curve.map((v,i)=><input key={i} type="number" min="0" max="1" step="0.01" value={v} onChange={(e)=>{const next=[...curve] as Bezier;next[i]=Math.max(0,Math.min(1,Number(e.target.value)));setEasing("custom",next)}}/>)}</div></div>}<button className="danger" onClick={()=>editorActions.deleteSelectedKeyframe()}>Delete keyframe</button></section>}</>}</aside>
    </main><TimelineV2/>
  </div>;
}
