import { Download, Eye, EyeOff, Image as ImageIcon, Lock, Plus, Trash2, Type, Unlock, Upload } from "lucide-react";
import { useRef } from "react";
import { formats } from "../model";
import type { Bezier, Easing } from "../timeline";
import CanvasV2 from "./CanvasV2";
import TimelineV2 from "./TimelineV2";
import { editorActions, getEditorState, useEditorState, type ProjectState } from "./editorStore";
import "./core.css";

const download = (blob: Blob, name: string) => { const a=document.createElement("a");a.href=URL.createObjectURL(blob);a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000); };

export default function EditorCoreV2() {
  const state=useEditorState();
  const imageInput=useRef<HTMLInputElement>(null),projectInput=useRef<HTMLInputElement>(null);
  const elements=state.elementsByFormat[state.activeFormat]??[];
  const selected=elements.find((e)=>e.id===state.selectedId)??null;
  const selectedKey=state.selectedId&&state.selectedKeyframeId?(state.keyframesByFormat[state.activeFormat]?.[state.selectedId]??[]).find((f)=>f.id===state.selectedKeyframeId)??null:null;
  const save=()=>download(new Blob([editorActions.exportProject()],{type:"application/json"}),`${state.title.replace(/[^a-z0-9-_]+/gi,"-").toLowerCase()||"banner-project"}.banner.json`);
  const open=async(file?:File)=>{if(!file)return;try{const parsed=JSON.parse(await file.text()) as ProjectState;if(parsed.version!==2)throw new Error("Unsupported project version");editorActions.importProject(parsed)}catch(error){alert(error instanceof Error?error.message:"Could not open project")}};
  const addFiles=async(files:FileList|null)=>{if(!files)return;for(const file of Array.from(files)){if(!file.type.startsWith("image/"))continue;const url=await new Promise<string>((resolve,reject)=>{const reader=new FileReader();reader.onload=()=>resolve(String(reader.result));reader.onerror=reject;reader.readAsDataURL(file)});editorActions.addImage(file.name,url)}if(imageInput.current)imageInput.current.value=""};
  const changeEasing=(easing:Easing)=>{if(!selectedKey)return;const curve=(selectedKey.bezier??[.42,0,.58,1]) as Bezier;editorActions.setSelectedKeyEasing(easing,curve)};
  return <div className="core-app">
    <header className="core-topbar"><div className="core-brand"><b>B</b><span><strong>{state.title}</strong><small>Editor Core v2 · Konva</small></span></div><nav><button onClick={()=>{if(confirm("Create a new project? Unsaved changes will be cleared."))editorActions.newProject()}}>New</button><button onClick={()=>projectInput.current?.click()}>Open</button><button onClick={save}>Save</button><button className="primary" onClick={save}><Download size={15}/> Save project</button></nav><input ref={projectInput} hidden type="file" accept=".json,.banner.json,application/json" onChange={(e)=>{void open(e.target.files?.[0]);e.currentTarget.value=""}}/></header>
    <main className="core-main"><aside className="core-sidebar"><div className="core-section-head"><span>ASSETS</span><b>Library</b></div><input ref={imageInput} hidden type="file" multiple accept="image/*" onChange={(e)=>void addFiles(e.target.files)}/><button className="core-upload" onClick={()=>imageInput.current?.click()}><Upload size={15}/> Upload images</button><button className="core-upload" onClick={()=>editorActions.addText()}><Type size={15}/> Add text</button><div className="core-section-head formats"><span>CAMPAIGN</span><b>Formats</b></div>{formats.map((f)=><button key={f.id} className={`core-format ${state.activeFormat===f.id?"active":""}`} onClick={()=>editorActions.setFormat(f.id)}><i style={{aspectRatio:`${f.width}/${f.height}`}}/><span><b>{f.label}</b><small>{f.width} × {f.height}</small></span></button>)}</aside>
      <section className="core-workspace"><div className="core-stagebar"><b>{formats.find((f)=>f.id===state.activeFormat)?.label}</b><span>{formats.find((f)=>f.id===state.activeFormat)?.width} × {formats.find((f)=>f.id===state.activeFormat)?.height}</span><div/><button onClick={()=>editorActions.addText()}><Plus size={14}/> Text</button><button onClick={()=>imageInput.current?.click()}><ImageIcon size={14}/> Image</button></div><CanvasV2/></section>
      <aside className="core-right"><div className="core-section-head"><span>LAYERS</span><b>{elements.length} layers</b></div><div className="core-layers">{elements.slice().reverse().map((el)=><div key={el.id} className={`core-layer ${el.id===state.selectedId?"active":""}`}><button onClick={()=>editorActions.updateElement(el.id,{visible:!el.visible},false)}>{el.visible?<Eye size={14}/>:<EyeOff size={14}/>}</button><button className="name" onClick={()=>editorActions.select(el.id)}>{el.kind==="image"?<ImageIcon size={14}/>:<Type size={14}/>}<span>{el.name}</span></button><button onClick={()=>editorActions.updateElement(el.id,{locked:!el.locked},false)}>{el.locked?<Lock size={14}/>:<Unlock size={14}/>}</button></div>)}</div>{selected&&<><div className="core-object-actions"><button onClick={()=>editorActions.removeSelected()}><Trash2 size={14}/> Delete layer</button></div>{selectedKey&&<section className="core-easing"><div className="core-section-head"><span>KEYFRAME</span><b>Easing</b></div><label>Interpolation<select value={selectedKey.easing??"linear"} onChange={(e)=>changeEasing(e.target.value as Easing)}><option value="linear">Linear</option><option value="ease-in">Ease in</option><option value="ease-out">Ease out</option><option value="ease-in-out">Ease in-out</option><option value="custom">Custom cubic-bezier</option></select></label>{selectedKey.easing==="custom"&&<div className="core-bezier-fields">{(selectedKey.bezier??[.42,0,.58,1]).map((v,i)=><input key={i} type="number" min="0" max="1" step="0.01" value={v} onChange={(e)=>{const next=[...(selectedKey.bezier??[.42,0,.58,1])] as Bezier;next[i]=Math.max(0,Math.min(1,Number(e.target.value)));editorActions.setSelectedKeyEasing("custom",next)}}/>)}</div>}<button className="danger" onClick={()=>editorActions.deleteSelectedKeyframe()}>Delete selected keyframe</button></section>}</>}</aside>
    </main><TimelineV2/>
  </div>;
}
