import {useState} from 'react';
import {ArrowLeft,ArrowRight,Check,Languages,LockKeyhole,ShieldCheck} from 'lucide-react';
import {api} from './api';
import type {Locale} from './i18n';

type Mode='login'|'register';

export default function AuthPage({mode:initialMode,inviteToken='',locale,onLocale,onAuthenticated,onBack}:{mode:Mode;inviteToken?:string;locale:Locale;onLocale:(l:Locale)=>void;onAuthenticated:()=>void;onBack:()=>void}){
 const ru=locale==='ru';const invited=Boolean(inviteToken);
 const [mode,setMode]=useState<Mode>(invited?'register':initialMode),[name,setName]=useState(''),[email,setEmail]=useState(''),[password,setPassword]=useState(''),[busy,setBusy]=useState(false),[error,setError]=useState('');
 const submit=async()=>{if(busy)return;setBusy(true);setError('');try{if(invited)await api.acceptInvitation({token:inviteToken,password,name});else if(mode==='login')await api.login({email,password});else await api.register({email,password,name});onAuthenticated()}catch(e){setError(e instanceof Error?e.message:String(e))}finally{setBusy(false)}};
 const valid=invited?password.length>=8&&name.trim().length>=2:email.includes('@')&&password.length>=8&&(mode==='login'||name.trim().length>=2);
 return <main className="ne-auth"><header className="ne-auth-nav"><button className="ne-public-brand" onClick={onBack}><i>B</i><b>Bannermatic</b></button><div className="ne-public-actions"><button className="ne-public-button" onClick={onBack}><ArrowLeft size={13}/>{ru?'На главную':'Back'}</button><div className="ne-public-locale"><Languages size={12}/><button className={locale==='en'?'on':''} onClick={()=>onLocale('en')}>EN</button><button className={locale==='ru'?'on':''} onClick={()=>onLocale('ru')}>RU</button></div></div></header><section className="ne-auth-layout">
  <aside className="ne-auth-copy"><span className="ne-public-pill">CAMPAIGN COMPILER</span><h1>{invited?(ru?'Вас пригласили в рабочее пространство Bannermatic.':'You have been invited to a Bannermatic workspace.'):(ru?'От медиаплана до готовой кампании — в одном потоке.':'From media plan to a ready campaign in one connected flow.')}</h1><p>{ru?'Создайте workspace, загрузите план размещений и подключите Figma. Bannermatic соберёт структуру кампании и проведёт её до delivery.':'Create a workspace, attach a placement plan and connect Figma. Bannermatic builds the campaign structure and guides it through delivery.'}</p><div className="ne-auth-points"><span><Check size={14}/>{ru?'Один visual format для нескольких placements':'One visual format across multiple placements'}</span><span><Check size={14}/>{ru?'TT и compliance на уровне размещения':'Placement-level TT & compliance'}</span><span><Check size={14}/>{ru?'Creative остаётся редактируемым в Figma':'Creative stays editable in Figma'}</span></div></aside>
  <section className="ne-auth-card"><div className="ne-brand-mark">B</div><div className="ne-kicker" style={{marginTop:14}}>Bannermatic Cloud</div><h2>{invited?(ru?'Принять приглашение':'Join workspace'):mode==='login'?(ru?'С возвращением':'Welcome back'):(ru?'Создайте workspace':'Create your workspace')}</h2><p>{invited?(ru?'Создайте профиль — роль и workspace уже заданы приглашением.':'Create your profile — role and workspace are already defined by the invitation.'):mode==='login'?(ru?'Войдите, чтобы продолжить работу с кампаниями.':'Sign in to continue working with your campaigns.'):(ru?'Первый workspace создаётся вместе с аккаунтом.':'Your first workspace is created with your account.')}</p>{!invited&&<div className="ne-auth-tabs"><button className={mode==='login'?'on':''} onClick={()=>{setMode('login');setError('')}}>{ru?'Войти':'Sign in'}</button><button className={mode==='register'?'on':''} onClick={()=>{setMode('register');setError('')}}>{ru?'Создать аккаунт':'Create account'}</button></div>}{(invited||mode==='register')&&<label className="ne-auth-field"><span>{ru?'Имя':'Name'}</span><input value={name} onChange={e=>setName(e.target.value)} autoComplete="name" placeholder={ru?'Как к вам обращаться':'Your name'}/></label>}{!invited&&<label className="ne-auth-field"><span>{ru?'Рабочая почта':'Work email'}</span><input type="email" value={email} onChange={e=>setEmail(e.target.value)} autoComplete="email" placeholder="name@company.com"/></label>}<label className="ne-auth-field"><span>{ru?'Пароль':'Password'}</span><input type="password" value={password} onChange={e=>setPassword(e.target.value)} autoComplete={mode==='login'?'current-password':'new-password'} placeholder={ru?'Минимум 8 символов':'At least 8 characters'} onKeyDown={e=>{if(e.key==='Enter'&&valid)void submit()}}/></label>{error&&<div className="ne-auth-error" role="alert">{error}</div>}<button className="ne-public-button primary ne-auth-submit" disabled={!valid||busy} onClick={()=>void submit()}>{busy?(ru?'Подождите…':'Please wait…'):invited?(ru?'Присоединиться к workspace':'Join workspace'):mode==='login'?(ru?'Войти в Bannermatic':'Sign in to Bannermatic'):(ru?'Создать аккаунт':'Create account')}<ArrowRight size={14}/></button><div className="ne-auth-trust"><span><LockKeyhole size={12}/>{ru?'Сессия хранится на сервере':'Server-backed session'}</span><span><ShieldCheck size={12}/>{ru?'Пароль не хранится открытым':'Passwords are never stored in plaintext'}</span></div></section>
 </section></main>;
}
