import {useState} from 'react';
import {ArrowLeft,ArrowRight,Check,Languages,LockKeyhole,ShieldCheck} from 'lucide-react';
import {api} from './api';
import type {Locale} from './i18n';

type Mode='login'|'register';

export default function AuthPage({mode:initialMode,inviteToken='',locale,onLocale,onAuthenticated,onBack}:{mode:Mode;inviteToken?:string;locale:Locale;onLocale:(l:Locale)=>void;onAuthenticated:()=>void;onBack:()=>void}){
 const ru=locale==='ru';const invited=Boolean(inviteToken);
 const [mode,setMode]=useState<Mode>(invited?'register':initialMode),[name,setName]=useState(''),[email,setEmail]=useState(''),[password,setPassword]=useState(''),[busy,setBusy]=useState(false),[error,setError]=useState('');
 const submit=async()=>{if(busy)return;setBusy(true);setError('');try{if(invited)await api.acceptInvitation({token:inviteToken,password,name});else if(mode==='login')await api.login({email,password});else await api.register({email,password,name});onAuthenticated()}catch(e){setError(e instanceof Error?e.message:String(e))}finally{setBusy(false)}};
 const valid=invited?password.length>=8&&name.trim().length>=2:email.includes('@')&&password.length>=8&&(mode==='login'||name.trim().length>=2);
 return <main className="bm-auth-v2"><header className="bm-auth-nav"><button className="bm-mkt-brand" onClick={onBack}><span>B</span><b>Bannermatic</b></button><div className="bm-locale"><Languages size={14}/><button className={locale==='en'?'on':''} onClick={()=>onLocale('en')}>EN</button><button className={locale==='ru'?'on':''} onClick={()=>onLocale('ru')}>RU</button></div></header><section className="bm-auth-layout">
   <aside className="bm-auth-story"><button className="bm-auth-back" onClick={onBack}><ArrowLeft size={14}/>{ru?'На главную':'Back to product'}</button><span className="bm-kicker">CAMPAIGN COMPILER</span><h1>{invited?(ru?'Вас пригласили в рабочее пространство Bannermatic.':'You have been invited to a Bannermatic workspace.'):(ru?'От медиаплана до готовой кампании — в одном потоке.':'From media plan to a ready campaign in one connected flow.')}</h1><p>{ru?'Создайте workspace, загрузите план размещений и подключите Figma. Bannermatic соберёт структуру кампании и будет вести её до delivery.':'Create a workspace, attach a placement plan and connect Figma. Bannermatic builds the campaign structure and keeps it connected through delivery.'}</p><div className="bm-auth-points"><span><Check size={15}/>{ru?'Один visual format для нескольких placements':'One visual format across multiple placements'}</span><span><Check size={15}/>{ru?'TT и compliance на уровне размещения':'Placement-level TT & compliance'}</span><span><Check size={15}/>{ru?'Creative остаётся редактируемым в Figma':'Creative stays editable in Figma'}</span></div></aside>
   <section className="bm-auth-panel bm-surface"><div className="bm-auth-panel-head"><div className="bm-logo large">B</div><span className="bm-eyebrow">BANNERMATIC CLOUD</span><h2>{invited?(ru?'Принять приглашение':'Join workspace'):mode==='login'?(ru?'С возвращением':'Welcome back'):(ru?'Создайте workspace':'Create your workspace')}</h2><p>{invited?(ru?'Создайте профиль — роль и workspace уже заданы приглашением.':'Create your profile — your role and workspace are already defined by the invitation.'):mode==='login'?(ru?'Войдите, чтобы продолжить работу с кампаниями.':'Sign in to continue working with your campaigns.'):(ru?'Первый workspace создаётся вместе с аккаунтом.':'Your first workspace is created with your account.')}</p></div>{!invited&&<div className="bm-auth-tabs"><button className={mode==='login'?'on':''} onClick={()=>{setMode('login');setError('')}}>{ru?'Войти':'Sign in'}</button><button className={mode==='register'?'on':''} onClick={()=>{setMode('register');setError('')}}>{ru?'Создать аккаунт':'Create account'}</button></div>}{(invited||mode==='register')&&<label className="bm-field"><span>{ru?'Имя':'Name'}</span><input className="bm-input" value={name} onChange={e=>setName(e.target.value)} autoComplete="name" placeholder={ru?'Как к вам обращаться':'Your name'}/></label>}{!invited&&<label className="bm-field"><span>{ru?'Рабочая почта':'Work email'}</span><input className="bm-input" type="email" value={email} onChange={e=>setEmail(e.target.value)} autoComplete="email" placeholder="name@company.com"/></label>}<label className="bm-field"><span>{ru?'Пароль':'Password'}</span><input className="bm-input" type="password" value={password} onChange={e=>setPassword(e.target.value)} autoComplete={mode==='login'?'current-password':'new-password'} placeholder={ru?'Минимум 8 символов':'At least 8 characters'} onKeyDown={e=>{if(e.key==='Enter'&&valid)void submit()}}/></label>{error&&<div className="bm-auth-error" role="alert">{error}</div>}<button className="bm-primary bm-wide" disabled={!valid||busy} onClick={()=>void submit()}>{busy?(ru?'Подождите…':'Please wait…'):invited?(ru?'Присоединиться к workspace':'Join workspace'):mode==='login'?(ru?'Войти в Bannermatic':'Sign in to Bannermatic'):(ru?'Создать аккаунт':'Create account')}<ArrowRight size={16}/></button><div className="bm-auth-trust"><span><LockKeyhole size={13}/>{ru?'Сессия хранится на сервере':'Server-backed session'}</span><span><ShieldCheck size={13}/>{ru?'Пароль не хранится открытым':'Passwords are never stored in plaintext'}</span></div></section>
  </section></main>;
}
