import {useEffect,useMemo,useState} from 'react';
import {ArrowRight,ChevronDown,CircleAlert,FileSpreadsheet,Grid2X2,Languages,LayoutDashboard,LogOut,Plus,Settings,ShieldCheck,Users2,WandSparkles} from 'lucide-react';
import {api,type SessionPayload,type WorkspaceInvitation} from './api';
import {campaignReadiness,can,type AccessRole,type Campaign} from './domain';
import {t,type Locale} from './i18n';
import MediaPlanWorkspace from './MediaPlanWorkspace';
import CampaignWall from './CampaignWall';
import DeliveryWorkspace from './DeliveryWorkspace';
import FigmaConnectPanel from './FigmaConnectPanel';

type Screen='campaigns'|'overview'|'media'|'creative'|'delivery'|'settings';
type Member={id:string;role:AccessRole;user:{id:string;email:string;name:string}|null};
const EMPTY:Campaign={id:'',name:'Untitled',status:'draft',placements:[],formats:[],locale:'en'};
const CREATIVE_REFRESH_MS=4000;

export default function BannermaticProduct(){
 const [session,setSession]=useState<SessionPayload|null>(null),[locale,setLocale]=useState<Locale>(()=>(localStorage.getItem('bannermatic:locale') as Locale)||'en'),[screen,setScreen]=useState<Screen>('campaigns'),[campaigns,setCampaigns]=useState<Campaign[]>([]),[campaign,setCampaign]=useState<Campaign>(EMPTY),[newName,setNewName]=useState(''),[members,setMembers]=useState<Member[]>([]),[invitations,setInvitations]=useState<WorkspaceInvitation[]>([]),[inviteEmail,setInviteEmail]=useState(''),[inviteRole,setInviteRole]=useState<AccessRole>('designer'),[inviteLink,setInviteLink]=useState(''),[loading,setLoading]=useState(true),[error,setError]=useState('');
 const role=(session?.role||'viewer') as AccessRole;const readiness=useMemo(()=>campaignReadiness(campaign),[campaign]);const ru=locale==='ru';
 const setLang=(value:Locale)=>{localStorage.setItem('bannermatic:locale',value);setLocale(value)};
 const applyCampaign=(next:Campaign)=>{setCampaign(next);setCampaigns(list=>list.some(c=>c.id===next.id)?list.map(c=>c.id===next.id?next:c):[next,...list])};
 const refreshCampaigns=async()=>{const data=await api.campaigns();setCampaigns(data.items);if(campaign.id){const current=data.items.find(c=>c.id===campaign.id);if(current)setCampaign(current)}else if(data.items[0])setCampaign(data.items[0])};
 const refreshCurrentCampaign=async()=>{if(!campaign.id)return;try{applyCampaign(await api.campaign(campaign.id))}catch(e){setError(e instanceof Error?e.message:String(e))}};
 const refreshAccess=async()=>{try{const m=await api.members();setMembers(m.items);if(can(role,'manage-access')){const i=await api.invitations();setInvitations(i.items)}}catch(e){setError(e instanceof Error?e.message:String(e))}};
 useEffect(()=>{(async()=>{try{const s=await api.me();setSession(s);await refreshCampaigns()}catch{location.href='?auth=login'}finally{setLoading(false)}})()},[]);
 useEffect(()=>{if(screen==='settings'&&session)void refreshAccess()},[screen,session?.workspace.id,role]);
 useEffect(()=>{if(screen!=='creative'||!campaign.id)return;void refreshCurrentCampaign();const timer=window.setInterval(()=>void refreshCurrentCampaign(),CREATIVE_REFRESH_MS);const onFocus=()=>void refreshCurrentCampaign();window.addEventListener('focus',onFocus);return()=>{window.clearInterval(timer);window.removeEventListener('focus',onFocus)}},[screen,campaign.id]);
 const createCampaign=async()=>{if(!newName.trim()||!can(role,'edit-campaign'))return;setLoading(true);setError('');try{const next=await api.createCampaign(newName.trim(),locale);applyCampaign(next);setNewName('');setScreen('overview')}catch(e){setError(e instanceof Error?e.message:String(e))}finally{setLoading(false)}};
 const chooseCampaign=(next:Campaign)=>{setCampaign(next);setScreen('overview');setError('')};
 const openFigma=()=>{if(!campaign.id||!can(role,'edit-creative'))return;location.href=`?view=editor&campaign=${encodeURIComponent(campaign.id)}`};
 const logout=async()=>{await api.logout();location.href='/'};
 const updateRole=async(id:string,next:AccessRole)=>{setError('');try{await api.setRole(id,next);await refreshAccess()}catch(e){setError(e instanceof Error?e.message:String(e))}};
 const invite=async()=>{if(!inviteEmail.includes('@')||!can(role,'manage-access'))return;setError('');setInviteLink('');try{const created=await api.invite(inviteEmail,inviteRole);setInviteEmail('');setInviteLink(`${location.origin}/?invite=${encodeURIComponent(created.token||'')}`);await refreshAccess()}catch(e){setError(e instanceof Error?e.message:String(e))}};
 if(loading&&!session)return <main className="bm-auth"><section className="bm-auth-card"><div className="bm-logo large">B</div><span className="bm-eyebrow">BANNERMATIC CLOUD</span><h2>{ru?'Загружаем workspace…':'Loading workspace…'}</h2><div className="bm-skeleton-line"/><div className="bm-skeleton-line short"/></section></main>;
 if(!session)return null;
 return <div className="bm-app bm-app-v2">
  <aside className="bm-sidebar"><button className="bm-brand bm-brand-button" onClick={()=>setScreen('campaigns')}><div className="bm-logo">B</div><div><b>Bannermatic</b><span>Campaign Compiler</span></div></button><div className="bm-workspace"><span>{t(locale,'workspace')}</span><button onClick={()=>setScreen('settings')}><i>{session.workspace.name.slice(0,2).toUpperCase()}</i><b>{session.workspace.name}</b><ChevronDown size={14}/></button></div><nav className="bm-nav"><button onClick={()=>setScreen('campaigns')} className={screen==='campaigns'?'active':''}><Grid2X2 size={17}/>{t(locale,'campaigns')}</button><span>CAMPAIGN</span><button onClick={()=>setScreen('overview')} className={screen==='overview'?'active':''} disabled={!campaign.id}><LayoutDashboard size={17}/>{t(locale,'overview')}</button><button onClick={()=>setScreen('media')} className={screen==='media'?'active':''} disabled={!campaign.id}><FileSpreadsheet size={17}/>{t(locale,'media')}</button><button onClick={()=>setScreen('creative')} className={screen==='creative'?'active':''} disabled={!campaign.id}><WandSparkles size={17}/>Creative</button><button onClick={()=>setScreen('delivery')} className={screen==='delivery'?'active':''} disabled={!campaign.id}><ShieldCheck size={17}/>{t(locale,'delivery')}</button></nav><div className="bm-sidebar-foot"><button onClick={()=>setScreen('settings')} className={screen==='settings'?'active':''}><Settings size={16}/>{ru?'Настройки':'Settings'}</button><button onClick={()=>void logout()}><LogOut size={16}/>{ru?'Выйти':'Sign out'}</button></div></aside>
  <main className="bm-main"><header className="bm-topbar"><div><span className="bm-eyebrow">{campaign.id&&screen!=='campaigns'?'CAMPAIGN':'WORKSPACE'}</span><h2>{campaign.id&&screen!=='campaigns'?campaign.name:session.workspace.name}</h2></div><div className="bm-top-actions"><div className="bm-locale"><Languages size={15}/><button className={locale==='en'?'on':''} onClick={()=>setLang('en')}>EN</button><button className={locale==='ru'?'on':''} onClick={()=>setLang('ru')}>RU</button></div><span className="bm-role"><Users2 size={15}/>{role}</span>{campaign.id&&screen!=='campaigns'&&<button className="bm-secondary" onClick={openFigma} disabled={!can(role,'edit-creative')}>{t(locale,'openFigma')}</button>}</div></header>
  {error&&<div className="bm-global-feedback bm-error"><CircleAlert size={16}/><span>{error}</span><button onClick={()=>setError('')}>×</button></div>}
  {screen==='campaigns'&&<section className="bm-page"><div className="bm-page-head"><div><span className="bm-eyebrow">WORKSPACE</span><h1>{t(locale,'campaigns')}</h1><p>{ru?'Один объект кампании связывает медиаплан, creative, TT, compliance и delivery.':'One campaign object connects media plan, creative, TT, compliance and delivery.'}</p></div>{can(role,'edit-campaign')&&<div className="bm-create-inline"><input className="bm-input" value={newName} onChange={e=>setNewName(e.target.value)} placeholder={ru?'Название кампании':'Campaign name'} onKeyDown={e=>{if(e.key==='Enter')void createCampaign()}}/><button className="bm-primary" disabled={loading||!newName.trim()} onClick={()=>void createCampaign()}><Plus size={15}/>{t(locale,'newCampaign')}</button></div>}</div><div className="bm-campaign-grid">{campaigns.map(c=><button key={c.id} className="bm-campaign-card" onClick={()=>chooseCampaign(c)}><span>{c.status}</span><h3>{c.name}</h3><p>{c.placements.length} placements · {c.formats.length} unique creatives</p><div><b>{ru?'Открыть кампанию':'Open campaign'}</b><ArrowRight size={15}/></div></button>)}</div>{!campaigns.length&&<div className="bm-empty"><Grid2X2 size={30}/><h3>{ru?'Создайте первую кампанию':'Create your first campaign'}</h3><p>{ru?'После создания загрузите медиаплан — Campaign Compiler соберёт production plan.':'Then attach a media plan — Campaign Compiler will build the production plan.'}</p></div>}</section>}
  {screen==='overview'&&campaign.id&&<section className="bm-page"><div className="bm-page-head"><div><span className="bm-eyebrow">CAMPAIGN OVERVIEW</span><h1>{campaign.name}</h1><p>{ru?'От медиаплана до delivery — одно актуальное состояние кампании.':'One current campaign state from media plan to delivery.'}</p></div></div><div className="bm-metrics"><article><span>{readiness.total}</span><p>{t(locale,'placements')}</p></article><article><span>{campaign.formats.length}</span><p>{t(locale,'unique')}</p></article><article><span>{readiness.ready}/{readiness.total}</span><p>{t(locale,'ready')}</p></article><article className={readiness.unknown?'warn':''}><span>{readiness.unknown}</span><p>{t(locale,'unknown')}</p></article></div><div className="bm-overview-grid"><article className="bm-surface bm-next-card"><span className="bm-eyebrow">NEXT STEP</span><h3>{!campaign.placements.length?(ru?'Скомпилируйте медиаплан':'Compile the media plan'):campaign.formats.some(f=>f.creativeState==='missing')?(ru?'Создайте creative в Figma':'Create creative in Figma'):(ru?'Проверьте delivery':'Review delivery')}</h3><p>{!campaign.placements.length?(ru?'Bannermatic определит placements и уникальные creative formats.':'Bannermatic will resolve placements and unique creative formats.'):`${campaign.placements.length} placements → ${campaign.formats.length} unique creatives`}</p><button className="bm-primary" onClick={()=>campaign.placements.length?setScreen('creative'):setScreen('media')}>{campaign.placements.length?(ru?'Перейти к Creative':'Open Creative'):(ru?'Открыть Campaign Compiler':'Open Campaign Compiler')}<ArrowRight size={15}/></button></article><article className="bm-surface bm-compiler-summary"><span className="bm-eyebrow">CAMPAIGN COMPILER</span><div><b>{campaign.placements.length}</b><span>placements</span><ArrowRight/><b>{campaign.formats.length}</b><span>unique creatives</span></div><p>{ru?'Одинаковые размеры используют один visual creative и сохраняют разные delivery contexts.':'Equal sizes share one visual creative while preserving independent delivery contexts.'}</p></article></div></section>}
  {screen==='media'&&campaign.id&&<MediaPlanWorkspace campaign={campaign} locale={locale} canEdit={can(role,'edit-campaign')} onUpdated={applyCampaign} onError={setError}/>}
  {screen==='creative'&&campaign.id&&<section className="bm-page"><div className="bm-page-head"><div><span className="bm-eyebrow">CAMPAIGN WALL</span><h1>{ru?'Creative кампании':'Campaign Creative'}</h1><p>{ru?'Все уникальные форматы, placements и синхронный playback на одном экране.':'All unique formats, placements and synchronized playback on one screen.'}</p></div></div><FigmaConnectPanel campaign={campaign} locale={locale} enabled={can(role,'edit-creative')} onError={setError}/>{campaign.formats.length?<CampaignWall campaign={campaign} locale={locale} onOpenFigma={openFigma}/>:<div className="bm-empty"><WandSparkles size={30}/><h3>{ru?'Сначала скомпилируйте кампанию':'Compile the campaign first'}</h3><p>{ru?'Required creative set появится после медиаплана.':'The required creative set appears after the media plan.'}</p><button className="bm-primary" onClick={()=>setScreen('media')}>{ru?'Открыть медиаплан':'Open Media Plan'}</button></div>}</section>}
  {screen==='delivery'&&campaign.id&&<DeliveryWorkspace campaign={campaign} locale={locale} canDeliver={can(role,'deliver')} onOpenFigma={openFigma} onError={setError}/>}
  {screen==='settings'&&<section className="bm-page"><div className="bm-page-head"><div><span className="bm-eyebrow">WORKSPACE</span><h1>{ru?'Настройки':'Settings'}</h1><p>{session.workspace.name} · {session.user.email}</p></div></div><div className="bm-settings-grid"><article className="bm-surface bm-settings-card"><span className="bm-eyebrow">ACCOUNT</span><h3>{session.user.name}</h3><p>{session.user.email}</p><div className="bm-role-row"><span>{ru?'Ваша роль':'Your role'}</span><b>{role}</b></div></article><article className="bm-surface bm-settings-card members"><span className="bm-eyebrow">MEMBERS</span><h3>{ru?'Доступ к workspace':'Workspace access'}</h3>{can(role,'manage-access')&&<div className="bm-invite-row"><input className="bm-input" type="email" value={inviteEmail} onChange={e=>setInviteEmail(e.target.value)} placeholder="designer@company.com"/><select className="bm-select" value={inviteRole} onChange={e=>setInviteRole(e.target.value as AccessRole)}>{['admin','designer','producer','viewer'].map(r=><option key={r} value={r}>{r}</option>)}</select><button className="bm-primary" disabled={!inviteEmail.includes('@')} onClick={()=>void invite()}>{ru?'Пригласить':'Invite'}</button></div>}{inviteLink&&<div className="bm-notice"><span>{ru?'Ссылка приглашения:':'Invitation link:'}</span><input className="bm-input" readOnly value={inviteLink} onFocus={e=>e.currentTarget.select()}/></div>}{invitations.map(i=><div className="bm-member-row pending" key={i.id}><span><b>{i.email}</b><small>{ru?'Ожидает принятия':'Pending invitation'}</small></span><em>{i.role}</em></div>)}{members.map(m=><div className="bm-member-row" key={m.id}><span><b>{m.user?.name||'Member'}</b><small>{m.user?.email||''}</small></span>{can(role,'manage-access')?<select className="bm-select" value={m.role} onChange={e=>void updateRole(m.id,e.target.value as AccessRole)}>{['owner','admin','designer','producer','viewer'].map(r=><option key={r} value={r}>{r}</option>)}</select>:<em>{m.role}</em>}</div>)}</article></div></section>}
  </main>
 </div>;
}
