import {useEffect,useMemo,useRef,useState} from 'react';
import {ArrowRight,CheckCircle2,ChevronDown,CircleAlert,FileSpreadsheet,Grid2X2,Languages,LayoutDashboard,Link2,LogOut,Pause,Play,Plus,RefreshCcw,Settings,ShieldCheck,Upload,Users2,WandSparkles} from 'lucide-react';
import {processDeliveryInput} from '../campaign/deliveryPlan';
import {api,type SessionPayload} from './api';
import {campaignReadiness,can,compileVisualFormats,type AccessRole,type Campaign,type Placement,type VisualFormat} from './domain';
import {t,type Locale} from './i18n';

type Screen='campaigns'|'overview'|'media'|'creative'|'delivery'|'settings';
type WallMode='creative'|'delivery';
type Member={id:string;role:AccessRole;user:{id:string;email:string;name:string}|null};
const EMPTY:Campaign={id:'',name:'Untitled',status:'draft',placements:[],formats:[],locale:'en'};
const statusClass=(v:string)=>`bm-status bm-${v}`;
const hasTT=(p:Placement)=>Boolean(p.requirements.sourceUrl||p.requirements.sourceLabel&&!p.requirements.sourceLabel.startsWith('Unknown'));

function Preview({format,playing,onOpen}:{format:VisualFormat;playing:boolean;onOpen:()=>void}){
 return <button className={`bm-preview ${playing?'playing':''}`} style={{aspectRatio:`${format.width}/${format.height}`}} onClick={onOpen}><i/><div className="bm-preview-copy"><strong>BANNERMATIC</strong><b>One campaign.<br/>Every placement.</b><span>Compile → adapt → deliver</span></div></button>;
}

export default function BannermaticCloud(){
 const [session,setSession]=useState<SessionPayload|null>(null),[locale,setLocale]=useState<Locale>(()=>(localStorage.getItem('bannermatic:locale') as Locale)||'en'),[screen,setScreen]=useState<Screen>('campaigns'),[campaigns,setCampaigns]=useState<Campaign[]>([]),[campaign,setCampaign]=useState<Campaign>(EMPTY),[newName,setNewName]=useState(''),[loading,setLoading]=useState(true),[message,setMessage]=useState(''),[error,setError]=useState(''),[wallMode,setWallMode]=useState<WallMode>('creative'),[playing,setPlaying]=useState(false),[playKey,setPlayKey]=useState(0),[members,setMembers]=useState<Member[]>([]);
 const mediaInput=useRef<HTMLInputElement>(null);
 const role=(session?.role||'viewer') as AccessRole;
 const readiness=useMemo(()=>campaignReadiness(campaign),[campaign]);
 const setLang=(value:Locale)=>{localStorage.setItem('bannermatic:locale',value);setLocale(value)};
 const placementFor=(id:string)=>campaign.placements.find(p=>p.id===id);
 const refreshCampaigns=async()=>{const data=await api.campaigns();setCampaigns(data.items);if(campaign.id){const same=data.items.find(c=>c.id===campaign.id);if(same)setCampaign(same)}else if(data.items[0])setCampaign(data.items[0]);};
 useEffect(()=>{(async()=>{try{const s=await api.me();setSession(s);await refreshCampaigns()}catch{location.href='?auth=login'}finally{setLoading(false)}})()},[]);
 useEffect(()=>{if(screen!=='settings'||!session)return;api.members().then(d=>setMembers(d.items)).catch(e=>setError(e instanceof Error?e.message:String(e)))},[screen,session?.workspace.id]);
 const chooseCampaign=(c:Campaign)=>{setCampaign(c);setScreen('overview');setMessage('');setError('')};
 const createCampaign=async()=>{if(!newName.trim()||!can(role,'edit-campaign'))return;setLoading(true);setError('');try{const c=await api.createCampaign(newName.trim(),locale);setCampaigns(list=>[c,...list]);setCampaign(c);setNewName('');setScreen('overview')}catch(e){setError(e instanceof Error?e.message:String(e))}finally{setLoading(false)}};
 const saveCampaign=async(patch:Partial<Campaign>)=>{const next=await api.updateCampaign(campaign.id,patch);setCampaign(next);setCampaigns(list=>list.map(c=>c.id===next.id?next:c));return next};
 const importPlan=async(files:FileList|null)=>{if(!files?.length||!can(role,'edit-campaign'))return;setLoading(true);setError('');setMessage('');try{const plan=await processDeliveryInput(Array.from(files));const placements:Placement[]=plan.placements.map(p=>({id:p.id,platform:p.platform||'Unknown platform',placement:p.source||'Placement',width:p.width,height:p.height,creativeType:p.creativeType,requirements:{...p.requirements,sourceUrl:p.ttUrl,sourceLabel:p.ttUrl?'Imported TT link':'Imported media plan'}}));const formats=compileVisualFormats(placements,campaign.formats);await saveCampaign({placements,formats,status:'media-ready'});setMessage(`${placements.length} placements → ${formats.length} unique creatives${plan.needsAi?` · ${plan.needsAi} source(s) need TT review`:''}`);setScreen('overview')}catch(e){setError(e instanceof Error?e.message:String(e))}finally{setLoading(false);if(mediaInput.current)mediaInput.current.value=''}};
 const openCreative=()=>{if(!campaign.id||!can(role,'edit-creative'))return;location.href=`?view=editor&campaign=${encodeURIComponent(campaign.id)}`};
 const logout=async()=>{await api.logout();location.href='/'};
 const updateRole=async(id:string,next:AccessRole)=>{setError('');try{await api.setRole(id,next);const data=await api.members();setMembers(data.items)}catch(e){setError(e instanceof Error?e.message:String(e))}};
 if(loading&&!session)return <main className="bm-auth"><section className="bm-auth-card"><div className="bm-logo large">B</div><span className="bm-eyebrow">BANNERMATIC CLOUD</span><h2>Loading workspace…</h2><div className="bm-skeleton-line"/><div className="bm-skeleton-line short"/></section></main>;
 if(!session)return null;
 return <div className="bm-app bm-app-v2">
  <aside className="bm-sidebar"><button className="bm-brand bm-brand-button" onClick={()=>setScreen('campaigns')}><div className="bm-logo">B</div><div><b>Bannermatic</b><span>Campaign Compiler</span></div></button><div className="bm-workspace"><span>{t(locale,'workspace')}</span><button onClick={()=>setScreen('settings')}><i>{session.workspace.name.slice(0,2).toUpperCase()}</i><b>{session.workspace.name}</b><ChevronDown size={14}/></button></div><nav className="bm-nav"><button onClick={()=>setScreen('campaigns')} className={screen==='campaigns'?'active':''}><Grid2X2 size={17}/>{t(locale,'campaigns')}</button><span>CAMPAIGN</span><button onClick={()=>setScreen('overview')} className={screen==='overview'?'active':''} disabled={!campaign.id}><LayoutDashboard size={17}/>{t(locale,'overview')}</button><button onClick={()=>setScreen('media')} className={screen==='media'?'active':''} disabled={!campaign.id}><FileSpreadsheet size={17}/>{t(locale,'media')}</button><button onClick={()=>setScreen('creative')} className={screen==='creative'?'active':''} disabled={!campaign.id}><WandSparkles size={17}/>Creative</button><button onClick={()=>setScreen('delivery')} className={screen==='delivery'?'active':''} disabled={!campaign.id}><ShieldCheck size={17}/>{t(locale,'delivery')}</button></nav><div className="bm-sidebar-foot"><button onClick={()=>setScreen('settings')} className={screen==='settings'?'active':''}><Settings size={16}/>{locale==='ru'?'Настройки':'Settings'}</button><button onClick={()=>void logout()}><LogOut size={16}/>{locale==='ru'?'Выйти':'Sign out'}</button></div></aside>
  <main className="bm-main"><header className="bm-topbar"><div><span className="bm-eyebrow">{campaign.id&&screen!=='campaigns'?'CAMPAIGN':'WORKSPACE'}</span><h2>{campaign.id&&screen!=='campaigns'?campaign.name:session.workspace.name}</h2></div><div className="bm-top-actions"><div className="bm-locale"><Languages size={15}/><button className={locale==='en'?'on':''} onClick={()=>setLang('en')}>EN</button><button className={locale==='ru'?'on':''} onClick={()=>setLang('ru')}>RU</button></div><span className="bm-role"><Users2 size={15}/>{role}</span>{campaign.id&&screen!=='campaigns'&&<button className="bm-secondary" onClick={openCreative} disabled={!can(role,'edit-creative')}>{t(locale,'openFigma')}</button>}</div></header>
   {error&&<div className="bm-global-feedback bm-error"><CircleAlert size={16}/><span>{error}</span><button onClick={()=>setError('')}>×</button></div>}
   {screen==='campaigns'&&<section className="bm-page"><div className="bm-page-head"><div><span className="bm-eyebrow">WORKSPACE</span><h1>{t(locale,'campaigns')}</h1><p>{locale==='ru'?'Кампания объединяет медиаплан, placements, creative, TT и delivery в одном объекте.':'Campaign is the primary production object: media plan, placements, creative, TT and delivery stay connected.'}</p></div>{can(role,'edit-campaign')&&<div className="bm-create-inline"><input className="bm-input" value={newName} onChange={e=>setNewName(e.target.value)} placeholder={locale==='ru'?'Название кампании':'Campaign name'} onKeyDown={e=>{if(e.key==='Enter')void createCampaign()}}/><button className="bm-primary" disabled={loading||!newName.trim()} onClick={()=>void createCampaign()}><Plus size={15}/>{t(locale,'newCampaign')}</button></div>}</div><div className="bm-campaign-grid">{campaigns.map(c=><button key={c.id} className="bm-campaign-card" onClick={()=>chooseCampaign(c)}><span>{c.status}</span><h3>{c.name}</h3><p>{c.placements.length} placements · {c.formats.length} unique creatives</p><div><b>{locale==='ru'?'Открыть кампанию':'Open campaign'}</b><ArrowRight size={15}/></div></button>)}</div>{!campaigns.length&&<div className="bm-empty"><Grid2X2 size={30}/><h3>{locale==='ru'?'Создайте первую кампанию':'Create your first campaign'}</h3><p>{locale==='ru'?'Затем загрузите медиаплан — Campaign Compiler определит placements и необходимый набор уникальных форматов.':'Then attach a media plan — Campaign Compiler will determine placements and the required unique creative set.'}</p></div>}</section>}
   {screen==='overview'&&campaign.id&&<section className="bm-page"><div className="bm-page-head"><div><span className="bm-eyebrow">CAMPAIGN OVERVIEW</span><h1>{campaign.name}</h1><p>{locale==='ru'?'Состояние кампании от медиаплана до delivery.':'Campaign state from media plan through delivery.'}</p></div><button className="bm-primary" onClick={()=>mediaInput.current?.click()} disabled={!can(role,'edit-campaign')||loading}><Upload size={15}/>{locale==='ru'?'Загрузить медиаплан':'Attach media plan'}</button><input ref={mediaInput} hidden type="file" multiple accept=".xlsx,.csv,.tsv,.txt,.docx,.pdf" onChange={e=>void importPlan(e.target.files)}/></div>{message&&<div className="bm-notice"><CheckCircle2 size={16}/><span>{message}</span></div>}<div className="bm-metrics"><article><span>{readiness.total}</span><p>{t(locale,'placements')}</p></article><article><span>{campaign.formats.length}</span><p>{t(locale,'unique')}</p></article><article><span>{readiness.ready}/{readiness.total}</span><p>{t(locale,'ready')}</p></article><article className={readiness.unknown?'warn':''}><span>{readiness.unknown}</span><p>{t(locale,'unknown')}</p></article></div><div className="bm-overview-grid"><article className="bm-surface bm-next-card"><span className="bm-eyebrow">NEXT STEP</span><h3>{campaign.placements.length?campaign.formats.some(f=>f.creativeState==='missing')?(locale==='ru'?'Создайте creative в Figma':'Create creative in Figma'):(locale==='ru'?'Проверьте delivery':'Review delivery'):(locale==='ru'?'Добавьте медиаплан':'Attach a media plan')}</h3><p>{campaign.placements.length?`${campaign.formats.length} unique creative format${campaign.formats.length===1?'':'s'} required.`:(locale==='ru'?'Campaign Compiler построит production plan и сохранит все placements.':'Campaign Compiler will build the production plan while preserving every placement.')}</p><button className="bm-primary" onClick={campaign.placements.length?openCreative:()=>mediaInput.current?.click()}>{campaign.placements.length?t(locale,'openFigma'):(locale==='ru'?'Загрузить план':'Attach plan')}<ArrowRight size={15}/></button></article><article className="bm-surface bm-compiler-summary"><span className="bm-eyebrow">CAMPAIGN COMPILER</span><div><b>{campaign.placements.length}</b><span>placements</span><ArrowRight/><b>{campaign.formats.length}</b><span>unique creatives</span></div><p>{locale==='ru'?'Одинаковые размеры объединяются в один visual creative, но сохраняют независимые TT и delivery contexts.':'Equal sizes share one visual creative while keeping independent TT and delivery contexts.'}</p></article></div></section>}
   {screen==='media'&&campaign.id&&<section className="bm-page"><div className="bm-page-head"><div><span className="bm-eyebrow">CAMPAIGN COMPILER</span><h1>{t(locale,'media')}</h1><p>{locale==='ru'?'Импорт и ручное редактирование должны вести в одну placement-модель.':'Import and manual changes feed one placement model.'}</p></div><button className="bm-primary" onClick={()=>mediaInput.current?.click()} disabled={!can(role,'edit-campaign')}><Upload size={15}/>{locale==='ru'?'Обновить медиаплан':'Update media plan'}</button></div>{campaign.placements.length?<div className="bm-table"><div className="bm-table-head"><span>Platform</span><span>Placement</span><span>Format</span><span>TT source</span><span>Creative</span></div>{campaign.placements.map(p=>{const f=campaign.formats.find(x=>x.placementIds.includes(p.id));return <div className="bm-table-row" key={p.id}><b>{p.platform}</b><span>{p.placement}</span><span>{p.width}×{p.height}</span><span>{p.requirements.sourceLabel||'Unknown'}</span><em className={statusClass(f?.creativeState==='published'?'ready':f?.creativeState==='draft'?'warning':'blocked')}>{f?.creativeState||'missing'}</em></div>})}</div>:<div className="bm-empty"><FileSpreadsheet size={28}/><h3>{locale==='ru'?'Медиаплан ещё не загружен':'No media plan yet'}</h3><p>{locale==='ru'?'Загрузите Excel/CSV, чтобы построить placements и required creative set.':'Attach Excel/CSV to build placements and the required creative set.'}</p><button className="bm-primary" onClick={()=>mediaInput.current?.click()}>{locale==='ru'?'Выбрать файл':'Choose file'}</button></div>}</section>}
   {screen==='creative'&&campaign.id&&<section className="bm-page"><div className="bm-page-head"><div><span className="bm-eyebrow">CAMPAIGN WALL</span><h1>Creative</h1><p>{locale==='ru'?'Все уникальные форматы кампании на одном экране. Live HTML preview подключается через Publish Creative из Figma.':'All unique campaign creatives on one screen. Live HTML preview is connected through Publish Creative from Figma.'}</p></div><button className="bm-primary" onClick={openCreative} disabled={!can(role,'edit-creative')}>{t(locale,'openFigma')}<ArrowRight size={15}/></button></div><div className="bm-wall-toolbar"><div className="bm-segment"><button className={wallMode==='creative'?'active':''} onClick={()=>setWallMode('creative')}>{t(locale,'creativeView')}</button><button className={wallMode==='delivery'?'active':''} onClick={()=>setWallMode('delivery')}>{t(locale,'deliveryView')}</button></div><div className="bm-play-controls"><button onClick={()=>setPlaying(v=>!v)}>{playing?<Pause size={14}/>:<Play size={14}/>} {playing?t(locale,'pauseAll'):t(locale,'playAll')}</button><button onClick={()=>{setPlayKey(v=>v+1);setPlaying(true)}}><RefreshCcw size={14}/>{t(locale,'replay')}</button></div></div>{campaign.formats.length?<div className="bm-wall">{campaign.formats.map(f=>{const ps=f.placementIds.map(placementFor).filter(Boolean) as Placement[];return <article className="bm-creative-card" key={`${f.id}-${playKey}`}><div className="bm-card-head"><div><b>{f.size}</b><span>{ps.length} placement{ps.length===1?'':'s'}</span></div><span className={statusClass(f.creativeState==='published'?'ready':f.creativeState==='draft'?'warning':'blocked')}>{f.creativeState}</span></div><Preview format={f} playing={playing} onOpen={openCreative}/><div className="bm-card-meta">{wallMode==='creative'?<><div><span>Creative version</span><b>v{f.creativeVersion}</b></div><div><span>Preview</span><b>{f.previewUrl?'Live':'Development placeholder'}</b></div></>:<div className="bm-placement-list">{ps.map(p=><div key={p.id}><span><b>{p.platform}</b><small>{p.placement}</small></span><em className={statusClass(hasTT(p)?'ready':'unknown')}>{hasTT(p)?'TT ✓':'TT ?'}</em></div>)}</div>}</div></article>})}</div>:<div className="bm-empty"><WandSparkles size={28}/><h3>{locale==='ru'?'Сначала скомпилируйте кампанию':'Compile the campaign first'}</h3><p>{locale==='ru'?'Набор creative formats появится после медиаплана.':'The creative set appears after a media plan is attached.'}</p></div>}</section>}
   {screen==='delivery'&&campaign.id&&<section className="bm-page"><div className="bm-page-head"><div><span className="bm-eyebrow">TT & DELIVERY</span><h1>{t(locale,'delivery')}</h1><p>{locale==='ru'?'Readiness считается отдельно для каждого placement. Unknown остаётся Unknown.':'Readiness is evaluated per placement. Unknown remains Unknown.'}</p></div></div><div className="bm-compliance-list">{campaign.placements.map(p=>{const f=campaign.formats.find(x=>x.placementIds.includes(p.id));const ready=Boolean(f&&f.creativeState!=='missing'&&hasTT(p));return <article key={p.id}><div><b>{p.platform}</b><span>{p.placement}</span></div><div><span>Format</span><b>{p.width}×{p.height}</b></div><div><span>TT</span><b>{p.requirements.sourceLabel||'Unknown'}</b></div><div><span>Creative</span><b>{f?.creativeState||'missing'}</b></div><em className={statusClass(ready?'ready':hasTT(p)?'blocked':'unknown')}>{ready?'Ready':hasTT(p)?'Creative needed':'TT unknown'}</em></article>})}</div>{!campaign.placements.length&&<div className="bm-empty"><ShieldCheck size={28}/><h3>{locale==='ru'?'Нет placements для проверки':'Nothing to validate yet'}</h3><p>{locale==='ru'?'Добавьте медиаплан, затем система сможет рассчитывать delivery readiness.':'Attach a media plan before delivery readiness can be calculated.'}</p></div>}</section>}
   {screen==='settings'&&<section className="bm-page"><div className="bm-page-head"><div><span className="bm-eyebrow">WORKSPACE</span><h1>{locale==='ru'?'Настройки':'Settings'}</h1><p>{session.workspace.name} · {session.user.email}</p></div></div><div className="bm-settings-grid"><article className="bm-surface bm-settings-card"><span className="bm-eyebrow">ACCOUNT</span><h3>{session.user.name}</h3><p>{session.user.email}</p><div className="bm-role-row"><span>{locale==='ru'?'Ваша роль':'Your role'}</span><b>{role}</b></div></article><article className="bm-surface bm-settings-card members"><span className="bm-eyebrow">MEMBERS</span><h3>{locale==='ru'?'Доступ к workspace':'Workspace access'}</h3>{members.map(m=><div className="bm-member-row" key={m.id}><span><b>{m.user?.name||'Member'}</b><small>{m.user?.email||''}</small></span>{can(role,'manage-access')?<select className="bm-select" value={m.role} onChange={e=>void updateRole(m.id,e.target.value as AccessRole)}>{['owner','admin','designer','producer','viewer'].map(r=><option key={r} value={r}>{r}</option>)}</select>:<em>{m.role}</em>}</div>)}</article></div></section>}
  </main>
 </div>;
}
