import ContentWorkspace from './ContentWorkspace';
import TemplateWorkspace from './TemplateWorkspace';
import './vnext.css';
import {useEffect,useMemo,useState} from 'react';
import {ArrowRight,Check,ChevronDown,CircleAlert,FileSpreadsheet,Grid2X2,Languages,LayoutDashboard,LogOut,Pencil,Plus,RefreshCcw,Settings,ShieldCheck,Trash2,Users2,WandSparkles,X} from 'lucide-react';
import {api,type SessionPayload,type WorkspaceInvitation} from './api';
import {campaignReadiness,can,type AccessRole,type Campaign} from './domain';
import {t,type Locale} from './i18n';
import MediaPlanWorkspace from './MediaPlanWorkspace';
import CampaignWall from './CampaignWall';
import DeliveryWorkspace from './DeliveryWorkspace';

type Screen='campaigns'|'overview'|'media'|'creative'|'delivery'|'settings'|'content';
type Member={id:string;role:AccessRole;user:{id:string;email:string;name:string}|null};
const EMPTY:Campaign={id:'',name:'Untitled',status:'draft',placements:[],formats:[],locale:'en'};
const CREATIVE_REFRESH_MS=4000;

function CampaignCard({item,ru,editable,editingName,onOpen,onStartRename,onRenameChange,onSaveRename,onCancelRename,onDelete}:{item:Campaign;ru:boolean;editable:boolean;editingName:string|null;onOpen:()=>void;onStartRename:()=>void;onRenameChange:(value:string)=>void;onSaveRename:()=>void;onCancelRename:()=>void;onDelete:()=>void}){
 const editing=editingName!==null;
 return <article className="ne-campaign-card"><div className="top"><span className="ne-badge">{item.status}</span>{editable&&<div className="ne-card-actions">{editing?<><button title={ru?'Сохранить':'Save'} onClick={onSaveRename}><Check size={14}/></button><button title={ru?'Отмена':'Cancel'} onClick={onCancelRename}><X size={14}/></button></>:<><button title={ru?'Переименовать':'Rename'} onClick={onStartRename}><Pencil size={14}/></button><button className="danger" title={ru?'Удалить':'Delete'} onClick={onDelete}><Trash2 size={14}/></button></>}</div>}</div>{editing?<input className="ne-input ne-rename-input" autoFocus value={editingName} onChange={e=>onRenameChange(e.target.value)} onKeyDown={e=>{if(e.key==='Enter')onSaveRename();if(e.key==='Escape')onCancelRename()}}/>:<button className="ne-campaign-open" onClick={onOpen}><h3>{item.name}</h3><p>{item.placements.length} placements · {item.formats.length} unique creatives</p><footer><span>{ru?'Открыть кампанию':'Open campaign'}</span><ArrowRight size={14}/></footer></button>}<span className="ne-card-locale">{item.locale.toUpperCase()}</span></article>;
}

export default function BannermaticProduct(){
 const [session,setSession]=useState<SessionPayload|null>(null),[locale,setLocale]=useState<Locale>(()=>(localStorage.getItem('bannermatic:locale') as Locale)||'en'),[screen,setScreen]=useState<Screen>('campaigns'),[campaigns,setCampaigns]=useState<Campaign[]>([]),[campaign,setCampaign]=useState<Campaign>(EMPTY),[newName,setNewName]=useState(''),[editingId,setEditingId]=useState(''),[editingName,setEditingName]=useState(''),[deleteCandidate,setDeleteCandidate]=useState<Campaign|null>(null),[campaignsLoading,setCampaignsLoading]=useState(false),[members,setMembers]=useState<Member[]>([]),[invitations,setInvitations]=useState<WorkspaceInvitation[]>([]),[inviteEmail,setInviteEmail]=useState(''),[inviteRole,setInviteRole]=useState<AccessRole>('designer'),[inviteLink,setInviteLink]=useState(''),[loading,setLoading]=useState(true),[error,setError]=useState('');
 const role=(session?.role||'viewer') as AccessRole;const readiness=useMemo(()=>campaignReadiness(campaign),[campaign]);const ru=locale==='ru';
 const setLang=(value:Locale)=>{localStorage.setItem('bannermatic:locale',value);setLocale(value)};
 const applyCampaign=(next:Campaign)=>{setCampaign(next);setCampaigns(list=>list.some(c=>c.id===next.id)?list.map(c=>c.id===next.id?next:c):[next,...list])};
 const refreshCampaigns=async()=>{setCampaignsLoading(true);try{const data=await api.campaigns();setCampaigns(data.items);setCampaign(current=>data.items.find(c=>c.id===current.id)||data.items[0]||EMPTY);setError('')}catch(e){setError(ru?'Не удалось загрузить кампании. Список не был очищен — попробуйте ещё раз.':`Could not load campaigns. The current list was preserved — try again. ${e instanceof Error?e.message:String(e)}`)}finally{setCampaignsLoading(false)}};
 const refreshCurrentCampaign=async()=>{if(!campaign.id)return;try{applyCampaign(await api.campaign(campaign.id))}catch(e){setError(e instanceof Error?e.message:String(e))}};
 const refreshAccess=async()=>{try{const m=await api.members();setMembers(m.items);if(can(role,'manage-access')){const i=await api.invitations();setInvitations(i.items)}}catch(e){setError(e instanceof Error?e.message:String(e))}};
 useEffect(()=>{(async()=>{try{setSession(await api.me())}catch{location.href='?auth=login';return}try{await refreshCampaigns()}finally{setLoading(false)}})()},[]);
 useEffect(()=>{if(screen==='settings'&&session)void refreshAccess()},[screen,session?.workspace.id,role]);
 useEffect(()=>{if(screen!=='creative'||!campaign.id)return;void refreshCurrentCampaign();const timer=window.setInterval(()=>void refreshCurrentCampaign(),CREATIVE_REFRESH_MS);const onFocus=()=>void refreshCurrentCampaign();window.addEventListener('focus',onFocus);return()=>{window.clearInterval(timer);window.removeEventListener('focus',onFocus)}},[screen,campaign.id]);
 const createCampaign=async()=>{if(!newName.trim()||!can(role,'edit-campaign'))return;setLoading(true);setError('');try{const next=await api.createCampaign(newName.trim(),locale);applyCampaign(next);setNewName('');setScreen('overview')}catch(e){setError(e instanceof Error?e.message:String(e))}finally{setLoading(false)}};
 const renameCampaign=async(item:Campaign)=>{const name=editingName.trim();if(!name||name===item.name){setEditingId('');return}setError('');try{applyCampaign(await api.updateCampaign(item.id,{name}));setEditingId('')}catch(e){setError(e instanceof Error?e.message:String(e))}};
 const deleteCampaign=async()=>{if(!deleteCandidate)return;setLoading(true);setError('');try{await api.deleteCampaign(deleteCandidate.id);const remaining=campaigns.filter(item=>item.id!==deleteCandidate.id);setCampaigns(remaining);if(campaign.id===deleteCandidate.id)setCampaign(remaining[0]||EMPTY);setDeleteCandidate(null);setScreen('campaigns')}catch(e){setError(e instanceof Error?e.message:String(e))}finally{setLoading(false)}};
 const chooseCampaign=(next:Campaign)=>{setCampaign(next);setScreen('overview');setError('')};
 const openCreativeEditor=()=>{if(!campaign.id||!can(role,'edit-creative'))return;location.href=`/?view=scene-editor&campaignId=${encodeURIComponent(campaign.id)}`};
 const logout=async()=>{await api.logout();location.href='/'};
 const updateRole=async(id:string,next:AccessRole)=>{setError('');try{await api.setRole(id,next);await refreshAccess()}catch(e){setError(e instanceof Error?e.message:String(e))}};
 const invite=async()=>{if(!inviteEmail.includes('@')||!can(role,'manage-access'))return;setError('');setInviteLink('');try{const created=await api.invite(inviteEmail,inviteRole);setInviteEmail('');setInviteLink(`${location.origin}/?invite=${encodeURIComponent(created.token||'')}`);await refreshAccess()}catch(e){setError(e instanceof Error?e.message:String(e))}};
 if(loading&&!session)return <main className="ne-loading"><section className="ne-loading-card"><div className="ne-brand-mark">B</div><div className="ne-kicker">BANNERMATIC CLOUD</div><h2>{ru?'Загружаем workspace…':'Loading workspace…'}</h2><div className="ne-skeleton"/><div className="ne-skeleton short"/></section></main>;
 if(!session)return null;
 const title=screen==='campaigns'?session.workspace.name:screen==='settings'?(ru?'Настройки':'Settings'):campaign.name;
 return <div className="ne-app">
  <aside className="ne-sidebar">
   <button className="ne-brand" onClick={()=>setScreen('campaigns')}><div className="ne-brand-mark">B</div><div className="ne-brand-copy"><strong>Bannermatic</strong><span>Campaign Compiler</span></div></button>
   <div className="ne-workspace"><span className="ne-workspace-label">{t(locale,'workspace')}</span><button className="ne-workspace-button" onClick={()=>setScreen('settings')}><i>{session.workspace.name.slice(0,2).toUpperCase()}</i><b>{session.workspace.name}</b><ChevronDown size={13}/></button></div>
   <nav className="ne-nav"><button onClick={()=>setScreen('campaigns')} className={screen==='campaigns'?'active':''}><Grid2X2 size={16}/><span>{t(locale,'campaigns')}</span></button><div className="ne-nav-group"><span className="ne-nav-label">Campaign</span><button onClick={()=>setScreen('overview')} className={screen==='overview'?'active':''} disabled={!campaign.id}><LayoutDashboard size={16}/><span>{t(locale,'overview')}</span></button><button onClick={()=>setScreen('media')} className={screen==='media'?'active':''} disabled={!campaign.id}><FileSpreadsheet size={16}/><span>{t(locale,'media')}</span></button><button onClick={()=>setScreen('content')} className={screen==='content'?'active':''} disabled={!campaign.id}><FileSpreadsheet size={16}/><span>Content</span></button><button onClick={()=>setScreen('creative')} className={screen==='creative'?'active':''} disabled={!campaign.id}><WandSparkles size={16}/><span>Creative</span></button><button onClick={()=>setScreen('delivery')} className={screen==='delivery'?'active':''} disabled={!campaign.id}><ShieldCheck size={16}/><span>{t(locale,'delivery')}</span></button></div></nav>
   <div className="ne-sidebar-footer"><button onClick={()=>setScreen('settings')} className={screen==='settings'?'active':''}><Settings size={16}/><span>{ru?'Настройки':'Settings'}</span></button><button className="danger" onClick={()=>void logout()}><LogOut size={16}/><span>{ru?'Выйти':'Sign out'}</span></button></div>
  </aside>
  <main className="ne-main">
   <header className="ne-topbar"><div className="ne-breadcrumb"><span>{screen==='campaigns'?'Workspace':'Bannermatic'} /</span><b>{title}</b></div><div className="ne-actions"><div className="ne-locale"><Languages size={14}/><button className={locale==='en'?'on':''} onClick={()=>setLang('en')}>EN</button><button className={locale==='ru'?'on':''} onClick={()=>setLang('ru')}>RU</button></div><span className="ne-role"><Users2 size={14}/>{role}</span>{campaign.id&&screen!=='campaigns'&&<button className="ne-button" onClick={openCreativeEditor} disabled={!can(role,'edit-creative')}>{ru?'Открыть редактор':'Open editor'}</button>}</div></header>
   {error&&<div className="ne-error"><CircleAlert size={15}/><span>{error}</span><button onClick={()=>setError('')}>×</button></div>}
   <div className="ne-content">
    {screen==='campaigns'&&<section className="ne-page"><div className="ne-page-head"><div><div className="ne-kicker">Workspace</div><h1>{t(locale,'campaigns')}</h1><p>{ru?'Кампании объединяют медиаплан, creative, TT, compliance и delivery в одном производственном потоке.':'Campaigns connect media plan, creative, TT, compliance and delivery in one production flow.'}</p></div><div className="ne-create"><button className="ne-button" disabled={campaignsLoading} onClick={()=>void refreshCampaigns()}><RefreshCcw size={14}/>{campaignsLoading?(ru?'Обновляем…':'Refreshing…'):(ru?'Обновить':'Refresh')}</button>{can(role,'edit-campaign')&&<><input className="ne-input" value={newName} onChange={e=>setNewName(e.target.value)} placeholder={ru?'Название кампании':'Campaign name'} onKeyDown={e=>{if(e.key==='Enter')void createCampaign()}}/><button className="ne-button primary" disabled={loading||!newName.trim()} onClick={()=>void createCampaign()}><Plus size={14}/>{t(locale,'newCampaign')}</button></>}</div></div><div className="ne-campaign-grid">{campaigns.map(item=><CampaignCard key={item.id} item={item} ru={ru} editable={can(role,'edit-campaign')} editingName={editingId===item.id?editingName:null} onOpen={()=>chooseCampaign(item)} onStartRename={()=>{setEditingId(item.id);setEditingName(item.name)}} onRenameChange={setEditingName} onSaveRename={()=>void renameCampaign(item)} onCancelRename={()=>setEditingId('')} onDelete={()=>setDeleteCandidate(item)}/>)}</div>{!campaigns.length&&!campaignsLoading&&<div className="ne-empty"><div className="ne-empty-inner"><div className="ne-empty-icon"><Grid2X2 size={18}/></div><h3>{ru?'Создайте первую кампанию':'Create your first campaign'}</h3><p>{ru?'Начните с названия кампании. Следующим шагом Bannermatic проведёт через медиаплан и Campaign Compiler.':'Start with a campaign name. Bannermatic will then guide you through the media plan and Campaign Compiler.'}</p></div></div>}{deleteCandidate&&<div className="ne-dialog-backdrop" role="presentation" onMouseDown={e=>{if(e.target===e.currentTarget)setDeleteCandidate(null)}}><section className="ne-dialog" role="dialog" aria-modal="true" aria-labelledby="delete-campaign-title"><div className="ne-danger-icon"><Trash2 size={18}/></div><h2 id="delete-campaign-title">{ru?'Удалить кампанию?':'Delete campaign?'}</h2><p>{ru?`«${deleteCandidate.name}» и её связи с Figma, версии creative и сборки будут удалены без возможности восстановления.`:`“${deleteCandidate.name}” and its Figma connections, creative versions and builds will be permanently deleted.`}</p><div className="ne-dialog-actions"><button className="ne-button" onClick={()=>setDeleteCandidate(null)}>{ru?'Отмена':'Cancel'}</button><button className="ne-button danger-solid" disabled={loading} onClick={()=>void deleteCampaign()}><Trash2 size={14}/>{loading?(ru?'Удаляем…':'Deleting…'):(ru?'Удалить кампанию':'Delete campaign')}</button></div></section></div>}</section>}
    {screen==='overview'&&campaign.id&&<section className="ne-page"><div className="ne-page-head"><div><div className="ne-kicker">Campaign overview</div><h1>{campaign.name}</h1><p>{ru?'Актуальное состояние кампании — от медиаплана до delivery.':'Current campaign state from media plan through delivery.'}</p></div></div><div className="ne-stat-grid"><article className="ne-stat"><label>{t(locale,'placements')}</label><strong>{readiness.total}</strong><small>{ru?'в медиаплане':'in media plan'}</small></article><article className="ne-stat"><label>{t(locale,'unique')}</label><strong>{campaign.formats.length}</strong><small>{ru?'визуальных форматов':'visual formats'}</small></article><article className="ne-stat"><label>{t(locale,'ready')}</label><strong>{readiness.ready}/{readiness.total}</strong><small>{ru?'готово к delivery':'delivery ready'}</small></article><article className="ne-stat"><label>{t(locale,'unknown')}</label><strong>{readiness.unknown}</strong><small>{ru?'требуют уточнения TT':'need TT clarification'}</small></article></div><div className="ne-overview-grid"><article className="ne-card"><div className="ne-kicker">Next step</div><h3>{!campaign.placements.length?(ru?'Скомпилируйте медиаплан':'Compile the media plan'):campaign.formats.some(f=>f.creativeState==='missing')?(ru?'Создайте creative в редакторе':'Create creative in editor'):(ru?'Проверьте delivery':'Review delivery')}</h3><p>{!campaign.placements.length?(ru?'Bannermatic определит placements, уникальные размеры и TT readiness.':'Bannermatic will resolve placements, unique sizes and TT readiness.'):`${campaign.placements.length} placements → ${campaign.formats.length} unique creatives`}</p><div style={{marginTop:16}}><button className="ne-button primary" onClick={()=>campaign.placements.length?setScreen('creative'):setScreen('media')}>{campaign.placements.length?(ru?'Перейти к Creative':'Open Creative'):(ru?'Открыть Campaign Compiler':'Open Campaign Compiler')}<ArrowRight size={14}/></button></div></article><article className="ne-card"><div className="ne-kicker">Campaign compiler</div><div className="ne-flow"><div className="ne-flow-block"><strong>{campaign.placements.length}</strong><span>placements</span></div><ArrowRight/><div className="ne-flow-block"><strong>{campaign.formats.length}</strong><span>unique creatives</span></div></div><p>{ru?'Одинаковые размеры используют один visual creative, сохраняя разные delivery contexts.':'Equal sizes share one visual creative while keeping independent delivery contexts.'}</p></article></div></section>}
    {screen==='media'&&campaign.id&&<MediaPlanWorkspace key={campaign.id} campaign={campaign} locale={locale} canEdit={can(role,'edit-campaign')} onUpdated={applyCampaign} onError={setError} onOpenCreative={()=>setScreen('creative')}/>}
    {screen==='content'&&campaign.id&&<ContentWorkspace key={campaign.id} campaign={campaign} ru={ru} canEdit={can(role,'edit-campaign')} onUpdated={applyCampaign} onError={setError}/>}
    {screen==='creative'&&campaign.id&&<section className="ne-page"><div className="ne-page-head"><div><div className="ne-kicker">Campaign wall</div><h1>{ru?'Creative кампании':'Campaign Creative'}</h1><p>{ru?'Все уникальные форматы, placements и синхронный playback на одном экране.':'All unique formats, placements and synchronized playback on one screen.'}</p></div></div><TemplateWorkspace campaign={campaign} ru={ru} canEdit={can(role,'edit-creative')&&can(role,'edit-campaign')} onUpdated={applyCampaign} onError={setError}/>{campaign.formats.length?<CampaignWall campaign={campaign} locale={locale} onOpenEditor={openCreativeEditor}/>:<div className="ne-empty"><div className="ne-empty-inner"><div className="ne-empty-icon"><WandSparkles size={18}/></div><h3>{ru?'Сначала скомпилируйте кампанию':'Compile the campaign first'}</h3><p>{ru?'Required creative set появится после подтверждения медиаплана.':'The required creative set appears after the media plan is confirmed.'}</p><button className="ne-button primary" onClick={()=>setScreen('media')}>{ru?'Открыть медиаплан':'Open Media Plan'}</button></div></div>}</section>}
    {screen==='delivery'&&campaign.id&&<DeliveryWorkspace key={campaign.id} campaign={campaign} locale={locale} canDeliver={can(role,'deliver')} onOpenEditor={openCreativeEditor} onError={setError}/>}
    {screen==='settings'&&<section className="ne-page"><div className="ne-page-head"><div><div className="ne-kicker">Workspace</div><h1>{ru?'Настройки':'Settings'}</h1><p>{session.workspace.name} · {session.user.email}</p></div></div><div className="ne-settings-grid"><article className="ne-card"><div className="ne-kicker">Account</div><h3>{session.user.name}</h3><p>{session.user.email}</p><div className="ne-flow-block" style={{marginTop:16}}><span>{ru?'Ваша роль':'Your role'}</span><strong style={{fontSize:14,textTransform:'capitalize'}}>{role}</strong></div></article><article className="ne-card"><div className="ne-kicker">Members</div><h3>{ru?'Доступ к workspace':'Workspace access'}</h3>{can(role,'manage-access')&&<div className="ne-invite"><input className="ne-input" type="email" value={inviteEmail} onChange={e=>setInviteEmail(e.target.value)} placeholder="designer@company.com"/><select className="ne-select" value={inviteRole} onChange={e=>setInviteRole(e.target.value as AccessRole)}>{['admin','designer','producer','viewer'].map(r=><option key={r} value={r}>{r}</option>)}</select><button className="ne-button primary" disabled={!inviteEmail.includes('@')} onClick={()=>void invite()}>{ru?'Пригласить':'Invite'}</button></div>}{inviteLink&&<div className="ne-flow-block"><span>{ru?'Ссылка приглашения':'Invitation link'}</span><input className="ne-input" readOnly value={inviteLink} onFocus={e=>e.currentTarget.select()} style={{marginTop:8}}/></div>}<div className="ne-member-list">{invitations.map(i=><div className="ne-member-row" key={i.id}><span><b>{i.email}</b><small className="ne-pending">{ru?'Ожидает принятия':'Pending invitation'}</small></span><em className="ne-badge">{i.role}</em></div>)}{members.map(m=><div className="ne-member-row" key={m.id}><span><b>{m.user?.name||'Member'}</b><small>{m.user?.email||''}</small></span>{can(role,'manage-access')?<select className="ne-select" value={m.role} onChange={e=>void updateRole(m.id,e.target.value as AccessRole)}>{['owner','admin','designer','producer','viewer'].map(r=><option key={r} value={r}>{r}</option>)}</select>:<em className="ne-badge">{m.role}</em>}</div>)}</div></article></div></section>}
   </div>
  </main>
 </div>;
}
