import {useEffect,useMemo,useRef,useState} from 'react';
import {ArrowDownToLine,ArrowRight,Pause,Play,RefreshCcw} from 'lucide-react';
import FigmaImportBrowser from './FigmaImportBrowser';
import {assetQualityForCampaign,formatRequirementBadges,normalizedExportScale,type Campaign,type Placement,type VisualFormat} from './domain';
import type {Locale} from './i18n';

type WallMode='creative'|'delivery';
type Command={type:'bannermatic:play'|'bannermatic:pause'|'bannermatic:seek'|'bannermatic:replay';time?:number};
const ttKnown=(p:Placement)=>Boolean(p.requirements.sourceUrl||p.requirements.sourceLabel&&!String(p.requirements.sourceLabel).toLowerCase().startsWith('unknown'));
const statusClass=(v:string)=>`ne-wall-status ${v}`;
const svgDoc=(svg:string)=>`<!doctype html><html><head><meta charset="utf-8"><style>html,body{margin:0;width:100%;height:100%;overflow:hidden;background:transparent}svg{display:block;width:100%;height:100%}</style></head><body>${svg}</body></html>`;
const isLive=(format:VisualFormat)=>Boolean(format.previewHtml||format.previewUrl);

function CreativePreview({format,command,onOpen}:{format:VisualFormat;command:Command;onOpen:()=>void}){
 const frame=useRef<HTMLIFrameElement>(null);const live=isLive(format);
 useEffect(()=>{if(live)frame.current?.contentWindow?.postMessage(command,'*')},[command,live]);
 if(format.previewHtml)return <div className="ne-wall-preview" style={{aspectRatio:`${format.width}/${format.height}`}}><iframe ref={frame} srcDoc={format.previewHtml} title={`${format.size} live creative`} sandbox="allow-scripts"/><span className="ne-wall-preview-kind">Live HTML</span><button className="ne-wall-open" onClick={onOpen} aria-label="Open creative in editor">↗</button></div>;
 if(format.previewUrl)return <div className="ne-wall-preview" style={{aspectRatio:`${format.width}/${format.height}`}}><iframe ref={frame} src={format.previewUrl} title={`${format.size} live creative`} sandbox="allow-scripts allow-same-origin"/><span className="ne-wall-preview-kind">Live HTML</span><button className="ne-wall-open" onClick={onOpen} aria-label="Open creative in editor">↗</button></div>;
 if(format.previewSvg)return <div className="ne-wall-preview" style={{aspectRatio:`${format.width}/${format.height}`}}><iframe srcDoc={svgDoc(format.previewSvg)} title={`${format.size} published creative preview`} sandbox=""/><span className="ne-wall-preview-kind">Creative snapshot</span><button className="ne-wall-open" onClick={onOpen} aria-label="Open creative in editor">↗</button></div>;
 return <button className="ne-wall-placeholder" style={{aspectRatio:`${format.width}/${format.height}`}} onClick={onOpen}><div><strong>BANNERMATIC</strong><b>{format.size}</b><span>Open the editor to create this format.</span></div></button>;
}

export default function CampaignWall({campaign,locale,onOpenEditor}:{campaign:Campaign;locale:Locale;onOpenEditor:()=>void}){
 const [mode,setMode]=useState<WallMode>('creative'),[playing,setPlaying]=useState(false),[time,setTime]=useState(0),[nonce,setNonce]=useState(0),[requirementsOnly,setRequirementsOnly]=useState(false),[overrideId,setOverrideId]=useState(''),[importOpen,setImportOpen]=useState(false);const started=useRef(0),raf=useRef<number|undefined>(undefined);
 const quality=useMemo(()=>assetQualityForCampaign(campaign),[campaign]),insufficient=quality.filter(q=>q.state==='insufficient'),qualityByFormat=(id:string)=>quality.filter(q=>q.formatId===id&&q.state!=='ok');const liveCount=useMemo(()=>campaign.formats.filter(isLive).length,[campaign.formats]);const highResCount=useMemo(()=>campaign.formats.filter(f=>normalizedExportScale(f.exportScale)===2).length,[campaign.formats]);const visibleFormats=requirementsOnly?campaign.formats.filter(f=>normalizedExportScale(f.exportScale)===2):campaign.formats;
 const maxDuration=useMemo(()=>Math.max(6,...campaign.formats.filter(isLive).map(f=>Number(f.durationSec)||0)),[campaign.formats]);
 useEffect(()=>{if(!liveCount&&playing)setPlaying(false)},[liveCount,playing]);
 useEffect(()=>{if(!playing){if(raf.current)cancelAnimationFrame(raf.current);return}started.current=performance.now()-time*1000;const tick=(now:number)=>{const next=Math.min(maxDuration,(now-started.current)/1000);setTime(next);if(next>=maxDuration){setPlaying(false);return}raf.current=requestAnimationFrame(tick)};raf.current=requestAnimationFrame(tick);return()=>{if(raf.current)cancelAnimationFrame(raf.current)}},[playing,maxDuration,nonce]);
 const command:Command=playing?{type:'bannermatic:play',time}:{type:'bannermatic:pause',time};const replay=()=>{if(!liveCount)return;setTime(0);setNonce(n=>n+1);setPlaying(true)};const seek=(value:number)=>{if(!liveCount)return;setTime(value);setNonce(n=>n+1)};const placement=(id:string)=>campaign.placements.find(p=>p.id===id);const ru=locale==='ru';
 const setManualScale=async(format:VisualFormat,scale:1|2)=>{try{const formats=campaign.formats.map(f=>f.id===format.id?{...f,exportScale:scale,exportScaleSource:'manual' as const}:f);await import('./api').then(({api})=>api.updateCampaign(campaign.id,{formats}));location.reload()}catch{}};
 return <div className="ne-workspace-page">{importOpen&&<FigmaImportBrowser campaign={campaign} locale={locale} onClose={()=>setImportOpen(false)}/>}
  {insufficient.length>0&&<details className="ne-quality-campaign"><summary><b>{insufficient.length}</b> {ru?"asset quality issues":"asset quality issues"}</summary>{insufficient.map(q=><button key={`${q.formatId}-${q.sceneId}-${q.layerId}`} onClick={onOpenEditor}><span>{q.layerName} · {campaign.formats.find(f=>f.id===q.formatId)?.size}</span><em>{q.density.toFixed(2)}× / {q.requiredScale}×</em></button>)}</details>}<div className="ne-requirement-summary"><button className={requirementsOnly?'active':''} onClick={()=>setRequirementsOnly(v=>!v)}><b>{highResCount}</b><span>{ru?`из ${campaign.formats.length} форматов требуют @2x`:`of ${campaign.formats.length} formats require @2x`}</span></button><small>{ru?'Нажмите, чтобы выделить требующие high-res source':'Click to filter formats requiring high-res source'}</small></div><div className="ne-wall-toolbar"><div className="ne-tabs"><button className="ne-import-design" onClick={()=>setImportOpen(true)}><ArrowDownToLine size={13}/>{ru?"Импорт дизайна":"Import design"}</button><button className={mode==='creative'?'active':''} onClick={()=>setMode('creative')}>Creative</button><button className={mode==='delivery'?'active':''} onClick={()=>setMode('delivery')}>Delivery</button></div><div className="ne-wall-playback"><button disabled={!liveCount} title={!liveCount?(ru?'Live HTML previews ещё не опубликованы':'No live HTML previews published yet'):''} onClick={()=>setPlaying(v=>!v)}>{playing?<Pause size={13}/>:<Play size={13}/>} {playing?(ru?'Пауза':'Pause all'):(ru?'Играть все':'Play all')}</button><button disabled={!liveCount} onClick={replay}><RefreshCcw size={13}/>{ru?'Сначала':'Replay all'}</button><label className={!liveCount?'disabled':''}><span>{time.toFixed(1)}s</span><input disabled={!liveCount} aria-label="Shared campaign playhead" type="range" min="0" max={maxDuration} step="0.1" value={time} onChange={e=>seek(Number(e.target.value))}/><em>{maxDuration.toFixed(1)}s</em></label><small>{liveCount}/{campaign.formats.length} live</small></div></div>
  <div className="ne-wall-grid">{visibleFormats.map(format=>{const ps=format.placementIds.map(placement).filter(Boolean) as Placement[];const previewLabel=isLive(format)?'Live HTML':format.previewSvg?'Creative snapshot':'Not published';const state=format.creativeState==='published'?'ready':format.creativeState==='draft'?'warning':'blocked',formatQuality=qualityByFormat(format.id);return <article className="ne-wall-card" key={format.id}><div className="ne-wall-card-head"><div><b>{format.size}</b><small>{ps.length} placement{ps.length===1?'':'s'}</small><div className="ne-format-badges">{formatRequirementBadges(format).map(b=><em key={b}>{b}</em>)}{format.exportScaleSource==='manual'&&<em>MANUAL</em>}<button className="ne-scale-override" title={ru?'Расширенная ручная настройка scale':'Advanced manual scale override'} onClick={()=>setOverrideId(overrideId===format.id?'':format.id)}>⋯</button>{overrideId===format.id&&<span className="ne-scale-menu"><button onClick={()=>void setManualScale(format,1)}>@1x</button><button onClick={()=>void setManualScale(format,2)}>@2x</button></span>}</div></div><span className={statusClass(state)}>{format.creativeState}</span></div>{formatQuality.length>0&&<div className="ne-quality-warning"><b>Asset quality</b><span>{formatQuality.length} {formatQuality.some(q=>q.state==='insufficient')?(ru?'недостаточно':'insufficient'):(ru?'предупреждение':'warning')}</span></div>}<CreativePreview format={format} command={command} onOpen={onOpenEditor}/>{mode==='creative'?<div className="ne-wall-meta"><div><span>Creative version</span><b>v{format.creativeVersion}</b></div><div><span>Preview</span><b>{previewLabel}</b></div><button onClick={onOpenEditor}>{ru?'Открыть в редакторе':'Open in editor'}<ArrowRight size={12}/></button></div>:<div className="ne-wall-meta"><div className="ne-placement-list">{ps.map(p=><div className="ne-placement-row" key={p.id}><span><b>{p.platform}</b><small>{p.placement}</small></span><em className={statusClass(ttKnown(p)?'ready':'unknown')}>{ttKnown(p)?'TT ✓':'TT ?'}</em></div>)}</div></div>}</article>})}</div>
 </div>;
}
