import {useState} from 'react';
import {api} from './api';
import type {Campaign,ContentVariant} from './domain';
export default function ContentWorkspace({campaign,ru,canEdit,onUpdated,onError}:{campaign:Campaign;ru:boolean;canEdit:boolean;onUpdated:(c:Campaign)=>void;onError:(s:string)=>void}){
 const [items,setItems]=useState<ContentVariant[]>(campaign.contentVariants||[]),[placements,setPlacements]=useState(campaign.placements),[busy,setBusy]=useState(false),[saved,setSaved]=useState(false);
 const edit=(id:string,key:keyof ContentVariant,value:string)=>{setSaved(false);setItems(items.map(v=>v.id===id?{...v,[key]:value}:v))};
 const save=async()=>{setBusy(true);onError('');try{onUpdated(await api.updateCampaign(campaign.id,{contentVariants:items,placements}));setSaved(true)}catch(e){onError(String(e))}finally{setBusy(false)}};
 return <section className="ne-page"><div className="ne-page-head"><div><div className="ne-kicker">Content</div><h1>{ru?'Контент кампании':'Campaign content'}</h1><p>{ru?'Создайте варианты текста и назначьте их размещениям. После изменения опубликованного текста потребуется Publish Changes.':'Create copy variants and assign them to placements. Changes to published copy require Publish Changes.'}</p></div><button className="ne-button primary" disabled={!canEdit||busy||!items.length} onClick={()=>void save()}>{busy?'…':ru?'Сохранить контент':'Save content'}</button></div>
 {saved&&<p role="status">{ru?'Сохранено. Проверьте Creative и опубликуйте изменения.':'Saved. Review Creative and publish your changes.'}</p>}
 <div className="vnext-content-grid">{items.map(v=><fieldset className="ne-card" key={v.id} disabled={!canEdit||busy}><legend>{v.name||'Content variant'}</legend>{(['name','language','headline','copy','cta','legal'] as const).map(key=><label className="vnext-field" key={key}><span>{({name:ru?'Название':'Name',language:ru?'Язык':'Language',headline:'Headline',copy:ru?'Дополнительный текст':'Supporting copy',cta:'CTA',legal:ru?'Юридический текст':'Legal'})[key]}</span><textarea rows={key==='headline'||key==='legal'?2:1} value={v[key]} onChange={e=>edit(v.id,key,e.target.value)}/></label>)}</fieldset>)}</div>
 <button className="ne-button" disabled={!canEdit||busy} onClick={()=>{setItems([...items,{id:crypto.randomUUID(),name:`Variant ${items.length+1}`,language:ru?'ru':'en',headline:'',copy:'',cta:'',legal:''}]);setSaved(false)}}>{ru?'Добавить вариант':'Add content variant'}</button>
 {!items.length&&<p>{ru?'Начните с headline и CTA. Обязательный legal переносите точно из требований.':'Start with a headline and CTA. Copy mandatory legal text exactly from the requirements.'}</p>}
 <h2>{ru?'Назначения размещениям':'Placement assignments'}</h2><p>{ru?'Отметьте только разрешённые сочетания. Каждая отметка — отдельный deliverable.':'Select only approved combinations. Each selection creates one deliverable.'}</p>
 {placements.map(p=><fieldset className="ne-card" key={p.id} disabled={!canEdit||busy}><legend>{p.platform} · {p.placement} · {p.width}×{p.height}</legend>{items.map(v=><label className="vnext-assignment" key={v.id}><input type="checkbox" checked={p.contentVariantIds?.includes(v.id)||false} onChange={e=>{setSaved(false);setPlacements(placements.map(x=>x.id===p.id?{...x,contentVariantIds:e.target.checked?[...(x.contentVariantIds||[]),v.id]:(x.contentVariantIds||[]).filter(id=>id!==v.id)}:x))}}/>{v.name} · {v.language}</label>)}</fieldset>)}
 </section>;
}
