import {useEffect,useMemo,useState} from 'react';
import {ArrowRight,CheckCircle2,CircleAlert,Clock3,Download,FileCheck2,RefreshCcw,ShieldCheck,Sparkles} from 'lucide-react';
import {api,type CampaignBuild,type CreativeVersion,type TTResolution} from './api';
import type {Campaign} from './domain';
import type {Locale} from './i18n';

type Compliance={campaignId:string;creativeVersion:number;mediaPlanVersion:number;ttSnapshotVersion:number;summary:{ready:number;warning:number;blocked:number;total:number};placements:Array<any>};
const statusClass=(value:string)=>`ne-wall-status ${value}`;

export default function DeliveryWorkspace({campaign,locale,canDeliver,onOpenEditor,onError}:{campaign:Campaign;locale:Locale;canDeliver:boolean;onOpenEditor:()=>void;onError:(s:string)=>void}){
 const ru=locale==='ru';const [compliance,setCompliance]=useState<Compliance|null>(null),[tt,setTT]=useState<TTResolution|null>(null),[builds,setBuilds]=useState<CampaignBuild[]>([]),[versions,setVersions]=useState<CreativeVersion[]>([]),[busy,setBusy]=useState(false),[notice,setNotice]=useState('');
 const refresh=async()=>{if(!campaign.id)return;setBusy(true);onError('');try{const [c,t,b,v]=await Promise.all([api.compliance(campaign.id),api.ttResolve(campaign.id),api.builds(campaign.id),api.creativeVersions(campaign.id)]);setCompliance(c);setTT(t);setBuilds(b.items);setVersions(v.items)}catch(e){onError(e instanceof Error?e.message:String(e))}finally{setBusy(false)}};
 useEffect(()=>{void refresh()},[campaign.id,campaign.updatedAt,campaign.creativeVersion,campaign.mediaPlanVersion,campaign.ttSnapshotVersion]);
 const ttMap=useMemo(()=>new Map((tt?.results||[]).map((r:any)=>[r.placementId,r])),[tt]);
 const createBuild=async()=>{if(!canDeliver)return;setBusy(true);setNotice('');onError('');try{const result=await api.createBuild(campaign.id);setNotice(ru?`Build ${result.build.id} создан.`:`Build ${result.build.id} created.`);await refresh()}catch(e){onError(e instanceof Error?e.message:String(e));await refresh()}finally{setBusy(false)}};
 const downloadPackage=async(build:CampaignBuild)=>{setBusy(true);try{const blob=await api.downloadBuild(campaign.id,build.id),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=`campaign-${build.id}.zip`;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000)}catch(e){onError(e instanceof Error?e.message:String(e))}finally{setBusy(false)}};

 const summary=compliance?.summary||{ready:0,warning:0,blocked:0,total:campaign.placements.length};const allReady=summary.total>0&&summary.ready===summary.total;
 return <section className="ne-workspace-page"><div className="ne-workspace-header"><div><div className="ne-kicker">TT Intelligence · Live Compliance · Delivery</div><h1>{ru?'TT и Delivery':'TT & Delivery'}</h1><p>{ru?'Требования живут на уровне placement. Compliance пересчитывается по опубликованной creative version.':'Requirements live at placement level. Compliance is recalculated against the published creative version.'}</p></div><button className="ne-button" onClick={()=>void refresh()} disabled={busy}><RefreshCcw size={13}/>{ru?'Обновить':'Refresh'}</button></div>
 <div className="ne-delivery-hero"><div><div className="ne-kicker">Campaign readiness</div><strong>{summary.ready}/{summary.total}</strong><p>{allReady?(ru?'Все placements готовы к delivery.':'All placements are ready for delivery.'):(ru?'Есть placements, требующие TT или creative-исправлений.':'Some placements still need TT or creative fixes.')}</p></div><div><div className="ne-readiness-track"><i style={{width:`${summary.total?summary.ready/summary.total*100:0}%`}}/></div><div className="ne-readiness-meta"><span>{summary.ready} ready</span><span>{summary.warning} warning</span><span>{summary.blocked} blocked</span></div></div><button className="ne-button primary" onClick={()=>void createBuild()} disabled={!canDeliver||busy||!allReady}><FileCheck2 size={14}/>{ru?'Собрать Campaign Build':'Build campaign'}</button></div>
 {notice&&<div className="ne-delivery-notice"><CheckCircle2 size={14}/>{notice}</div>}
 <div className="ne-delivery-layout"><section className="ne-delivery-section"><div className="ne-section-bar"><div><div className="ne-kicker">Placement preflight</div><h2>{ru?'Проверка размещений':'Placement preflight'}</h2></div><ShieldCheck size={18}/></div>{(compliance?.placements||[]).map((p:any)=>{const resolved:any=ttMap.get(p.placementId);return <article className="ne-preflight" key={p.placementId}><div className="ne-preflight-title"><span><b>{p.platform}</b><small>{p.placement} · {p.size}</small></span><em className={statusClass(p.status==='ready'?'ready':p.status==='warning'?'warning':'blocked')}>{p.status}</em></div><div className="ne-check-grid">{p.checks.map((c:any)=><div key={c.name} className={`ne-check ${c.status}`}><span>{c.name}</span><b>{c.status}</b>{c.detail&&<small>{c.detail}</small>}{c.actual!==null&&<small>{String(c.actual)}{c.expected!==null?` / ${String(c.expected)}`:''}</small>}</div>)}</div>{resolved&&<div className="ne-tt-source"><Sparkles size={11}/><span>{resolved.status==='matched'?resolved.matches?.[0]?.sourceTitle||resolved.matches?.[0]?.platform:resolved.status==='ambiguous'?(ru?'Нужно уточнить placement/product':'Specify placement/product'):(ru?'Проверенный источник TT не найден':'No verified TT source found')}</span></div>}{p.status!=='ready'&&<button className="ne-inline-action" onClick={onOpenEditor}>{ru?'Открыть creative в editor':'Open creative in editor'}<ArrowRight size={11}/></button>}</article>})}{!campaign.placements.length&&<div className="ne-empty"><div className="ne-empty-inner"><div className="ne-empty-icon"><CircleAlert size={17}/></div><h3>{ru?'Нет placements':'No placements yet'}</h3><p>{ru?'Сначала добавьте медиаплан.':'Attach a media plan first.'}</p></div></div>}</section>
 <aside className="ne-delivery-side"><section className="ne-delivery-section"><div className="ne-section-bar"><div><div className="ne-kicker">Version pins</div><h2>{ru?'Активное состояние':'Active state'}</h2></div><Clock3 size={17}/></div><div className="ne-version-stack"><div><span>Creative</span><b>v{campaign.creativeVersion||0}</b></div><div><span>Media Plan</span><b>v{campaign.mediaPlanVersion||0}</b></div><div><span>TT snapshot</span><b>v{campaign.ttSnapshotVersion||0}</b></div></div><p className="ne-small-note">{ru?'Каждый final build фиксирует эти три версии.':'Every final build pins these three versions.'}</p></section>
 <section className="ne-delivery-section"><div className="ne-section-bar"><div><div className="ne-kicker">Creative history</div><h2>{ru?'Публикации':'Publications'}</h2></div></div><div className="ne-history-list">{versions.slice(0,6).map(v=><div className="ne-history-item" key={v.id}><span>Creative v{v.version}</span><b>{v.formats.length} formats</b><small>{new Date(v.createdAt).toLocaleString(locale)}</small></div>)}{!versions.length&&<p className="ne-history-empty">{ru?'Ещё нет публикаций из editor.':'No editor publications yet.'}</p>}</div></section>
 <section className="ne-delivery-section"><div className="ne-section-bar"><div><div className="ne-kicker">Campaign builds</div><h2>{ru?'История сборок':'Build history'}</h2></div></div><div className="ne-history-list">{builds.map(b=><div className="ne-history-item" key={b.id}><span>{b.state==='ready'?'Ready build':'Blocked build'}</span><b>{b.compliance.ready}/{b.compliance.total}</b><small>{new Date(b.createdAt).toLocaleString(locale)}</small><button disabled={busy||b.state!=='ready'} onClick={()=>void downloadPackage(b)} title="Download HTML5 packages"><Download size={12}/></button></div>)}{!builds.length&&<p className="ne-history-empty">{ru?'Готовых сборок пока нет.':'No campaign builds yet.'}</p>}</div></section></aside></div>
 </section>;
}
