import {useEffect,useMemo,useState} from 'react';
import {ArrowRight,CheckCircle2,CircleAlert,Clock3,Download,FileCheck2,RefreshCcw,ShieldCheck,Sparkles} from 'lucide-react';
import {api,type CampaignBuild,type CreativeVersion,type TTResolution} from './api';
import type {Campaign} from './domain';
import type {Locale} from './i18n';

type Compliance={campaignId:string;creativeVersion:number;mediaPlanVersion:number;ttSnapshotVersion:number;summary:{ready:number;warning:number;blocked:number;total:number};placements:Array<any>};
const statusClass=(value:string)=>`bm-status bm-${value}`;

export default function DeliveryWorkspace({campaign,locale,canDeliver,onOpenFigma,onError}:{campaign:Campaign;locale:Locale;canDeliver:boolean;onOpenFigma:()=>void;onError:(s:string)=>void}){
 const ru=locale==='ru';const [compliance,setCompliance]=useState<Compliance|null>(null),[tt,setTT]=useState<TTResolution|null>(null),[builds,setBuilds]=useState<CampaignBuild[]>([]),[versions,setVersions]=useState<CreativeVersion[]>([]),[busy,setBusy]=useState(false),[notice,setNotice]=useState('');
 const refresh=async()=>{if(!campaign.id)return;setBusy(true);onError('');try{const [c,t,b,v]=await Promise.all([api.compliance(campaign.id),api.ttResolve(campaign.id),api.builds(campaign.id),api.creativeVersions(campaign.id)]);setCompliance(c);setTT(t);setBuilds(b.items);setVersions(v.items)}catch(e){onError(e instanceof Error?e.message:String(e))}finally{setBusy(false)}};
 useEffect(()=>{void refresh()},[campaign.id,campaign.updatedAt,campaign.creativeVersion,campaign.mediaPlanVersion,campaign.ttSnapshotVersion]);
 const ttMap=useMemo(()=>new Map((tt?.results||[]).map((r:any)=>[r.placementId,r])),[tt]);
 const createBuild=async()=>{if(!canDeliver)return;setBusy(true);setNotice('');onError('');try{const result=await api.createBuild(campaign.id);setNotice(ru?`Build ${result.build.id} создан.`:`Build ${result.build.id} created.`);await refresh()}catch(e){onError(e instanceof Error?e.message:String(e));await refresh()}finally{setBusy(false)}};
 const downloadManifest=(build:CampaignBuild)=>{const blob=new Blob([JSON.stringify(build,null,2)],{type:'application/json'}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=`bannermatic-${campaign.name.replace(/[^a-z0-9_-]+/gi,'-')}-${build.id}.json`;a.click();URL.revokeObjectURL(url)};
 const summary=compliance?.summary||{ready:0,warning:0,blocked:0,total:campaign.placements.length};const allReady=summary.total>0&&summary.ready===summary.total;
 return <section className="bm-page"><div className="bm-page-head"><div><span className="bm-eyebrow">TT INTELLIGENCE · LIVE COMPLIANCE · DELIVERY</span><h1>{ru?'TT и Delivery':'TT & Delivery'}</h1><p>{ru?'Требования живут на уровне placement. Compliance пересчитывается по опубликованной creative version.':'Requirements live at placement level. Compliance is recalculated against the published creative version.'}</p></div><button className="bm-secondary" onClick={()=>void refresh()} disabled={busy}><RefreshCcw size={14}/>{ru?'Обновить':'Refresh'}</button></div>
 <div className="bm-readiness-hero bm-surface"><div><span className="bm-eyebrow">CAMPAIGN READINESS</span><strong>{summary.ready}/{summary.total}</strong><p>{allReady?(ru?'Все placements готовы к delivery.':'All placements are ready for delivery.'):(ru?'Есть placements, требующие TT или creative-исправлений.':'Some placements still need TT or creative fixes.')}</p></div><div className="bm-readiness-bars"><span className="ready"><i style={{width:`${summary.total?summary.ready/summary.total*100:0}%`}}/></span><div><em>{summary.ready} ready</em><em>{summary.warning} warning</em><em>{summary.blocked} blocked</em></div></div><button className="bm-primary" onClick={()=>void createBuild()} disabled={!canDeliver||busy||!allReady}><FileCheck2 size={15}/>{ru?'Собрать Campaign Build':'Build campaign'}</button></div>
 {notice&&<div className="bm-notice"><CheckCircle2 size={15}/>{notice}</div>}
 <div className="bm-delivery-grid"><section className="bm-surface bm-delivery-section"><div className="bm-section-bar"><div><span className="bm-eyebrow">PLACEMENT PREFLIGHT</span><h2>{ru?'Проверка размещений':'Placement preflight'}</h2></div><ShieldCheck size={19}/></div>{(compliance?.placements||[]).map((p:any)=>{const resolved:any=ttMap.get(p.placementId);return <article className="bm-preflight" key={p.placementId}><div className="bm-preflight-title"><span><b>{p.platform}</b><small>{p.placement} · {p.size}</small></span><em className={statusClass(p.status==='ready'?'ready':p.status==='warning'?'warning':'blocked')}>{p.status}</em></div><div className="bm-check-grid">{p.checks.map((c:any)=><div key={c.name} className={`bm-check ${c.status}`}><span>{c.name}</span><b>{c.status}</b>{c.actual!==null&&<small>{String(c.actual)}{c.expected!==null?` / ${String(c.expected)}`:''}</small>}</div>)}</div>{resolved&&<div className="bm-tt-source"><Sparkles size={12}/><span>{resolved.status==='matched'?resolved.matches?.[0]?.sourceTitle||resolved.matches?.[0]?.platform:resolved.status==='ambiguous'?(ru?'Нужно уточнить placement/product':'Specify placement/product'):(ru?'Проверенный источник TT не найден':'No verified TT source found')}</span></div>}{p.status!=='ready'&&<button className="bm-ghost bm-inline-action" onClick={onOpenFigma}>{ru?'Открыть creative в Figma':'Open creative in Figma'}<ArrowRight size={12}/></button>}</article>})}{!campaign.placements.length&&<div className="bm-empty compact"><CircleAlert size={24}/><h3>{ru?'Нет placements':'No placements yet'}</h3><p>{ru?'Сначала добавьте медиаплан.':'Attach a media plan first.'}</p></div>}</section>
 <aside className="bm-delivery-side"><section className="bm-surface bm-delivery-section"><div className="bm-section-bar"><div><span className="bm-eyebrow">VERSION PINS</span><h2>{ru?'Активное состояние':'Active state'}</h2></div><Clock3 size={18}/></div><div className="bm-version-stack"><div><span>Creative</span><b>v{campaign.creativeVersion||0}</b></div><div><span>Media Plan</span><b>v{campaign.mediaPlanVersion||0}</b></div><div><span>TT snapshot</span><b>v{campaign.ttSnapshotVersion||0}</b></div></div><p className="bm-small-note">{ru?'Каждый final build фиксирует эти три версии.':'Every final build pins these three versions.'}</p></section>
 <section className="bm-surface bm-delivery-section"><div className="bm-section-bar"><div><span className="bm-eyebrow">CREATIVE HISTORY</span><h2>{ru?'Публикации':'Publications'}</h2></div></div><div className="bm-history-list">{versions.slice(0,6).map(v=><div key={v.id}><span>Creative v{v.version}</span><b>{v.formats.length} formats</b><small>{new Date(v.createdAt).toLocaleString(locale)}</small></div>)}{!versions.length&&<p>{ru?'Ещё нет публикаций из Figma.':'No Figma publications yet.'}</p>}</div></section>
 <section className="bm-surface bm-delivery-section"><div className="bm-section-bar"><div><span className="bm-eyebrow">CAMPAIGN BUILDS</span><h2>{ru?'История сборок':'Build history'}</h2></div></div><div className="bm-history-list">{builds.map(b=><div key={b.id}><span>{b.state==='ready'?'Ready build':'Blocked build'}</span><b>{b.compliance.ready}/{b.compliance.total}</b><small>{new Date(b.createdAt).toLocaleString(locale)}</small><button onClick={()=>downloadManifest(b)} title="Download build manifest"><Download size={13}/></button></div>)}{!builds.length&&<p>{ru?'Готовых сборок пока нет.':'No campaign builds yet.'}</p>}</div></section></aside></div>
 </section>;
}
