import {useEffect,useState} from 'react';
import {ArrowRight,Check,Copy,Link2,RefreshCcw} from 'lucide-react';
import {api,type FigmaConnectionStatus,type FigmaPair} from './api';
import type {Campaign} from './domain';
import type {Locale} from './i18n';

export default function FigmaConnectPanel({campaign,locale,enabled,onError}:{campaign:Campaign;locale:Locale;enabled:boolean;onError:(s:string)=>void}){
 const [pair,setPair]=useState<FigmaPair|null>(null),[connection,setConnection]=useState<FigmaConnectionStatus|null>(null),[busy,setBusy]=useState(false),[copied,setCopied]=useState(false),[now,setNow]=useState(Date.now());const ru=locale==='ru';
 const refresh=async()=>{try{setConnection(await api.figmaStatus(campaign.id))}catch(e){onError(e instanceof Error?e.message:String(e))}};
 useEffect(()=>{void refresh();const timer=window.setInterval(()=>void refresh(),3000);return()=>window.clearInterval(timer)},[campaign.id]);
 const create=async()=>{if(!enabled)return;setBusy(true);setCopied(false);onError('');try{const next=await api.figmaPair(campaign.id);setPair(next);await refresh()}catch(e){onError(e instanceof Error?e.message:String(e))}finally{setBusy(false)}};
 const copy=async()=>{if(!pair)return;await navigator.clipboard.writeText(pair.code);setCopied(true);setTimeout(()=>setCopied(false),1500)};
 useEffect(()=>{if(!pair)return;const timer=window.setInterval(()=>setNow(Date.now()),1000);return()=>window.clearInterval(timer)},[pair?.expiresAt]);
 const state=connection?.state||'not_connected',connected=state==='connected'||state==='published',secondsLeft=pair?Math.max(0,Math.ceil((new Date(pair.expiresAt).getTime()-now)/1000)):0,expired=Boolean(pair)&&secondsLeft===0;
 const validity=expired?(ru?'Код истёк — создайте новый':'Code expired — create a new one'):(ru?`Действует ещё ${Math.ceil(secondsLeft/60)} мин. · одно использование`:`Valid for ${Math.ceil(secondsLeft/60)} min · one use`);
 return <section className="ne-figma-connect"><div className="ne-figma-copy"><div className="ne-kicker">Browser → Figma</div><div className="ne-figma-title-row"><h2>{ru?`Продолжить ${campaign.name} в Figma`:`Continue ${campaign.name} in Figma`}</h2><span className={`ne-figma-state ${state}`}>{state==='published'?(ru?'Опубликовано':'Published'):connected?(ru?'Figma подключена':'Figma connected'):state==='ready_to_continue'?(ru?'Готово к переходу':'Ready to continue'):(ru?'Не подключено':'Not connected')}</span></div><p>{ru?`Это та же кампания: ${campaign.placements.length} placements и ${campaign.formats.length} required formats. Плагин продолжит её без повторной настройки.`:`This is the same campaign: ${campaign.placements.length} placements and ${campaign.formats.length} required formats. The plugin continues it without rebuilding campaign context.`}</p>{connected&&<small>{ru?'Нужен вход в новой версии плагина или другом Figma-файле? Выпустите новый одноразовый код — текущая связь останется активной.':'Signing in from a new plugin version or another Figma file? Generate a new one-time code; the existing connection stays active.'}</small>}</div>{pair?<div className="ne-pair-code"><span>{ru?'Новый код для Bannermatic plugin':'New code for the Bannermatic plugin'}</span><strong>{pair.code}</strong><small>{validity}</small><div className="ne-pair-actions"><button className="ne-button primary" onClick={()=>void copy()} disabled={expired}>{copied?<Check size={13}/>:<Copy size={13}/>} {copied?(ru?'Код скопирован':'Code copied'):(ru?'Скопировать код':'Copy code')}</button><button className="ne-button" onClick={()=>void create()} disabled={busy}><RefreshCcw size={13}/>{ru?'Заменить код':'Replace code'}</button></div></div>:<button className="ne-button primary ne-figma-continue" onClick={()=>void create()} disabled={!enabled||busy}><Link2 size={14}/>{busy?(ru?'Готовим код…':'Preparing code…'):connected?(ru?'Новый код для плагина':'New plugin code'):(ru?'Продолжить в Figma':'Continue in Figma')}<ArrowRight size={14}/></button>}<div className="ne-pair-steps"><span className="done"><Check size={12}/></span><p><b>{campaign.name}</b><small>{ru?'Кампания подготовлена в браузере':'Campaign prepared in Browser'}</small></p><span className={connected?'done':''}>{connected?<Check size={12}/>:2}</span><p><b>Figma Creative Workspace</b><small>{connected?(ru?'Связана с этой кампанией':'Connected to this campaign'):(ru?'Откройте plugin и введите код':'Open the plugin and enter the code')}</small></p><span className={state==='published'?'done':''}>{state==='published'?<Check size={12}/>:3}</span><p><b>{ru?'Вернуться в Cloud':'Return to Cloud'}</b><small>{state==='published'?(ru?`Creative v${connection?.creativeVersion} опубликован`:`Creative v${connection?.creativeVersion} published`):(ru?'Publish вернёт результат в эту кампанию':'Publish returns the result to this campaign')}</small></p></div></section>;
}
