import {useEffect,useState} from 'react';
import {ArrowRight,Check,Copy,Link2,RefreshCcw,WandSparkles} from 'lucide-react';
import {api,type FigmaConnectionStatus,type FigmaPair} from './api';
import type {Campaign} from './domain';
import type {Locale} from './i18n';

export default function FigmaConnectPanel({campaign,locale,enabled,onError}:{campaign:Campaign;locale:Locale;enabled:boolean;onError:(s:string)=>void}){
 const [pair,setPair]=useState<FigmaPair|null>(null),[connection,setConnection]=useState<FigmaConnectionStatus|null>(null),[busy,setBusy]=useState(false),[copied,setCopied]=useState(false),[now,setNow]=useState(Date.now());const ru=locale==='ru';
 const refresh=async()=>{try{setConnection(await api.figmaStatus(campaign.id))}catch(e){onError(e instanceof Error?e.message:String(e))}};
 useEffect(()=>{void refresh();const timer=window.setInterval(()=>void refresh(),3000);return()=>window.clearInterval(timer)},[campaign.id]);
 const create=async()=>{if(!enabled)return;setBusy(true);setCopied(false);onError('');try{const next=await api.figmaPair(campaign.id);setPair(next);await refresh()}catch(e){onError(e instanceof Error?e.message:String(e))}finally{setBusy(false)}};
 const copy=async()=>{if(!pair)return;await navigator.clipboard.writeText(pair.code);setCopied(true);setTimeout(()=>setCopied(false),1500)};
 useEffect(()=>{if(!pair)return;const timer=window.setInterval(()=>setNow(Date.now()),1000);return()=>window.clearInterval(timer)},[pair?.expiresAt]);
 const state=connection?.state||'not_connected',connected=state==='connected'||state==='published',secondsLeft=pair?Math.max(0,Math.ceil((new Date(pair.expiresAt).getTime()-now)/1000)):0,expired=Boolean(pair)&&secondsLeft===0;
 const validity=expired?(ru?'Код истёк — создайте новый':'Code expired — create a new one'):(ru?`Действует ещё ${Math.ceil(secondsLeft/60)} мин. · одно использование`:`Valid for ${Math.ceil(secondsLeft/60)} min · one use`);
 const openEditor=()=>{location.href=`?view=scene-editor&campaignId=${encodeURIComponent(campaign.id)}`};
 return <section className="ne-figma-connect"><div className="ne-figma-copy"><div className="ne-kicker">Campaign → Creative</div><div className="ne-figma-title-row"><h2>{ru?`Создать creative для ${campaign.name}`:`Create creative for ${campaign.name}`}</h2><span className="ne-figma-state ready_to_continue">{campaign.formats.length} formats</span></div><p>{ru?`Редактор получает эту же кампанию: ${campaign.placements.length} placements, ${campaign.formats.length} required formats и TT из медиаплана. Никакой повторной настройки.`:`The editor receives the same campaign: ${campaign.placements.length} placements, ${campaign.formats.length} required formats and media-plan TT. No setup is repeated.`}</p></div><button className="ne-button primary ne-figma-continue" onClick={openEditor} disabled={!enabled}><WandSparkles size={14}/>{ru?'Открыть Creative Editor':'Open Creative Editor'}<ArrowRight size={14}/></button><div className="ne-pair-steps"><span className="done"><Check size={12}/></span><p><b>{campaign.name}</b><small>{ru?'Медиаплан и TT подготовлены':'Media plan and TT prepared'}</small></p><span className="done"><Check size={12}/></span><p><b>Web Creative Editor</b><small>{ru?'Scenes, Master, responsive formats, motion presets':'Scenes, Master, responsive formats, motion presets'}</small></p><span>{3}</span><p><b>Delivery</b><small>{ru?'TT validation и сборка после creative':'TT validation and build after creative'}</small></p></div><div className="ne-divider"/><div className="ne-figma-copy"><div className="ne-kicker">Optional bridge</div><h3>{ru?'Нужна Figma?':'Need Figma?'}</h3><p>{ru?'Figma остаётся дополнительным импорт/экспорт-мостом, а не основным редактором кампании.':'Figma remains an optional import/export bridge, not the campaign runtime editor.'}</p></div>{pair?<div className="ne-pair-code"><span>{ru?'Код для Bannermatic plugin':'Code for Bannermatic plugin'}</span><strong>{pair.code}</strong><small>{validity}</small><div className="ne-pair-actions"><button className="ne-button" onClick={()=>void copy()} disabled={expired}>{copied?<Check size={13}/>:<Copy size={13}/>} {copied?(ru?'Код скопирован':'Code copied'):(ru?'Скопировать код':'Copy code')}</button><button className="ne-button" onClick={()=>void create()} disabled={busy}><RefreshCcw size={13}/>{ru?'Заменить код':'Replace code'}</button></div></div>:<button className="ne-button" onClick={()=>void create()} disabled={!enabled||busy}><Link2 size={14}/>{busy?(ru?'Готовим код…':'Preparing code…'):(connected?(ru?'Новый код для Figma':'New Figma code'):(ru?'Подключить Figma':'Connect Figma'))}</button>}</section>;
}
