import {useMemo,useState} from 'react';
import {ArrowRight,Plus,Trash2} from 'lucide-react';
import {api} from './api';
import {compileVisualFormats,type Campaign,type Placement} from './domain';
import {diffMediaPlan,preserveVisualsForPlan} from './planDiff';
import type {Locale} from './i18n';

type Row={id:string;platform:string;placement:string;width:string;height:string};
const blank=():Row=>({id:`manual_${crypto.randomUUID?.()||Date.now()}_${Math.random().toString(36).slice(2)}`,platform:'',placement:'',width:'',height:''});
const toRow=(p:Placement):Row=>({id:p.id,platform:p.platform==='Unknown platform'?'':p.platform,placement:p.placement==='Placement'?'':p.placement,width:String(p.width||''),height:String(p.height||'')});

export default function ManualCampaignSetup({campaign,locale,canEdit,onUpdated,onError}:{campaign:Campaign;locale:Locale;canEdit:boolean;onUpdated:(c:Campaign)=>void;onError:(s:string)=>void}){
 const ru=locale==='ru';const [rows,setRows]=useState<Row[]>(()=>campaign.placements.length?campaign.placements.map(toRow):[blank()]);const [busy,setBusy]=useState(false),[review,setReview]=useState(false);
 const placements=useMemo<Placement[]>(()=>rows.map(r=>({id:r.id,platform:r.platform.trim()||'Unknown platform',placement:r.placement.trim()||'Placement',width:Number(r.width),height:Number(r.height),requirements:{sourceLabel:'Manual setup'}})).filter(p=>p.width>0&&p.height>0),[rows]);
 const diff=useMemo(()=>diffMediaPlan(campaign.placements,placements),[campaign.placements,placements]);
 const uniqueCount=useMemo(()=>compileVisualFormats(placements,campaign.formats).length,[placements,campaign.formats]);
 const update=(id:string,key:keyof Row,value:string)=>setRows(list=>list.map(r=>r.id===id?{...r,[key]:value}:r));
 const add=()=>setRows(list=>[...list,blank()]);
 const remove=(id:string)=>setRows(list=>list.length===1?[blank()]:list.filter(r=>r.id!==id));
 const apply=async()=>{if(!canEdit||!placements.length)return;setBusy(true);onError('');try{const compiled=compileVisualFormats(placements,campaign.formats),formats=preserveVisualsForPlan(compiled,campaign.formats),next=await api.updateCampaign(campaign.id,{placements,formats,status:'media-ready',mediaPlanVersion:Number(campaign.mediaPlanVersion||0)+1});onUpdated(next);setReview(false)}catch(e){onError(e instanceof Error?e.message:String(e))}finally{setBusy(false)}};
 return <div className="ne-manual"><div className="ne-workspace-header"><div><div className="ne-kicker">Manual campaign</div><h1>{ru?'Placements вручную':'Build placements manually'}</h1><p>{ru?'Добавьте любые размеры и placements. Одинаковые размеры автоматически используют один visual creative.':'Add any sizes and placements. Equal sizes automatically share one visual creative.'}</p></div><button className="ne-button" disabled={!canEdit} onClick={add}><Plus size={13}/>{ru?'Добавить placement':'Add placement'}</button></div><div className="ne-manual-table"><div className="ne-manual-head"><span>Platform</span><span>Placement</span><span>Width</span><span>Height</span><span/></div>{rows.map((r,i)=><div className="ne-manual-row" key={r.id}><input className="ne-input" value={r.platform} onChange={e=>update(r.id,'platform',e.target.value)} placeholder={i?'AdRiver':'Yandex'}/><input className="ne-input" value={r.placement} onChange={e=>update(r.id,'placement',e.target.value)} placeholder="Homepage / ROS"/><input className="ne-input" inputMode="numeric" value={r.width} onChange={e=>update(r.id,'width',e.target.value.replace(/\D/g,''))} placeholder="300"/><input className="ne-input" inputMode="numeric" value={r.height} onChange={e=>update(r.id,'height',e.target.value.replace(/\D/g,''))} placeholder="250"/><button className="ne-icon-button" title={ru?'Удалить placement':'Remove placement'} onClick={()=>remove(r.id)}><Trash2 size={13}/></button></div>)}</div><div className="ne-manual-footer"><span>{placements.length} placements → {uniqueCount} unique creatives</span><button className="ne-button primary" disabled={!canEdit||!placements.length} onClick={()=>setReview(true)}>{ru?'Проверить перед применением':'Review changes'}<ArrowRight size={13}/></button></div>{review&&<div className="ne-review"><div className="ne-review-head"><div><div className="ne-kicker">Review before compile</div><h2>{ru?'Изменения кампании':'Campaign changes'}</h2><p>{ru?'Visual creative сохраняется для размеров, которые остаются в кампании.':'Existing visual creative is preserved for sizes that remain in the campaign.'}</p></div></div><div className="ne-diff-grid"><article><b>+{diff.added.length}</b><span>{ru?'новых placements':'added placements'}</span></article><article><b>−{diff.removed.length}</b><span>{ru?'удалено':'removed'}</span></article><article><b>{diff.changed.length}</b><span>{ru?'изменено':'changed'}</span></article><article><b>{diff.requiredFormatsAdded.length}</b><span>{ru?'новых форматов':'new formats'}</span></article></div><div className="ne-review-actions"><button className="ne-button" onClick={()=>setReview(false)}>{ru?'Назад':'Back'}</button><button className="ne-button primary" disabled={busy} onClick={()=>void apply()}>{busy?(ru?'Применяем…':'Applying…'):(ru?'Применить и скомпилировать':'Apply & compile')}<ArrowRight size={13}/></button></div></div>}</div>;
}
