import {ArrowRight,Check,FileSpreadsheet,Layers3,Play,ShieldCheck,Sparkles} from 'lucide-react';
import type {Locale} from './i18n';

export default function MarketingHome({locale,onLocale,onSignIn,onStart}:{locale:Locale;onLocale:(l:Locale)=>void;onSignIn:()=>void;onStart:()=>void}){
 const ru=locale==='ru';
 return <div className="bm-marketing">
  <header className="bm-mkt-nav"><a className="bm-mkt-brand" href="#top"><span>B</span><b>Bannermatic</b></a><nav><a href="#product">{ru?'Продукт':'Product'}</a><a href="#workflow">{ru?'Как работает':'Workflow'}</a><a href="#wall">Campaign Wall</a></nav><div className="bm-mkt-actions"><div className="bm-locale"><button className={!ru?'on':''} onClick={()=>onLocale('en')}>EN</button><button className={ru?'on':''} onClick={()=>onLocale('ru')}>RU</button></div><button className="bm-mkt-ghost" onClick={onSignIn}>{ru?'Войти':'Sign in'}</button><button className="bm-primary" onClick={onStart}>{ru?'Начать':'Get started'}<ArrowRight size={15}/></button></div></header>
  <main id="top">
   <section className="bm-hero"><div className="bm-hero-orb"/><div className="bm-hero-copy"><span className="bm-kicker"><Sparkles size={14}/>{ru?'CAMPAIGN COMPILER ДЛЯ FIGMA':'CAMPAIGN COMPILER FOR FIGMA'}</span><h1>{ru?'Из медиаплана — в готовую рекламную кампанию.':'From media plan to a production-ready campaign.'}</h1><p>{ru?'Bannermatic понимает размещения и ТТ, создаёт нужный набор форматов в Figma, синхронизирует creative и проверяет готовность каждого placement перед delivery.':'Bannermatic understands placements and technical requirements, creates the right Figma formats, keeps creative in sync and validates every placement before delivery.'}</p><div className="bm-hero-actions"><button className="bm-primary bm-hero-primary" onClick={onStart}>{ru?'Скомпилировать кампанию':'Compile your campaign'}<ArrowRight size={17}/></button><a href="#wall"><Play size={15}/>{ru?'Посмотреть Campaign Wall':'See Campaign Wall'}</a></div><div className="bm-proofline"><span><Check size={13}/>{ru?'Figma остаётся source of truth':'Figma stays creative source of truth'}</span><span><Check size={13}/>{ru?'TT и delivery живут в Cloud':'TT & delivery live in Cloud'}</span></div></div>
    <div className="bm-hero-product" aria-label="Bannermatic Campaign Compiler preview"><div className="bm-windowbar"><i/><i/><i/><span>Nike / Autumn Launch</span><em>17/17 ready</em></div><div className="bm-product-shell"><aside><b>B</b><span>Overview</span><span>Media Plan</span><span>Creative</span><span>TT & Delivery</span></aside><div className="bm-product-main"><div className="bm-mini-head"><div><small>CAMPAIGN WALL</small><strong>Autumn Launch</strong></div><button>▶ Play all</button></div><div className="bm-mini-stats"><span><b>17</b> placements</span><span><b>9</b> creatives</span><span><b>17/17</b> compliant</span></div><div className="bm-mini-wall"><article className="portrait"><label>240×400 · Yandex</label><div><b>MOVE<br/>FASTER.</b><small>New collection</small></div></article><article className="landscape"><label>728×90 · AdRiver</label><div><b>MOVE FASTER.</b><small>New collection →</small></div></article><article><label>300×250 · 4 placements</label><div><b>MOVE<br/>FASTER.</b><small>New collection</small></div></article></div></div></div></div>
   </section>
   <section className="bm-mkt-strip"><span>MEDIA PLAN</span><ArrowRight/><span>TT INTELLIGENCE</span><ArrowRight/><span>FIGMA CREATIVE</span><ArrowRight/><span>LIVE COMPLIANCE</span><ArrowRight/><span>DELIVERY</span></section>
   <section id="product" className="bm-mkt-section"><div className="bm-section-intro"><span className="bm-eyebrow">{ru?'НЕ ЕЩЁ ОДИН RESIZER':'NOT ANOTHER RESIZER'}</span><h2>{ru?'Система понимает, что именно нужно произвести.':'The system understands what actually needs to be produced.'}</h2><p>{ru?'Один размер может участвовать в нескольких размещениях с разными ТТ. Bannermatic сохраняет один visual creative и несколько независимых delivery contexts.':'One size can serve several placements with different requirements. Bannermatic keeps one visual creative and multiple independent delivery contexts.'}</p></div><div className="bm-feature-grid"><article><FileSpreadsheet/><span>01</span><h3>Campaign Compiler</h3><p>{ru?'Импортирует медиаплан, находит placements, дедуплицирует размеры и строит production plan.':'Imports the media plan, resolves placements, deduplicates sizes and builds the production plan.'}</p></article><article><Layers3/><span>02</span><h3>Figma Creative</h3><p>{ru?'Master, AI adaptation, animation и ручные overrides остаются редактируемыми в Figma.':'Master, AI adaptation, animation and manual overrides remain editable in Figma.'}</p></article><article><ShieldCheck/><span>03</span><h3>Live Compliance</h3><p>{ru?'Каждый placement получает собственный readiness: TT, duration, ZIP, tracking и delivery status.':'Every placement gets its own readiness state: TT, duration, ZIP, tracking and delivery status.'}</p></article></div></section>
   <section id="workflow" className="bm-mkt-section bm-workflow"><div className="bm-section-intro"><span className="bm-eyebrow">WORKFLOW</span><h2>{ru?'Один поток вместо папок, таблиц и ручной проверки.':'One connected flow instead of folders, sheets and manual QA.'}</h2></div><div className="bm-steps">{[['01',ru?'Загрузите медиаплан':'Attach media plan'],['02',ru?'Проверьте TT и conflicts':'Review TT & conflicts'],['03',ru?'Создайте creative в Figma':'Build creative in Figma'],['04',ru?'Смотрите всю кампанию':'Review the whole campaign'],['05',ru?'Соберите delivery build':'Build delivery']].map(([n,s])=><div key={n}><span>{n}</span><b>{s}</b></div>)}</div></section>
   <section id="wall" className="bm-mkt-section bm-wall-story"><div><span className="bm-eyebrow">CAMPAIGN WALL</span><h2>{ru?'Вся кампания играет перед вами одновременно.':'See the whole campaign play at once.'}</h2><p>{ru?'Не набор файлов. Живая стена форматов с названиями placements, общим playback и readiness каждого размещения.':'Not a folder of files. A live wall of formats with placement labels, synchronized playback and readiness for every delivery.'}</p><button className="bm-primary" onClick={onStart}>{ru?'Создать первую кампанию':'Create your first campaign'}<ArrowRight size={15}/></button></div><div className="bm-wall-abstract"><span>240×400</span><span>300×250</span><span>728×90</span><span>160×600</span><span>970×250</span></div></section>
  </main><footer className="bm-mkt-footer"><div className="bm-mkt-brand"><span>B</span><b>Bannermatic</b></div><p>Campaign Compiler for Figma · MVP2</p></footer>
 </div>
}
