import {ArrowRight,Check,FileSpreadsheet,Layers3,Play,ShieldCheck,Sparkles} from 'lucide-react';
import type {Locale} from './i18n';

export default function MarketingHome({locale,onLocale,onSignIn,onStart}:{locale:Locale;onLocale:(l:Locale)=>void;onSignIn:()=>void;onStart:()=>void}){
 const ru=locale==='ru';
 return <div className="ne-public">
  <header className="ne-public-nav"><a className="ne-public-brand" href="#top"><i>B</i><b>Bannermatic</b></a><nav><a href="#product">{ru?'Продукт':'Product'}</a><a href="#workflow">{ru?'Как работает':'Workflow'}</a><a href="#wall">Campaign Wall</a></nav><div className="ne-public-actions"><div className="ne-public-locale"><button className={!ru?'on':''} onClick={()=>onLocale('en')}>EN</button><button className={ru?'on':''} onClick={()=>onLocale('ru')}>RU</button></div><button className="ne-public-button" onClick={onSignIn}>{ru?'Войти':'Sign in'}</button><button className="ne-public-button primary" onClick={onStart}>{ru?'Начать':'Get started'}<ArrowRight size={14}/></button></div></header>
  <main id="top">
   <section className="ne-public-hero"><div className="ne-public-hero-copy"><span className="ne-public-pill"><Sparkles size={12}/>{ru?'CAMPAIGN COMPILER ДЛЯ FIGMA':'CAMPAIGN COMPILER FOR FIGMA'}</span><h1>{ru?'Из медиаплана — в готовую рекламную кампанию.':'From media plan to a production-ready campaign.'}</h1><p>{ru?'Bannermatic понимает placements и ТТ, создаёт нужный набор форматов в Figma, синхронизирует creative и проверяет готовность каждого placement перед delivery.':'Bannermatic understands placements and technical requirements, creates the right Figma formats, keeps creative in sync and validates every placement before delivery.'}</p><div className="ne-public-hero-actions"><button className="ne-public-button primary" onClick={onStart}>{ru?'Скомпилировать кампанию':'Compile your campaign'}<ArrowRight size={14}/></button><a className="ne-public-button" href="#wall"><Play size={13}/>{ru?'Посмотреть Campaign Wall':'See Campaign Wall'}</a></div></div>
    <div className="ne-public-preview" aria-label="Illustrative Bannermatic product preview"><div className="ne-preview-bar"><i/><i/><i/><span>Demo campaign / Product launch</span></div><div className="ne-preview-layout"><aside className="ne-preview-sidebar"><b>Bannermatic</b><span>Campaigns</span><span className="active">Overview</span><span>Media Plan</span><span>Creative</span><span>TT & Delivery</span></aside><div className="ne-preview-main"><div className="ne-preview-heading"><div><small>Campaign wall · demo</small><strong>Product Launch</strong></div><button>▶ Play all</button></div><div className="ne-preview-stats"><div><span>Placements</span><b>17</b></div><div><span>Unique creatives</span><b>9</b></div><div><span>Ready</span><b>17/17</b></div><div><span>Unknown</span><b>0</b></div></div><div className="ne-preview-cards"><article className="ne-preview-card"><label>240×400 · Placement A</label><div className="ne-preview-ad"><b>MOVE<br/>FASTER.</b></div></article><article className="ne-preview-card wide"><label>728×90 · Placement B</label><div className="ne-preview-ad"><b>MOVE FASTER.</b></div></article><article className="ne-preview-card"><label>300×250 · 4 placements</label><div className="ne-preview-ad"><b>MOVE<br/>FASTER.</b></div></article></div></div></div></div>
   </section>
   <section className="ne-public-flow"><div><span>MEDIA PLAN</span><ArrowRight size={12}/><span>TT INTELLIGENCE</span><ArrowRight size={12}/><span>FIGMA CREATIVE</span><ArrowRight size={12}/><span>LIVE COMPLIANCE</span><ArrowRight size={12}/><span>DELIVERY</span></div></section>
   <section id="product" className="ne-public-section"><div className="ne-public-section-head"><span className="ne-public-kicker">{ru?'НЕ ЕЩЁ ОДИН RESIZER':'NOT ANOTHER RESIZER'}</span><h2>{ru?'Система понимает, что именно нужно произвести.':'The system understands what actually needs to be produced.'}</h2><p>{ru?'Один размер может участвовать в нескольких размещениях с разными ТТ. Bannermatic сохраняет один visual creative и несколько независимых delivery contexts.':'One size can serve several placements with different requirements. Bannermatic keeps one visual creative and multiple independent delivery contexts.'}</p></div><div className="ne-public-grid"><article className="ne-public-card"><FileSpreadsheet size={18}/><small>01</small><h3>Campaign Compiler</h3><p>{ru?'Импортирует медиаплан, находит placements, дедуплицирует размеры и строит production plan.':'Imports the media plan, resolves placements, deduplicates sizes and builds the production plan.'}</p></article><article className="ne-public-card"><Layers3 size={18}/><small>02</small><h3>Figma Creative</h3><p>{ru?'Master, AI adaptation, animation и ручные overrides остаются редактируемыми в Figma.':'Master, AI adaptation, animation and manual overrides remain editable in Figma.'}</p></article><article className="ne-public-card"><ShieldCheck size={18}/><small>03</small><h3>Live Compliance</h3><p>{ru?'Каждый placement получает собственный readiness: TT, duration, ZIP, tracking и delivery status.':'Every placement gets its own readiness state: TT, duration, ZIP, tracking and delivery status.'}</p></article></div></section>
   <section id="workflow" className="ne-public-section"><div className="ne-public-section-head"><span className="ne-public-kicker">WORKFLOW</span><h2>{ru?'Один поток вместо папок, таблиц и ручной проверки.':'One connected flow instead of folders, sheets and manual QA.'}</h2></div><div className="ne-public-steps">{[['01',ru?'Загрузите медиаплан':'Attach media plan'],['02',ru?'Проверьте TT и conflicts':'Review TT & conflicts'],['03',ru?'Создайте creative в Figma':'Build creative in Figma'],['04',ru?'Смотрите всю кампанию':'Review the whole campaign'],['05',ru?'Соберите delivery build':'Build delivery']].map(([n,s])=><div className="ne-public-step" key={n}><span>{n}</span><b>{s}</b></div>)}</div></section>
   <section id="wall" className="ne-public-section"><div className="ne-public-section-head"><span className="ne-public-kicker">CAMPAIGN WALL</span><h2>{ru?'Вся кампания играет перед вами одновременно.':'See the whole campaign play at once.'}</h2><p>{ru?'Не набор файлов. Живая стена форматов с названиями placements, общим playback и readiness каждого размещения.':'Not a folder of files. A live wall of formats with placement labels, synchronized playback and readiness for every delivery.'}</p><div style={{marginTop:20}}><button className="ne-public-button primary" onClick={onStart}>{ru?'Создать первую кампанию':'Create your first campaign'}<ArrowRight size={14}/></button></div></div></section>
  </main><footer className="ne-public-footer"><div className="ne-public-brand"><i>B</i><b>Bannermatic</b></div><span>Campaign Compiler for Figma</span></footer>
 </div>
}
