import {useRef,useState} from 'react';
import {ArrowRight,CheckCircle2,FileSpreadsheet,RefreshCcw,Upload,X} from 'lucide-react';
import {processDeliveryInput} from '../campaign/deliveryPlan';
import {api} from './api';
import {compileVisualFormats,type Campaign,type Placement} from './domain';
import {diffMediaPlan,preserveVisualsForPlan,type MediaPlanDiff} from './planDiff';
import type {Locale} from './i18n';
import ManualCampaignSetup from './ManualCampaignSetup';

type Pending={placements:Placement[];diff:MediaPlanDiff;sourceNames:string[];needsAi:number};
type EntryMode='plan'|'manual';
function toPlacements(plan:any):Placement[]{return (plan.placements||[]).map((p:any)=>({id:p.id,platform:p.platform||'Unknown platform',placement:p.source||p.placement||'Placement',width:Number(p.width),height:Number(p.height),creativeType:p.creativeType,requirements:{...p.requirements,sourceUrl:p.ttUrl,sourceLabel:p.ttUrl?'Imported TT link':'Imported media plan'}}));}

export default function MediaPlanWorkspace({campaign,locale,canEdit,onUpdated,onError}:{campaign:Campaign;locale:Locale;canEdit:boolean;onUpdated:(c:Campaign)=>void;onError:(s:string)=>void}){
 const input=useRef<HTMLInputElement>(null);const [mode,setMode]=useState<EntryMode>('plan'),[pending,setPending]=useState<Pending|null>(null),[busy,setBusy]=useState(false),[done,setDone]=useState('');const ru=locale==='ru';
 const pick=()=>input.current?.click();
 const parse=async(files:FileList|null)=>{if(!files?.length||!canEdit)return;setBusy(true);setDone('');onError('');try{const list=Array.from(files),plan=await processDeliveryInput(list),placements=toPlacements(plan),diff=diffMediaPlan(campaign.placements,placements);setPending({placements,diff,sourceNames:list.map(f=>f.name),needsAi:Number(plan.needsAi||0)})}catch(e){onError(e instanceof Error?e.message:String(e))}finally{setBusy(false);if(input.current)input.current.value=''}};
 const apply=async()=>{if(!pending||!canEdit)return;setBusy(true);onError('');try{const compiled=compileVisualFormats(pending.placements,campaign.formats),formats=preserveVisualsForPlan(compiled,campaign.formats),next=await api.updateCampaign(campaign.id,{placements:pending.placements,formats,status:'media-ready',mediaPlanVersion:Number(campaign.mediaPlanVersion||0)+1});onUpdated(next);setDone(`${pending.placements.length} placements → ${formats.length} unique creatives`);setPending(null)}catch(e){onError(e instanceof Error?e.message:String(e))}finally{setBusy(false)}};
 const d=pending?.diff;
 return <section className="ne-workspace-page"><div className="ne-workspace-header"><div><div className="ne-kicker">Campaign Compiler</div><h1>{ru?'Кампания и медиаплан':'Campaign Plan'}</h1><p>{ru?'Импорт и ручная настройка работают с одной placement-моделью. Перед применением Bannermatic всегда показывает изменения.':'Import and manual setup use the same placement model. Bannermatic always shows changes before applying them.'}</p></div>{mode==='plan'&&<><button className="ne-button primary" onClick={pick} disabled={!canEdit||busy}><Upload size={14}/>{campaign.placements.length?(ru?'Загрузить новую версию':'Import new version'):(ru?'Загрузить медиаплан':'Attach media plan')}</button><input ref={input} hidden type="file" multiple accept=".xlsx,.csv,.tsv,.txt,.docx,.pdf" onChange={e=>void parse(e.target.files)}/></>}</div><div className="ne-tabs"><button className={mode==='plan'?'active':''} onClick={()=>setMode('plan')}>{ru?'Медиаплан / TT':'Media Plan / TT'}</button><button className={mode==='manual'?'active':''} onClick={()=>setMode('manual')}>{ru?'Вручную':'Manual setup'}</button></div>{mode==='manual'?<ManualCampaignSetup campaign={campaign} locale={locale} canEdit={canEdit} onUpdated={onUpdated} onError={onError}/>:<>{done&&<div className="ne-notice"><CheckCircle2 size={15}/><span>{done}</span></div>}
 {pending&&d&&<div className="ne-review"><div className="ne-review-head"><div><div className="ne-kicker">Review before compile</div><h2>{ru?'Изменения медиаплана':'Media plan changes'}</h2><p>{pending.sourceNames.join(', ')}</p></div><button className="ne-button" onClick={()=>setPending(null)}><X size={14}/>{ru?'Отмена':'Cancel'}</button></div><div className="ne-diff-grid"><article><b>+{d.added.length}</b><span>{ru?'новых placements':'added placements'}</span></article><article><b>−{d.removed.length}</b><span>{ru?'удалено':'removed'}</span></article><article><b>{d.changed.length}</b><span>{ru?'изменено':'changed'}</span></article><article><b>{d.requiredFormatsAdded.length}</b><span>{ru?'новых форматов':'new formats'}</span></article></div>{d.requiredFormatsAdded.length>0&&<div className="ne-review-row"><span>{ru?'Нужно создать в Figma':'New creative formats required'}</span><div>{d.requiredFormatsAdded.map(s=><em key={s}>+ {s}</em>)}</div></div>}{d.requiredFormatsRemoved.length>0&&<div className="ne-review-row"><span>{ru?'Больше не требуются':'No longer required by plan'}</span><div>{d.requiredFormatsRemoved.map(s=><em key={s}>− {s}</em>)}</div></div>}{pending.needsAi>0&&<div className="ne-review-warning">{ru?`${pending.needsAi} источник(а) требуют дополнительного TT/AI разбора.`:`${pending.needsAi} source(s) need additional TT/AI extraction.`}</div>}<div className="ne-review-actions"><span>{ru?'Существующие creative для совпадающих размеров сохранятся.':'Existing creative is preserved for sizes that remain required.'}</span><button className="ne-button primary" disabled={busy} onClick={()=>void apply()}>{busy?(ru?'Применяем…':'Applying…'):(ru?'Применить и скомпилировать':'Apply & compile')}<ArrowRight size={14}/></button></div></div>}
 {!pending&&(campaign.placements.length?<div className="ne-data-table"><div className="ne-data-head"><span>Platform</span><span>Placement</span><span>Format</span><span>TT source</span><span>Creative</span></div>{campaign.placements.map(p=>{const f=campaign.formats.find(x=>x.placementIds.includes(p.id));const state=f?.creativeState||'missing';return <div className="ne-data-row" key={p.id}><b>{p.platform}</b><span>{p.placement}</span><span>{p.width}×{p.height}</span><span>{p.requirements.sourceLabel||'Unknown'}</span><em className={`ne-status ${state==='published'?'ready':state==='draft'?'warning':'blocked'}`}>{state}</em></div>})}</div>:<div className="ne-empty"><div className="ne-empty-inner"><div className="ne-empty-icon"><FileSpreadsheet size={18}/></div><h3>{ru?'Начните с реального медиаплана':'Start with a real media plan'}</h3><p>{ru?'Excel/CSV превращается в placements и уникальный creative set. Повторный импорт всегда проходит через diff.':'Excel/CSV becomes placements and a unique creative set. Every re-import is reviewed as a diff.'}</p><button className="ne-button primary" disabled={!canEdit} onClick={pick}><FileSpreadsheet size={14}/>{ru?'Выбрать файл':'Choose file'}</button></div></div>)}
 {campaign.placements.length>0&&!pending&&<div className="ne-version"><RefreshCcw size={12}/><span>Media Plan v{campaign.mediaPlanVersion||0}</span><b>{campaign.placements.length} placements · {campaign.formats.length} unique creatives</b></div>}</>}</section>;
}
