import {useMemo,useRef,useState} from 'react';
import {ArrowRight,CheckCircle2,ChevronDown,Columns3,FileSpreadsheet,RefreshCcw,Search,Upload,X} from 'lucide-react';
import {processDeliveryInput} from '../campaign/deliveryPlan';
import {api} from './api';
import {compileVisualFormats,formatRequirementBadges,normalizedExportScale,type Campaign,type ExportType,type Placement,type VisualFormat} from './domain';
import {diffMediaPlan,placementKey,preserveVisualsForPlan,type MediaPlanDiff} from './planDiff';
import type {Locale} from './i18n';
import ManualCampaignSetup from './ManualCampaignSetup';

type Pending={placements:Placement[];diff:MediaPlanDiff;sourceNames:string[];needsAi:number;errors:string[]};
type EntryMode='plan'|'manual';
type CreativeFilter='all'|'ready'|'attention'|'missing';

const hasKnownTT=(p:Placement)=>Boolean(p.requirements.sourceUrl||p.requirements.sourceLabel&&!String(p.requirements.sourceLabel).toLowerCase().startsWith('unknown'));
const formatFor=(campaign:Campaign,p:Placement)=>campaign.formats.find(f=>f.placementIds.includes(p.id));
const creativeFilterFor=(format?:VisualFormat):CreativeFilter=>format?.creativeState==='published'?'ready':format?.creativeState==='draft'?'attention':'missing';

function toPlacements(plan:any):Placement[]{return (plan.placements||[]).map((p:any)=>({id:p.id,platform:p.platform||'Unknown platform',placement:p.placement||p.source||'Placement',width:Number(p.width),height:Number(p.height),creativeType:p.creativeType,language:p.language,reviewIssues:p.reviewIssues,requirements:{...p.requirements,exportScale:normalizedExportScale(p.exportScale??p.requirements?.exportScale),exportType:(p.exportType??p.requirements?.exportType) as ExportType|undefined,sourceUrl:p.ttUrl,sourceLabel:p.source||'Imported media plan'}}));}

export default function MediaPlanWorkspace({campaign,locale,canEdit,onUpdated,onError,onOpenCreative}:{campaign:Campaign;locale:Locale;canEdit:boolean;onUpdated:(c:Campaign)=>void;onError:(s:string)=>void;onOpenCreative:()=>void}){
 const input=useRef<HTMLInputElement>(null);
 const [mode,setMode]=useState<EntryMode>(()=>new URLSearchParams(location.search).get('mode')==='manual'?'manual':'plan'),[pending,setPending]=useState<Pending|null>(null),[busy,setBusy]=useState(false),[done,setDone]=useState('');
 const [query,setQuery]=useState(''),[creativeFilter,setCreativeFilter]=useState<CreativeFilter>('all'),[showRequirements,setShowRequirements]=useState(true);
 const ru=locale==='ru';
 const pick=()=>input.current?.click();
 const parse=async(files:FileList|null)=>{if(!files?.length||!canEdit)return;setBusy(true);setDone('');onError('');try{const list=Array.from(files),plan=await processDeliveryInput(list),placements=toPlacements(plan).map(p=>{const old=campaign.placements.find(x=>placementKey(x)===placementKey(p));return old?{...p,id:old.id,contentVariantIds:old.contentVariantIds}:p}),diff=diffMediaPlan(campaign.placements,placements);setPending({placements,diff,sourceNames:list.map(f=>f.name),needsAi:Number(plan.needsAi||0),errors:plan.sources.filter(s=>s.status==='error').map(s=>s.name+': '+s.detail)})}catch(e){onError(e instanceof Error?e.message:String(e))}finally{setBusy(false);if(input.current)input.current.value=''}};
 const apply=async()=>{if(!pending||!canEdit||!pending.placements.length||pending.errors.length||pending.needsAi||pending.placements.some(p=>p.width<1||p.height<1||p.reviewIssues?.length))return;setBusy(true);onError('');try{const compiled=compileVisualFormats(pending.placements,campaign.formats),formats=preserveVisualsForPlan(compiled,campaign.formats),next=await api.updateCampaign(campaign.id,{placements:pending.placements,formats,status:'media-ready',mediaPlanVersion:Number(campaign.mediaPlanVersion||0)+1});onUpdated(next);setDone(`${pending.placements.length} placements → ${formats.length} unique creatives`);setPending(null)}catch(e){onError(e instanceof Error?e.message:String(e))}finally{setBusy(false)}};
 const d=pending?.diff;
 const updateRow=(id:string,field:string,value:string)=>{if(!pending)return;const placements=pending.placements.map(p=>{if(p.id!==id)return p;if(field==='width'||field==='height')return {...p,[field]:Number(value)};if(field.startsWith('requirements.')){const key=field.split('.')[1];return {...p,requirements:{...p.requirements,[key]:key==='maxZipKb'||key==='maxDurationSec'?(value?Number(value):undefined):key==='exportScale'?normalizedExportScale(value):value}}}return {...p,[field]:value}});setPending({...pending,placements,diff:diffMediaPlan(campaign.placements,placements)})};
 const blocked=!pending?.placements.length||Boolean(pending?.errors.length||pending?.needsAi||pending?.placements.some(p=>p.width<1||p.height<1||p.reviewIssues?.length));
 const groups=useMemo(()=>{const needle=query.trim().toLowerCase(),map=new Map<string,Placement[]>();for(const p of campaign.placements){const format=formatFor(campaign,p),state=creativeFilterFor(format);if(creativeFilter!=='all'&&state!==creativeFilter)continue;const haystack=[p.platform,p.placement,p.width+'x'+p.height,p.requirements.sourceLabel,format?.creativeState].join(' ').toLowerCase();if(needle&&!haystack.includes(needle))continue;map.set(p.platform,[...(map.get(p.platform)||[]),p])}return [...map.entries()].sort(([a],[b])=>a.localeCompare(b));},[campaign,query,creativeFilter]);
 const visibleCount=groups.reduce((sum,[,placements])=>sum+placements.length,0);
 const readyCount=campaign.placements.filter(p=>creativeFilterFor(formatFor(campaign,p))==='ready'&&hasKnownTT(p)).length;

 return <section className="ne-workspace-page">
  <div className="ne-workspace-header"><div><div className="ne-kicker">Campaign Compiler</div><h1>{ru?'Кампания и медиаплан':'Campaign Plan'}</h1><p>{ru?'Импорт и ручная настройка работают с одной placement-моделью. Перед применением Bannermatic всегда показывает изменения.':'Import and manual setup use the same placement model. Bannermatic always shows changes before applying them.'}</p></div>{mode==='plan'&&<><button className="ne-button primary" onClick={pick} disabled={!canEdit||busy}><Upload size={14}/>{campaign.placements.length?(ru?'Загрузить новую версию':'Import new version'):(ru?'Загрузить медиаплан':'Attach media plan')}</button><input ref={input} hidden type="file" multiple accept=".xlsx,.csv,.tsv,.txt,.docx,.pdf" onChange={e=>void parse(e.target.files)}/></>}</div>
  <div className="ne-tabs"><button className={mode==='plan'?'active':''} onClick={()=>setMode('plan')}>{ru?'Медиаплан / TT':'Media Plan / TT'}</button><button className={mode==='manual'?'active':''} onClick={()=>setMode('manual')}>{ru?'Вручную':'Manual setup'}</button></div>
  {mode==='manual'?<ManualCampaignSetup campaign={campaign} locale={locale} canEdit={canEdit} onUpdated={onUpdated} onError={onError}/>:<>
   {done&&<div className="ne-notice"><CheckCircle2 size={15}/><span>{done}</span></div>}
   {pending&&d&&<div className="ne-review"><div className="ne-review-head"><div><div className="ne-kicker">Review before compile</div><h2>{ru?'Изменения медиаплана':'Media plan changes'}</h2><p>{pending.sourceNames.join(', ')}</p></div><button className="ne-button" onClick={()=>setPending(null)}><X size={14}/>{ru?'Отмена':'Cancel'}</button></div><div className="ne-diff-grid"><article><b>+{d.added.length}</b><span>{ru?'новых placements':'added placements'}</span></article><article><b>−{d.removed.length}</b><span>{ru?'удалено':'removed'}</span></article><article><b>{d.changed.length}</b><span>{ru?'изменено':'changed'}</span></article><article><b>{d.requiredFormatsAdded.length}</b><span>{ru?'новых форматов':'new formats'}</span></article></div>{d.requiredFormatsAdded.length>0&&<div className="ne-review-row"><span>{ru?'Нужно создать в Figma':'New creative formats required'}</span><div>{d.requiredFormatsAdded.map(s=><em key={s}>+ {s}</em>)}</div></div>}{d.requiredFormatsRemoved.length>0&&<div className="ne-review-row"><span>{ru?'Больше не требуются':'No longer required by plan'}</span><div>{d.requiredFormatsRemoved.map(s=><em key={s}>− {s}</em>)}</div></div>}{pending.needsAi>0&&<div className="ne-review-warning">{ru?`${pending.needsAi} источник(а) требуют дополнительного TT/AI разбора.`:`${pending.needsAi} source(s) need additional TT/AI extraction.`}</div>}<div className="vnext-matrix"><table><thead><tr>{['Platform','Placement','Width','Height','Scale','Type','Max KB','Duration','Click URL','Legal'].map(h=><th key={h}>{h}</th>)}</tr></thead><tbody>{pending.placements.map(p=><tr key={p.id}>{['platform','placement','width','height','requirements.exportScale','requirements.exportType','requirements.maxZipKb','requirements.maxDurationSec','requirements.clickUrl','requirements.legal'].map(field=><td key={field}><input aria-label={`${p.placement} ${field}`} value={String(field.startsWith('requirements.')?(p.requirements as any)[field.split('.')[1]]??'':(p as any)[field]??'')} onChange={e=>updateRow(p.id,field,e.target.value)}/></td>)}</tr>)}</tbody></table></div>{pending.errors.map(e=><p className="vnext-issue" key={e}>{e}</p>)}{pending.placements.filter(p=>p.reviewIssues?.length).map(p=><div className="vnext-review" key={p.id}><b>{p.platform} · {p.placement}</b>{p.reviewIssues?.map((issue,i)=><p key={i}>{issue}</p>)}<button className="ne-button" onClick={()=>setPending({...pending,placements:pending.placements.map(x=>x.id===p.id?{...x,reviewIssues:[]}:x)})}>{ru?'Проверено и исправлено':'Reviewed and corrected'}</button></div>)}<div className="ne-review-actions"><span>{ru?'Существующие creative для совпадающих размеров сохранятся.':'Existing creative is preserved for sizes that remain required.'}</span><button className="ne-button primary" disabled={busy||blocked} onClick={()=>void apply()}>{busy?(ru?'Применяем…':'Applying…'):(ru?'Применить и скомпилировать':'Apply & compile')}<ArrowRight size={14}/></button></div></div>}
   {!pending&&(campaign.placements.length?<div className="ne-plan-grid-shell">
    <div className="ne-plan-summary"><div><strong>{campaign.placements.length}</strong><span>{ru?'размещений':'placements'}</span></div><div><strong>{campaign.formats.length}</strong><span>{ru?'уникальных форматов':'unique formats'}</span></div><div><strong>{readyCount}/{campaign.placements.length}</strong><span>{ru?'готово к delivery':'delivery ready'}</span></div><div><strong>v{campaign.mediaPlanVersion||0}</strong><span>{ru?'версия медиаплана':'media plan version'}</span></div></div>
    <div className="ne-plan-toolbar"><label className="ne-plan-search"><Search size={14}/><input aria-label={ru?'Поиск по медиаплану':'Search media plan'} value={query} onChange={e=>setQuery(e.target.value)} placeholder={ru?'Платформа, placement, формат…':'Platform, placement, format…'}/></label><label className="ne-plan-filter"><span>Creative</span><select aria-label={ru?'Фильтр состояния creative':'Creative status filter'} value={creativeFilter} onChange={e=>setCreativeFilter(e.target.value as CreativeFilter)}><option value="all">{ru?'Все состояния':'All states'}</option><option value="ready">{ru?'Опубликовано':'Published'}</option><option value="attention">{ru?'Черновик':'Draft'}</option><option value="missing">{ru?'Не создано':'Missing'}</option></select><ChevronDown size={13}/></label><button className={`ne-plan-columns${showRequirements?' active':''}`} onClick={()=>setShowRequirements(v=>!v)} aria-pressed={showRequirements}><Columns3 size={14}/>{ru?'TT и лимиты':'TT & limits'}</button><span className="ne-plan-visible">{visibleCount} / {campaign.placements.length}</span></div>
    <div className="ne-plan-table-wrap"><table className={`ne-plan-table${showRequirements?'':' compact'}`}><thead><tr><th>{ru?'Размещение':'Placement'}</th><th>{ru?'Формат':'Format'}</th>{showRequirements&&<><th>TT</th><th>{ru?'Экспорт':'Export'}</th><th>ZIP</th><th>{ru?'Длительность':'Duration'}</th></>}<th>{ru?'Контент':'Content'}</th><th>Creative</th></tr></thead><tbody>{groups.map(([platform,placements])=><FragmentGroup key={platform} platform={platform} placements={placements} campaign={campaign} showRequirements={showRequirements} ru={ru} onOpenCreative={onOpenCreative}/>)}</tbody></table>{!visibleCount&&<div className="ne-plan-no-results"><Search size={18}/><b>{ru?'Ничего не найдено':'No placements found'}</b><span>{ru?'Измените поиск или фильтр состояния.':'Change the search or status filter.'}</span></div>}</div>
   </div>:<div className="ne-empty"><div className="ne-empty-inner"><div className="ne-empty-icon"><FileSpreadsheet size={18}/></div><h3>{ru?'Начните с реального медиаплана':'Start with a real media plan'}</h3><p>{ru?'Excel/CSV превращается в placements и уникальный creative set. Повторный импорт всегда проходит через diff.':'Excel/CSV becomes placements and a unique creative set. Every re-import is reviewed as a diff.'}</p><button className="ne-button primary" disabled={!canEdit} onClick={pick}><FileSpreadsheet size={14}/>{ru?'Выбрать файл':'Choose file'}</button></div></div>)}
   {campaign.placements.length>0&&!pending&&<div className="ne-version"><RefreshCcw size={12}/><span>Media Plan v{campaign.mediaPlanVersion||0}</span><b>{campaign.placements.length} placements · {campaign.formats.length} unique creatives</b></div>}
  </>}
 </section>;
}

function FragmentGroup({platform,placements,campaign,showRequirements,ru,onOpenCreative}:{platform:string;placements:Placement[];campaign:Campaign;showRequirements:boolean;ru:boolean;onOpenCreative:()=>void}){
 const columns=showRequirements?8:4;
 return <><tr className="ne-plan-group"><th colSpan={columns}><span>{platform}</span><em>{placements.length} {ru?'размещений':'placements'}</em></th></tr>{placements.map(p=>{const format=formatFor(campaign,p),state=creativeFilterFor(format),known=hasKnownTT(p);return <tr key={p.id}><td><b>{p.placement}</b><small>{p.creativeType||(ru?'Баннер':'Banner')}</small></td><td><strong>{p.width}×{p.height}</strong><small>{p.language?.toUpperCase()||campaign.locale.toUpperCase()}</small></td>{showRequirements&&<><td><span className={`ne-tt-state ${known?'known':'unknown'}`}>{known?(ru?'Проверено':'Known'):(ru?'Уточнить':'Review')}</span><small title={p.requirements.sourceLabel}>{p.requirements.sourceLabel||'Unknown'}</small></td><td><div className="ne-format-badges">{formatRequirementBadges(format||{exportScale:normalizedExportScale(p.requirements.exportScale),maxBytes:p.requirements.maxZipKb?Number(p.requirements.maxZipKb)*1000:undefined,exportType:p.requirements.exportType||undefined}).map(b=><em key={b}>{b}</em>)}</div></td><td><strong>{p.requirements.maxZipKb?`≤ ${p.requirements.maxZipKb} KB`:'—'}</strong></td><td><strong>{p.requirements.maxDurationSec?`≤ ${p.requirements.maxDurationSec}s`:'—'}</strong></td></>}<td><strong>{p.contentVariantIds?.length||0}</strong><small>{ru?'вариантов':'variants'}</small></td><td><button className="ne-creative-link" onClick={onOpenCreative}><span className={`ne-status ${state==='ready'?'ready':state==='attention'?'warning':'blocked'}`}>{format?.creativeState||'missing'}</span><small>{format?`${format.size} · v${format.creativeVersion}`:(ru?'Открыть Creative':'Open Creative')}</small></button></td></tr>})}</>;
}
