import {useRef,useState} from 'react';
import {ArrowRight,CheckCircle2,FileSpreadsheet,RefreshCcw,Upload,X} from 'lucide-react';
import {processDeliveryInput} from '../campaign/deliveryPlan';
import {api} from './api';
import {compileVisualFormats,type Campaign,type Placement} from './domain';
import {diffMediaPlan,preserveVisualsForPlan,type MediaPlanDiff} from './planDiff';
import type {Locale} from './i18n';

type Pending={placements:Placement[];diff:MediaPlanDiff;sourceNames:string[];needsAi:number};

function toPlacements(plan:any):Placement[]{return (plan.placements||[]).map((p:any)=>({id:p.id,platform:p.platform||'Unknown platform',placement:p.source||p.placement||'Placement',width:Number(p.width),height:Number(p.height),creativeType:p.creativeType,requirements:{...p.requirements,sourceUrl:p.ttUrl,sourceLabel:p.ttUrl?'Imported TT link':'Imported media plan'}}));}

export default function MediaPlanWorkspace({campaign,locale,canEdit,onUpdated,onError}:{campaign:Campaign;locale:Locale;canEdit:boolean;onUpdated:(c:Campaign)=>void;onError:(s:string)=>void}){
 const input=useRef<HTMLInputElement>(null);const [pending,setPending]=useState<Pending|null>(null),[busy,setBusy]=useState(false),[done,setDone]=useState('');const ru=locale==='ru';
 const pick=()=>input.current?.click();
 const parse=async(files:FileList|null)=>{if(!files?.length||!canEdit)return;setBusy(true);setDone('');onError('');try{const list=Array.from(files),plan=await processDeliveryInput(list),placements=toPlacements(plan),diff=diffMediaPlan(campaign.placements,placements);setPending({placements,diff,sourceNames:list.map(f=>f.name),needsAi:Number(plan.needsAi||0)})}catch(e){onError(e instanceof Error?e.message:String(e))}finally{setBusy(false);if(input.current)input.current.value=''}};
 const apply=async()=>{if(!pending||!canEdit)return;setBusy(true);onError('');try{const compiled=compileVisualFormats(pending.placements,campaign.formats),formats=preserveVisualsForPlan(compiled,campaign.formats),next=await api.updateCampaign(campaign.id,{placements:pending.placements,formats,status:'media-ready',mediaPlanVersion:Number(campaign.mediaPlanVersion||0)+1});onUpdated(next);setDone(`${pending.placements.length} placements → ${formats.length} unique creatives`);setPending(null)}catch(e){onError(e instanceof Error?e.message:String(e))}finally{setBusy(false)}};
 const d=pending?.diff;
 return <section className="bm-page"><div className="bm-page-head"><div><span className="bm-eyebrow">CAMPAIGN COMPILER</span><h1>{ru?'Медиаплан':'Media Plan'}</h1><p>{ru?'Сначала Bannermatic показывает, что изменится. Ничего не применяется молча.':'Bannermatic shows the change set before applying it. Nothing is changed silently.'}</p></div><button className="bm-primary" onClick={pick} disabled={!canEdit||busy}><Upload size={15}/>{campaign.placements.length?(ru?'Загрузить новую версию':'Import new version'):(ru?'Загрузить медиаплан':'Attach media plan')}</button><input ref={input} hidden type="file" multiple accept=".xlsx,.csv,.tsv,.txt,.docx,.pdf" onChange={e=>void parse(e.target.files)}/></div>{done&&<div className="bm-notice"><CheckCircle2 size={16}/><span>{done}</span></div>}
 {pending&&d&&<div className="bm-review bm-surface"><div className="bm-review-head"><div><span className="bm-eyebrow">REVIEW BEFORE COMPILE</span><h2>{ru?'Изменения медиаплана':'Media plan changes'}</h2><p>{pending.sourceNames.join(', ')}</p></div><button className="bm-ghost" onClick={()=>setPending(null)}><X size={15}/>{ru?'Отмена':'Cancel'}</button></div><div className="bm-diff-metrics"><article><b>+{d.added.length}</b><span>{ru?'новых placements':'added placements'}</span></article><article><b>−{d.removed.length}</b><span>{ru?'удалено':'removed'}</span></article><article><b>{d.changed.length}</b><span>{ru?'изменено':'changed'}</span></article><article><b>{d.requiredFormatsAdded.length}</b><span>{ru?'новых форматов':'new formats'}</span></article></div>{d.requiredFormatsAdded.length>0&&<div className="bm-review-row"><span>{ru?'Нужно создать в Figma':'New creative formats required'}</span><div>{d.requiredFormatsAdded.map(s=><em key={s}>+ {s}</em>)}</div></div>}{d.requiredFormatsRemoved.length>0&&<div className="bm-review-row muted"><span>{ru?'Больше не требуются':'No longer required by plan'}</span><div>{d.requiredFormatsRemoved.map(s=><em key={s}>− {s}</em>)}</div></div>}{pending.needsAi>0&&<div className="bm-review-warning">{ru?`${pending.needsAi} источник(а) требуют дополнительного TT/AI разбора.`:`${pending.needsAi} source(s) need additional TT/AI extraction.`}</div>}<div className="bm-review-actions"><span>{ru?'Существующие creative для совпадающих размеров сохранятся.':'Existing creative is preserved for sizes that remain required.'}</span><button className="bm-primary" disabled={busy} onClick={()=>void apply()}>{busy?(ru?'Применяем…':'Applying…'):(ru?'Применить и скомпилировать':'Apply & compile')}<ArrowRight size={15}/></button></div></div>}
 {!pending&&(campaign.placements.length?<div className="bm-table"><div className="bm-table-head"><span>Platform</span><span>Placement</span><span>Format</span><span>TT source</span><span>Creative</span></div>{campaign.placements.map(p=>{const f=campaign.formats.find(x=>x.placementIds.includes(p.id));return <div className="bm-table-row" key={p.id}><b>{p.platform}</b><span>{p.placement}</span><span>{p.width}×{p.height}</span><span>{p.requirements.sourceLabel||'Unknown'}</span><em className={`bm-status bm-${f?.creativeState==='published'?'ready':f?.creativeState==='draft'?'warning':'blocked'}`}>{f?.creativeState||'missing'}</em></div>})}</div>:<div className="bm-empty"><FileSpreadsheet size={30}/><h3>{ru?'Начните с реального медиаплана':'Start with a real media plan'}</h3><p>{ru?'Excel/CSV превращается в placements и уникальный creative set. Повторный импорт всегда проходит через diff.':'Excel/CSV becomes placements and a unique creative set. Every re-import is reviewed as a diff.'}</p><button className="bm-primary" disabled={!canEdit} onClick={pick}><FileSpreadsheet size={15}/>{ru?'Выбрать файл':'Choose file'}</button></div>)}
 {campaign.placements.length>0&&!pending&&<div className="bm-version-line"><RefreshCcw size={13}/><span>Media Plan v{campaign.mediaPlanVersion||0}</span><b>{campaign.placements.length} placements · {campaign.formats.length} unique creatives</b></div>}
 </section>;
}
