import {useState} from 'react';
import {api} from './api';
import {familyFor,renderTemplate,sourceFingerprint} from './production.mjs';
import type {Campaign} from './domain';
export default function TemplateWorkspace({campaign,ru,canEdit,onUpdated,onError}:{campaign:Campaign;ru:boolean;canEdit:boolean;onUpdated:(c:Campaign)=>void;onError:(s:string)=>void}){
 const [busy,setBusy]=useState(false),[review,setReview]=useState(false),[variantId,setVariantId]=useState(campaign.contentVariants?.[0]?.id||'');
 const content=campaign.contentVariants?.find(v=>v.id===variantId)||campaign.contentVariants?.[0];
 const affected=campaign.formats.filter(f=>f.sourceFingerprint!==sourceFingerprint(campaign,f));
 const locked=campaign.formats.some(f=>f.creativeState==='published'&&f.sourceType!=='template');
 const update=async(formatId:string,font:string)=>{if(!font||!Number.isFinite(Number(font)))return;setBusy(true);try{const formats=campaign.formats.map(f=>f.id===formatId?{...f,roleOverrides:{...f.roleOverrides,'headline.primary':{...f.roleOverrides?.['headline.primary'],fontSize:Number(font)}}}:f);onUpdated(await api.updateCampaign(campaign.id,{formats}));setReview(false)}catch(e){onError(String(e))}finally{setBusy(false)}};
 const publish=async()=>{setBusy(true);onError('');try{onUpdated(await api.publishTemplate(campaign.id));setReview(false)}catch(e){onError(String(e))}finally{setBusy(false)}};
 return <section className="ne-card"><div className="ne-page-head"><div><div className="ne-kicker">Template source · Type Retail</div><h2>{ru?'Типографическая кампания':'Typographic campaign'}</h2><p>{ru?'Отдельные композиции для Square, Portrait, Landscape и Strip. Проверяйте исключения перед экспортом.':'Separate compositions for Square, Portrait, Landscape and Strip. Review exceptions before export.'}</p></div><button className="ne-button primary" disabled={!canEdit||busy||!content||!campaign.formats.length||locked} onClick={()=>setReview(true)}>Publish Changes</button></div>
 {locked&&<p role="status">{ru?'В кампании опубликован Figma creative. Он сохранён; этот шаблон не заменяет его.':'This campaign has published Figma creative. This template will not replace it.'}</p>}
 {!content&&<p>{ru?'Сначала добавьте контент и назначения в Content.':'First add copy and assignments in Content.'}</p>}
 {content&&<label className="vnext-field"><span>{ru?'Предпросмотр варианта':'Preview content variant'}</span><select value={content.id} onChange={e=>setVariantId(e.target.value)}>{campaign.contentVariants?.map(v=><option key={v.id} value={v.id}>{v.name} · {v.language}</option>)}</select></label>}
 {review&&<div className="vnext-review" role="region" aria-label="Publish review"><h3>{ru?'Проверка публикации':'Review publication'}</h3><p>{ru?'Область: вся кампания.':'Scope: entire campaign.'} {affected.length} {ru?'изменённых форматов':'changed formats'} · {campaign.placements.reduce((n,p)=>n+(p.contentVariantIds?.length||0),0)} deliverables.</p><p>{ru?'Обновятся тексты и композиции шаблона. Локальные font-size overrides сохранятся. Проблемы Preflight блокируют экспорт.':'Template content and compositions will update. Local font-size overrides are retained. Preflight issues block export.'}</p><button className="ne-button primary" disabled={busy} onClick={()=>void publish()}>{ru?'Опубликовать':'Publish'}</button><button className="ne-button" onClick={()=>setReview(false)}>{ru?'Отмена':'Cancel'}</button></div>}
 <div className="vnext-preview-grid">{content&&campaign.formats.map(f=>{const result=renderTemplate(f,content,campaign.templateMotion??.8);return <article className="ne-card" key={f.id}><h3>{f.size} · {familyFor(f.width,f.height)}</h3><p>{f.sourceFingerprint!==sourceFingerprint(campaign,f)?'Outdated / unpublished':'Published'} · {result.productionIssues.length} {ru?'замечаний':'issues'}</p><div className="vnext-preview" style={{height:Math.min(f.height,320)}}><iframe title={`${f.size} ${content.name}`} sandbox="allow-scripts" srcDoc={result.previewHtml} style={{width:f.width,height:f.height,transform:`scale(${Math.min(1,300/f.width,320/f.height)})`,transformOrigin:'top left'}}/></div><label className="vnext-field"><span>headline.primary · Size override (px)</span><input key={`${f.id}-${f.roleOverrides?.['headline.primary']?.fontSize}`} type="number" min="12" max="100" disabled={!canEdit||busy||locked} defaultValue={f.roleOverrides?.['headline.primary']?.fontSize??''} placeholder="Linked" onBlur={e=>void update(f.id,e.target.value)}/></label>{result.productionIssues.map((i:any,n:number)=><p className="vnext-issue" key={n}>{i.detail}</p>)}</article>})}</div>
 </section>;
}
