const NS="banner_campaign";
const SLOT_CATALOG={background:{id:"background",label:"Background",kind:"visual",system:true},headline:{id:"headline",label:"Headline",kind:"text",system:true},copy:{id:"copy",label:"Copy",kind:"text",system:true},cta:{id:"cta",label:"CTA",kind:"visual",system:true,required:true},tracking_pixel:{id:"tracking_pixel",label:"Tracking pixel",kind:"technical",system:true,required:true,technical:true}};
const DEFAULT_SLOT_IDS=["background","headline","copy","cta","tracking_pixel"];
figma.showUI(__html__,{width:620,height:760,themeColors:true});
const meta=(n,k,v)=>n.setSharedPluginData(NS,k,String(v??""));
const getMeta=(n,k)=>n.getSharedPluginData(NS,k);
const copy=v=>v==null?v:JSON.parse(JSON.stringify(v));
const rgb=h=>{let v=String(h).replace("#","").trim();if(v.length===3)v=v.split("").map(c=>c+c).join("");return{r:parseInt(v.slice(0,2),16)/255,g:parseInt(v.slice(2,4),16)/255,b:parseInt(v.slice(4,6),16)/255}};
const familyFor=(w,h)=>h<=100||w/h>=3?"Strip":h>w?"Vertical":"Rectangle";
const defaultRegistry=()=>DEFAULT_SLOT_IDS.map(id=>copy(SLOT_CATALOG[id]));
const parseJson=(raw,fallback=[])=>{try{const v=JSON.parse(raw||"");return v??fallback}catch{return fallback}};
const ttReady=p=>{const r=p?.requirements||{};return Object.values(r).some(v=>v!==null&&v!==undefined&&v!=="")};
function formatRoot(n){let c=n;while(c&&c!==figma.currentPage){if(getMeta(c,"formatId"))return c;c=c.parent}return null}
function allRoots(){return figma.currentPage.findAll(n=>n.type==="COMPONENT"&&getMeta(n,"formatId")&&getMeta(n,"campaignId"))}
function rootsForCampaign(id,roots=null){return(roots||allRoots()).filter(r=>getMeta(r,"campaignId")===id)}
function selectedCampaignId(roots=null){const n=figma.currentPage.selection[0],r=n&&(getMeta(n,"formatId")?n:formatRoot(n));if(r)return getMeta(r,"campaignId");const ids=[...new Set((roots||allRoots()).map(r=>getMeta(r,"campaignId")))];return ids.length===1?ids[0]:""}
function registryForCampaign(id,roots=null){const root=rootsForCampaign(id,roots)[0];if(!root)return defaultRegistry();const r=parseJson(getMeta(root,"slotRegistry"),[]);return Array.isArray(r)&&r.length?r:defaultRegistry()}
function writeRegistry(id,registry,roots=null){const raw=JSON.stringify(registry);for(const r of rootsForCampaign(id,roots))meta(r,"slotRegistry",raw)}
async function addText(root,name,text,x,y,size,slot,opts={}){const n=figma.createText();n.name=name;n.fontName={family:"Inter",style:opts.bold?"Bold":"Regular"};n.fontSize=size;n.characters=text;n.x=x;n.y=y;n.lineHeight={unit:"PIXELS",value:Math.max(size+2,Math.round(size*(opts.lineHeight||1.12)))};n.resize(Math.max(8,opts.width||root.width-x*2),Math.max(8,opts.height||size*1.5));n.visible=opts.visible!==false;meta(n,"slotId",slot);meta(n,"responsiveVisibility",opts.visible===false?"hidden-by-format":"visible");root.appendChild(n);return n}
async function addTextStack(root,x,y,width,headlineText,copyText,c){const stack=figma.createFrame();stack.name="Headline + Copy";stack.fills=[];stack.clipsContent=false;stack.x=x;stack.y=y;stack.resize(Math.max(8,width),1);stack.layoutMode="VERTICAL";stack.itemSpacing=Math.max(2,Math.round(c.headline*.22));stack.primaryAxisSizingMode="AUTO";stack.counterAxisSizingMode="FIXED";meta(stack,"layoutRole","headline-copy-autolayout");root.appendChild(stack);const headline=await addText(stack,"Headline",headlineText,0,0,c.headline,"headline",{bold:true,width:Math.max(8,width),lineHeight:c.strip?1.05:1.08});headline.textAutoResize="HEIGHT";headline.layoutAlign="STRETCH";const subline=await addText(stack,"Copy",copyText,0,0,c.copySize,"copy",{width:Math.max(8,width),visible:c.showCopy,lineHeight:c.strip?1.05:1.08});subline.textAutoResize="HEIGHT";subline.layoutAlign="STRETCH";return stack}
function addRect(root,name,x,y,w,h,color,slot,opts={}){const n=figma.createRectangle();n.name=name;n.x=x;n.y=y;n.resize(Math.max(1,w),Math.max(1,h));n.fills=[{type:"SOLID",color:rgb(color)}];if(opts.radius!=null)n.cornerRadius=Math.min(opts.radius,w/2,h/2);n.visible=opts.visible!==false;meta(n,"slotId",slot);meta(n,"responsiveVisibility",opts.visible===false?"hidden-by-format":"visible");root.appendChild(n);return n}
function addTrackingPixel(root){const n=addRect(root,"Tracking pixel",Math.max(0,root.width-1),Math.max(0,root.height-1),1,1,"#000000","tracking_pixel");n.opacity=.01;n.locked=true;meta(n,"technicalRole","tracking_pixel");return n}
function compositionFor(w,h){const area=w*h,ratio=w/h,min=Math.min(w,h),strip=h<=120||ratio>=3,micro=area<=8000||min<=40,tiny=area<=18000||min<=60,compact=area<=45000||h<=100;let pad=Math.max(6,Math.round(Math.min(w,h)*.075)),headline=Math.max(8,Math.min(28,Math.round(Math.min(w,h)*.085))),copySize=Math.max(7,Math.round(headline*.58));if(strip){pad=Math.max(8,Math.round(h*.18));headline=Math.max(10,Math.min(22,Math.round(h*.23)));copySize=Math.max(8,Math.round(headline*.62))}if(tiny){headline=Math.max(7,Math.min(11,Math.round(min*.18)));copySize=Math.max(6,Math.round(headline*.72))}if(micro)headline=Math.max(6,Math.min(9,Math.round(min*.22)));const showCopy=!micro&&(!tiny||area>12000),showCTA=!micro&&!tiny&&w>=140&&h>=80;return{pad,headline,copySize,showCopy,showCTA,strip,micro,tiny}}
function normalizeFormats(formats){const out=[],seen=new Set();for(const raw of formats||[]){let w=Number(raw.width)||0,h=Number(raw.height)||0;if(!w||!h)continue;const key=`${w}x${h}`;if(seen.has(key))continue;seen.add(key);out.push({id:raw.id||`format-${key}`,width:w,height:h,family:raw.family||familyFor(w,h),placements:Array.isArray(raw.placements)?copy(raw.placements):[],conflicts:Array.isArray(raw.conflicts)?copy(raw.conflicts):[]})}return out}
async function createRoot(f,campaignId,name,duration,registry,x,y){const r=figma.createComponent();r.name=`${f.width}×${f.height}, ${f.family}`;r.resize(f.width,f.height);r.x=x;r.y=y;r.clipsContent=true;r.fills=[{type:"SOLID",color:rgb("#f2f3ef")}];for(const[k,v]of Object.entries({campaignId,campaignName:name,formatId:f.id,familyId:f.family,duration,slotRegistry:JSON.stringify(registry),deliveryPlacements:JSON.stringify(f.placements||[]),ttConflicts:JSON.stringify(f.conflicts||[])}))meta(r,k,v);const c=compositionFor(f.width,f.height),headlineText=c.micro?"Campaign":"Campaign headline",copyText=c.tiny?"Campaign":"Campaign copy";if(c.strip){const textW=Math.max(20,Math.round(f.width*(c.showCTA?.72:.92)));await addTextStack(r,c.pad,Math.max(4,c.pad-2),textW,headlineText,copyText,c);const bw=Math.min(110,Math.max(58,Math.round(f.width*.14))),bh=Math.min(34,Math.max(22,Math.round(f.height*.34)));addRect(r,"CTA",f.width-c.pad-bw,Math.max(c.pad,f.height-c.pad-bh),bw,bh,"#171812","cta",{radius:8,visible:c.showCTA})}else{const textW=Math.max(16,f.width-c.pad*2);await addTextStack(r,c.pad,c.pad,textW,headlineText,copyText,c);const bw=Math.min(Math.max(64,Math.round(f.width*.44)),140),bh=Math.min(38,Math.max(24,Math.round(f.height*.095)));addRect(r,"CTA",c.pad,f.height-c.pad-bh,bw,bh,"#171812","cta",{radius:8,visible:c.showCTA})}addTrackingPixel(r);return r}
function updateExistingFromFormats(existing,normalized){let updated=0;for(const root of existing){const key=`${Math.round(root.width)}x${Math.round(root.height)}`,f=normalized.find(x=>`${x.width}x${x.height}`===key);if(!f)continue;meta(root,"deliveryPlacements",JSON.stringify(f.placements||[]));meta(root,"ttConflicts",JSON.stringify(f.conflicts||[]));updated++}return updated}
async function createCampaignFromFormats(name,duration,formats,requestedCampaignId=""){await figma.currentPage.loadAsync();await Promise.all([{family:"Inter",style:"Regular"},{family:"Inter",style:"Bold"}].map(f=>figma.loadFontAsync(f)));const normalized=normalizeFormats(formats);if(!normalized.length)throw Error("No valid creative sizes");const pageRoots=allRoots();const requestedExists=requestedCampaignId&&pageRoots.some(r=>getMeta(r,"campaignId")===requestedCampaignId);const campaignId=requestedExists?requestedCampaignId:`campaign-${Date.now()}`;const existing=rootsForCampaign(campaignId,pageRoots);const campaignName=existing.length?(getMeta(existing[0],"campaignName")||name||"Campaign"):(name||"Campaign");const registry=existing.length?registryForCampaign(campaignId,pageRoots):defaultRegistry();const updated=updateExistingFromFormats(existing,normalized);const existingKeys=new Set(existing.map(r=>`${Math.round(r.width)}x${Math.round(r.height)}`));const missing=normalized.filter(f=>!existingKeys.has(`${f.width}x${f.height}`));let x=existing.length?Math.min(...existing.map(r=>r.x)):0,y=existing.length?Math.max(...existing.map(r=>r.y+r.height))+100:0,row=0;const roots=[];for(const f of missing){const r=await createRoot(f,campaignId,campaignName,duration,registry,x,y);roots.push(r);x+=f.width+80;row=Math.max(row,f.height);if(x>1900){x=0;y+=row+100;row=0}}const allAfter=pageRoots.concat(roots);writeRegistry(campaignId,registry,allAfter);if(roots.length){figma.currentPage.selection=roots;figma.viewport.scrollAndZoomIntoView(roots)}return{campaignId,count:roots.length,updated,total:existing.length+roots.length,skipped:normalized.length-roots.length,name:campaignName}}
function rootTTState(r){const placements=parseJson(getMeta(r,"deliveryPlacements"),[]);return{id:getMeta(r,"formatId"),nodeId:r.id,size:`${Math.round(r.width)}×${Math.round(r.height)}`,width:Math.round(r.width),height:Math.round(r.height),family:getMeta(r,"familyId"),placements,conflicts:parseJson(getMeta(r,"ttConflicts"),[]),ttReady:placements.length>0&&placements.every(ttReady),ttReadyCount:placements.filter(ttReady).length}}
function updateFormatTT(campaignId,formatId,placements,conflicts=[]){const root=rootsForCampaign(campaignId).find(r=>getMeta(r,"formatId")===formatId);if(!root)return{error:"Campaign format not found"};meta(root,"deliveryPlacements",JSON.stringify(Array.isArray(placements)?placements:[]));meta(root,"ttConflicts",JSON.stringify(Array.isArray(conflicts)?conflicts:[]));return{format:rootTTState(root)}}
function updateFormatsTT(campaignId,updates=[]){const roots=rootsForCampaign(campaignId),results=[];for(const u of Array.isArray(updates)?updates:[]){const root=roots.find(r=>getMeta(r,"formatId")===u.formatId);if(!root){results.push({formatId:u.formatId,error:"Campaign format not found"});continue}meta(root,"deliveryPlacements",JSON.stringify(Array.isArray(u.placements)?u.placements:[]));meta(root,"ttConflicts",JSON.stringify(Array.isArray(u.conflicts)?u.conflicts:[]));results.push({formatId:u.formatId,format:rootTTState(root)})}return{count:results.filter(r=>!r.error).length,results}}
function campaignState(){const pageRoots=allRoots();const campaign=selectedCampaignId(pageRoots);if(!campaign)return{campaignId:"",formatCount:0,formatSizes:[],formats:[],slots:[],presets:[]};const roots=rootsForCampaign(campaign,pageRoots),registry=registryForCampaign(campaign,pageRoots);const slotMaps=new Map(roots.map(r=>[r.id,new Set(r.findAll(n=>Boolean(getMeta(n,"slotId"))).map(n=>getMeta(n,"slotId")))]));const formats=roots.map(rootTTState);return{campaignId:campaign,campaignName:getMeta(roots[0],"campaignName")||"Campaign",formatCount:roots.length,formatSizes:formats.map(f=>f.size),formats,tt:{ready:formats.filter(f=>f.ttReady).length,total:formats.length},slots:registry.map(s=>{let linked=0;for(const r of roots)if(slotMaps.get(r.id)?.has(s.id))linked++;return{...s,linkedCount:linked,totalCount:roots.length,missingCount:roots.length-linked}}),presets:[]}}
function postState(){figma.ui.postMessage({type:"campaign-state",state:campaignState()})}
function layerForSlot(root,slotId){return root.findAll(n=>getMeta(n,"slotId")===slotId)[0]||null}
function linkSelection(slotId){const campaign=selectedCampaignId();if(!campaign)return{error:"Select a layer inside a campaign format"};let count=0;for(const n of figma.currentPage.selection){const r=formatRoot(n);if(!r||getMeta(r,"campaignId")!==campaign)continue;for(const old of r.findAll(x=>x.id!==n.id&&getMeta(x,"slotId")===slotId))meta(old,"slotId","");meta(n,"slotId",slotId);count++}return{count}}
function createMissing(slotId){const campaign=selectedCampaignId();if(!campaign)return{error:"Select a campaign format"};const roots=rootsForCampaign(campaign),sourceRoot=roots.find(r=>layerForSlot(r,slotId)),source=sourceRoot&&layerForSlot(sourceRoot,slotId);if(!source)return{error:"Link this layer in one format first"};let count=0;for(const root of roots){if(layerForSlot(root,slotId))continue;const clone=source.clone();root.appendChild(clone);meta(clone,"slotId",slotId);clone.x=Math.max(0,Math.min(root.width-clone.width,(source.x/sourceRoot.width)*root.width));clone.y=Math.max(0,Math.min(root.height-clone.height,(source.y/sourceRoot.height)*root.height));count++}return{count}}
function syncSlot(slotId,parts,scope){const source=figma.currentPage.selection[0];const sourceRoot=source&&formatRoot(source);if(!source||!sourceRoot||getMeta(source,"slotId")!==slotId)return{error:"Select the linked source layer in Figma first"};const campaign=getMeta(sourceRoot,"campaignId"),family=getMeta(sourceRoot,"familyId");const targets=rootsForCampaign(campaign).filter(r=>r.id!==sourceRoot.id&&(scope!=="family"||getMeta(r,"familyId")===family));let count=0;for(const root of targets){const target=layerForSlot(root,slotId);if(!target)continue;if(parts.includes("content")&&"characters" in source&&"characters" in target)target.characters=source.characters;if(parts.includes("appearance")){if("opacity" in target)target.opacity=source.opacity;if("rotation" in target)target.rotation=source.rotation;if("fills" in source&&"fills" in target)target.fills=copy(source.fills)}if(parts.includes("layout")){target.x=Math.max(0,Math.min(root.width-target.width,(source.x/sourceRoot.width)*root.width));target.y=Math.max(0,Math.min(root.height-target.height,(source.y/sourceRoot.height)*root.height))}for(const field of ["manualKeyframeTracks","animations","animationStyles"]){if((parts.includes("motionType")||parts.includes("timing")||parts.includes("easing")||parts.includes("geometry"))&&field in source&&field in target){try{target[field]=copy(source[field])}catch{}}}count++}return{count}}
function exportCampaign(){const pageRoots=allRoots();const campaign=selectedCampaignId(pageRoots);if(!campaign)return{error:"Select campaign"};const roots=rootsForCampaign(campaign,pageRoots);return{data:{version:1,campaignId:campaign,name:getMeta(roots[0],"campaignName"),formats:roots.map(rootTTState)}}}
figma.ui.onmessage=async m=>{try{if(m.type==="refresh"){await figma.currentPage.loadAsync();postState();return}if(m.type==="create-from-plan"){const result=await createCampaignFromFormats(m.name,m.duration,m.formats,m.campaignId||"");figma.ui.postMessage({type:"plan-formats-created",result});postState();return}if(m.type==="update-format-tt"){const result=updateFormatTT(m.campaignId||selectedCampaignId(),m.formatId,m.placements,m.conflicts);figma.ui.postMessage({type:"tt-update-result",result});postState();return}if(m.type==="update-formats-tt"){const result=updateFormatsTT(m.campaignId||selectedCampaignId(),m.updates);figma.ui.postMessage({type:"tt-batch-update-result",result});postState();return}if(m.type==="link-selection"){figma.ui.postMessage({type:"action-result",action:"link",result:linkSelection(m.slotId)});postState();return}if(m.type==="create-missing"){figma.ui.postMessage({type:"action-result",action:"missing",result:createMissing(m.slotId)});postState();return}if(m.type==="sync"){figma.ui.postMessage({type:"action-result",action:"sync",result:syncSlot(m.slotId,m.parts||[],m.scope||"all")});postState();return}if(m.type==="export"){const result=exportCampaign();figma.ui.postMessage({type:"export-result",result});return}}catch(error){figma.ui.postMessage({type:"plugin-error",message:error instanceof Error?error.message:String(error)})}};
(async()=>{await figma.currentPage.loadAsync();postState()})();