const NS="banner_campaign";
const SLOT_CATALOG={background:{id:"background",label:"Background",kind:"visual",system:true},headline:{id:"headline",label:"Headline",kind:"text",system:true},copy:{id:"copy",label:"Copy",kind:"text",system:true},cta:{id:"cta",label:"CTA",kind:"visual",system:true,required:true},tracking_pixel:{id:"tracking_pixel",label:"Tracking pixel",kind:"technical",system:true,required:true,technical:true}};
const DEFAULT_SLOT_IDS=["background","headline","copy","cta","tracking_pixel"];
figma.showUI(__html__,{width:620,height:760,themeColors:true});
const meta=(n,k,v)=>n.setSharedPluginData(NS,k,String(v??""));
const getMeta=(n,k)=>n.getSharedPluginData(NS,k);
const copy=v=>v==null?v:JSON.parse(JSON.stringify(v));
const rgb=h=>{let v=String(h).replace("#","").trim();if(v.length===3)v=v.split("").map(c=>c+c).join("");return{r:parseInt(v.slice(0,2),16)/255,g:parseInt(v.slice(2,4),16)/255,b:parseInt(v.slice(4,6),16)/255}};
const familyFor=(w,h)=>h<=100||w/h>=3?"Strip":h>w?"Vertical":"Rectangle";
const defaultRegistry=()=>DEFAULT_SLOT_IDS.map(id=>copy(SLOT_CATALOG[id]));
function formatRoot(n){let c=n;while(c&&c!==figma.currentPage){if(getMeta(c,"formatId"))return c;c=c.parent}return null}
function allRoots(){return figma.currentPage.findAll(n=>n.type==="COMPONENT"&&getMeta(n,"formatId")&&getMeta(n,"campaignId"))}
function rootsForCampaign(id){return allRoots().filter(r=>getMeta(r,"campaignId")===id)}
function selectedCampaignId(){const n=figma.currentPage.selection[0],r=n&&(getMeta(n,"formatId")?n:formatRoot(n));if(r)return getMeta(r,"campaignId");const ids=[...new Set(allRoots().map(r=>getMeta(r,"campaignId")))];return ids.length===1?ids[0]:""}
function registryForCampaign(id){const root=rootsForCampaign(id)[0];if(!root)return defaultRegistry();try{const r=JSON.parse(getMeta(root,"slotRegistry")||"[]");return Array.isArray(r)&&r.length?r:defaultRegistry()}catch{return defaultRegistry()}}
function writeRegistry(id,registry){const raw=JSON.stringify(registry);for(const r of rootsForCampaign(id))meta(r,"slotRegistry",raw)}
async function addText(root,name,text,x,y,size,slot){await figma.loadFontAsync({family:"Inter",style:"Regular"});const n=figma.createText();n.name=name;n.fontName={family:"Inter",style:"Regular"};n.fontSize=size;n.characters=text;n.x=x;n.y=y;n.resize(Math.max(50,root.width-x*2),Math.max(24,size*1.4));meta(n,"slotId",slot);root.appendChild(n);return n}
function addRect(root,name,x,y,w,h,color,slot){const n=figma.createRectangle();n.name=name;n.x=x;n.y=y;n.resize(w,h);n.fills=[{type:"SOLID",color:rgb(color)}];meta(n,"slotId",slot);root.appendChild(n);return n}
function addTrackingPixel(root){const n=addRect(root,"Tracking pixel",Math.max(0,root.width-1),Math.max(0,root.height-1),1,1,"#000000","tracking_pixel");n.opacity=.01;n.locked=true;meta(n,"technicalRole","tracking_pixel");return n}
function normalizeFormats(formats){const out=[],seen=new Set();for(const raw of formats||[]){let w=Number(raw.width)||0,h=Number(raw.height)||0;if(!w||!h)continue;const key=`${w}x${h}`;if(seen.has(key))continue;seen.add(key);out.push({id:raw.id||`format-${key}`,width:w,height:h,family:raw.family||familyFor(w,h),placements:Array.isArray(raw.placements)?copy(raw.placements):[],conflicts:Array.isArray(raw.conflicts)?copy(raw.conflicts):[]})}return out}
async function createRoot(f,campaignId,name,duration,registry,x,y){const r=figma.createComponent();r.name=`${f.width}×${f.height}, ${f.family}`;r.resize(f.width,f.height);r.x=x;r.y=y;r.clipsContent=true;r.fills=[{type:"SOLID",color:rgb("#eef0ec")}];for(const[k,v]of Object.entries({campaignId,campaignName:name,formatId:f.id,familyId:f.family,duration,slotRegistry:JSON.stringify(registry),deliveryPlacements:JSON.stringify(f.placements||[]),ttConflicts:JSON.stringify(f.conflicts||[])}))meta(r,k,v);const compact=f.height<=100;await addText(r,"Headline","Campaign headline",compact?18:Math.round(f.width*.08),compact?14:Math.round(f.height*.16),compact?18:Math.max(18,Math.round(f.width*.045)),"headline");if(!compact)await addText(r,"Copy","Campaign copy",Math.round(f.width*.08),Math.round(f.height*.42),Math.max(12,Math.round(f.width*.018)),"copy");addRect(r,"CTA",compact?Math.max(8,f.width-110):Math.round(f.width*.08),compact?14:Math.max(8,f.height-58),compact?Math.min(92,f.width-16):Math.min(130,f.width*.5),compact?28:38,"#171812","cta");addTrackingPixel(r);return r}
async function createCampaignFromFormats(name,duration,formats,requestedCampaignId=""){await figma.currentPage.loadAsync();const normalized=normalizeFormats(formats);if(!normalized.length)throw Error("No valid creative sizes");const campaignId=requestedCampaignId&&rootsForCampaign(requestedCampaignId).length?requestedCampaignId:`campaign-${Date.now()}`;const existing=rootsForCampaign(campaignId);const campaignName=existing.length?(getMeta(existing[0],"campaignName")||name||"Campaign"):(name||"Campaign");const registry=existing.length?registryForCampaign(campaignId):defaultRegistry();const existingKeys=new Set(existing.map(r=>`${Math.round(r.width)}x${Math.round(r.height)}`));const missing=normalized.filter(f=>!existingKeys.has(`${f.width}x${f.height}`));let x=existing.length?Math.min(...existing.map(r=>r.x)):0,y=existing.length?Math.max(...existing.map(r=>r.y+r.height))+100:0,row=0;const roots=[];for(const f of missing){const r=await createRoot(f,campaignId,campaignName,duration,registry,x,y);roots.push(r);x+=f.width+80;row=Math.max(row,f.height);if(x>1900){x=0;y+=row+100;row=0}}writeRegistry(campaignId,registry);if(roots.length){figma.currentPage.selection=roots;figma.viewport.scrollAndZoomIntoView(roots)}return{campaignId,count:roots.length,total:existing.length+roots.length,skipped:normalized.length-roots.length,name:campaignName}}
function layerForSlot(root,slotId){return root.findAll(n=>getMeta(n,"slotId")===slotId)[0]||null}
function campaignState(){const campaign=selectedCampaignId();if(!campaign)return{campaignId:"",formatCount:0,formatSizes:[],slots:[],presets:[]};const roots=rootsForCampaign(campaign),registry=registryForCampaign(campaign);return{campaignId:campaign,campaignName:getMeta(roots[0],"campaignName")||"Campaign",formatCount:roots.length,formatSizes:roots.map(r=>`${Math.round(r.width)}×${Math.round(r.height)}`),slots:registry.map(s=>({...s,linkedCount:roots.filter(r=>layerForSlot(r,s.id)).length,totalCount:roots.length,missingCount:roots.filter(r=>!layerForSlot(r,s.id)).length})),presets:[]}}
function postState(){figma.ui.postMessage({type:"campaign-state",state:campaignState()})}
function linkSelection(slotId){const campaign=selectedCampaignId();if(!campaign)return{error:"Select a layer inside a campaign format"};let count=0;for(const n of figma.currentPage.selection){const r=formatRoot(n);if(!r||getMeta(r,"campaignId")!==campaign)continue;for(const old of r.findAll(x=>x.id!==n.id&&getMeta(x,"slotId")===slotId))meta(old,"slotId","");meta(n,"slotId",slotId);count++}return{count}}
function createMissing(slotId){const campaign=selectedCampaignId();if(!campaign)return{error:"Select a campaign format"};const roots=rootsForCampaign(campaign),sourceRoot=roots.find(r=>layerForSlot(r,slotId)),source=sourceRoot&&layerForSlot(sourceRoot,slotId);if(!source)return{error:"Link this layer in one format first"};let count=0;for(const root of roots){if(layerForSlot(root,slotId))continue;const clone=source.clone();root.appendChild(clone);meta(clone,"slotId",slotId);clone.x=Math.max(0,Math.min(root.width-clone.width,(source.x/sourceRoot.width)*root.width));clone.y=Math.max(0,Math.min(root.height-clone.height,(source.y/sourceRoot.height)*root.height));count++}return{count}}
function syncSlot(slotId,parts,scope){const source=figma.currentPage.selection[0];const sourceRoot=source&&formatRoot(source);if(!source||!sourceRoot||getMeta(source,"slotId")!==slotId)return{error:"Select the linked source layer in Figma first"};const campaign=getMeta(sourceRoot,"campaignId"),family=getMeta(sourceRoot,"familyId");const targets=rootsForCampaign(campaign).filter(r=>r.id!==sourceRoot.id&&(scope!=="family"||getMeta(r,"familyId")===family));let count=0;for(const root of targets){const target=layerForSlot(root,slotId);if(!target)continue;if(parts.includes("content")&&"characters" in source&&"characters" in target)target.characters=source.characters;if(parts.includes("appearance")){if("opacity" in target)target.opacity=source.opacity;if("rotation" in target)target.rotation=source.rotation;if("fills" in source&&"fills" in target)target.fills=copy(source.fills)}if(parts.includes("layout")){target.x=Math.max(0,Math.min(root.width-target.width,(source.x/sourceRoot.width)*root.width));target.y=Math.max(0,Math.min(root.height-target.height,(source.y/sourceRoot.height)*root.height))}for(const field of ["manualKeyframeTracks","animations","animationStyles"]){if((parts.includes("motionType")||parts.includes("timing")||parts.includes("easing")||parts.includes("geometry"))&&field in source&&field in target){try{target[field]=copy(source[field])}catch{}}}count++}return{count}}
function exportCampaign(){const campaign=selectedCampaignId();if(!campaign)return{error:"Select campaign"};const roots=rootsForCampaign(campaign);return{data:{version:1,campaignId:campaign,name:getMeta(roots[0],"campaignName"),formats:roots.map(r=>({id:getMeta(r,"formatId"),size:`${Math.round(r.width)}×${Math.round(r.height)}`,family:getMeta(r,"familyId"),placements:JSON.parse(getMeta(r,"deliveryPlacements")||"[]"),conflicts:JSON.parse(getMeta(r,"ttConflicts")||"[]")}))}}}
figma.ui.onmessage=async m=>{try{if(m.type==="refresh"){await figma.currentPage.loadAsync();postState();return}if(m.type==="create-from-plan"){const result=await createCampaignFromFormats(m.name,m.duration,m.formats,m.campaignId||"");figma.ui.postMessage({type:"plan-formats-created",result});postState();return}if(m.type==="link-selection"){figma.ui.postMessage({type:"action-result",action:"link",result:linkSelection(m.slotId)});postState();return}if(m.type==="create-missing"){figma.ui.postMessage({type:"action-result",action:"missing",result:createMissing(m.slotId)});postState();return}if(m.type==="sync"){figma.ui.postMessage({type:"action-result",action:"sync",result:syncSlot(m.slotId,m.parts||[],m.scope||"all")});postState();return}if(m.type==="export"){const result=exportCampaign();figma.ui.postMessage({type:"export-result",result});return}}catch(error){figma.ui.postMessage({type:"plugin-error",message:error instanceof Error?error.message:String(error)})}};
(async()=>{await figma.currentPage.loadAsync();postState()})();