import { useEffect, useMemo, useRef, useState } from "react";
import { ArrowLeft, ChevronDown, ChevronRight, CircleCheck, Copy, Download, Eye, EyeOff, GripVertical, Image, Lock, MoreHorizontal, Play, Redo2, RotateCcw, Sparkles, Trash2, Type, Undo2, Unlock, Upload, ZoomIn, ZoomOut } from "lucide-react";
import { fitPreview, formats, initialElements, platformProfiles, type BannerElement } from "./model";
import { moveKeyframe, upsertKeyframe, type AnimatableProperty, type FormatKeyframes, type Keyframe } from "./timeline";

const clamp=(value:number,min:number,max:number)=>Math.min(max,Math.max(min,value));
type AssetItem={id:string;name:string;group:"primary"|"additional";type:"image"|"font";url?:string};

export default function App(){
 const [activeFormat,setActiveFormat]=useState("master");
 const [elementsByFormat,setElementsByFormat]=useState<Record<string,BannerElement[]>>(()=>{
  const saved=localStorage.getItem("banner-editor:format-elements");
  if(saved){try{const parsed=JSON.parse(saved) as Record<string,BannerElement[]>;return Object.fromEntries(formats.map(format=>[format.id,(parsed[format.id]??initialElements).map(element=>({...initialElements.find(seed=>seed.id===element.id),...element}))]))}catch{localStorage.removeItem("banner-editor:format-elements")}}
  return Object.fromEntries(formats.map(item=>[item.id,initialElements.map(element=>({...element}))]));
 });
 const [selectedId,setSelectedId]=useState("headline");
 const [zoom,setZoom]=useState(76);
 const [playing,setPlaying]=useState(false);
 const [platformId,setPlatformId]=useState("google");
 const [assets,setAssets]=useState<AssetItem[]>([{id:"product",name:"product.png",group:"primary",type:"image"},{id:"logo",name:"brand-logo.svg",group:"primary",type:"image"},{id:"bg",name:"background.jpg",group:"primary",type:"image"},{id:"texture",name:"texture.png",group:"additional",type:"image"},{id:"font",name:"Manrope.woff2",group:"additional",type:"font"}]);
 const assetInput=useRef<HTMLInputElement>(null);
 const uploadGroup=useRef<"primary"|"additional">("primary");
 const [playhead,setPlayhead]=useState(0);
 const [keyframesByFormat,setKeyframesByFormat]=useState<Record<string,FormatKeyframes>>(()=>{const saved=localStorage.getItem("banner-editor:keyframes");if(saved){try{return JSON.parse(saved)}catch{localStorage.removeItem("banner-editor:keyframes")}}return Object.fromEntries(formats.map(item=>[item.id,{}]))});
 const format=formats.find(item=>item.id===activeFormat)!;
 const elements=elementsByFormat[activeFormat]??initialElements;
 const selected=elements.find(item=>item.id===selectedId)??elements[0];
 const preview=useMemo(()=>fitPreview(format.width,format.height),[format]);
 const platform=platformProfiles.find(item=>item.id===platformId)!;
 useEffect(()=>localStorage.setItem("banner-editor:format-elements",JSON.stringify(elementsByFormat)),[elementsByFormat]);
 useEffect(()=>localStorage.setItem("banner-editor:keyframes",JSON.stringify(keyframesByFormat)),[keyframesByFormat]);
 const setElements=(update:BannerElement[]|((current:BannerElement[])=>BannerElement[]))=>setElementsByFormat(all=>{const current=all[activeFormat]??initialElements;return{...all,[activeFormat]:typeof update==="function"?update(current):update}});
 const switchFormat=(id:string)=>{const target=elementsByFormat[id]??initialElements;setActiveFormat(id);if(!target.some(item=>item.id===selectedId))setSelectedId(target[0].id)};
 const patchSelected=(patch:Partial<BannerElement>)=>setElements(current=>current.map(item=>item.id===selected.id?{...item,...patch}:item));
 const toggleVisible=(id:string)=>setElements(current=>current.map(item=>item.id===id?{...item,visible:!item.visible}:item));
 const duplicateSelected=()=>{const copy={...selected,id:`${selected.id}-${Date.now()}`,name:`${selected.name} copy`,x:selected.x+3,y:selected.y+3};setElements(current=>[...current,copy]);setSelectedId(copy.id)};
 const deleteSelected=()=>{if(elements.length===1)return;const remaining=elements.filter(item=>item.id!==selectedId);setElements(remaining);setSelectedId(remaining[0].id)};
 const dragCoordinate=(key:"x"|"y",startEvent:React.PointerEvent)=>{const start=startEvent.clientX;const value=selected[key];const move=(event:PointerEvent)=>patchSelected({[key]:Math.round((value+(event.clientX-start)*.25)*10)/10});const up=()=>{window.removeEventListener("pointermove",move);window.removeEventListener("pointerup",up)};window.addEventListener("pointermove",move);window.addEventListener("pointerup",up)};
 const dragElement=(startEvent:React.PointerEvent,id:string)=>{startEvent.stopPropagation();setSelectedId(id);const item=elements.find(el=>el.id===id)!;if(item.locked)return;const startX=startEvent.clientX,startY=startEvent.clientY;const move=(event:PointerEvent)=>setElements(current=>current.map(el=>el.id===id?{...el,x:clamp(item.x+(event.clientX-startX)/preview.width*100,0,96),y:clamp(item.y+(event.clientY-startY)/preview.height*100,0,96)}:el));const up=()=>{window.removeEventListener("pointermove",move);window.removeEventListener("pointerup",up)};window.addEventListener("pointermove",move);window.addEventListener("pointerup",up)};
 const openAssetUpload=(group:"primary"|"additional")=>{uploadGroup.current=group;assetInput.current?.click()};
 const uploadAssets=async(files:FileList|null)=>{if(!files?.length)return;const added=await Promise.all(Array.from(files).map(file=>new Promise<AssetItem>((resolve,reject)=>{const type=file.name.match(/\.(woff2?|ttf|otf)$/i)?"font":"image";const reader=new FileReader();reader.onload=()=>resolve({id:`asset-${crypto.randomUUID()}`,name:file.name,group:uploadGroup.current,type,url:String(reader.result)});reader.onerror=reject;reader.readAsDataURL(file)})));setAssets(current=>[...current,...added]);if(assetInput.current)assetInput.current.value=""};
 const addAssetToCanvas=(asset:AssetItem)=>{if(asset.type!=="image"||!asset.url)return;const image:BannerElement={id:`image-${crypto.randomUUID()}`,kind:"image",name:asset.name,text:"",assetUrl:asset.url,x:35,y:25,width:30,scale:100,rotation:0,opacity:100,fontFamily:"DM Sans",fontSize:12,lineHeight:100,color:"#ffffff",locked:false,visible:true};setElements(current=>[...current,image]);setSelectedId(image.id)};
 const formatKeyframes=keyframesByFormat[activeFormat]??{};
 const valueAt=(element:BannerElement,property:AnimatableProperty)=>{const frames=(formatKeyframes[element.id]??[]).filter(frame=>frame.property===property).sort((a,b)=>a.time-b.time);if(!frames.length)return element[property];const previous=[{time:0,value:element[property]},...frames].filter(frame=>frame.time<=playhead).at(-1)!;const next=frames.find(frame=>frame.time>=playhead);if(!next||next.time===previous.time)return previous.value;const progress=(playhead-previous.time)/(next.time-previous.time);return previous.value+(next.value-previous.value)*progress};
 const displayElements=elements.map(element=>({...element,x:valueAt(element,"x"),y:valueAt(element,"y"),scale:valueAt(element,"scale"),rotation:valueAt(element,"rotation"),opacity:valueAt(element,"opacity")}));
 useEffect(()=>{if(!playing)return;const started=performance.now()-playhead*1000;let frame=0;const tick=(now:number)=>{const time=(now-started)/1000;if(time>=6){setPlayhead(6);setPlaying(false);return}setPlayhead(time);frame=requestAnimationFrame(tick)};frame=requestAnimationFrame(tick);return()=>cancelAnimationFrame(frame)},[playing]);
 const addKeyframe=(property:AnimatableProperty)=>{const frame:Keyframe={id:crypto.randomUUID(),time:playhead,property,value:selected[property]};setKeyframesByFormat(all=>({...all,[activeFormat]:{...(all[activeFormat]??{}),[selected.id]:upsertKeyframe((all[activeFormat]?.[selected.id]??[]),frame)}}))};
 const dragKeyframe=(event:React.PointerEvent,elementId:string,id:string)=>{event.stopPropagation();const startX=event.clientX;const frame=(formatKeyframes[elementId]??[]).find(item=>item.id===id)!;const move=(pointer:PointerEvent)=>setKeyframesByFormat(all=>({...all,[activeFormat]:{...(all[activeFormat]??{}),[elementId]:moveKeyframe(all[activeFormat]?.[elementId]??[],id,frame.time+(pointer.clientX-startX)/440*6)}}));const up=()=>{window.removeEventListener("pointermove",move);window.removeEventListener("pointerup",up)};window.addEventListener("pointermove",move);window.addEventListener("pointerup",up)};
 return <main className="app-shell">
  <header className="topbar">
   <div className="brand-mark">B</div><button className="icon-button" aria-label="Back"><ArrowLeft size={18}/></button>
   <div className="project-name"><strong>Summer Product Launch</strong><span>Saved just now</span></div>
   <div className="topbar-actions"><button className="icon-button"><Undo2 size={17}/></button><button className="icon-button muted"><Redo2 size={17}/></button><div className="separator"/><button className="preview-button"><Play size={15} fill="currentColor"/> Preview</button><button className="export-button"><Download size={16}/> Export</button><button className="icon-button"><MoreHorizontal size={19}/></button></div>
  </header>
  <section className="workspace">
   <aside className="formats-panel">
    <div className="panel-heading"><div><span className="kicker">CAMPAIGN SOURCE</span><h2>Assets</h2></div></div>
    <input ref={assetInput} className="hidden-input" type="file" multiple accept="image/*,.svg,.woff,.woff2,.ttf,.otf" onChange={e=>uploadAssets(e.target.files)}/>
    <div className="asset-group"><div className="asset-group-title"><strong>Primary set</strong><button className="asset-add" onClick={()=>openAssetUpload("primary")}><Upload size={12}/> Add</button></div><div className="asset-grid">{assets.filter(item=>item.group==="primary").map(item=><button className={`asset-card ${item.url?"uploaded":""}`} key={item.id} onDoubleClick={()=>addAssetToCanvas(item)} style={item.type==="image"&&item.url?{backgroundImage:`url(${item.url})`}:undefined}>{item.type==="font"?<Type size={17}/>:!item.url&&<Image size={17}/>}<span>{item.name}</span></button>)}</div></div>
    <div className="asset-group additional"><div className="asset-group-title"><strong>Additional set</strong><button className="asset-add" onClick={()=>openAssetUpload("additional")}><Upload size={12}/> Add</button></div><div className="asset-grid">{assets.filter(item=>item.group==="additional").map(item=><button className={`asset-card ${item.url?"uploaded":""}`} key={item.id} onDoubleClick={()=>addAssetToCanvas(item)} style={item.type==="image"&&item.url?{backgroundImage:`url(${item.url})`}:undefined}>{item.type==="font"?<Type size={17}/>:!item.url&&<Image size={17}/>}<span>{item.name}</span></button>)}</div><small className="asset-hint">Double-click an image to place it</small></div>
    <div className="panel-heading formats-heading"><div><span className="kicker">OUTPUT</span><h2>Formats</h2></div><span className="count">5</span></div>
    <div className="format-list">{formats.map(item=><button key={item.id} className={`format-card ${activeFormat===item.id?"active":""}`} onClick={()=>switchFormat(item.id)}><span className="miniature" style={{aspectRatio:`${item.width}/${item.height}`}}/><span className="format-meta"><strong>{item.label}</strong><small>{item.width} × {item.height}</small></span>{item.status==="ready"?<CircleCheck size={15} className="success"/>:item.status==="review"?<span className="review-dot"/>:null}</button>)}</div>
    <button className="adapt-button"><Sparkles size={16}/> Adapt all formats</button>
   </aside>
   <section className="editor-stage">
    <div className="stage-toolbar"><div><strong>{format.label}</strong><span>{format.width} × {format.height}</span></div><div className="zoom-control"><button onClick={()=>setZoom(v=>clamp(v-10,30,150))}><ZoomOut size={15}/></button><span>{zoom}%</span><button onClick={()=>setZoom(v=>clamp(v+10,30,150))}><ZoomIn size={15}/></button><button><ChevronDown size={14}/></button></div></div>
    <div className="canvas-wrap"><div className="banner-canvas" style={{width:preview.width,height:preview.height,transform:`scale(${zoom/76})`}}><div className="orb orb-one"/><div className="orb orb-two"/><div className="product-shape"><span>01</span></div>{displayElements.filter(el=>el.visible).map(el=><button key={el.id} className={`canvas-element kind-${el.kind} ${selectedId===el.id?"selected":""}`} style={{left:`${el.x}%`,top:`${el.y}%`,width:`${el.width}%`,transform:`rotate(${el.rotation}deg) scale(${el.scale/100})`,transformOrigin:"left top",opacity:el.opacity/100,fontFamily:el.fontFamily,fontSize:`${Math.max(6,el.fontSize*preview.width/720)}px`,lineHeight:el.lineHeight/100,color:el.color}} onPointerDown={event=>dragElement(event,el.id)}>{el.kind==="image"&&el.assetUrl?<img src={el.assetUrl} alt=""/>:el.text}{selectedId===el.id&&<><span className="resize-handle"/><span className="rotate-handle"/></>}</button>)}</div></div>
    <div className="timeline"><div className="timeline-head"><button className="play-button" onClick={()=>setPlaying(v=>!v)}><Play size={15} fill="currentColor"/></button><strong>Timeline</strong><span>{playhead.toFixed(1)} / 6.0s</span><div className="timeline-spacer"/><button className="text-button" onClick={()=>setPlayhead(0)}><RotateCcw size={14}/> Rewind</button></div><div className="timeline-body"><div className="tracks"><div className="time-ruler timeline-ruler"><span>0s</span><span>1s</span><span>2s</span><span>3s</span><span>4s</span><span>5s</span><span>6s</span></div><div className="layer-tracks">{elements.map(element=><div className={`layer-track ${element.id===selected.id?"active":""}`} key={element.id} onClick={()=>setSelectedId(element.id)}><div className="track-name">{element.kind==="image"?<Image size={11}/>:<Type size={11}/>}<span>{element.name}</span></div><div className="track-line" onPointerDown={event=>{const rect=event.currentTarget.getBoundingClientRect();setPlayhead(clamp((event.clientX-rect.left)/rect.width*6,0,6))}}><span className="playhead" style={{left:`${playhead/6*100}%`}}/>{(formatKeyframes[element.id]??[]).map(frame=><button key={frame.id} className={`keyframe key-${frame.property}`} style={{left:`${frame.time/6*100}%`}} title={`${frame.property}: ${frame.value}`} onPointerDown={event=>dragKeyframe(event,element.id,frame.id)}/>)}</div></div>)}</div></div><aside className="requirements"><select value={platformId} onChange={e=>setPlatformId(e.target.value)}>{platformProfiles.map(item=><option key={item.id} value={item.id}>{item.name}</option>)}</select><div className="requirement-row"><CircleCheck size={13}/><span>ZIP weight</span><b>128 / {platform.maxZip} KB</b></div><div className="requirement-row"><CircleCheck size={13}/><span>Duration</span><b>6 / {platform.maxDuration}s</b></div><div className="requirement-row"><CircleCheck size={13}/><span>Click handler</span><b>{platform.click}</b></div><div className="requirement-row"><CircleCheck size={13}/><span>External files</span><b>None</b></div></aside></div></div>
   </section>
   <aside className="properties-panel">
    <div className="panel-heading property-title"><div><span className="kicker">SELECTED</span><h2>{selected.name}</h2></div><button className="icon-button"><MoreHorizontal size={18}/></button></div>
    <div className="object-actions"><button onClick={duplicateSelected}><Copy size={14}/> Duplicate</button><button className="danger" onClick={deleteSelected}><Trash2 size={14}/> Delete</button></div>
    <section className="property-section layers-section"><button className="section-title"><ChevronDown size={15}/> Layers <span>{elements.length}</span></button>{elements.map(item=><button key={item.id} className={`layer-row ${item.id===selectedId?"active":""}`} onClick={()=>setSelectedId(item.id)}><GripVertical size={14}/><span className={`layer-icon type-${item.kind}`}>{item.kind==="button"?"◉":"T"}</span><span>{item.name}</span><span className="row-spacer"/><span onClick={e=>{e.stopPropagation();toggleVisible(item.id)}}>{item.visible?<Eye size={14}/>:<EyeOff size={14}/>}</span>{item.locked&&<Lock size={13}/>}</button>)}</section>
    {selected.kind!=="image"&&<section className="property-section"><button className="section-title"><ChevronDown size={15}/> Typography</button><label className="field-label">Text</label><textarea value={selected.text} onChange={e=>patchSelected({text:e.target.value})}/><div className="type-controls"><select value={selected.fontFamily} onChange={e=>patchSelected({fontFamily:e.target.value})}><option>DM Sans</option><option>Manrope</option><option>Arial</option><option>Georgia</option></select><label><input type="color" value={selected.color} onChange={e=>patchSelected({color:e.target.value})}/><span>{selected.color}</span></label><label><span>Size</span><input type="number" value={selected.fontSize} onChange={e=>patchSelected({fontSize:Number(e.target.value)})}/></label></div><label className="range-field"><span>Line height</span><input type="range" min="70" max="250" value={selected.lineHeight} onChange={e=>patchSelected({lineHeight:Number(e.target.value)})}/><b>{selected.lineHeight}%</b></label></section>}
    <section className="property-section"><button className="section-title"><ChevronDown size={15}/> Transform</button><div className="field-grid"><label><span className="scrub-label" onPointerDown={e=>dragCoordinate("x",e)}>X</span><input type="number" value={Math.round(selected.x*10)/10} onChange={e=>patchSelected({x:Number(e.target.value)})}/></label><label><span className="scrub-label" onPointerDown={e=>dragCoordinate("y",e)}>Y</span><input type="number" value={Math.round(selected.y*10)/10} onChange={e=>patchSelected({y:Number(e.target.value)})}/></label><label><span>W</span><input type="number" value={selected.width} onChange={e=>patchSelected({width:Number(e.target.value)})}/></label><label><span>S</span><input type="number" value={selected.scale} onChange={e=>patchSelected({scale:Number(e.target.value)})}/></label><label><span>°</span><input type="number" value={selected.rotation} onChange={e=>patchSelected({rotation:Number(e.target.value)})}/></label><label><span>Opacity</span><input type="number" min="0" max="100" value={selected.opacity} onChange={e=>patchSelected({opacity:Number(e.target.value)})}/></label></div></section>
    <section className="property-section animation-panel"><button className="section-title"><ChevronDown size={15}/> Animation <span className="pill">{playhead.toFixed(1)}s</span></button><div className="keyframe-controls">{(["x","y","scale","rotation","opacity"] as AnimatableProperty[]).map(property=><button key={property} onClick={()=>addKeyframe(property)}><span className={`diamond key-${property}`}/><b>{property}</b><small>{selected[property]}</small></button>)}</div><p>Move the playhead, change a value, then add its keyframe.</p></section>
    <section className="property-section compact"><button className="lock-row" onClick={()=>patchSelected({locked:!selected.locked})}>{selected.locked?<Lock size={15}/>:<Unlock size={15}/>}<span><strong>{selected.locked?"Locked for adaptation":"Allow adaptation"}</strong><small>{selected.locked?"AI Director cannot change it":"AI Director may reposition it"}</small></span></button></section>
   </aside>
  </section>
 </main>
}
