import {useEffect,useMemo,useRef,useState} from "react";
import {ChevronDown,ChevronRight,Copy,Download,Eye,EyeOff,Image,Lock,MousePointer2,Play,Plus,RotateCcw,Sparkles,Trash2,Type,Unlock,Upload} from "lucide-react";
import {createTextElement,fitPreview,formats,platformProfiles,type BannerElement} from "./model";
import {moveKeyframe,upsertKeyframe,type AnimatableProperty,type FormatKeyframes,type Keyframe} from "./timeline";
import "./editor.css";

type Asset={id:string;name:string;group:"primary"|"additional";type:"image"|"font";url:string};
const clamp=(value:number,min:number,max:number)=>Math.min(max,Math.max(min,value));
const blankFormats=()=>Object.fromEntries(formats.map(format=>[format.id,[] as BannerElement[]]));
const blankKeyframes=()=>Object.fromEntries(formats.map(format=>[format.id,{} as FormatKeyframes]));

export default function Editor(){
 const [activeFormat,setActiveFormat]=useState("master");
 const [elementsByFormat,setElementsByFormat]=useState<Record<string,BannerElement[]>>(()=>{try{return JSON.parse(localStorage.getItem("banner-editor:v3:elements")||"")||blankFormats()}catch{return blankFormats()}});
 const [keyframesByFormat,setKeyframesByFormat]=useState<Record<string,FormatKeyframes>>(()=>{try{return JSON.parse(localStorage.getItem("banner-editor:v3:keyframes")||"")||blankKeyframes()}catch{return blankKeyframes()}});
 const [assets,setAssets]=useState<Asset[]>(()=>{try{return JSON.parse(localStorage.getItem("banner-editor:v3:assets")||"")||[]}catch{return[]}});
 const [selectedId,setSelectedId]=useState<string|null>(null);
 const [platformId,setPlatformId]=useState("google");
 const [playhead,setPlayhead]=useState(0);
 const [playing,setPlaying]=useState(false);
 const [zoom,setZoom]=useState(74);
 const uploadGroup=useRef<Asset["group"]>("primary");
 const fileInput=useRef<HTMLInputElement>(null);
 const format=formats.find(item=>item.id===activeFormat)!;
 const elements=elementsByFormat[activeFormat]??[];
 const selected=elements.find(item=>item.id===selectedId)??null;
 const frames=keyframesByFormat[activeFormat]??{};
 const preview=useMemo(()=>fitPreview(format.width,format.height,700,400),[format]);
 const platform=platformProfiles.find(item=>item.id===platformId)!;

 useEffect(()=>localStorage.setItem("banner-editor:v3:elements",JSON.stringify(elementsByFormat)),[elementsByFormat]);
 useEffect(()=>localStorage.setItem("banner-editor:v3:keyframes",JSON.stringify(keyframesByFormat)),[keyframesByFormat]);
 useEffect(()=>{try{localStorage.setItem("banner-editor:v3:assets",JSON.stringify(assets))}catch{}},[assets]);
 useEffect(()=>{if(!playing)return;const start=performance.now()-playhead*1000;let request=0;const tick=(now:number)=>{const time=(now-start)/1000;if(time>=6){setPlayhead(6);setPlaying(false);return}setPlayhead(time);request=requestAnimationFrame(tick)};request=requestAnimationFrame(tick);return()=>cancelAnimationFrame(request)},[playing]);

 const updateElements=(updater:(current:BannerElement[])=>BannerElement[])=>setElementsByFormat(all=>({...all,[activeFormat]:updater(all[activeFormat]??[])}));
 const updateSelected=(patch:Partial<BannerElement>)=>{if(!selected)return;updateElements(all=>all.map(item=>item.id===selected.id?{...item,...patch}:item))};
 const switchFormat=(id:string)=>{setActiveFormat(id);const target=elementsByFormat[id]??[];setSelectedId(target.some(item=>item.id===selectedId)?selectedId:target[0]?.id??null);setPlayhead(0);setPlaying(false)};
 const addText=()=>{const element=createTextElement();updateElements(all=>[...all,element]);setSelectedId(element.id)};
 const duplicate=()=>{if(!selected)return;const copy={...selected,id:`${selected.id}-${crypto.randomUUID()}`,name:`${selected.name} copy`,x:selected.x+3,y:selected.y+3};updateElements(all=>[...all,copy]);setSelectedId(copy.id)};
 const remove=()=>{if(!selected)return;updateElements(all=>all.filter(item=>item.id!==selected.id));setSelectedId(null)};
 const toggleLock=(id:string)=>updateElements(all=>all.map(item=>item.id===id?{...item,locked:!item.locked}:item));
 const toggleVisible=(id:string)=>updateElements(all=>all.map(item=>item.id===id?{...item,visible:!item.visible}:item));
 const startMove=(event:React.PointerEvent,id:string)=>{event.preventDefault();event.stopPropagation();const item=elements.find(element=>element.id===id);if(!item||item.locked)return;setPlaying(false);setSelectedId(id);const sx=event.clientX,sy=event.clientY;const move=(pointer:PointerEvent)=>updateElements(all=>all.map(element=>element.id===id?{...element,x:clamp(item.x+(pointer.clientX-sx)/preview.width*100,0,100),y:clamp(item.y+(pointer.clientY-sy)/preview.height*100,0,100)}:element));const end=()=>{window.removeEventListener("pointermove",move);window.removeEventListener("pointerup",end)};window.addEventListener("pointermove",move);window.addEventListener("pointerup",end)};
 const startScale=(event:React.PointerEvent,id:string)=>{event.preventDefault();event.stopPropagation();const item=elements.find(element=>element.id===id);const bounds=(event.currentTarget.parentElement as HTMLElement)?.getBoundingClientRect();if(!item||item.locked||!bounds)return;const cx=bounds.left+bounds.width/2,cy=bounds.top+bounds.height/2;const startDistance=Math.max(1,Math.hypot(event.clientX-cx,event.clientY-cy));const move=(pointer:PointerEvent)=>{const ratio=Math.hypot(pointer.clientX-cx,pointer.clientY-cy)/startDistance;updateElements(all=>all.map(element=>element.id===id?{...element,scale:clamp(item.scale*ratio,10,500)}:element))};const end=()=>{window.removeEventListener("pointermove",move);window.removeEventListener("pointerup",end)};window.addEventListener("pointermove",move);window.addEventListener("pointerup",end)};
 const startRotate=(event:React.PointerEvent,id:string)=>{event.preventDefault();event.stopPropagation();const item=elements.find(element=>element.id===id);const target=(event.currentTarget.parentElement as HTMLElement)?.getBoundingClientRect();if(!item||item.locked||!target)return;const cx=target.left+target.width/2,cy=target.top+target.height/2;const start=Math.atan2(event.clientY-cy,event.clientX-cx)*180/Math.PI;const move=(pointer:PointerEvent)=>{const angle=Math.atan2(pointer.clientY-cy,pointer.clientX-cx)*180/Math.PI;updateElements(all=>all.map(element=>element.id===id?{...element,rotation:Math.round(item.rotation+angle-start)}:element))};const end=()=>{window.removeEventListener("pointermove",move);window.removeEventListener("pointerup",end)};window.addEventListener("pointermove",move);window.addEventListener("pointerup",end)};
 const openUpload=(group:Asset["group"])=>{uploadGroup.current=group;fileInput.current?.click()};
 const upload=async(files:FileList|null)=>{if(!files?.length)return;const group=uploadGroup.current;const additions=await Promise.all(Array.from(files).map(file=>new Promise<Asset>((resolve,reject)=>{const reader=new FileReader();reader.onload=()=>resolve({id:crypto.randomUUID(),name:file.name,group,type:/\.(woff2?|ttf|otf)$/i.test(file.name)?"font":"image",url:String(reader.result)});reader.onerror=reject;reader.readAsDataURL(file)})));setAssets(all=>[...all,...additions]);if(fileInput.current)fileInput.current.value=""};
 const placeAsset=(asset:Asset)=>{if(asset.type!=="image")return;const element:BannerElement={id:crypto.randomUUID(),kind:"image",name:asset.name,text:"",assetUrl:asset.url,x:25,y:25,width:40,scale:100,rotation:0,opacity:100,fontFamily:"Arial",fontSize:16,lineHeight:100,color:"#000000",locked:false,visible:true};updateElements(all=>[...all,element]);setSelectedId(element.id)};
 const addKeyframe=(property:AnimatableProperty)=>{if(!selected)return;const frame:Keyframe={id:crypto.randomUUID(),time:playhead,property,value:selected[property]};setKeyframesByFormat(all=>({...all,[activeFormat]:{...(all[activeFormat]??{}),[selected.id]:upsertKeyframe(all[activeFormat]?.[selected.id]??[],frame)}}))};
 const dragKeyframe=(event:React.PointerEvent,elementId:string,id:string)=>{event.preventDefault();event.stopPropagation();const original=(frames[elementId]??[]).find(frame=>frame.id===id);if(!original)return;const sx=event.clientX;const move=(pointer:PointerEvent)=>setKeyframesByFormat(all=>({...all,[activeFormat]:{...(all[activeFormat]??{}),[elementId]:moveKeyframe(all[activeFormat]?.[elementId]??[],id,original.time+(pointer.clientX-sx)/440*6)}}));const end=()=>{window.removeEventListener("pointermove",move);window.removeEventListener("pointerup",end)};window.addEventListener("pointermove",move);window.addEventListener("pointerup",end)};
 const animatedValue=(element:BannerElement,property:AnimatableProperty)=>{const list=(frames[element.id]??[]).filter(frame=>frame.property===property).sort((a,b)=>a.time-b.time);if(!list.length)return element[property];const before=[{time:0,value:element[property]},...list].filter(frame=>frame.time<=playhead).at(-1)!;const after=list.find(frame=>frame.time>=playhead);if(!after||after.time===before.time)return before.value;return before.value+(after.value-before.value)*(playhead-before.time)/(after.time-before.time)};
 const displayElements=elements.map(element=>({...element,x:animatedValue(element,"x"),y:animatedValue(element,"y"),scale:animatedValue(element,"scale"),rotation:animatedValue(element,"rotation"),opacity:animatedValue(element,"opacity")}));

 return <div className="v2-app">
  <header className="v2-top"><div className="v2-logo">B</div><div><b>Untitled campaign</b><small>Local draft</small></div><div className="v2-top-actions"><button>Preview</button><button className="primary"><Download size={15}/> Export</button></div></header>
  <div className="v2-main">
   <aside className="v2-library"><div className="v2-panel-title"><span>LIBRARY</span><b>Assets</b></div><input ref={fileInput} hidden type="file" multiple accept="image/*,.svg,.woff,.woff2,.ttf,.otf" onChange={event=>upload(event.target.files)}/>{(["primary","additional"] as Asset["group"][]).map(group=><section className="v2-assets" key={group}><div><b>{group==="primary"?"Primary set":"Additional set"}</b><button onClick={()=>openUpload(group)}><Plus size={12}/> Add</button></div>{assets.filter(asset=>asset.group===group).length===0?<button className="asset-empty" onClick={()=>openUpload(group)}><Upload size={15}/><span>Upload assets</span></button>:<div className="v2-asset-grid">{assets.filter(asset=>asset.group===group).map(asset=><button key={asset.id} onDoubleClick={()=>placeAsset(asset)} style={asset.type==="image"?{backgroundImage:`url(${asset.url})`}:undefined}>{asset.type==="font"&&<Type size={16}/>}<span>{asset.name}</span></button>)}</div>}</section>)}<div className="v2-panel-title formats"><span>CAMPAIGN</span><b>Formats</b></div>{formats.map(item=><button className={`v2-format ${item.id===activeFormat?"active":""}`} key={item.id} onClick={()=>switchFormat(item.id)}><i style={{aspectRatio:`${item.width}/${item.height}`}}/><span><b>{item.label}</b><small>{item.width} × {item.height}</small></span></button>)}</aside>
   <section className="v2-stage"><div className="v2-stagebar"><b>{format.label}</b><span>{format.width} × {format.height}</span><div><button onClick={addText}><Type size={14}/> Text</button><button onClick={()=>openUpload("primary")}><Image size={14}/> Image</button><label>Zoom <input type="range" min="35" max="125" value={zoom} onChange={event=>setZoom(Number(event.target.value))}/><span>{zoom}%</span></label></div></div><div className="v2-canvas-area" onPointerDown={()=>setSelectedId(null)}><div className="v2-canvas" style={{width:preview.width,height:preview.height,transform:`scale(${zoom/74})`}}>{displayElements.length===0&&<div className="canvas-empty"><MousePointer2 size={20}/><b>Empty master</b><span>Add text or place an asset</span></div>}{displayElements.filter(element=>element.visible).map(element=><div className={`v2-object ${element.id===selectedId?"selected":""} ${element.locked?"locked":""}`} key={element.id} style={{left:`${element.x}%`,top:`${element.y}%`,width:`${element.width}%`,transform:`rotate(${element.rotation}deg) scale(${element.scale/100})`,opacity:element.opacity/100,fontFamily:element.fontFamily,fontSize:element.fontSize*preview.width/700,lineHeight:element.lineHeight/100,color:element.color}} onPointerDown={event=>startMove(event,element.id)}>{element.kind==="image"?<img src={element.assetUrl} alt=""/>:element.text}{element.id===selectedId&&!element.locked&&<><i className="handle nw" onPointerDown={event=>startScale(event,element.id)}/><i className="handle ne" onPointerDown={event=>startScale(event,element.id)}/><i className="handle sw" onPointerDown={event=>startScale(event,element.id)}/><i className="handle se" onPointerDown={event=>startScale(event,element.id)}/><i className="rotate" onPointerDown={event=>startRotate(event,element.id)}/></>}</div>)}</div></div>
   </section>
   <aside className="v2-inspector"><div className="v2-panel-title"><span>LAYERS</span><b>{elements.length} layers</b></div><div className="v2-layers">{elements.length===0?<p>No layers yet</p>:elements.slice().reverse().map(element=><div className={`v2-layer ${element.id===selectedId?"active":""}`} key={element.id}><button className="visibility" onClick={()=>toggleVisible(element.id)}>{element.visible?<Eye size={13}/>:<EyeOff size={13}/>}</button><button className="layer-name" onClick={()=>setSelectedId(element.id)}>{element.kind==="image"?<Image size={13}/>:<Type size={13}/>}<span>{element.name}</span></button><button className={`layer-lock ${element.locked?"on":""}`} onClick={()=>toggleLock(element.id)}>{element.locked?<Lock size={13}/>:<Unlock size={13}/>}</button></div>)}</div>{selected?<><div className="v2-object-actions"><button onClick={duplicate}><Copy size={13}/> Duplicate</button><button onClick={remove}><Trash2 size={13}/> Delete</button></div>{selected.kind!=="image"&&<section className="v2-section"><button className="section-head"><ChevronDown size={14}/> Typography</button><textarea value={selected.text} onChange={event=>updateSelected({text:event.target.value})}/><div className="v2-type-row"><select value={selected.fontFamily} onChange={event=>updateSelected({fontFamily:event.target.value})}><option>Manrope</option><option>DM Sans</option><option>Arial</option><option>Georgia</option></select><input type="number" value={selected.fontSize} onChange={event=>updateSelected({fontSize:Number(event.target.value)})}/><input type="color" value={selected.color} onChange={event=>updateSelected({color:event.target.value})}/></div><label className="v2-range"><span>Line height</span><input type="range" min="70" max="250" value={selected.lineHeight} onChange={event=>updateSelected({lineHeight:Number(event.target.value)})}/><b>{selected.lineHeight}%</b></label></section>}<section className="v2-section"><button className="section-head"><ChevronDown size={14}/> Transform</button><div className="v2-fields">{(["x","y","scale","rotation","opacity"] as AnimatableProperty[]).map(property=><label key={property}><span>{property}</span><input type="number" value={Math.round(selected[property]*10)/10} onChange={event=>updateSelected({[property]:Number(event.target.value)})}/><button title="Add keyframe" onClick={()=>addKeyframe(property)}>◆</button></label>)}</div></section></>:<div className="no-selection">Select a layer to edit</div>}<button className={`v2-lockbar ${selected?.locked?"locked":""}`} disabled={!selected} onClick={()=>selected&&toggleLock(selected.id)}>{selected?.locked?<Lock size={14}/>:<Unlock size={14}/>}<span>{selected?.locked?"Layer locked":"Lock selected layer"}</span></button></aside>
  </div>
  <section className="v2-timeline"><header><button className="v2-play" onClick={()=>{if(playhead>=6)setPlayhead(0);setPlaying(!playing)}}><Play size={13} fill="currentColor"/></button><b>Timeline</b><span>{playhead.toFixed(1)} / 6.0s</span><button onClick={()=>{setPlaying(false);setPlayhead(0)}}><RotateCcw size={13}/> Rewind</button><div className="tt"><select value={platformId} onChange={event=>setPlatformId(event.target.value)}>{platformProfiles.map(item=><option value={item.id} key={item.id}>{item.name}</option>)}</select><span>ZIP 128/{platform.maxZip}KB</span></div></header><div className="v2-timeline-grid"><div className="timeline-label-head">Layers</div><div className="v2-ruler">{[0,1,2,3,4,5,6].map(time=><span key={time} style={{left:`${time/6*100}%`}}>{time}s</span>)}</div>{elements.slice().reverse().map(element=><div className="timeline-row" key={element.id}><button onClick={()=>setSelectedId(element.id)}>{element.locked?<Lock size={11}/>:element.kind==="image"?<Image size={11}/>:<Type size={11}/>}<span>{element.name}</span></button><div className="timeline-track" onPointerDown={event=>{event.stopPropagation();const rect=event.currentTarget.getBoundingClientRect();setPlaying(false);setPlayhead(clamp((event.clientX-rect.left)/rect.width*6,0,6));setSelectedId(element.id)}}><i className="global-playhead" style={{left:`${playhead/6*100}%`}}/>{(frames[element.id]??[]).map(frame=><i key={frame.id} className={`timeline-key key-${frame.property}`} title={`${frame.property}: ${frame.value}`} style={{left:`${frame.time/6*100}%`}} onPointerDown={event=>dragKeyframe(event,element.id,frame.id)}/>)}</div></div>)}</div></section>
 </div>
}
