type StoredFrame={id:string;time:number;property:"x"|"y"|"scale"|"rotation"|"opacity";value:number;easing?:string;bezier?:[number,number,number,number]};
type StoredElement={id:string;kind:string;name:string;text:string;assetUrl?:string;x:number;y:number;width:number;scale:number;rotation:number;opacity:number;fontFamily:string;fontSize:number;lineHeight:number;color:string;locked:boolean;visible:boolean};
type StoredAsset={id:string;name:string;type:"image"|"font";url:string};
type ProjectFile={type:"banner-editor-project";version:1;savedAt:string;data:Record<string,string|null>};
const PREFIX="banner-editor:v3:";
const KEYS=["elements","keyframes","assets","settings","backgrounds","theme"].map(k=>PREFIX+k);
const FORMAT_META={master:{label:"Master",width:1200,height:628},medium:{label:"Medium rectangle",width:300,height:250},half:{label:"Half page",width:300,height:600},leader:{label:"Leaderboard",width:728,height:90},mobile:{label:"Mobile banner",width:320,height:50}} as const;
let fallback=new Map<string,string>();
let dbPromise:Promise<IDBDatabase>|null=null;
const openDb=()=>dbPromise??=new Promise((resolve,reject)=>{const request=indexedDB.open("banner-editor-project",1);request.onupgradeneeded=()=>{if(!request.result.objectStoreNames.contains("kv"))request.result.createObjectStore("kv")};request.onsuccess=()=>resolve(request.result);request.onerror=()=>reject(request.error)});
const dbPut=async(key:string,value:string)=>{try{const db=await openDb();await new Promise<void>((resolve,reject)=>{const tx=db.transaction("kv","readwrite");tx.objectStore("kv").put(value,key);tx.oncomplete=()=>resolve();tx.onerror=()=>reject(tx.error)})}catch{}}
const dbDelete=async(key:string)=>{try{const db=await openDb();await new Promise<void>((resolve,reject)=>{const tx=db.transaction("kv","readwrite");tx.objectStore("kv").delete(key);tx.oncomplete=()=>resolve();tx.onerror=()=>reject(tx.error)})}catch{}}
const dbGet=async(key:string)=>{try{const db=await openDb();return await new Promise<string|undefined>((resolve,reject)=>{const tx=db.transaction("kv","readonly");const req=tx.objectStore("kv").get(key);req.onsuccess=()=>resolve(typeof req.result==="string"?req.result:undefined);req.onerror=()=>reject(req.error)})}catch{return undefined}};

export async function bootstrapProjectPersistence(){
  if(typeof indexedDB!=="undefined")for(const key of KEYS){const value=await dbGet(key);if(value!==undefined)fallback.set(key,value)}
  const proto=Storage.prototype,nativeGet=proto.getItem,nativeSet=proto.setItem,nativeRemove=proto.removeItem;
  proto.getItem=function(key:string){const value=nativeGet.call(this,key);if(this===localStorage&&value===null&&fallback.has(key))return fallback.get(key)!;return value};
  proto.setItem=function(key:string,value:string){if(this===localStorage&&key.startsWith(PREFIX)){fallback.set(key,value);void dbPut(key,value)}try{return nativeSet.call(this,key,value)}catch(error){if(this===localStorage&&key.startsWith(PREFIX))return;throw error}};
  proto.removeItem=function(key:string){if(this===localStorage&&key.startsWith(PREFIX)){fallback.delete(key);void dbDelete(key)}return nativeRemove.call(this,key)};
}

const parse=<T,>(key:string,fallbackValue:T):T=>{try{return JSON.parse(localStorage.getItem(PREFIX+key)||"") as T}catch{return fallbackValue}};
const esc=(s:string)=>s.replaceAll("&","&amp;").replaceAll("<","&lt;").replaceAll(">","&gt;").replaceAll('"',"&quot;");
const safeFamily=(s:string)=>`"${s.replaceAll('"','\\"')}"`;
const activeFormatId=()=>{const text=(document.querySelector(".v2-format.active")?.textContent||"").toLowerCase();return (Object.entries(FORMAT_META).find(([,m])=>text.includes(m.label.toLowerCase()))?.[0]||"master") as keyof typeof FORMAT_META};
const currentTime=()=>{const text=document.querySelector(".v2-timeline header > span")?.textContent||"0";const match=text.match(/([0-9.]+)\s*\//);return match?Number(match[1]):0};

function makeHtml(formatId:keyof typeof FORMAT_META){
  const elements=parse<Record<string,StoredElement[]>>("elements",{}),keyframes=parse<Record<string,Record<string,StoredFrame[]>>>("keyframes",{}),assets=parse<StoredAsset[]>("assets",[]),backgrounds=parse<Record<string,{color:string}>>("backgrounds",{}),settings=parse<any>("settings",{}),meta=FORMAT_META[formatId],items=elements[formatId]||[],frames=keyframes[formatId]||{};
  const fonts=assets.filter(a=>a.type==="font"&&a.url).map(a=>{const family=a.name.replace(/\.[^.]+$/,"");return `@font-face{font-family:${safeFamily(family)};src:url(${JSON.stringify(a.url)})}`}).join("");
  const nodes=items.filter(i=>i.visible).map(i=>{const style=`position:absolute;left:${i.x}%;top:${i.y}%;width:${i.width}%;transform-origin:left top;transform:rotate(${i.rotation}deg) scale(${i.scale/100});opacity:${i.opacity/100};font-family:${safeFamily(i.fontFamily)};font-size:${i.fontSize}px;line-height:${i.lineHeight/100};color:${i.color};white-space:pre-wrap;`;return i.kind==="image"?`<img data-id="${esc(i.id)}" src="${esc(i.assetUrl||"")}" style="${style}height:auto;display:block">`:`<div data-id="${esc(i.id)}" style="${style}">${esc(i.text||"")}</div>`}).join("");
  const state=JSON.stringify({items,frames,duration:6}).replaceAll("<","\\u003c"),bg=backgrounds[formatId]?.color||"#fff",border=settings.borderEnabled?`border:1px solid ${settings.borderColor||"#000"};`:"",clickVar=/^[A-Za-z_$][\w$]*$/.test(settings.clickVariable||"")?settings.clickVariable:"clickTag";
  return `<!doctype html><html><head><meta charset="utf-8"><meta name="ad.size" content="width=${meta.width},height=${meta.height}"><style>${fonts}*{box-sizing:border-box}html,body{margin:0;width:${meta.width}px;height:${meta.height}px;overflow:hidden}body{position:relative;background:${bg};${border}${settings.clickSurface?"cursor:pointer;":""}}img{user-select:none;-webkit-user-drag:none}</style></head><body>${nodes}<script>var ${clickVar}=window.${clickVar}||"";const S=${state};const clamp=(v,a,b)=>Math.min(b,Math.max(a,v));function bez(t,b){const [x1,y1,x2,y2]=b||[0,0,1,1],cx=3*x1,bx=3*(x2-x1)-cx,ax=1-cx-bx,cy=3*y1,by=3*(y2-y1)-cy,ay=1-cy-by;let x=t;for(let i=0;i<6;i++){const f=((ax*x+bx)*x+cx)*x-t,d=(3*ax*x+2*bx)*x+cx;if(Math.abs(d)<1e-6)break;x=clamp(x-f/d,0,1)}return ((ay*x+by)*x+cy)*x}function ease(t,f){if(f?.easing==="custom")return bez(t,f.bezier);if(f?.easing==="ease-in")return bez(t,[.42,0,1,1]);if(f?.easing==="ease-out")return bez(t,[0,0,.58,1]);if(f?.easing==="ease-in-out")return bez(t,[.42,0,.58,1]);return t}function val(el,p,t){const fs=(S.frames[el.id]||[]).filter(f=>f&&f.property===p&&Number.isFinite(f.time)&&Number.isFinite(f.value)).sort((a,b)=>a.time-b.time);if(!fs.length)return el[p];let before={time:0,value:el[p]},after=null;for(const f of fs){if(f.time<=t)before=f;if(f.time>=t){after=f;break}}if(!after||after.time===before.time)return before.value;const q=ease((t-before.time)/(after.time-before.time),after);return before.value+(after.value-before.value)*q}function draw(t){for(const el of S.items){const n=document.querySelector('[data-id="'+CSS.escape(el.id)+'"]');if(!n)continue;const x=val(el,'x',t),y=val(el,'y',t),sc=val(el,'scale',t),r=val(el,'rotation',t),o=val(el,'opacity',t);n.style.left=x+'%';n.style.top=y+'%';n.style.transform='rotate('+r+'deg) scale('+(sc/100)+')';n.style.opacity=String(o/100)}}const start=performance.now();function tick(now){const t=((now-start)/1000)%S.duration;draw(t);requestAnimationFrame(tick)}requestAnimationFrame(tick);${settings.clickSurface?`document.body.addEventListener('click',()=>{if(window.${clickVar})window.open(window.${clickVar},'_blank')})`:""}<\/script></body></html>`;
}

const crcTable=(()=>{const table=new Uint32Array(256);for(let n=0;n<256;n++){let c=n;for(let k=0;k<8;k++)c=(c&1)?0xedb88320^(c>>>1):c>>>1;table[n]=c>>>0}return table})();
const crc32=(data:Uint8Array)=>{let c=0xffffffff;for(const b of data)c=crcTable[(c^b)&255]^(c>>>8);return (c^0xffffffff)>>>0};
const u16=(n:number)=>new Uint8Array([n&255,(n>>>8)&255]),u32=(n:number)=>new Uint8Array([n&255,(n>>>8)&255,(n>>>16)&255,(n>>>24)&255]);
const concat=(parts:Uint8Array[])=>{const out=new Uint8Array(parts.reduce((n,p)=>n+p.length,0));let o=0;for(const p of parts){out.set(p,o);o+=p.length}return out};
function zip(files:{name:string;content:string}[]){const enc=new TextEncoder(),locals:Uint8Array[]=[],centrals:Uint8Array[]=[];let offset=0;for(const file of files){const name=enc.encode(file.name),data=enc.encode(file.content),crc=crc32(data),local=concat([u32(0x04034b50),u16(20),u16(0x0800),u16(0),u16(0),u16(0),u32(crc),u32(data.length),u32(data.length),u16(name.length),u16(0),name,data]);locals.push(local);centrals.push(concat([u32(0x02014b50),u16(20),u16(20),u16(0x0800),u16(0),u16(0),u16(0),u32(crc),u32(data.length),u32(data.length),u16(name.length),u16(0),u16(0),u16(0),u16(0),u32(0),u32(offset),name]));offset+=local.length}const central=concat(centrals),body=concat(locals),end=concat([u32(0x06054b50),u16(0),u16(0),u16(files.length),u16(files.length),u32(central.length),u32(body.length),u16(0)]);return new Blob([body,central,end],{type:"application/zip"})}
const download=(blob:Blob,name:string)=>{const a=document.createElement("a");a.href=URL.createObjectURL(blob);a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000)};

function elementForCell(cell:HTMLElement){const formatId=activeFormatId(),elements=parse<Record<string,StoredElement[]>>("elements",{}),name=(cell.querySelector(".timeline-layer-name span")?.textContent||"").trim();return (elements[formatId]||[]).find(e=>e.name===name)}
function framesAt(elementId:string,time:number){const all=parse<Record<string,Record<string,StoredFrame[]>>>("keyframes",{}),list=all[activeFormatId()]?.[elementId]||[];return list.filter(f=>f&&Math.abs(f.time-time)<.035)}
function removeFramesAt(elementId:string,time:number){const formatId=activeFormatId(),all=parse<Record<string,Record<string,StoredFrame[]>>>("keyframes",{}),list=all[formatId]?.[elementId]||[];all[formatId]={...(all[formatId]||{}),[elementId]:list.filter(f=>!f||Math.abs(f.time-time)>=.035)};localStorage.setItem(PREFIX+"keyframes",JSON.stringify(all));sessionStorage.setItem("banner-editor:restore-time",String(time));location.reload()}
function addAllTransformKeys(cell:HTMLElement){(cell.querySelector(".timeline-layer-name") as HTMLButtonElement|null)?.click();requestAnimationFrame(()=>document.querySelectorAll<HTMLButtonElement>(".v2-fields button").forEach(b=>b.click()))}
function refreshKeyUi(){
  document.querySelectorAll<HTMLElement>(".timeline-layer-cell").forEach(cell=>{
    let button=cell.querySelector<HTMLButtonElement>(".runtime-key-button");
    if(!button){button=document.createElement("button");button.type="button";button.className="runtime-key-button";button.innerHTML='<span class="runtime-diamond" aria-hidden="true"></span>';const next=cell.querySelector<HTMLButtonElement>('button[title="Next keyframe"]');cell.insertBefore(button,next||null);button.addEventListener("click",e=>{e.preventDefault();e.stopPropagation();const element=elementForCell(cell);if(!element)return;const time=currentTime(),existing=framesAt(element.id,time);if(existing.length){removeFramesAt(element.id,time)}else addAllTransformKeys(cell)})}
    const element=elementForCell(cell),has=!!element&&framesAt(element.id,currentTime()).length>0;button.classList.toggle("keyed",has);button.title=has?"Delete keyframe at current time":"Add keyframe at current time";button.setAttribute("aria-label",button.title);
  });
  document.querySelectorAll<HTMLElement>(".timeline-track").forEach(track=>{const keys=[...track.querySelectorAll<HTMLElement>(".timeline-key")];const seen=new Set<string>();for(const key of keys){const left=(parseFloat(key.style.left||"0")).toFixed(3);if(seen.has(left)){key.classList.add("runtime-key-duplicate")}else{seen.add(left);key.classList.remove("runtime-key-duplicate");key.classList.add("runtime-key-group")}}});
}

function saveProject(){const data:Object=Object.fromEntries(KEYS.map(key=>[key,localStorage.getItem(key)]));const project:ProjectFile={type:"banner-editor-project",version:1,savedAt:new Date().toISOString(),data:data as Record<string,string|null>};download(new Blob([JSON.stringify(project,null,2)],{type:"application/json"}),`banner-project-${new Date().toISOString().slice(0,10)}.json`)}
async function loadProject(file:File){try{const parsed=JSON.parse(await file.text()) as ProjectFile;if(parsed.type!=="banner-editor-project"||parsed.version!==1||!parsed.data)throw new Error("Not a Banner Editor project");for(const key of KEYS){const value=parsed.data[key];if(typeof value==="string")localStorage.setItem(key,value);else localStorage.removeItem(key)}location.reload()}catch(error){alert(error instanceof Error?error.message:"Could not open project")}}
async function newProject(){if(!confirm("Create a new project? The current local draft will be cleared."))return;for(const key of KEYS){localStorage.removeItem(key);fallback.delete(key);await dbDelete(key)}location.reload()}
function installProjectActions(){const actions=document.querySelector(".v2-top-actions");if(!actions||actions.querySelector(".runtime-project-actions"))return;const wrap=document.createElement("div");wrap.className="runtime-project-actions";const save=document.createElement("button"),open=document.createElement("button"),fresh=document.createElement("button"),input=document.createElement("input");save.type=open.type=fresh.type="button";save.textContent="Save";open.textContent="Open";fresh.textContent="New";save.title="Save project file";open.title="Open project file";fresh.title="New blank project";input.type="file";input.accept="application/json,.json";input.hidden=true;save.onclick=saveProject;open.onclick=()=>input.click();fresh.onclick=()=>void newProject();input.onchange=()=>{const file=input.files?.[0];if(file)void loadProject(file);input.value=""};wrap.append(save,open,fresh,input);actions.prepend(wrap)}

export function installEditorRuntime(){
  const observer=new MutationObserver(()=>{installProjectActions();refreshKeyUi()});observer.observe(document.body,{subtree:true,childList:true});installProjectActions();refreshKeyUi();setInterval(refreshKeyUi,180);
  const restore=Number(sessionStorage.getItem("banner-editor:restore-time"));if(Number.isFinite(restore)&&restore>0){sessionStorage.removeItem("banner-editor:restore-time");setTimeout(()=>{const ruler=document.querySelector<HTMLElement>(".v2-ruler");if(!ruler)return;const box=ruler.getBoundingClientRect();ruler.dispatchEvent(new PointerEvent("pointerdown",{bubbles:true,clientX:box.left+(restore/6)*box.width,clientY:box.top+5}))},120)}
  document.addEventListener("pointerdown",event=>{const modal=document.querySelector(".bezier-editor");if(!modal)return;const target=event.target as Node;if(modal.contains(target)||document.querySelector(".easing-control")?.contains(target))return;(document.querySelector(".easing-preview.active") as HTMLButtonElement|null)?.click()},true);
  document.addEventListener("keydown",event=>{if(event.key!=="Delete"&&event.key!=="Backspace")return;const tag=(event.target as HTMLElement).tagName;if(["INPUT","TEXTAREA","SELECT"].includes(tag))return;const row=document.querySelector<HTMLElement>(".timeline-row.active"),cell=row?.querySelector<HTMLElement>(".timeline-layer-cell"),element=cell?elementForCell(cell):null,time=currentTime();if(element&&framesAt(element.id,time).length){event.preventDefault();removeFramesAt(element.id,time)}});
  document.addEventListener("click",event=>{const button=(event.target as HTMLElement).closest(".v2-top-actions > .primary") as HTMLButtonElement|null;if(!button)return;event.preventDefault();event.stopPropagation();event.stopImmediatePropagation();document.querySelector(".runtime-export-menu")?.remove();const menu=document.createElement("div");menu.className="runtime-export-menu";const current=document.createElement("button"),all=document.createElement("button");current.textContent="Export selected format";all.textContent="Export all formats (.zip)";current.onclick=()=>{const id=activeFormatId(),meta=FORMAT_META[id];download(new Blob([makeHtml(id)],{type:"text/html"}),`banner-${meta.width}x${meta.height}.html`);menu.remove()};all.onclick=()=>{const files=(Object.keys(FORMAT_META) as (keyof typeof FORMAT_META)[]).map(id=>{const m=FORMAT_META[id];return{name:`banner-${m.width}x${m.height}/index.html`,content:makeHtml(id)}});download(zip(files),"banner-campaign.zip");menu.remove()};menu.append(current,all);button.parentElement?.appendChild(menu)},true);
}

